var lab_h_arr = new Array();
lab_h_arr[0] = "<%=pageData.getWord("User Guide")%>";
lab_h_arr[1] = "<%=pageData.getWord("Click the sections below for full details")%>";

lab_h_arr[2] = "<%=pageData.getWord("Description")%>";
lab_h_arr[3] = "<%=pageData.getWord("The form builder allow users to generate PHP form pages for use with both inbound and outbound calls")%>";

lab_h_arr[4] = "<%=pageData.getWord("Interface")%>";
lab_h_arr[5] = "<%=pageData.getWord("The Aheeva Form Builder interface")%>";
lab_h_arr[6] = "<%=pageData.getWord("File and Tools menus")%>";
lab_h_arr[7] = "<%=pageData.getWord("Located at the left in the top tool bar")%>";
lab_h_arr[8] = "<%=pageData.getWord("File menu")%>";
lab_h_arr[9] = "<%=pageData.getWord("Contains options to save, open, delete and preview forms")%>";
lab_h_arr[10] = "<%=pageData.getWord("see")%>";
lab_h_arr[11] = "<%=pageData.getWord("Tools menu")%>";
lab_h_arr[12] = "<%=pageData.getWord("Contains options to configure form settings")%>";
lab_h_arr[13] = "<%=pageData.getWord("Shortcut icons")%>";
lab_h_arr[14] = "<%=pageData.getWord("The following shortcut icons are located below the File and Tools menus")%>";
lab_h_arr[15] = "<%=pageData.getWord("Save")%>";
lab_h_arr[16] = "<%=pageData.getWord("Save current form")%>";
lab_h_arr[17] = "<%=pageData.getWord("Save as")%>";
lab_h_arr[18] = "<%=pageData.getWord("Save the form with a different name")%>";
lab_h_arr[19] = "<%=pageData.getWord("Preview")%>";
lab_h_arr[20] = "<%=pageData.getWord("View current form in an html window")%>";
lab_h_arr[21] = "<%=pageData.getWord("Page elements-lc")%>";
lab_h_arr[22] = "<%=pageData.getWord("Page Elements")%>";
lab_h_arr[23] = "<%=pageData.getWord("located in the top tool bar")%>";
lab_h_arr[24] = "<%=pageData.getWord("Form toolbar")%>";
lab_h_arr[25] = "<%=pageData.getWord("located at the bottom of the interface")%>";
lab_h_arr[26] = "<%=pageData.getWord("Active checkbox")%>";
lab_h_arr[27] = "<%=pageData.getWord("Sets the state of the current form to")%>";
lab_h_arr[28] = "<%=pageData.getWord("Active")%>";
lab_h_arr[29] = "<%=pageData.getWord("editable")%>";
lab_h_arr[30] = "<%=pageData.getWord("or-lc")%>";
lab_h_arr[31] = "<%=pageData.getWord("Inactive")%>";
lab_h_arr[32] = "<%=pageData.getWord("locked")%>";
lab_h_arr[33] = "<%=pageData.getWord("Active/Inactive form state")%>";
lab_h_arr[34] = "<%=pageData.getWord("Work space")%>";
lab_h_arr[35] = "<%=pageData.getWord("located center of the interface")%>";
lab_h_arr[36] = "<%=pageData.getWord("The work space is where the form pages are constructed")%>";
lab_h_arr[37] = "<%=pageData.getWord("Page items are added here and can be positioned by clicking and dragging them to a new position")%>";
lab_h_arr[38] = "<%=pageData.getWord("A dotted red rectangle shows the dimension guide for the generated form")%>";
lab_h_arr[39] = "<%=pageData.getWord("Items placed outside the dotted lines will cause scrolling on the page in the generated form")%>";
lab_h_arr[40] = "<%=pageData.getWord("The dimensions of the generated form, and this guide, can be modified from the form toolbar")%>";
lab_h_arr[41] = "<%=pageData.getWord("The work space has a background grid to aid in aligning items")%>";
lab_h_arr[42] = "<%=pageData.getWord("The grid can be changed or removed using the grid shade tool")%>";
lab_h_arr[43] = "<%=pageData.getWord("A delete bin is located in the bottom right corner of the work space")%>";
lab_h_arr[44] = "<%=pageData.getWord("To delete an item from the page drag it over the delete bin")%>";
lab_h_arr[45] = "<%=pageData.getWord("Left Panel")%>";
lab_h_arr[46] = "<%=pageData.getWord("located to the left of the interface")%>";
lab_h_arr[47] = "<%=pageData.getWord("The form name is displayed at the top of the panel")%>";
lab_h_arr[48] = "<%=pageData.getWord("Click the name to view the form properties in the right panel")%>";
lab_h_arr[49] = "<%=pageData.getWord("A list of the form pages are shown in the left panel")%>";
lab_h_arr[50] = "<%=pageData.getWord("Pages") %>";
lab_h_arr[51] = "<%=pageData.getWord("Right Panel") %>";
lab_h_arr[52] = "<%=pageData.getWord("located to the right of the interface") %>";
lab_h_arr[53] = "<%=pageData.getWord("The right panel displays the properties for the selected form, page or page item") %>";
lab_h_arr[54] = "<%=pageData.getWord("Properties")%>";

lab_h_arr[55] = "<%=pageData.getWord("Create new form") %>";
lab_h_arr[56] = "<%=pageData.getWord("When you open the form builder, or click") %>";
lab_h_arr[57] = "<%=pageData.getWord("New") %>";
lab_h_arr[58] = "<%=pageData.getWord("in the") %>";
lab_h_arr[59] = "<%=pageData.getWord("you will be shown options for creating a new form") %>";
lab_h_arr[60] = "<%=pageData.getWord("Open an existing form") %>";
lab_h_arr[61] = "<%=pageData.getWord("If there are previously saved forms they can be opened by clicking the") %>";
lab_h_arr[62] = "<%=pageData.getWord("button-lc") %>";
lab_h_arr[63] = "<%=pageData.getWord("Button") %>";
lab_h_arr[64] = "<%=pageData.getWord("A window will appear with a list of the saved forms") %>";
lab_h_arr[65] = "<%=pageData.getWord("Select the form you wish to open by clicking the form name") %>";
lab_h_arr[66] = "<%=pageData.getWord("The form will be opened into the builder interface") %>";
lab_h_arr[67] = "<%=pageData.getWord("Create a new form") %>";
lab_h_arr[68] = "<%=pageData.getWord("A new form can be created for either inbound or outbound calls") %>";
lab_h_arr[69] = "<%=pageData.getWord("Check the radio button next to the appropriate text to select either inbound or outbound as the form type") %>";
lab_h_arr[70] = "<%=pageData.getWord("Add a name for the form in the Name field (the name cannot be the same as any previously saved forms)") %>";
lab_h_arr[71] = "<%=pageData.getWord("Click the 'Click here to continue' button") %>";
lab_h_arr[72] = "<%=pageData.getWord("The new form will be opened into the builder interface") %>";

lab_h_arr[73] = "<%=pageData.getWord("The form toolbar is located at the bottom of the interface") %>";
lab_h_arr[74] = "<%=pageData.getWord("It contains controls that affect the entire form") %>";
lab_h_arr[75] = "<%=pageData.getWord("Width and height") %>";
lab_h_arr[76] = "<%=pageData.getWord("Defines the guide area enclosed by a red dotted line in the work space") %>";
lab_h_arr[77] = "<%=pageData.getWord("The generated form window will be resized to this width and height. (Elements placed outside of the guide area in the work space will be viewable using scrollbars in the generated form.)")%>";
lab_h_arr[78] = "<%=pageData.getWord("Background") %>";
lab_h_arr[79] = "<%=pageData.getWord("Sets the background color for all form pages") %>";
lab_h_arr[80] = "<%=pageData.getWord("Click the color square to select the color - select from available colors or enter a hexadecimal value") %>";
lab_h_arr[81] = "<%=pageData.getWord("Required") %>";
lab_h_arr[82] = "<%=pageData.getWord("Required elements on all pages will be marked with the selected color") %>";
lab_h_arr[83] = "<%=pageData.getWord("Grid shade") %>";
lab_h_arr[84] = "<%=pageData.getWord("choose a grid shade that is visible against your choice of background color to aid in alignment of elements on the pages, or remove the grid entirely") %>";
lab_h_arr[85] = "<%=pageData.getWord("The grid is only visible in the work area and it does not affect the generated form") %>";

lab_h_arr[86] = "<%=pageData.getWord("A form can consist of a single page or multiple pages") %>";
lab_h_arr[87] = "<%=pageData.getWord("The page name(s) associated to the form are listed in the left panel (below '+ Add page')") %>";
lab_h_arr[88] = "<%=pageData.getWord("The page order of a multiple paged form is defined by the order they appear in the list (top first, bottom last)") %>";
lab_h_arr[89] = "<%=pageData.getWord("Creating the first page") %>";
lab_h_arr[90] = "<%=pageData.getWord("To start using the form builder you must create at least one page. Click the '+' icon and enter a name for the first page (the work space will then become active for this page)")%>";
lab_h_arr[91] = "<%=pageData.getWord("To add more pages to a form") %>";
lab_h_arr[92] = "<%=pageData.getWord("To create additional pages you should click on the '+' icon, then you will be prompted to enter a new page name") %>";
lab_h_arr[93] = "<%=pageData.getWord("You cannot create 2 pages with the same name under the same form") %>";
lab_h_arr[94] = "<%=pageData.getWord("Using the page list panel") %>";
lab_h_arr[95] = "<%=pageData.getWord("Select a page to edit by clicking on the page name (the name will be accentuated and the page content will be shown in the work space)") %>";
lab_h_arr[96] = "<%=pageData.getWord("The up and down arrow icons to the right of the page names are used to reorder the pages (change the order they appear in the generated form)") %>";
lab_h_arr[97] = "<%=pageData.getWord("When you click on a page name") %>";
lab_h_arr[98] = "<%=pageData.getWord("The page is shown in the work space where content can be added and edited") %>";
lab_h_arr[99] = "<%=pageData.getWord("The information of the page, 'page properties', is displayed in the right panel") %>";
lab_h_arr[100] = "<%=pageData.getWord("You can either rename or delete the page from here") %>";

lab_h_arr[101] = "<%=pageData.getWord("The page elements toolbar is located at the top of the interface") %>";
lab_h_arr[102] = "<%=pageData.getWord("It contains icons depicting the elements that can be added to form pages") %>";
lab_h_arr[103] = "<%=pageData.getWord("In order to add elements you should click on the appropriate page first to make it active in the work space, then click on the required element. The element will be added automatically as an item in the selected page's work space") %>";
lab_h_arr[104] = "<%=pageData.getWord("There are 3 categories of elements") %>";
lab_h_arr[105] = "<%=pageData.getWord("Form elements") %>";
lab_h_arr[106] = "<%=pageData.getWord("These elements can be read/written from/into the database") %>";
lab_h_arr[107] = "<%=pageData.getWord("Search elements") %>";
lab_h_arr[108] = "<%=pageData.getWord("Used to build a search bloc based on the parameters") %>";
lab_h_arr[109] = "<%=pageData.getWord("Design elements") %>";
lab_h_arr[110] = "<%=pageData.getWord("Elements to be displayed statically on the page") %>";
lab_h_arr[111] = "<%=pageData.getWord("such as company logo, intstructions, descriptions, section breaks, etc.") %>";
lab_h_arr[112] = "<%=pageData.getWord("A full list of page elements available in the Aheeva Form Builder can be seen in")%>";
lab_h_arr[113] = "<%=pageData.getWord("click here to view")%>";
lab_h_arr[114] = "<%=pageData.getWord("Edit the properties of an item") %>";
lab_h_arr[115] = "<%=pageData.getWord("the properties of an item are edited in the properties list (right panel)")%>";
lab_h_arr[116] = "<%=pageData.getWord("Delete an item")%>";
lab_h_arr[117] = "<%=pageData.getWord("To delete an item from the page select the item by clicking on it in the work area and then either click on the delete icon at the bottom of the properties list (right panel) or drag the item to the delet bin")%>";

lab_h_arr[118] = "<%=pageData.getWord("Properties for the form, a form page or a page item are viewed in the right panel")%>";
lab_h_arr[119] = "<%=pageData.getWord("to view the form properties")%>";
lab_h_arr[120] = "<%=pageData.getWord("click the form name in the top of the left panel")%>";
lab_h_arr[121] = "<%=pageData.getWord("The right panel displays general information about the form")%>";
lab_h_arr[122] = "<%=pageData.getWord("Name")%>";
lab_h_arr[123] = "<%=pageData.getWord("Type")%>";
lab_h_arr[124] = "<%=pageData.getWord("Created")%>";
lab_h_arr[125] = "<%=pageData.getWord("Created by")%>";
lab_h_arr[126] = "<%=pageData.getWord("Last modified")%>";
lab_h_arr[127] = "<%=pageData.getWord("Modified by")%>";
lab_h_arr[128] = "<%=pageData.getWord("Database information")%>";
lab_h_arr[129] = "<%=pageData.getWord("Below this are the editable sections of the properties list")%>";
lab_h_arr[130] = "<%=pageData.getWord("The form name can be edited in the 'name' text field")%>";
lab_h_arr[131] = "<%=pageData.getWord("The form type can be changed to inbound or outbound using the radio buttons")%>";
lab_h_arr[132] = "<%=pageData.getWord("The form can be completely deleted by clicking the 'delete' icon")%>";
lab_h_arr[133] = "<%=pageData.getWord("to view a form page properties")%>";
lab_h_arr[134] = "<%=pageData.getWord("click the page name in the left panel")%>";
lab_h_arr[135] = "<%=pageData.getWord("The right panel will show the form name")%>";
lab_h_arr[136] = "<%=pageData.getWord("The page can be deleted by clicking the 'delete' icon")%>";
lab_h_arr[137] = "<%=pageData.getWord("To view the properties of a specific item")%>";
lab_h_arr[138] = "<%=pageData.getWord("select the item by clicking on it in the work area")%>";
lab_h_arr[139] = "<%=pageData.getWord("The right panel will show the properties for the specific item")%>";
lab_h_arr[140] = "<%=pageData.getWord("Lists of the properties associated to each type of page element are available in topic")%>";
lab_h_arr[141] = "<%=pageData.getWord("Changing the properties will allow customisation of the page elements")%>";
lab_h_arr[142] = "<%=pageData.getWord("Property descriptions")%>";
lab_h_arr[143] = "<%=pageData.getWord("Label")%>";
lab_h_arr[144] = "<%=pageData.getWord("non mandatory")%>";
lab_h_arr[145] = "<%=pageData.getWord("A text entry displayed to the left of the item")%>";
lab_h_arr[146] = "<%=pageData.getWord("Except for button properties where the label is the text shown on the button")%>";
lab_h_arr[147] = "<%=pageData.getWord("Label width")%>";
lab_h_arr[148] = "<%=pageData.getWord("Sets the width (in pixels) of the area in which the label will be shown")%>";
lab_h_arr[149] = "<%=pageData.getWord("Align")%>";
lab_h_arr[150] = "<%=pageData.getWord("Alignment of the label (Left, right or center)")%>";
lab_h_arr[151] = "<%=pageData.getWord("Default")%>";
lab_h_arr[152] = "<%=pageData.getWord("Sets the default value of an item (the initial value shown in the form field)")%>";
lab_h_arr[153] = "<%=pageData.getWord("Data Source")%>";
lab_h_arr[154] = "<%=pageData.getWord("Used to relate an item to a field in a table")%>";
lab_h_arr[155] = "<%=pageData.getWord("To configure the Data Source Click on the")%>";
lab_h_arr[156] = "<%=pageData.getWord("A window appears with customisable options")%>";
lab_h_arr[157] = "<%=pageData.getWord("choose the required table, then the required field from the dropdown lists")%>";
lab_h_arr[158] = "<%=pageData.getWord("For tables to be listed in the dropdown menu they must be defined previously in the 'Table configuration section'")%>";
lab_h_arr[159] = "<%=pageData.getWord("Parameter")%>";
lab_h_arr[160] = "<%=pageData.getWord("You can assign a parameter value to an item")%>";
lab_h_arr[161] = "<%=pageData.getWord("If an item has a default value and a parameter value the form will check the parameter value first then the default value")%>";
lab_h_arr[162] = "<%=pageData.getWord("Top")%>";
lab_h_arr[163] = "<%=pageData.getWord("Left")%>";
lab_h_arr[164] = "<%=pageData.getWord("Sets the position of the item on the page")%>";
lab_h_arr[165] = "<%=pageData.getWord("Coordinates relative to the top left corner on the page, measured in pixels")%>";
lab_h_arr[166] = "<%=pageData.getWord("Width-uc")%>";
lab_h_arr[167] = "<%=pageData.getWord("Height-uc")%>";
lab_h_arr[168] = "<%=pageData.getWord("Sets the size of the item (in pixels)")%>";
lab_h_arr[169] = "<%=pageData.getWord("Font, Font Size, Font Style, Font Weight, Font Color")%>";
lab_h_arr[170] = "<%=pageData.getWord("Settings for the text of an item")%>";
lab_h_arr[171] = "<%=pageData.getWord("Determines whether a form item is required to be filled before the form can be submitted")%>";
lab_h_arr[172] = "<%=pageData.getWord("Required items are emphasized in the generated form")%>";
lab_h_arr[173] = "<%=pageData.getWord("Values")%>";
lab_h_arr[174] = "<%=pageData.getWord("Combo field and Radio buttons only")%>";
lab_h_arr[175] = "<%=pageData.getWord("Determines the options in the drop down menu (combo) or choices (radio button)")%>";
lab_h_arr[176] = "<%=pageData.getWord("Click on the")%>";
lab_h_arr[177] = "<%=pageData.getWord("to open a window where new options/choices can be entered")%>";
lab_h_arr[178] = "<%=pageData.getWord("Click 'Add row' to add an option/choice")%>";
lab_h_arr[179] = "<%=pageData.getWord("Code")%>";
lab_h_arr[180] = "<%=pageData.getWord("The hidden value that will be read/written from/into the database field")%>";
lab_h_arr[181] = "<%=pageData.getWord("e.g. a combo box with 2 values: 'M', 'Male' and 'F', 'Female', you can relate this combo to a column in a table containing 'F' or 'M' and display the description instead of the code")%>";
lab_h_arr[182] = "<%=pageData.getWord("the text to appear in the dropdown menu or next to the selected radio button")%>";
lab_h_arr[183] = "<%=pageData.getWord("the checked option/choice will be shown as the initial (default) result")%>";
lab_h_arr[184] = "<%=pageData.getWord("Delete")%>";
lab_h_arr[185] = "<%=pageData.getWord("Click to remove the option/choice from list")%>";
lab_h_arr[186] = "<%=pageData.getWord("Checked Value, Unchecked Value")%>";
lab_h_arr[187] = "<%=pageData.getWord("Checkbox only")%>";
lab_h_arr[188] = "<%=pageData.getWord("Determines the value to be returned when the item is checked/unchecked")%>";
lab_h_arr[189] = "<%=pageData.getWord("Minimum, Maximum")%>";
lab_h_arr[190] = "<%=pageData.getWord("Number fields only")%>";
lab_h_arr[191] = "<%=pageData.getWord("Determines the lowest and highest numbers that will be accepted as values entered into the filed")%>";
lab_h_arr[192] = "<%=pageData.getWord("Format")%>";
lab_h_arr[193] = "<%=pageData.getWord("Date field only")%>";
lab_h_arr[194] = "<%=pageData.getWord("Determines the way in which a date is shown (mm/dd/yyyy, dd/mm/yyyy, dd.mm.yyyy or yyyy-mm-dd)")%>";
lab_h_arr[195] = "<%=pageData.getWord("Button Type")%>";
lab_h_arr[196] = "<%=pageData.getWord("Button only")%>";
lab_h_arr[197] = "<%=pageData.getWord("Determines the function of the button")%>";
lab_h_arr[198] = "<%=pageData.getWord("Content")%>";
lab_h_arr[199] = "<%=pageData.getWord("Static Text only")%>";
lab_h_arr[200] = "<%=pageData.getWord("The text to be shown in the static text box")%>";
lab_h_arr[201] = "<%=pageData.getWord("Backgd Width")%>";
lab_h_arr[202] = "<%=pageData.getWord("Backgd Height")%>";
lab_h_arr[203] = "<%=pageData.getWord("Image field only")%>";
lab_h_arr[204] = "<%=pageData.getWord("Sets the width and height of the containing box for an image (in pixels)")%>";
lab_h_arr[205] = "<%=pageData.getWord("If the containing box is set smaller than the image the image will be resized to fit the box")%>";
lab_h_arr[206] = "<%=pageData.getWord("If the image is set larger than the containing box the containing box will be resized to fit the image")%>";
lab_h_arr[207] = "<%=pageData.getWord("File")%>";
lab_h_arr[208] = "<%=pageData.getWord("to upload an image into the item")%>";
lab_h_arr[209] = "<%=pageData.getWord("Backgd Color-uc")%>";
lab_h_arr[210] = "<%=pageData.getWord("Image field and Section Break only")%>";
lab_h_arr[211] = "<%=pageData.getWord("Sets the color of the containing box for an image, or the fill color for a section break")%>";
lab_h_arr[212] = "<%=pageData.getWord("Will show through any transparent areas of an image or, if the containing box is larger than the image, will be visible as a border around the image")%>";
lab_h_arr[213] = "<%=pageData.getWord("Border Color")%>";
lab_h_arr[214] = "<%=pageData.getWord("Section Break only")%>";
lab_h_arr[215] = "<%=pageData.getWord("Sets the border color for a section break")%>";
lab_h_arr[216] = "<%=pageData.getWord("If the border width is set to 0px the border color will not be visible")%>";
lab_h_arr[217] = "<%=pageData.getWord("Border Width")%>";
lab_h_arr[218] = "<%=pageData.getWord("Sets the border width for a section break")%>";
lab_h_arr[219] = "<%=pageData.getWord("set to 0px for no border")%>";
lab_h_arr[220] = "<%=pageData.getWord("Style")%>";
lab_h_arr[221] = "<%=pageData.getWord("Sets the style of the section break")%>";

lab_h_arr[222] = "<%=pageData.getWord("Click")%>";
lab_h_arr[223] = "<%=pageData.getWord("to open the dropdown file menu")%>";
lab_h_arr[224] = "<%=pageData.getWord("Creates a new form")%>";
lab_h_arr[225] = "<%=pageData.getWord("Save the form and generate necessary files")%>";
lab_h_arr[226] = "<%=pageData.getWord("If the name of the form has been changed since the last save")%>";
lab_h_arr[227] = "<%=pageData.getWord("the new name will overide the old name")%>";
lab_h_arr[228] = "<%=pageData.getWord("To save the form under a new name and keep the original form select")%>";
lab_h_arr[229] = "<%=pageData.getWord("Save the current form with a new name")%>";
lab_h_arr[230] = "<%=pageData.getWord("A window will apear and you will be prompted to enter a name for the form")%>";
lab_h_arr[231] = "<%=pageData.getWord("The name cannot be the same as a previously saved form")%>";
lab_h_arr[232] = "<%=pageData.getWord("Open-uc")%>";
lab_h_arr[233] = "<%=pageData.getWord("Open an existing form from a list of all previously saved forms")%>";
lab_h_arr[234] = "<%=pageData.getWord("Delete the current form")%>";
lab_h_arr[235] = "<%=pageData.getWord("Open the current form in an HTML window for previewing the generated form")%>";

lab_h_arr[236] = "<%=pageData.getWord("Tools")%>";
lab_h_arr[237] = "<%=pageData.getWord("Database Configuration")%>";
lab_h_arr[238] = "<%=pageData.getWord("Allows access to an existing Database")%>";
lab_h_arr[239] = "<%=pageData.getWord("Table Configuration")%>";
lab_h_arr[240] = "<%=pageData.getWord("Specify the tables used in the form for each database")%>";
lab_h_arr[241] = "<%=pageData.getWord("Parameters Configuration")%>";
lab_h_arr[242] = "<%=pageData.getWord("To catch the value of a parameter in the form")%>";
lab_h_arr[243] = "<%=pageData.getWord("Where clause configuration")%>";
lab_h_arr[244] = "<%=pageData.getWord("for limiting the data read from the database tables to the requested records only")%>";
lab_h_arr[245] = "<%=pageData.getWord("Element triggers")%>";
lab_h_arr[246] = "<%=pageData.getWord("to define action based on a specific value of an element")%>";
lab_h_arr[247] = "<%=pageData.getWord("Global Parameters")%>";
lab_h_arr[248] = "<%=pageData.getWord("parameters that are global for all forms")%>";

lab_h_arr[249] = "<%=pageData.getWord("Located in the")%>";
lab_h_arr[250] = "<%=pageData.getWord("dropdown menu")%>";
lab_h_arr[251] = "<%=pageData.getWord("Database Configuration allows users to access an existing Database. Aheevaccs database is given by default")%>";
lab_h_arr[252] = "<%=pageData.getWord("How to configure a new database")%>";
lab_h_arr[253] = "<%=pageData.getWord("Click the")%>";
lab_h_arr[254] = "<%=pageData.getWord("menu and select")%>";
lab_h_arr[255] = "<%=pageData.getWord("A window appears containing the list of configured databases")%>";
lab_h_arr[256] = "<%=pageData.getWord("aheevaccs is always shown and cannot be removed from the list")%>";
lab_h_arr[257] = "<%=pageData.getWord("Click on")%>";
lab_h_arr[258] = "<%=pageData.getWord("Add database")%>";
lab_h_arr[259] = "<%=pageData.getWord("A window appears where you can add the properties for the database")%>";
lab_h_arr[260] = "<%=pageData.getWord("Enter the information for the database in the following fields")%>";
lab_h_arr[261] = "<%=pageData.getWord("the name of database as it will appear in the form builder")%>";
lab_h_arr[262] = "<%=pageData.getWord("Password")%>";
lab_h_arr[263] = "<%=pageData.getWord("the password of the database")%>";
lab_h_arr[264] = "<%=pageData.getWord("Port")%>";
lab_h_arr[265] = "<%=pageData.getWord("the port used to access to the database")%>";
lab_h_arr[266] = "<%=pageData.getWord("IP")%>";
lab_h_arr[267] = "<%=pageData.getWord("IP of the database server")%>";
lab_h_arr[268] = "<%=pageData.getWord("User name")%>";
lab_h_arr[269] = "<%=pageData.getWord("Database username-lc")%>";
lab_h_arr[270] = "<%=pageData.getWord("DB name")%>";
lab_h_arr[271] = "<%=pageData.getWord("name of the database on the database server")%>";
lab_h_arr[272] = "<%=pageData.getWord("You can test the connection by clicking on 'Test connection'")%>";
lab_h_arr[273] = "<%=pageData.getWord("How to modify database configuration")%>";
lab_h_arr[274] = "<%=pageData.getWord("You can modify the configuration by selecting")%>";
lab_h_arr[275] = "<%=pageData.getWord("from the")%>";
lab_h_arr[276] = "<%=pageData.getWord("menu and clicking on the database name. The database properties list will be shown and can be edited")%>";
lab_h_arr[277] = "<%=pageData.getWord("Aheevaccs database's parameters are global parameters for all forms, which cannot be updated for a specific form. They are editable only from the")%>";
lab_h_arr[278] = "<%=pageData.getWord("menu in")%>";

lab_h_arr[279] = "<%=pageData.getWord("You should specify the tables used in the form for each database in order to relate elements or create where conditions")%>";
lab_h_arr[280] = "<%=pageData.getWord("How to choose the list of tables for a database")%>";
lab_h_arr[281] = "<%=pageData.getWord("A window appears containing the current list of selected tables for the specific database shown in the dropdown menu field")%>";
lab_h_arr[282] = "<%=pageData.getWord("Choose a database from the dropdown list")%>";
lab_h_arr[283] = "<%=pageData.getWord("button to show a list of available tables for this database")%>";
lab_h_arr[284] = "<%=pageData.getWord("You can select or deselect tables from this list by marking the tick box next to the table names")%>";
lab_h_arr[285] = "<%=pageData.getWord("The list of tables will be refreshed showing the new selection of tables for the database")%>";
lab_h_arr[286] = "<%=pageData.getWord("You can change the order of the tables by clicking on the up and down arrow icons next to the table names")%>";
lab_h_arr[287] = "<%=pageData.getWord("The order of the tables is the insert order while executing the save on the generated php code")%>";

lab_h_arr[288] = "<%=pageData.getWord("Parameters are the values sent to the form via the URL (ex: http://xxx.xxx.xxx.xxx/test.php?p1=1&p2=2)")%>";
lab_h_arr[289] = "<%=pageData.getWord("To catch the value of a parameter in the form you should define it during the creation of the form")%>";
lab_h_arr[290] = "<%=pageData.getWord("Parameters can be used when defining where clauses or used as an initial value of a page element")%>";
lab_h_arr[291] = "<%=pageData.getWord("How to define a parameter")%>";
lab_h_arr[292] = "<%=pageData.getWord("A window appears containing the current list of parameters")%>";
lab_h_arr[293] = "<%=pageData.getWord("Add Parameter")%>";
lab_h_arr[294] = "<%=pageData.getWord("A window appears with a text field for adding a parameter name")%>";
lab_h_arr[295] = "<%=pageData.getWord("Enter the parameter name")%>";
lab_h_arr[296] = "<%=pageData.getWord("It must be unique per form")%>";
lab_h_arr[297] = "<%=pageData.getWord("The list of parameters will be refreshed")%>";
lab_h_arr[298] = "<%=pageData.getWord("You can reconfigure a parameter by clicking on its name or remove the parameter by clicking the delete icon to the right of the name")%>";

lab_h_arr[299] = "<%=pageData.getWord("The where clause utility is for limiting the data read from the database tables to the requested records only")%>";
lab_h_arr[300] = "<%=pageData.getWord("This can increase the performance of the form")%>";
lab_h_arr[301] = "<%=pageData.getWord("How to configure where clauses")%>";
lab_h_arr[302] = "<%=pageData.getWord("Where Clause Config.")%>";
lab_h_arr[303] = "<%=pageData.getWord("A window appears containing the existing clauses for a specific database")%>";
lab_h_arr[304] = "<%=pageData.getWord("Choose a database from the dropdown list for which the where clause will be associated")%>";
lab_h_arr[305] = "<%=pageData.getWord("Click on 'Add Where Clause'")%>";
lab_h_arr[306] = "<%=pageData.getWord("A list of empty property fields will appear in the window")%>";
lab_h_arr[307] = "<%=pageData.getWord("Fill the appropriate fields")%>";
lab_h_arr[308] = "<%=pageData.getWord("From table")%>";
lab_h_arr[309] = "<%=pageData.getWord("the filtered table")%>";
lab_h_arr[310] = "<%=pageData.getWord("Where Field")%>";
lab_h_arr[311] = "<%=pageData.getWord("the filter will be based on this field")%>";
lab_h_arr[312] = "<%=pageData.getWord("to choose or change the field you have to click on the")%>";
lab_h_arr[313] = "<%=pageData.getWord("Dest. Type")%>";
lab_h_arr[314] = "<%=pageData.getWord("set this to 'Table' or 'Parameter' to determines the type of data used to filter the 'From table'")%>";
lab_h_arr[315] = "<%=pageData.getWord("When set to 'Table' specify the destination table and field, otherwise specify the destination parameter")%>";
lab_h_arr[316] = "<%=pageData.getWord("IMPORTANT")%>";
lab_h_arr[317] = "<%=pageData.getWord("You cannot use a table as the destination table before adding a where clause for this table")%>";
lab_h_arr[318] = "<%=pageData.getWord("The where clauses should be defined for each database alone")%>";

lab_h_arr[319] = "<%=pageData.getWord("The elements triggers utility is to define action based on a specific value of an element")%>";
lab_h_arr[320] = "<%=pageData.getWord("There are three types of action")%>";
lab_h_arr[321] = "<%=pageData.getWord("Show")%>";
lab_h_arr[322] = "<%=pageData.getWord("Shows a specific element when a defined value occurs in the trigger element")%>";
lab_h_arr[323] = "<%=pageData.getWord("Hide")%>";
lab_h_arr[324] = "<%=pageData.getWord("Hides a specific element when a defined value occurs in the trigger element")%>";
lab_h_arr[325] = "<%=pageData.getWord("Fill")%>";
lab_h_arr[326] = "<%=pageData.getWord("Affects the defined value(s) of a specific element when a defined value occurs in the trigger element")%>";
lab_h_arr[327] = "<%=pageData.getWord("How to add an element trigger")%>";
lab_h_arr[328] = "<%=pageData.getWord("A window appears containing the existing triggers")%>";
lab_h_arr[329] = "<%=pageData.getWord("Fill the name of the trigger (it should be unique for each form)")%>";
lab_h_arr[330] = "<%=pageData.getWord("Choose the page where the trigger element is located and identify which element will become the trigger")%>";
lab_h_arr[331] = "<%=pageData.getWord("If the element is not a combo box, radio button or checkbox, you can choose the operator to set the condition that will activate the trigger")%>";
lab_h_arr[332] = "<%=pageData.getWord("Enter the value on which the trigger will be executed")%>";
lab_h_arr[333] = "<%=pageData.getWord("Choose the action type (show, hide or fill)")%>";
lab_h_arr[334] = "<%=pageData.getWord("Identify the page and the element that will be affected by the trigger")%>";
lab_h_arr[335] = "<%=pageData.getWord("If the selected action is 'Fill' you have to define the value(s) of the affected element by clicking on the '...' button in the values column")%>";
lab_h_arr[336] = "<%=pageData.getWord("a window appears containing the relevant value options")%>";
lab_h_arr[337] = "<%=pageData.getWord("If the action element is a radio button or combo box")%>";
lab_h_arr[338] = "<%=pageData.getWord("choose the required values from the list")%>";
lab_h_arr[339] = "<%=pageData.getWord("If the action element is a check box")%>";
lab_h_arr[340] = "<%=pageData.getWord("specify either to check or uncheck the element")%>";
lab_h_arr[341] = "<%=pageData.getWord("If the action element is an input")%>";
lab_h_arr[342] = "<%=pageData.getWord("enter the required value in the text field")%>";
lab_h_arr[343] = "<%=pageData.getWord("to apply the defined values and close the values window")%>";

lab_h_arr[344] = "<%=pageData.getWord("These parameters are global for all forms")%>";
lab_h_arr[345] = "<%=pageData.getWord("Accessing the global parameters")%>";
lab_h_arr[346] = "<%=pageData.getWord("A window appears containing global parameter properties")%>";
lab_h_arr[347] = "<%=pageData.getWord("Php Generation Path")%>";
lab_h_arr[348] = "<%=pageData.getWord("The path of the directory created when you save the form")%>";
lab_h_arr[349] = "<%=pageData.getWord("This directory contains the php file for the form and all needed files to allow the execution of the form under apache server")%>";
lab_h_arr[350] = "<%=pageData.getWord("Other parameters")%>";
lab_h_arr[351] = "<%=pageData.getWord("parameters used to connect to the aheevaccs database")%>";

lab_h_arr[352] = "<%=pageData.getWord("The active checkbox is located at the top of the interface")%>";
lab_h_arr[353] = "<%=pageData.getWord("It changes the state of the curent form between")%>";
lab_h_arr[354] = "<%=pageData.getWord("when ticked and")%>";
lab_h_arr[355] = "<%=pageData.getWord("when unticked")%>";
lab_h_arr[356] = "<%=pageData.getWord("An active form is fully editable")%>";
lab_h_arr[357] = "<%=pageData.getWord("An inactive form is 'locked' and cannot be edited")%>";
lab_h_arr[358] = "<%=pageData.getWord("It can still be viewed and previewed although there are limited options in the file menu")%>";
lab_h_arr[359] = "<%=pageData.getWord("An inactive form can still be used in the same way as an active form")%>";

lab_h_arr[360] = "<%=pageData.getWord("Aheeva outbound form template")%>";
lab_h_arr[361] = "<%=pageData.getWord("The form builder is provided with a template called")%>";
lab_h_arr[362] = "<%=pageData.getWord("template_outbound")%>";
lab_h_arr[363] = "<%=pageData.getWord("It is customized to fit with Aheeva's standard calling lists")%>";
lab_h_arr[364] = "<%=pageData.getWord("Dispositions block")%>";
lab_h_arr[365] = "<%=pageData.getWord("Each value in any field of this block will execute a specific action")%>";
lab_h_arr[366] = "<%=pageData.getWord("There is also a list of actions not related to the display")%>";
lab_h_arr[367] = "<%=pageData.getWord("Disposition code = Sale")%>";
lab_h_arr[368] = "<%=pageData.getWord("Indicate that it is a sale")%>";
lab_h_arr[369] = "<%=pageData.getWord("Disposition code = Do not call")%>";
lab_h_arr[370] = "<%=pageData.getWord("The phone number of the called person will be inserted in the blacklist table")%>";
lab_h_arr[371] = "<%=pageData.getWord("Disposition code = Callback")%>";
lab_h_arr[372] = "<%=pageData.getWord("User should enter call back information and the system will try to call this person at the specified date and time")%>";
lab_h_arr[373] = "<%=pageData.getWord("How to use this template for a specific calling list")%>";
lab_h_arr[374] = "<%=pageData.getWord("Open the form")%>";
lab_h_arr[375] = "<%=pageData.getWord("Select 'template outbound' from the displayed list")%>";
lab_h_arr[376] = "<%=pageData.getWord("Enter a name for your form")%>";
lab_h_arr[377] = "<%=pageData.getWord("After save, click the")%>";
lab_h_arr[378] = "<%=pageData.getWord("Choose the concerned calling list and save")%>";
lab_h_arr[379] = "<%=pageData.getWord("Now you have a new form for the specified calling list")%>";
lab_h_arr[380] = "<%=pageData.getWord("To call the new form you simply have to call its URL with the following parameters")%>";
lab_h_arr[381] = "<%=pageData.getWord("ANI")%>";
lab_h_arr[382] = "<%=pageData.getWord("It is the phone number of the called person [Mandatory]")%>";
lab_h_arr[383] = "<%=pageData.getWord("Blacklist")%>";
lab_h_arr[384] = "<%=pageData.getWord("Name of the blacklist table [Optional]. (If omitted use 'cfg_black_list'.)")%>";

lab_h_arr[385] = "<%=pageData.getWord("Text Field")%>";
lab_h_arr[386] = "<%=pageData.getWord("Form element")%>";
lab_h_arr[387] = "<%=pageData.getWord("Used to display a single line of editable alphanumeric values")%>";
lab_h_arr[388] = "<%=pageData.getWord("The item generated on the page can be related to a table field and/or a parameter")%>";
lab_h_arr[389] = "<%=pageData.getWord("Text properties")%>";
lab_h_arr[390] = "<%=pageData.getWord("Sets the default value of an item (the initial value shown in the generated form)")%>";

lab_h_arr[391] = "<%=pageData.getWord("Combo Field")%>";
lab_h_arr[392] = "<%=pageData.getWord("Used to display a user-defined list of values")%>";
lab_h_arr[393] = "<%=pageData.getWord("it can be assigned values and a default value can be specified from the list of assigned values")%>";
lab_h_arr[394] = "<%=pageData.getWord("Combo properties")%>";
lab_h_arr[395] = "<%=pageData.getWord("Determines the options in the drop down menu")%>";
lab_h_arr[396] = "<%=pageData.getWord("button to open a window where new options can be entered")%>";
lab_h_arr[397] = "<%=pageData.getWord("Click 'Add row' to add an option")%>";
lab_h_arr[398] = "<%=pageData.getWord("the text to appear in the dropdown menu")%>";
lab_h_arr[399] = "<%=pageData.getWord("the checked option will be shown as the initial (default) result")%>";
lab_h_arr[400] = "<%=pageData.getWord("Click to remove the option from list")%>";

lab_h_arr[401] = "<%=pageData.getWord("Text Area Field")%>";
lab_h_arr[402] = "<%=pageData.getWord("Used to display multiple lines of editable alphanumeric values")%>";
lab_h_arr[403] = "<%=pageData.getWord("Text Area properties")%>";

lab_h_arr[404] = "<%=pageData.getWord("Radio Button")%>";
lab_h_arr[405] = "<%=pageData.getWord("Radio properties")%>";
lab_h_arr[406] = "<%=pageData.getWord("Determines the radio button choices")%>";
lab_h_arr[407] = "<%=pageData.getWord("button to open a window where new choices can be entered")%>";
lab_h_arr[408] = "<%=pageData.getWord("Click 'Add row' to add a choice")%>";
lab_h_arr[409] = "<%=pageData.getWord("the text to appear next to the selected radio button")%>";
lab_h_arr[410] = "<%=pageData.getWord("the checked choice will be shown as the initial (default) result")%>";
lab_h_arr[411] = "<%=pageData.getWord("Click to remove the choice from list")%>";

lab_h_arr[412] = "<%=pageData.getWord("Checkbox")%>";
lab_h_arr[413] = "<%=pageData.getWord("Used to display a checkbox")%>";
lab_h_arr[414] = "<%=pageData.getWord("it can be assigned a value to return when checked and another one when unchecked")%>";
lab_h_arr[415] = "<%=pageData.getWord("Checkbox properties")%>";

lab_h_arr[416] = "<%=pageData.getWord("Display Value Field")%>";
lab_h_arr[417] = "<%=pageData.getWord("Used to display a single line of non-editable alphanumeric values")%>";
lab_h_arr[418] = "<%=pageData.getWord("Display Value properties")%>";

lab_h_arr[419] = "<%=pageData.getWord("Number Field")%>";
lab_h_arr[420] = "<%=pageData.getWord("Used to display an editable numeric value")%>";
lab_h_arr[421] = "<%=pageData.getWord("The item generated on the page can be relate to a table field and/or a parameter, the number value can be limited to a defined range by setting the minimum and maximum properties")%>";
lab_h_arr[422] = "<%=pageData.getWord("Number properties")%>";

lab_h_arr[423] = "<%=pageData.getWord("Date Field")%>";
lab_h_arr[424] = "<%=pageData.getWord("Used to display an editable date value")%>";
lab_h_arr[425] = "<%=pageData.getWord("Date properties")%>";

lab_h_arr[426] = "<%=pageData.getWord("Time Field")%>";
lab_h_arr[427] = "<%=pageData.getWord("Used to display an editable time value (HH:MM:SS)")%>";
lab_h_arr[428] = "<%=pageData.getWord("Time properties")%>";

lab_h_arr[429] = "<%=pageData.getWord("Phone Number Field")%>";
lab_h_arr[430] = "<%=pageData.getWord("Phone Number properties")%>";

lab_h_arr[431] = "<%=pageData.getWord("Email Field")%>";
lab_h_arr[432] = "<%=pageData.getWord("Used to display an editable email value (mymail@mycompany.com)")%>";
lab_h_arr[433] = "<%=pageData.getWord("Email properties")%>";

lab_h_arr[434] = "<%=pageData.getWord("Search element")%>";
lab_h_arr[435] = "<%=pageData.getWord("Used to display a search button")%>";
lab_h_arr[436] = "<%=pageData.getWord("The button generated on the page is used to refresh data")%>";
lab_h_arr[437] = "<%=pageData.getWord("Button properties")%>";
lab_h_arr[438] = "<%=pageData.getWord("The text shown on the button")%>";

lab_h_arr[439] = "<%=pageData.getWord("Search Item Field")%>";
lab_h_arr[440] = "<%=pageData.getWord("Used to display a search item")%>";
lab_h_arr[441] = "<%=pageData.getWord("The item generated on the page can be related to a parameter, thus when changing its value it refresh the data with then newly entered value")%>";
lab_h_arr[442] = "<%=pageData.getWord("Search Item properties")%>";

lab_h_arr[443] = "<%=pageData.getWord("Static Text Field")%>";
lab_h_arr[444] = "<%=pageData.getWord("Design element")%>";
lab_h_arr[445] = "<%=pageData.getWord("Used to Display multiple lines of static (non-editable) alphanumeric values")%>";
lab_h_arr[446] = "<%=pageData.getWord("Static Text properties")%>";
lab_h_arr[447] = "<%=pageData.getWord("Alignment of the content (Left, right or center)")%>";

lab_h_arr[448] = "<%=pageData.getWord("Image Field")%>";
lab_h_arr[449] = "<%=pageData.getWord("Used to display a static image on the page")%>";
lab_h_arr[450] = "<%=pageData.getWord("Accepted file types are '.gif', '.bmp' or '.jpg'")%>";
lab_h_arr[451] = "<%=pageData.getWord("A background color can be added to the image")%>";
lab_h_arr[452] = "<%=pageData.getWord("Image properties")%>";
lab_h_arr[453] = "<%=pageData.getWord("Sets the color of the containing box for an image")%>";
lab_h_arr[454] = "<%=pageData.getWord("A window appears containing the upload application")%>";
lab_h_arr[455] = "<%=pageData.getWord("To upload an image")%>";
lab_h_arr[456] = "<%=pageData.getWord("Enter the location of the image to upload into the text field or click 'browse' and select an image from your folders")%>";
lab_h_arr[457] = "<%=pageData.getWord("Click 'upload' to place the image in the selected item in the form builder")%>";
lab_h_arr[458] = "<%=pageData.getWord("The image will appear in the form builder work space and will be visible in the upload application view area")%>";
lab_h_arr[459] = "<%=pageData.getWord("The image file name is show in the upload appication window to confirm the file has been uploaded successfully")%>";
lab_h_arr[460] = "<%=pageData.getWord("Click 'close' to close the upload application window")%>";
lab_h_arr[461] = "<%=pageData.getWord("To change an image")%>";
lab_h_arr[462] = "<%=pageData.getWord("Select the image to change in the work space and click the '...' button in the properties list")%>";
lab_h_arr[463] = "<%=pageData.getWord("The upload application will open in a new window")%>";
lab_h_arr[464] = "<%=pageData.getWord("The current image will be shown in the upload application view area")%>";
lab_h_arr[465] = "<%=pageData.getWord("Select a new image by browsing your folders or enter the location of the new image in the text field")%>";
lab_h_arr[466] = "<%=pageData.getWord("Click 'upload' to change the image to the new selection")%>";
lab_h_arr[467] = "<%=pageData.getWord("The new image will appear in the form builder work space and in the view area of the upload application")%>";

lab_h_arr[468] = "<%=pageData.getWord("Section Break")%>";
lab_h_arr[469] = "<%=pageData.getWord("Used to display a bar")%>";
lab_h_arr[470] = "<%=pageData.getWord("The item generated on the page can be used to indicate breaks in sections of the page or the height and width can be modify and the item used as a background canvas")%>";
lab_h_arr[471] = "<%=pageData.getWord("Section Break properties")%>";
lab_h_arr[472] = "<%=pageData.getWord("Sets the fill color for a section break")%>";
lab_h_arr[473] = "<%=pageData.getWord("Search query cannot contain")%>";
lab_h_arr[474] = "<%=pageData.getWord("Search query must contain more than 3 characters")%>";
lab_h_arr[475] = "<%=pageData.getWord("Sorry")%>";
lab_h_arr[476] = "<%=pageData.getWord("Your search for")%>";
lab_h_arr[477] = "<%=pageData.getWord("was unsucessful")%>";
lab_h_arr[478] = "<%=pageData.getWord("No results match your search criteria")%>";
lab_h_arr[479] = "<%=pageData.getWord("Please try another search")%>";
lab_h_arr[480] = "<%=pageData.getWord("Found")%>";
lab_h_arr[481] = "<%=pageData.getWord("sections containing the text")%>";