var lab_arr = new Array();
lab_arr[0] = "<%=pageData.getWord("Add page")%>";
lab_arr[1] = "<%=pageData.getWord("Page")%>";
lab_arr[2] = "<%=pageData.getWord("Page name")%>";
lab_arr[3] = "<%=pageData.getWord("Add")%>";
lab_arr[4] = "<%=pageData.getWord("Cancel")%>";
lab_arr[5] = "<%=pageData.getWord("Please enter a page name")%>";
lab_arr[6] = "<%=pageData.getWord("Are you sure you want to delete this object?")%>";
lab_arr[7] = "<%=pageData.getWord("Add row")%>";
lab_arr[8] = "<%=pageData.getWord("Delete")%>";
lab_arr[9] = "<%=pageData.getWord("Save")%>";
lab_arr[10] = "<%=pageData.getWord("List of values")%>";
lab_arr[11] = "<%=pageData.getWord("Description")%>";
lab_arr[12] = "<%=pageData.getWord("Default")%>";
lab_arr[13] = "<%=pageData.getWord("Datasource")%>";
lab_arr[14] = "<%=pageData.getWord("Table")%>";
lab_arr[15] = "<%=pageData.getWord("Form name should not be empty")%>";
lab_arr[16] = "<%=pageData.getWord("Colors pannel")%>";
lab_arr[17] = "<%=pageData.getWord("Ok")%>";
lab_arr[18] = "<%=pageData.getWord("Code")%>";
lab_arr[19] = "<%=pageData.getWord("Are you sure you want to delete this page?")%>";
lab_arr[20] = "<%=pageData.getWord("Please enter form name")%>";
lab_arr[21] = "<%=pageData.getWord("Field")%>";
lab_arr[22] = "<%=pageData.getWord("Database configuration")%>";
lab_arr[23] = "<%=pageData.getWord("Add database")%>";
lab_arr[24] = "<%=pageData.getWord("Close")%>";
lab_arr[25] = "<%=pageData.getWord("Add Parameter")%>";
lab_arr[26] = "<%=pageData.getWord("Parameters configuration")%>";
lab_arr[27] = "<%=pageData.getWord("Where Clause Config.")%>";
lab_arr[28] = "<%=pageData.getWord("Database")%>";
lab_arr[29] = "<%=pageData.getWord("Add Where Clause")%>";
lab_arr[30] = "<%=pageData.getWord("From table")%>";
lab_arr[31] = "<%=pageData.getWord("Where Field")%>";
lab_arr[32] = "<%=pageData.getWord("Dest. type")%>";
lab_arr[33] = "<%=pageData.getWord("Dest. table")%>";
lab_arr[34] = "<%=pageData.getWord("Dest. Field")%>";
lab_arr[35] = "<%=pageData.getWord("Dest. Param")%>";
lab_arr[36] = "<%=pageData.getWord("Fields list")%>";
lab_arr[37] = "<%=pageData.getWord("Are you sure you want to delete this parameter?")%>";
lab_arr[38] = "<%=pageData.getWord("Are you sure you want to remove the link to this database?")%>";
lab_arr[39] = "<%=pageData.getWord("Tables configuration")%>";
lab_arr[40] = "<%=pageData.getWord("Tables list")%>";
lab_arr[41] = "<%=pageData.getWord("Test Connection")%>";
lab_arr[42] = "<%=pageData.getWord("Properties list")%>";
lab_arr[43] = "<%=pageData.getWord("RGB")%>";
lab_arr[44] = "<%=pageData.getWord("Connection succeded")%>";
lab_arr[45] = "<%=pageData.getWord("Connection failed")%>";
lab_arr[46] = "<%=pageData.getWord("Parameter")%>";
lab_arr[47] = "<%=pageData.getWord("List forms")%>";
lab_arr[48] = "<%=pageData.getWord("Pop:")%>";
lab_arr[49] = "<%=pageData.getWord("Databases list")%>";
lab_arr[50] = "<%=pageData.getWord("Please do not forget that you must have at least one page in your form") %>";
lab_arr[51] = "<%=pageData.getWord("Delete item") %>";
lab_arr[52] = "<%=pageData.getWord("This form name already exists, please enter another one") %>";
lab_arr[53] = "<%=pageData.getWord("Page properties") %>";
lab_arr[54] = "<%=pageData.getWord("Delete page")%>";
lab_arr[55] = "<%=pageData.getWord("from table should not be empty, please choose one") %>";
lab_arr[56] = "<%=pageData.getWord("from field should not be empty, please choose one") %>";
lab_arr[57] = "<%=pageData.getWord("To parameter should not be empty, please choose one") %>";
lab_arr[58] = "<%=pageData.getWord("To table should not be empty, please choose one") %>";
lab_arr[59] = "<%=pageData.getWord("To field should not be empty, please choose one") %>";
lab_arr[60] = "<%=pageData.getWord("The path sould not be empty, please enter one") %>";
lab_arr[61] = "<%=pageData.getWord("Database Label already exists, please enter another one") %>";
lab_arr[62] = "<%=pageData.getWord("Save as form") %>";
lab_arr[63] = "<%=pageData.getWord("Form name") %>";
lab_arr[64] = "<%=pageData.getWord("You cannot add filter to a table already used as filter for another table, please change it") %>";
lab_arr[65] = "<%=pageData.getWord("You cannot use table as filter before defining the filters for it, please change it") %>";
lab_arr[66] = "<%=pageData.getWord("Files path") %>";
lab_arr[67] = "<%=pageData.getWord("Path for the php genration files") %>";
lab_arr[68] = "<%=pageData.getWord("should not be empty") %>";
lab_arr[69] = "<%=pageData.getWord("value should be greater than") %>";
lab_arr[70] = "<%=pageData.getWord("value should be less than") %>";
lab_arr[71] = "<%=pageData.getWord("Name") %>";
lab_arr[72] = "<%=pageData.getWord("Properties") %>";
lab_arr[73] = "<%=pageData.getWord("Master") %>";
lab_arr[74] = "<%=pageData.getWord("You must choose a master") %>";
lab_arr[75] = "<%=pageData.getWord("Outbound form should be related to one calling list") %>";
lab_arr[76] = "<%=pageData.getWord("You should add elements related to") %>";
lab_arr[77] = "<%=pageData.getWord("Please enter a valid hexadecimal color value")%>";
lab_arr[78] = "<%=pageData.getWord("This page name already exists, please enter another one") %>";
lab_arr[79] = "<%=pageData.getWord("Color should not be empty, please choose one") %>";
lab_arr[80] = "<%=pageData.getWord("Please enter a unique code") %>";
lab_arr[81] = "<%=pageData.getWord("Please enter a unique description") %>";
lab_arr[82] = "<%=pageData.getWord("Please remove the specified characters") %>";
lab_arr[83] = "<%=pageData.getWord("Are you sure you want to delete this form?") %>";
lab_arr[84] = "<%=pageData.getWord("Delete form") %>";
lab_arr[85] = "<%=pageData.getWord("This parameter already exists, please enter another one") %>";
lab_arr[86] = "<%=pageData.getWord("List tables [Displayed in insert order]") %>";
lab_arr[87] = "<%=pageData.getWord("Warning:") %>";
lab_arr[88] = "<%=pageData.getWord("Are you sure you want to remove this condition?") %>";
lab_arr[89] = "<%=pageData.getWord("Please verify the order of insert for the tables") %>";
lab_arr[90] = "<%=pageData.getWord("Type:")%>";
lab_arr[91] = "<%=pageData.getWord("Name:") %>";
lab_arr[92] = "<%=pageData.getWord("Created:") %>";
lab_arr[93] = "<%=pageData.getWord("Created by:") %>";
lab_arr[94] = "<%=pageData.getWord("Last modified:") %>";
lab_arr[95] = "<%=pageData.getWord("Modified by:") %>";
lab_arr[96] = "<%=pageData.getWord("Database information") %>";
lab_arr[97] = "<%=pageData.getWord("Outbound") %>";
lab_arr[98] = "<%=pageData.getWord("Inbound") %>";
lab_arr[99] = "<%=pageData.getWord("Form Properties") %>";
lab_arr[100] = "<%=pageData.getWord("Elements triggers") %>";
lab_arr[101] = "<%=pageData.getWord("Add element trigger") %>";
lab_arr[102] = "<%=pageData.getWord("Trigger page") %>";
lab_arr[103] = "<%=pageData.getWord("Element") %>";
lab_arr[104] = "<%=pageData.getWord("Operator") %>";
lab_arr[105] = "<%=pageData.getWord("Value") %>";
lab_arr[106] = "<%=pageData.getWord("Action") %>";
lab_arr[107] = "<%=pageData.getWord("Action page") %>";
lab_arr[108] = "<%=pageData.getWord("Values") %>";
lab_arr[109] = "<%=pageData.getWord("Trigger and action elements should be different") %>";
lab_arr[110] = "<%=pageData.getWord("Check") %>";
lab_arr[111] = "<%=pageData.getWord("Uncheck") %>";
lab_arr[112] = "<%=pageData.getWord("Are you sure you want to delete this trigger?")%>";
lab_arr[113] = "<%=pageData.getWord("Are you sure you want to delete this row?")%>";
lab_arr[114] = "<%=pageData.getWord("Trigger name") %>";
lab_arr[116] = "<%=pageData.getWord("Type")%>";
lab_arr[117] = "<%=pageData.getWord("You have changed the name of this form.")%>";
lab_arr[118] = "<%=pageData.getWord("Clicking 'OK' will overwrite form:")%>";
lab_arr[119] = "<%=pageData.getWord("If you want to keep the original form")%>";
lab_arr[120] = "<%=pageData.getWord("click 'Cancel' and select 'Save as' from the file menu")%>";
lab_arr[121] = "<%=pageData.getWord("Changing form state...")%>";
lab_arr[122] = "<%=pageData.getWord("Please wait")%>";
lab_arr[123] = "<%=pageData.getWord("Saving form...")%>";
lab_arr[124] = "<%=pageData.getWord("before setting the state to inactive.")%>";
lab_arr[125] = "<%=pageData.getWord("Changes have been made to the form.")%>";
lab_arr[126] = "<%=pageData.getWord("Clicking 'OK' will save these changes and set the form state to inactive.")%>";
lab_arr[127] = "<%=pageData.getWord("Click 'Cancel' to make further alterations.")%>";
lab_arr[128] = "<%=pageData.getWord("Event name should not be empty")%>";
lab_arr[129] = "<%=pageData.getWord("Event page should not be empty")%>";
lab_arr[130] = "<%=pageData.getWord("Event element should not be empty")%>";
lab_arr[131] = "<%=pageData.getWord("Action page should not be empty")%>";
lab_arr[132] = "<%=pageData.getWord("Action element should not be empty")%>";
lab_arr[133] = "<%=pageData.getWord("You should not have same data for 2 triggers")%>";
lab_arr[134] = "<%=pageData.getWord("Name shoud be unique")%>";
lab_arr[135] = "<%=pageData.getWord("Changes have been made to your current form.")%>";
lab_arr[136] = "<%=pageData.getWord("If you continue any unsaved data will be lost.")%>";
lab_arr[137] = "<%=pageData.getWord("Loading form...")%>";
lab_arr[138] = "<%=pageData.getWord("You will lose any unsaved data.")%>";