package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.*;
import aheevaManager.ressources.*;
import java.util.*;
import jxl.*;

public final class Activity1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Add an Activity1</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
    pageData.openConnection();


      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("<LINK href=\"style.css\" type=text/css rel=stylesheet >\r\n");
      out.write("<LINK href=\"livestats.css\" \trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<meta http-equiv=Content-Language content=en-us>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<script language=JavaScript src=\"jsUtil.js\"></script>\r\n");
      out.write("<script language=javascript src=\"Browser.js\" type=text/javascript></script>\r\n");
      out.write("\r\n");
      out.write("<script language=javascript type=text/javascript>\r\n");
      out.write("/*\r\n");
      out.write("var NRR_DBID       \t= '';\r\n");
      out.write("var NRRName          \t= '';\r\n");
      out.write("var notReadyReasonName\t\t= '';\r\n");
      out.write("var tenant_dbid\t\t= \"NULL\";\r\n");
      out.write("*/\r\n");
      out.write("function enabledUpdateButton()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById(\"updateInfo\").disabled = false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checkOnUnload()\r\n");
      out.write("{\r\n");
      out.write("\t//document.nrr.updateInfo.disabled = false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function enableReload()\r\n");
      out.write("{\r\n");
      out.write("   appletObj.fReloadMenu = true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function displayActivityInfo()\r\n");
      out.write("{\r\n");
      out.write("\tvar activityName;\r\n");
      out.write("\r\n");
      out.write("\ttenant_dbid = normalizeString(QueryString('tenant_dbid'));\r\n");
      out.write("\tactivity_dbid = normalizeString(QueryString('activity_dbid'));   //activity_dbid=\"+anActivity[0]+\"\r\n");
      out.write("\tactivityName   = normalizeString(QueryString('activity_name'));\r\n");
      out.write("\t\r\n");
      out.write("\tif(activityName == '' || activityName == 'null')\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById(\"updateInfo\").value = \"");
      out.print( pageData.getWord("Save"));
      out.write("\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//document.getElementById(\"deleteActivity\").disabled = true;\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById(\"activity_name\").value = activityName;\r\n");
      out.write("\t\tdocument.getElementById(\"updateInfo\").disabled = false;\r\n");
      out.write("\t\tdocument.getElementById(\"activity_dbid\").value = activity_dbid;\r\n");
      out.write("\t\t//document.getElementById(\"deleteActivity\").disabled = false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function validateInfo()\r\n");
      out.write("{\r\n");
      out.write("\tvar can_save = true, \r\n");
      out.write("\t\tactivity_name = document.getElementById(\"activity_name\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("\tif(activity_name.length == 0){\r\n");
      out.write("\t\talert('");
      out.print( pageData.getWord("Activity name cannot be null"));
      out.write("');\t\r\n");
      out.write("\t\tdocument.getElementById(\"activity_name\").focus();\t\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// Verify if Activity name contains spaces only\r\n");
      out.write("\t\r\n");
      out.write("\tif(allSpaces(activity_name) == '0')\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert('");
      out.print( pageData.getWord("The activity name cannot be all space(s)"));
      out.write("');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar activities = appletObj.getActivities() + \"\";\r\n");
      out.write("\t\r\n");
      out.write("\tvar jsActivities = activities.split(\"|\");\r\n");
      out.write("\t\r\n");
      out.write("\tfor (var i = 0; i < jsActivities.length; i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar one_activity = jsActivities[i].split(\"^\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif ( (activity_name == one_activity[1]) && (one_activity[2] == tenant_dbid)  )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tcan_save = false;\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif (can_save == true)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif (document.getElementById(\"updateInfo\").value == \"Save\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\r\n");
      out.write("\t\t\tif ((validation(activity_name) != 0))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tappletObj.saveActivity(tenant_dbid, activity_name);\r\n");
      out.write("\t\t\t\tdocument.location = \"./Activity1.jsp?tenant_dbid=\"+tenant_dbid;\r\n");
      out.write("\t\t\t\tenableReload();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"");
      out.print( pageData.getWord("Invalid use of character"));
      out.write("\");\r\n");
      out.write("\t\t\t\treturn ;\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif ((validation(activity_name) != 0))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar values = document.getElementById(\"activity_dbid\").value + \"^\" + activity_name;\r\n");
      out.write("\t\t\t\tappletObj.modifyActivity(values);\r\n");
      out.write("\t\t\t\tdocument.location = \"./Activity1.jsp?tenant_dbid=\"+tenant_dbid;\r\n");
      out.write("\t\t\t\tenableReload();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert('");
      out.print( pageData.getWord("Invalid use of character"));
      out.write("');\r\n");
      out.write("\t\t\t\treturn ;\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("This activity already exists. Please choose another name !"));
      out.write("\");\r\n");
      out.write("\t\tdocument.getElementById(\"activity_name\").value = \"\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/***********************************************************************\r\n");
      out.write("************************************************************************/\r\n");
      out.write("\r\n");
      out.write("function askDelete()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\tanswer = confirm('");
      out.print( pageData.getWord("Are you sure, you wish to delete this activity? This can affect your reports!!"));
      out.write("');\r\n");
      out.write("\tif(answer)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif (document.getElementById(\"activity_name\").value != '')\r\n");
      out.write("\t\t\tappletObj.deleteActivity(document.getElementById(\"activity_name\").value);\r\n");
      out.write("\t\t// refresh the current page\r\n");
      out.write("\t\tdocument.location = \"../defaultpage.htm\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!--<body BGCOLOR=\"#C0C0C0\" TEXT=\"#000000\" LINK=\"#000066\" VLINK=\"#666666\" onLoad=\"displayCampaignInfo()\" onUnload=\" return checkOnUnload()\"> -->\r\n");
      out.write("<script language=javascript id=clientEventHandlersJS>\r\n");
      out.write("<!--\r\n");
      out.write("//function Checkbox4_onclick() {}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .contentText{\r\n");
      out.write("\tfont:\t\t\t12px Tahoma;\r\n");
      out.write("\tcolor:\t\t\tBlack;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\tclear:\t\t\tboth;\r\n");
      out.write("\tborder:\t\t\t1px solid rgb( 145, 155, 156 );\r\n");
      out.write("\tbackground:\t\trgb( 252, 252, 254 );\r\n");
      out.write("\tz-index:\t\t2;\r\n");
      out.write("\tposition:\t\trelative;\r\n");
      out.write("\ttop:\t\t\t-2px;\r\n");
      out.write("\r\n");
      out.write("\tfont:\t\t\t11px Tahoma;\r\n");
      out.write("\tcolor:\t\t\tBlack;\r\n");
      out.write("\r\n");
      out.write("\tfilter:\t\t\tprogid:DXImageTransform.Microsoft.Gradient(StartColorStr=#fffcfcfe, EndColorStr=#fff4f3ee, GradientType=0)\r\n");
      out.write("\t\t\t\t\tprogid:DXImageTransform.Microsoft.Shadow(Color=#ff919899, Strength=2, Direction=135);\r\n");
      out.write("\r\n");
      out.write("\t/* 244, 243, 238 */\r\n");
      out.write("\t/*145, 155, 156 */\r\n");
      out.write("\tpadding:\t\t10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-row {\r\n");
      out.write("\tz-index:\t\t1;\r\n");
      out.write("\twhite-space:\tnowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-row .tab.selected {\r\n");
      out.write("\twidth:\t\t\t\t74px  ;\r\n");
      out.write("\theight:\t\t\t\t18px  ;\r\n");
      out.write("\tbackground-image:\turl( \"tab.active.png\" )  ;\r\n");
      out.write("\tbackground-repaet:\tno-repeat;\r\n");
      out.write("\r\n");
      out.write("\tborder-bottom-width:\t0;\r\n");
      out.write("\tz-index:\t\t3;\r\n");
      out.write("\tpadding:\t\t2px 0 0px 0;\r\n");
      out.write("\tmargin:\t\t\t1px -3px -3px 0px;\r\n");
      out.write("\ttop:\t\t\t-2px;\r\n");
      out.write("\tfont:\t\t\t11px Tahoma;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-row .tab a {\r\n");
      out.write("\tfont:\t\t\t\t11px Tahoma;\r\n");
      out.write("\tcolor:\t\t\t\tBlack;\r\n");
      out.write("\ttext-decoration:\tnone;\r\n");
      out.write("\tcursor:\t\t\t\tdefault;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-row .tab.hover {\r\n");
      out.write("\tfont:\t\t\t\t11px Tahoma;\r\n");
      out.write("\twidth:\t\t\t\t70px;\r\n");
      out.write("\theight:\t\t\t\t16px;\r\n");
      out.write("\tbackground-image:\turl( \"tab.hover.png\" );\r\n");
      out.write("\tbackground-repaet:\tno-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page {\r\n");
      out.write("/*\theight:\t\t200px;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html, body {\r\n");
      out.write("\tbackground:\tThreeDFace;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("\tmargin:\t\t0;\r\n");
      out.write("\tpadding:\t0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* over ride styles from webfxlayout */\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:\t\t10px;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("\theight:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control h2 {\r\n");
      out.write("\ttext-align:\tcenter;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control h2 a {\r\n");
      out.write("\tdisplay:\tinline;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control a:hover {\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" .dynamic-tab-pane-control.tab-pane {\r\n");
      out.write("\tposition:\trelative;\r\n");
      out.write("\twidth:\t\t100%;\r\n");
      out.write("\tmargin-right:\t-2px;\r\n");
      out.write("/*\theight:\t\t200px;*/\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("    // Associate a default button with pressing the Enter key\r\n");
      out.write("\tfunction KeyDownHandler(btn)\r\n");
      out.write("    {\r\n");
      out.write("        // process only the Enter key\r\n");
      out.write("        if (event.keyCode == 13)\r\n");
      out.write("        {\r\n");
      out.write("            // cancel the default submit\r\n");
      out.write("            event.returnValue=false;\r\n");
      out.write("            event.cancel = true;\r\n");
      out.write("            // submit the form by programmatically clicking the specified button\r\n");
      out.write("            btn.click();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\t<body class=\"f_i_act_body\" onLoad=\"displayActivityInfo()\">\r\n");
      out.write("\t\t<div class=\"dynamic-tab-pane-control\">\r\n");
      out.write("\t\t\t<div class=\"tab-pane\" id=\"tabPane1\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("    <div class=\"tab-page\" id=\"general\"> \r\n");
      out.write("      <fieldset>\r\n");
      out.write("      <legend> \r\n");
      out.write("      ");
      out.print( pageData.getWord("General"));
      out.write("\r\n");
      out.write("      </legend>\r\n");
      out.write("      <form name=\"theForm\" onKeyDown=\"KeyDownHandler(updateInfo)\">\r\n");
      out.write("        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\" width=\"100%\">\r\n");
      out.write("          <tr> \r\n");
      out.write("            <td width='30%' height=25> <div align=\"center\"> \r\n");
      out.write("               ");
      out.print( pageData.getWord("Activity name1"));
      out.write("\r\n");
      out.write("                &nbsp;&nbsp; </div></td>\r\n");
      out.write("            <td align=left width='70%' height=25> <input id=\"activity_name\" type=text onChange=\"enabledUpdateButton()\" onClick=\"enabledUpdateButton()\" size=30 name=\"activity_name\"> \r\n");
      out.write("              <input type=\"hidden\" id=\"activity_dbid\" name=\"activity_dbid\" value=\"\"> \r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr> \r\n");
      out.write("            <td width='30%' height=\"60\"></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("      </form>\r\n");
      out.write("      </fieldset>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t<tr valign=\"top\">\r\n");
      out.write("\t\t\t\t<td align=\"left\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<input disabled  id=\"updateInfo\"  name=\"updateInfo\" type=\"button\" value='");
      out.print( pageData.getWord("Update"));
      out.write("' onClick=\"validateInfo()\">&nbsp;\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("</body>\r\n");
 pageData.closeConnection(); 
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
