package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.*;
import aheevaManager.ressources.*;
import java.util.*;
import jxl.*;
import java.text.*;
import aheevaManager.schedule.*;
import aheevaManager.ressources.*;
import java.util.*;
import jxl.*;

public final class adherenceReport1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/aheevaManager/Resources_pages/xc2_default_labels.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
    pageData.openConnection();

      out.write("\r\n");
      out.write("<LINK href=\"style.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"xc2_default.css\" type=\"text/css\">\r\n");
      out.write("<LINK href=\"livestats.css\" \trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" >\r\n");
      out.write("\r\n");
      out.write("<!-- Start Tab pane -->\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"tab_luna.css\" />\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style_2.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\" href=\"slider/css/luna.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t100px;\r\n");
      out.write("}\r\n");
      out.write("html, body {\r\n");
      out.write("\t/*background:\tThreeDFace;*/\r\n");
      out.write("}\r\n");
      out.write("form {\r\n");
      out.write("\tmargin:\t\t0;\r\n");
      out.write("\tpadding:\t0;\r\n");
      out.write("}\r\n");
      out.write("/* over ride styles from webfxlayout */\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:\t\t10px;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("\theight:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 {\r\n");
      out.write("\ttext-align:\tcenter;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 a {\r\n");
      out.write("\tdisplay:\tinline;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control a:hover {\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../Resources_pages/tabpane.js\"></script>\r\n");
      out.write("<!-- End Tab Pane -->\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\" src=\"jsUtil.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Browser.js\"></script>\r\n");
      out.write("<!-- Calendrier début -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pagexc2Data = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pagexc2Data.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
pagexc2Data.openConnection();
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("// variables of labels;// \r\n");
      out.write("var phrase= new Array();\r\n");
      out.write("phrase[0]=\"");
      out.print( pagexc2Data.getWord("January"));
      out.write("\";\r\n");
      out.write("phrase[1]=\"");
      out.print( pagexc2Data.getWord("February"));
      out.write("\";\r\n");
      out.write("phrase[2]=\"");
      out.print( pagexc2Data.getWord("March"));
      out.write("\";\r\n");
      out.write("phrase[3]=\"");
      out.print( pagexc2Data.getWord("April"));
      out.write("\";\r\n");
      out.write("phrase[4]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";         \r\n");
      out.write("phrase[5]=\"");
      out.print( pagexc2Data.getWord("June"));
      out.write("\";\r\n");
      out.write("phrase[6]=\"");
      out.print( pagexc2Data.getWord("July"));
      out.write("\";\r\n");
      out.write("phrase[7]=\"");
      out.print( pagexc2Data.getWord("August"));
      out.write("\";\r\n");
      out.write("phrase[8]=\"");
      out.print( pagexc2Data.getWord("September"));
      out.write("\";\r\n");
      out.write("phrase[9]=\"");
      out.print( pagexc2Data.getWord("October"));
      out.write("\";\r\n");
      out.write("phrase[10]=\"");
      out.print( pagexc2Data.getWord("November"));
      out.write("\";\r\n");
      out.write("phrase[11]=\"");
      out.print( pagexc2Data.getWord("December"));
      out.write("\";\r\n");
      out.write("phrase[12]=\"");
      out.print( pagexc2Data.getWord("Jan"));
      out.write("\";\r\n");
      out.write("phrase[13]=\"");
      out.print( pagexc2Data.getWord("Feb"));
      out.write("\";\r\n");
      out.write("phrase[14]=\"");
      out.print( pagexc2Data.getWord("Mar"));
      out.write("\";\r\n");
      out.write("phrase[15]=\"");
      out.print( pagexc2Data.getWord("Apr"));
      out.write("\";\r\n");
      out.write("phrase[16]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";\r\n");
      out.write("phrase[17]=\"");
      out.print( pagexc2Data.getWord("Jun"));
      out.write("\";\r\n");
      out.write("phrase[18]=\"");
      out.print( pagexc2Data.getWord("Jul"));
      out.write("\";\r\n");
      out.write("phrase[19]=\"");
      out.print( pagexc2Data.getWord("Aug"));
      out.write("\";\r\n");
      out.write("phrase[20]=\"");
      out.print( pagexc2Data.getWord("Sep"));
      out.write("\";\r\n");
      out.write("phrase[21]=\"");
      out.print( pagexc2Data.getWord("Oct"));
      out.write("\";\r\n");
      out.write("phrase[22]=\"");
      out.print( pagexc2Data.getWord("Nov"));
      out.write("\";\r\n");
      out.write("phrase[23]=\"");
      out.print( pagexc2Data.getWord("Dec"));
      out.write("\";\r\n");
      out.write("phrase[24]=\"");
      out.print( pagexc2Data.getWord("Sunday"));
      out.write("\";\r\n");
      out.write("phrase[25]=\"");
      out.print( pagexc2Data.getWord("Monday"));
      out.write("\";\r\n");
      out.write("phrase[26]=\"");
      out.print( pagexc2Data.getWord("Tuesday"));
      out.write("\";\r\n");
      out.write("phrase[27]=\"");
      out.print( pagexc2Data.getWord("Wednesday"));
      out.write("\";\r\n");
      out.write("phrase[28]=\"");
      out.print( pagexc2Data.getWord("Thursday"));
      out.write("\";\r\n");
      out.write("phrase[29]=\"");
      out.print( pagexc2Data.getWord("Friday"));
      out.write("\";\r\n");
      out.write("phrase[30]=\"");
      out.print( pagexc2Data.getWord("Saturday"));
      out.write("\";\r\n");
      out.write("phrase[31]=\"");
      out.print( pagexc2Data.getWord("Sun"));
      out.write("\";\r\n");
      out.write("phrase[32]=\"");
      out.print( pagexc2Data.getWord("Mon"));
      out.write("\";\r\n");
      out.write("phrase[33]=\"");
      out.print( pagexc2Data.getWord("Tue"));
      out.write("\";\r\n");
      out.write("phrase[34]=\"");
      out.print( pagexc2Data.getWord("Wed"));
      out.write("\";\r\n");
      out.write("phrase[35]=\"");
      out.print( pagexc2Data.getWord("Thu"));
      out.write("\";\r\n");
      out.write("phrase[36]=\"");
      out.print( pagexc2Data.getWord("Fri"));
      out.write("\";\r\n");
      out.write("phrase[37]=\"");
      out.print( pagexc2Data.getWord("Sat"));
      out.write("\";\r\n");
      out.write("phrase[38]=\"");
      out.print( pagexc2Data.getWord("Su"));
      out.write("\";\r\n");
      out.write("phrase[39]=\"");
      out.print( pagexc2Data.getWord("Mo"));
      out.write("\";\r\n");
      out.write("phrase[40]=\"");
      out.print( pagexc2Data.getWord("Tu"));
      out.write("\";\r\n");
      out.write("phrase[41]=\"");
      out.print( pagexc2Data.getWord("We"));
      out.write("\";\r\n");
      out.write("phrase[42]=\"");
      out.print( pagexc2Data.getWord("Th"));
      out.write("\";\r\n");
      out.write("phrase[43]=\"");
      out.print( pagexc2Data.getWord("Fr"));
      out.write("\";\r\n");
      out.write("phrase[44]=\"");
      out.print( pagexc2Data.getWord("Sa"));
      out.write("\";\r\n");
      out.write("phrase[45]=\"");
      out.print( pagexc2Data.getWord(" Today "));
      out.write("\";\r\n");
      out.write("phrase[46]=\"");
      out.print( pagexc2Data.getWord("Clear"));
      out.write("\";\r\n");
      out.write("phrase[47]=\"");
      out.print( pagexc2Data.getWord("Back"));
      out.write("\";\r\n");
      out.write("phrase[48]=\"");
      out.print( pagexc2Data.getWord("Close"));
      out.write("\";\r\n");
      out.write("phrase[49]=\"");
      out.print( pagexc2Data.getWord("Reset"));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 pagexc2Data.closeConnection(); 
      out.write("\r\n");
      out.write("<script language=\"javascript\" src=\"xc2_default.js\"></script>\r\n");
      out.write("<script language=\"javascript\">xcAutoHide=1000;</script>\r\n");
      out.write("<script language=\"javascript\" src=\"xc2_inpage.js\"></script>\r\n");
      out.write("<!-- Calendrier fin -->\r\n");
      out.write("<script language=\"JavaScript\" src=\"jsUtil.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("\r\n");
      out.write("var tenant_dbid = normalizeString(QueryString('tenant_dbid'));\r\n");
      out.write("var agentGroups = String( appletObj.getAgentGroupByName(tenant_dbid) );\r\n");
      out.write("\r\n");
      out.write("function sortSelect(o)\r\n");
      out.write("{\r\n");
      out.write("\t/*var o = new Array();\r\n");
      out.write("\tif (obj.options==null) { return; }\r\n");
      out.write("\tfor (var i=0; i<obj.options.length; i++) {\r\n");
      out.write("\t\to[o.length] = new Option( obj.options[i].text, obj.options[i].value, obj.options[i].defaultSelected, obj.options[i].selected) ;\r\n");
      out.write("\t\t}*/\r\n");
      out.write("\tif (o.length==0) { return; }\r\n");
      out.write("\r\n");
      out.write("\tif(document.theForm.viewckbox.checked == false){\r\n");
      out.write("\t\to = o.sort(\r\n");
      out.write("\t\t\tfunction(a,b) {\r\n");
      out.write("\t\t\t\tif ((a.text+\"\") < (b.text+\"\")) { return -1; }\r\n");
      out.write("\t\t\t\tif ((a.text+\"\") > (b.text+\"\")) { return 1; }\r\n");
      out.write("\t\t\t\treturn 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\to = o.sort(\r\n");
      out.write("\t\t\tfunction(a,b) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (parseInt(a.value) < parseInt(b.value)) { return -1; }\r\n");
      out.write("\t\t\t\t\tif (parseInt(a.value) > parseInt(b.value)) { return 1; }\r\n");
      out.write("\t\t\t\t\treturn 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t}\r\n");
      out.write("\t/*for (var i=0; i<o.length; i++) {\r\n");
      out.write("\t\tobj.options[i] = new Option(o[i].text, o[i].value, o[i].defaultSelected, o[i].selected);\r\n");
      out.write("\t\t}*/\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fillObjectCombo()\r\n");
      out.write("{\r\n");
      out.write("\t//var vValue = normalizeString(QueryString('type'));\r\n");
      out.write("\t\tvar agents = String( appletObj.getAgentsByName(tenant_dbid) );\r\n");
      out.write("\t\tvar o = new Array();\r\n");
      out.write("\r\n");
      out.write("\t/*Fill agents combo box with agents name*/\r\n");
      out.write("        var jsAgents = agents + \"\";\r\n");
      out.write("    \tarrayAgents = jsAgents.split(\"|\");\r\n");
      out.write("    \tif(agents.length > 0 ){\r\n");
      out.write("    \t\tfor (j = 0; j <arrayAgents.length; j++){\r\n");
      out.write("    \t\t\tvar iStartPos = arrayAgents[j].indexOf('[');\r\n");
      out.write("    \t\t\tvar iEndPos   = arrayAgents[j].indexOf(']');\r\n");
      out.write("    \t\t\tvar login\t  = arrayAgents[j].substr(iStartPos+1,iEndPos-iStartPos-1);\r\n");
      out.write("\t\t\t\tvar name = login+'['+arrayAgents[j].substr(0,iStartPos)+']';\r\n");
      out.write("\t\t\t\tif (document.theForm.viewckbox.checked == false)\t  \t\t// show agents name as : firstname, lastname[login]\r\n");
      out.write("      \t\t\t\tmyOption = new Option(arrayAgents [j],login)\r\n");
      out.write("\t\t\t\telse\t\t\t\t\t\t\t\t\t// show agents name as : login[firstname, lastname]\r\n");
      out.write("\t\t\t\t\tmyOption = new Option(name,login)\r\n");
      out.write("\t\t\t\t//optionPos = objects.options.length\r\n");
      out.write("\t\t\t\t//objects.options[optionPos]=myOption\r\n");
      out.write("\t\t\t\to[o.length]= myOption;\r\n");
      out.write("\r\n");
      out.write("    \t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//Sort the object\r\n");
      out.write("\t\tsortSelect(o);\r\n");
      out.write("\t\t/*o = o.sort(\r\n");
      out.write("\t\t\t\tfunction(a,b) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tif (parseInt(a.value) < parseInt(b.value)) { return -1; }\r\n");
      out.write("\t\t\t\t\t\tif (parseInt(a.value) > parseInt(b.value)) { return 1; }\r\n");
      out.write("\t\t\t\t\t\treturn 0;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t); */\r\n");
      out.write("\t\tfor (var i=0; i<o.length; i++) {\r\n");
      out.write("\t\t\tdocument.theForm.objects.options[i+1] = new Option(o[i].text, o[i].value, o[i].defaultSelected, o[i].selected);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("        /*Fill agents group combo box with agent group name*/\r\n");
      out.write("        var jsAgentGroups = agentGroups + \"\";\r\n");
      out.write("    \tarrayGroups = jsAgentGroups.split(\"|\");\r\n");
      out.write("    \tfor (j = 0; j <arrayGroups.length; j++){\r\n");
      out.write("    \t\tmyOption = new Option(arrayGroups[j],arrayGroups[j])\r\n");
      out.write("\t\t\toptionPos = document.theForm.agtGrp.options.length\r\n");
      out.write("\t\t\tdocument.theForm.agtGrp.options[optionPos]=myOption\r\n");
      out.write("    \t}\r\n");
      out.write("  // sortSelect(document.theForm.objects);\r\n");
      out.write("\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getAgentsInGroup()\r\n");
      out.write("{\r\n");
      out.write("\tvar o = new Array();\r\n");
      out.write("\tif(document.theForm.agtGrp.value =='AllGroups')\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//Empty the agents combo box\r\n");
      out.write("\t\tvar j=document.theForm.objects.options.length;\r\n");
      out.write("        if (j>0){\r\n");
      out.write("           document.theForm.objects.length = 0;\r\n");
      out.write("        }\r\n");
      out.write("        var defaultvalue =  \"- All Agents -\" ;\r\n");
      out.write("\t\tmyOption = new Option(defaultvalue,\"AllAgents\")\r\n");
      out.write("\t\t//optionPos = document.theForm.objects.options.length\r\n");
      out.write("\t\t//document.theForm.objects.options[optionPos]=myOption\r\n");
      out.write("\t\to[o.length]= myOption;\r\n");
      out.write("\r\n");
      out.write("\t\t//fillObjectCombo();\r\n");
      out.write("        var agents = String( appletObj.getAgentsByName(tenant_dbid) );\r\n");
      out.write("        var jsAgents = agents + \"\";\r\n");
      out.write("    \tarrayAgents = jsAgents.split(\"|\");\r\n");
      out.write("    \tif(agents.length > 0 ){\r\n");
      out.write("    \t\tfor (j = 0; j <arrayAgents.length; j++){\r\n");
      out.write("    \t\t\tvar iStartPos = arrayAgents[j].indexOf('[');\r\n");
      out.write("    \t\t\tvar iEndPos   = arrayAgents[j].indexOf(']');\r\n");
      out.write("    \t\t\tvar login\t  = arrayAgents[j].substr(iStartPos+1,iEndPos-iStartPos-1);\r\n");
      out.write("\t\t\t\tvar name = login+'['+arrayAgents[j].substr(0,iStartPos)+']';\r\n");
      out.write("\t\t\t\tif (document.theForm.viewckbox.checked == false)\t  \t\t// show agents name as : firstname, lastname[login]\r\n");
      out.write("      \t\t\t\tmyOption = new Option(arrayAgents [j],login)\r\n");
      out.write("\t\t\t\telse\t\t\t\t\t\t\t\t\t// show agents name as : login[firstname, lastname]\r\n");
      out.write("\t\t\t\t\tmyOption = new Option(name,login)\r\n");
      out.write("\t\t\t\t//optionPos = document.theForm.objects.options.length\r\n");
      out.write("\t\t\t\t//document.theForm.objects.options[optionPos]=myOption\r\n");
      out.write("\t\t\t\to[o.length]= myOption;\r\n");
      out.write("    \t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t }\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\r\n");
      out.write("\t\tvar agents = String( appletObj.getAvailableAgentListInGroupByStatus(document.theForm.agtGrp.value,1) );\r\n");
      out.write("\t\tvar jsAgents = agents + \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t// Remove all agents from agents option field\r\n");
      out.write("\t\tvar i=document.theForm.objects.options.length;\r\n");
      out.write("        if (i>0){\r\n");
      out.write("              document.theForm.objects.length = 0;\r\n");
      out.write("        }\r\n");
      out.write("        var defaultvalue =  \"- All Agents -\" ;\r\n");
      out.write("\t\tmyOption = new Option(defaultvalue,\"AllAgents\")\r\n");
      out.write("\t\t//optionPos = document.theForm.objects.options.length\r\n");
      out.write("\t\t//document.theForm.objects.options[optionPos]=myOption\r\n");
      out.write("\t\to[o.length]= myOption;\r\n");
      out.write("\r\n");
      out.write("\t\tif(agents.length > 0 ){\r\n");
      out.write("\t\t\tarrayAgents = jsAgents.split(\"|\");\r\n");
      out.write("    \t\tfor (j = 0; j <arrayAgents.length; j++){\r\n");
      out.write("    \t\t\tvar iStartPos = arrayAgents[j].indexOf('[');\r\n");
      out.write("    \t\t\tvar iEndPos   = arrayAgents[j].indexOf(']');\r\n");
      out.write("    \t\t\tvar login\t  = arrayAgents[j].substr(iStartPos+1,iEndPos-iStartPos-1);\r\n");
      out.write("    \t\t\t//myOption = new Option(arrayAgents [j],login)\r\n");
      out.write("\t\t\t\tvar name = login+'['+arrayAgents[j].substr(0,iStartPos)+']';\r\n");
      out.write("\t\t\t\tif (document.theForm.viewckbox.checked == false)\t  \t\t// show agents name as : firstname, lastname[login]\r\n");
      out.write("      \t\t\t\tmyOption = new Option(arrayAgents [j],login)\r\n");
      out.write("\t\t\t\telse\t\t\t\t\t\t\t\t\t// show agents name as : login[firstname, lastname]\r\n");
      out.write("\t\t\t\t\tmyOption = new Option(name,login)\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t//optionPos = document.theForm.objects.options.length\r\n");
      out.write("\t\t\t\t//document.theForm.objects.options[optionPos]=myOption\r\n");
      out.write("\t\t\t\to[o.length]= myOption;\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tsortSelect(o);\r\n");
      out.write("\r\n");
      out.write("\tfor (var i=0; i<o.length; i++) {\r\n");
      out.write("\t\tdocument.theForm.objects.options[i] = new Option(o[i].text, o[i].value, o[i].defaultSelected, o[i].selected);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\treturn;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function changeAgentListView(){\r\n");
      out.write("\tvar agents;\r\n");
      out.write("\tvar name=\"\";\r\n");
      out.write("\tvar o = new Array();\r\n");
      out.write("\tdocument.theForm.objects.length = 0;\r\n");
      out.write("\t/*while(document.theForm.objects.length > 0){\r\n");
      out.write("\t\tdocument.theForm.objects.options[0]= null;\r\n");
      out.write("\t }\r\n");
      out.write("\tif (ckbox.checked == true)\r\n");
      out.write("    \tagents = appletObj.getAgentsByName(tenant_dbid);\r\n");
      out.write("\telse\r\n");
      out.write("\tagents = appletObj.getAgentsByNameActif(tenant_dbid);*/\r\n");
      out.write("    var defaultvalue =  \"- All Agents -\" ;\r\n");
      out.write("\tmyOption = new Option(defaultvalue,\"AllAgents\")\r\n");
      out.write("\t//optionPos = document.theForm.objects.options.length\r\n");
      out.write("\to[o.length]=myOption\r\n");
      out.write("\r\n");
      out.write("\tif(document.theForm.agtGrp.value == 'AllGroups')\r\n");
      out.write("\t\tagents = String( appletObj.getAgentsByNameActif(tenant_dbid) );\r\n");
      out.write("\telse\r\n");
      out.write("\t\tagents = String( appletObj.getAvailableAgentListInGroupByStatus(document.theForm.agtGrp.value,1) );\r\n");
      out.write("    var jsAgents = agents + \"\";\r\n");
      out.write("    arrayAgents = jsAgents.split(\"|\");\r\n");
      out.write("    for (j = 0; j <arrayAgents.length; j++){\r\n");
      out.write("\t\t  var iStartPos = arrayAgents[j].indexOf('[');\r\n");
      out.write("\t\t  var iEndPos   = arrayAgents[j].indexOf(']');\r\n");
      out.write("\t\t  var login\t  = arrayAgents[j].substr(iStartPos+1,iEndPos-iStartPos-1);\r\n");
      out.write("\t\t  name = login+'['+arrayAgents[j].substr(0,iStartPos)+']'\r\n");
      out.write("\t\t  if (document.theForm.viewckbox.checked == false)  // show agents name as : firstname, lastname[login]\r\n");
      out.write("\t\t\tmyOption = new Option(arrayAgents [j],login);  // show agents name as : login[firstname, lastname]\r\n");
      out.write("\t\t  else\r\n");
      out.write("\t\t\tmyOption = new Option(name,login);\r\n");
      out.write("\t\t  //optionPos = document.theForm.objects.options.length;\r\n");
      out.write("\t\t  o[o.length]=myOption\r\n");
      out.write("\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("\tsortSelect(o);\r\n");
      out.write("\r\n");
      out.write("\tfor (var i=0; i<o.length; i++) {\r\n");
      out.write("\t\tdocument.theForm.objects.options[i] = new Option(o[i].text, o[i].value, o[i].defaultSelected, o[i].selected);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function changeDisabled(){\r\n");
      out.write("\tif(document.theForm.period[0].checked){\r\n");
      out.write("\t\tdocument.theForm.startingDateDaily.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.endingDateDaily.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.starting_year_yearly.disabled = false;\r\n");
      out.write("\t\tdocument.theForm.ending_year_yearly.disabled = false;\r\n");
      out.write("\t\tdocument.theForm.starting_month_monthly.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.starting_year_monthly.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.ending_month_monthly.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.ending_year_monthly.disabled = true;\r\n");
      out.write("\t} else if(document.theForm.period[1].checked){\r\n");
      out.write("\t\tdocument.theForm.startingDateDaily.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.endingDateDaily.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.starting_year_yearly.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.ending_year_yearly.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.starting_month_monthly.disabled = false;\r\n");
      out.write("\t\tdocument.theForm.starting_year_monthly.disabled = false;\r\n");
      out.write("\t\tdocument.theForm.ending_month_monthly.disabled = false;\r\n");
      out.write("\t\tdocument.theForm.ending_year_monthly.disabled = false;\r\n");
      out.write("\t} else if(document.theForm.period[2].checked){\r\n");
      out.write("\t\tdocument.theForm.startingDateDaily.disabled = false;\r\n");
      out.write("\t\tdocument.theForm.endingDateDaily.disabled = false;\r\n");
      out.write("\t\tdocument.theForm.starting_year_yearly.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.ending_year_yearly.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.starting_month_monthly.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.starting_year_monthly.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.ending_month_monthly.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.ending_year_monthly.disabled = true;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getSelectedObjects()\r\n");
      out.write("{\r\n");
      out.write("\tselectedAgents = new Array()\r\n");
      out.write("\tfor (i=document.theForm.objects.selectedIndex;i<document.theForm.objects.options.length;i++) {\r\n");
      out.write("  \t\tif (document.theForm.objects.options[i].selected) {\r\n");
      out.write("  \t\t\tselectedAgents[selectedAgents.length]=document.theForm.objects.options[i].value;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t}\r\n");
      out.write("\tvar url = '';\r\n");
      out.write("\tif (selectedAgents.length > 0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\turl= escape(selectedAgents.join('/'))\r\n");
      out.write("\t}\r\n");
      out.write("\treturn url;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getRequestedReport()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\tvar destination = '';\r\n");
      out.write("\tif(document.theForm.period[2].checked){\r\n");
      out.write("\t\tif(document.theForm.startingDateDaily.value.length == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert('");
      out.print( pageData.getWord("Please enter a starting date"));
      out.write("');\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.theForm.endingDateDaily.value.length == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert('");
      out.print( pageData.getWord("Please enter an ending date"));
      out.write("');\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tif(document.theForm.objects.selectedIndex == -1)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert('");
      out.print( pageData.getWord("Please select at least one object"));
      out.write("');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(dateChecker() == false)\r\n");
      out.write("\t{\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    destination = \"../jsp/adherenceReport.jsp\";\r\n");
      out.write("\tdestination += \"?startingDateDaily=\"\r\n");
      out.write("\tdestination += document.theForm.startingDateDaily.value;\r\n");
      out.write("\tdestination +=\"&endingDateDaily=\";\r\n");
      out.write("\tdestination += document.theForm.endingDateDaily.value;\r\n");
      out.write("\tdestination +=\"&starting_year_yearly=\";\r\n");
      out.write("\tdestination += document.theForm.starting_year_yearly.value\r\n");
      out.write("\tdestination +=\"&ending_year_yearly=\";\r\n");
      out.write("\tdestination += document.theForm.ending_year_yearly.value\r\n");
      out.write("\tdestination +=\"&starting_month_monthly=\";\r\n");
      out.write("\tdestination += document.theForm.starting_month_monthly.value\r\n");
      out.write("\tdestination +=\"&starting_year_monthly=\";\r\n");
      out.write("\tdestination += document.theForm.starting_year_monthly.value\r\n");
      out.write("\tdestination +=\"&ending_month_monthly=\";\r\n");
      out.write("\tdestination += document.theForm.ending_month_monthly.value\r\n");
      out.write("\tdestination +=\"&ending_year_monthly=\";\r\n");
      out.write("\tdestination += document.theForm.ending_year_monthly.value\r\n");
      out.write("\r\n");
      out.write("\tdestination +=\"&reportType=\";\r\n");
      out.write("\tif(document.theForm.period[0].checked){\r\n");
      out.write("\t\tdestination += \"Yearly\";\r\n");
      out.write("\t} else if(document.theForm.period[1].checked){\r\n");
      out.write("\t\tdestination += \"Monthly\";\r\n");
      out.write("\t} else if(document.theForm.period[2].checked){\r\n");
      out.write("\t\tdestination += \"Daily\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tdestination +=\"&objects=\";\r\n");
      out.write("\tdestination += getSelectedObjects();\r\n");
      out.write("\tdestination +=\"&agtGrp=\";\r\n");
      out.write("\t//destination += agtGrp.value;\r\n");
      out.write("\r\n");
      out.write("\tvar selectedGroups = document.theForm.agtGrp.value;\r\n");
      out.write("\tif(document.theForm.agtGrp.value == 'AllGroups')\r\n");
      out.write("\t{\r\n");
      out.write("\t  selectedGroups = selectedGroups + '/';\r\n");
      out.write("\t  var i;\r\n");
      out.write("\t  for(i=1; i<document.theForm.agtGrp.options.length; i++){\r\n");
      out.write("\t\t selectedGroups = selectedGroups + document.theForm.agtGrp.options[i].value + '!';\r\n");
      out.write("\t   }\r\n");
      out.write("\t  if(document.theForm.agtGrp.options.length > 1)\r\n");
      out.write("\t\t selectedGroups = selectedGroups.substring(0,selectedGroups.length-1);\r\n");
      out.write("\t}\r\n");
      out.write("\tdestination += selectedGroups;\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tdestination +=\"&order=\";\r\n");
      out.write("\tif(document.theForm.adherenceOrder[0].checked){\r\n");
      out.write("\t\tdestination += \"desc\";\r\n");
      out.write("\t} else if(document.theForm.adherenceOrder[1].checked){\r\n");
      out.write("\t\tdestination += \"loginID\";\r\n");
      out.write("\t} else if(document.theForm.adherenceOrder[2].checked){\r\n");
      out.write("\t\tdestination += \"asc\";\r\n");
      out.write("\t} else if(document.theForm.adherenceOrder[3].checked){\r\n");
      out.write("\t\tdestination += \"name\";\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tdestination += \"&lang=\"+lang;\r\n");
      out.write("\tdestination +=\"&prec=-1&suiv=1&current=0&all_obj=0\";\r\n");
      out.write("\t//document.location = destination;\r\n");
      out.write("\twindow.open(destination);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function dateChecker()\r\n");
      out.write("{\r\n");
      out.write("\tif(document.theForm.period[2].checked){// daily\r\n");
      out.write("\t\tvar startDate=new Date(document.theForm.startingDateDaily.value);\r\n");
      out.write("\t\tvar endDate = new Date(document.theForm.endingDateDaily.value);\r\n");
      out.write("\t\tif(endDate < startDate)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert('");
      out.print( pageData.getWord("Your ending date cannnot be smaller than your starting date"));
      out.write("');\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t} else if (document.theForm.period[1].checked){ // monthly\r\n");
      out.write("\t\tvar startDate='01-'+ document.theForm.starting_month_monthly.value + '-' + document.theForm.starting_year_monthly.value;\r\n");
      out.write("\t\tvar endDate ='01-'+  document.theForm.ending_month_monthly.value+ '-' + document.theForm.ending_year_monthly.value;\r\n");
      out.write("\t\tstartDate = new Date(startDate);\r\n");
      out.write("\t\tendDate = new Date(endDate);\r\n");
      out.write("\r\n");
      out.write("\t\tif(endDate < startDate)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert('");
      out.print( pageData.getWord("Your ending date cannnot be smaller than your starting date"));
      out.write("');\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}else if (document.theForm.period[0].checked){// yearly\r\n");
      out.write("\t\tvar startDate=document.theForm.starting_year_yearly.value ;\r\n");
      out.write("\t\tvar endDate = document.theForm.ending_year_yearly.value ;\r\n");
      out.write("\r\n");
      out.write("\t\tif(endDate < startDate)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert('");
      out.print( pageData.getWord("Your ending date cannnot be smaller than your starting date"));
      out.write("');\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" function setDefaultValue()\r\n");
      out.write(" {\r\n");
      out.write("     var vValue = normalizeString(QueryString('type'));\t \r\n");
      out.write("\t if(  vValue == 'AgentAdherenceReport'){\r\n");
      out.write("\t\tvar thetime = new Date();\r\n");
      out.write("\t\tvar thisYear = thetime.getYear();\r\n");
      out.write("\t\tvar thisMonth = thetime.getMonth()+1;\r\n");
      out.write("\t    \r\n");
      out.write("\t\tfor (j = 0; j <document.theForm.starting_year_yearly.length; j++){\r\n");
      out.write("\t\t\tif(document.theForm.starting_year_yearly.options[j].value == thisYear)\r\n");
      out.write("\t\t\t\t{document.theForm.starting_year_yearly.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfor (j = 0; j <document.theForm.ending_year_yearly.length; j++){\r\n");
      out.write("\t\t\tif(document.theForm.ending_year_yearly.options[j].value == thisYear)\r\n");
      out.write("\t\t\t\t{document.theForm.ending_year_yearly.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t}\t    \r\n");
      out.write("\t\tfor (j = 0; j <document.theForm.starting_year_monthly.length; j++){\r\n");
      out.write("\t\t\tif(document.theForm.starting_year_monthly.options[j].value == thisYear)\r\n");
      out.write("\t\t\t\t{document.theForm.starting_year_monthly.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfor (j = 0; j <document.theForm.starting_month_monthly.length; j++){\r\n");
      out.write("\t\t\tif(document.theForm.starting_month_monthly.options[j].value == thisMonth)\r\n");
      out.write("\t\t\t\t{document.theForm.starting_month_monthly.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t    \r\n");
      out.write("\t\tfor (j = 0; j <document.theForm.ending_year_monthly.length; j++){\r\n");
      out.write("\t\t\tif(document.theForm.ending_year_monthly.options[j].value == thisYear)\r\n");
      out.write("\t\t\t\t{document.theForm.ending_year_monthly.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("    \r\n");
      out.write("\t\tfor (j = 0; j <document.theForm.ending_month_monthly.length; j++){\r\n");
      out.write("\t\t\tif(document.theForm.ending_month_monthly.options[j].value == thisMonth)\r\n");
      out.write("\t\t\t\t{document.theForm.ending_month_monthly.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function displayStats()\r\n");
      out.write("{\r\n");
      out.write("\t//alert(window.top.main.body.rows)\r\n");
      out.write("\r\n");
      out.write(" if (statsChk.checked)\r\n");
      out.write("  {\r\n");
      out.write("  \tdocument.body.rows = \"*,100%,*\";\t\r\n");
      out.write("  }\r\n");
      out.write("  else{    \t\r\n");
      out.write("\tdocument.body.rows = \"60%,40%,*\";\t\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("    // Associate a default button with pressing the Enter key\r\n");
      out.write("\tfunction KeyDownHandler(btn)\r\n");
      out.write("    {\r\n");
      out.write("        // process only the Enter key\r\n");
      out.write("        if (event.keyCode == 13)\r\n");
      out.write("        {\r\n");
      out.write("            // cancel the default submit\r\n");
      out.write("            event.returnValue=false;\r\n");
      out.write("            event.cancel = true;\r\n");
      out.write("            // submit the form by programmatically clicking the specified button\r\n");
      out.write("            btn.click();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\t\r\n");
      out.write("\t\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"></head>\r\n");
      out.write("\t\r\n");
      out.write("<body class=\"adher_body\" onLoad=\"fillObjectCombo()\">\r\n");
      out.write("\t<div class=\"tab-pane\" id=\"tabPane1\">\r\n");
      out.write("<form name=\"theForm\" onKeyDown=\"KeyDownHandler(submit)\">\r\n");
      out.write("  \t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\ttp1 = new WebFXTabPane( document.getElementById( \"tabPane1\" ) );\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<div class=\"tab-page\" id=\"tabGeneral\">\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t<legend id=\"caption\">\r\n");
      out.write("\t\t\t\t\t");
      out.print( pageData.getWord("Adherence Report"));
      out.write("\r\n");
      out.write("\t\t\t\t</legend>\r\n");
      out.write("  \r\n");
      out.write("  <table style=\"BORDER-COLLAPSE: collapse\" cellSpacing=\"0\" cellPadding=\"0\" width=\"650\" border=\"0\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colSpan=\"4\">&nbsp;</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"136\" height=\"23\">");
      out.print( pageData.getWord("Agent Groups"));
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"201\"><select onChange=\"getAgentsInGroup()\" name=\"agtGrp\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AllGroups\" selected>- ");
      out.print( pageData.getWord("All groups"));
      out.write(" -</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"136\" height=\"23\">");
      out.print( pageData.getWord("Agent"));
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"201\"><select name=\"objects\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AllAgents\" selected>- ");
      out.print( pageData.getWord("All agents"));
      out.write(" -</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td valign=\"top\" width=\"45%\" >\r\n");
      out.write("\t\t\t\t\t");
      out.print( pageData.getWord("Show agent by ID"));
      out.write("<input type=\"checkbox\" name=\"viewckbox\" onClick=\"changeAgentListView()\" ID=\"Checkbox2\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"136\"></td>\r\n");
      out.write("\t\t\t\t<td width=\"201\" colSpan=\"2\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<!--<tr>\r\n");
      out.write("\t\t\t\t<td height=\"23\"><b>Call time </b>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td height=\"23\"><b>From</b> <input onfocus=\"getCalendarFor(this); this.blur()\" type=\"text\" size=\"20\" name=\"startingDate\"></td>\r\n");
      out.write("\t\t\t\t<td colSpan=\"2\" height=\"23\"><b>To</b> <input onfocus=\"getCalendarFor(this); this.blur()\" type=\"text\" size=\"20\" name=\"endingDate\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>-->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"left\"></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td height=\"20\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td height=\"20\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td height=\"20\">&nbsp;</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"26\" valign=\"top\">\r\n");
      out.write("\t\t\t\t<td width=\"34%\">\r\n");
      out.write("\t\t\t\t\t<b>");
      out.print( pageData.getWord("Report type"));
      out.write("</b>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"38%\">\r\n");
      out.write("\t\t\t\t\t<b>");
      out.print( pageData.getWord("Starting date"));
      out.write("</b>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"28%\">\r\n");
      out.write("\t\t\t\t\t<b>");
      out.print( pageData.getWord("Ending date"));
      out.write("</b>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"26\">\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input name=\"period\" type=\"radio\" value=\"yearly\" onClick=\"changeDisabled()\" ID=\"Radio4\">");
      out.print( pageData.getWord("detail for each year"));
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td valign=\"top\" width=\"34%\">\r\n");
      out.write("\t\t\t\t\t<select name=\"starting_year_yearly\" disabled ID=\"Select8\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2004\">2004</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2005\" selected>2005</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2006\">2006</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2007\">2007</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2008\">2008</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2009\">2009</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2010\">2010</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2011\">2011</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2012\">2012</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2013\">2013</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2014\">2014</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2015\">2015</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td valign=\"top\" width=\"38%\">\r\n");
      out.write("\t\t\t\t\t<select name=\"ending_year_yearly\" disabled ID=\"Select9\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2004\">2004</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2005\" selected>2005</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2006\">2006</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2007\">2007</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2008\">2008</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2009\">2009</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2010\">2010</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2011\">2011</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2012\">2012</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2013\">2013</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2014\">2014</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2015\">2015</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input name=\"period\" type=\"radio\" value=\"monthly\" onClick=\"changeDisabled()\" ID=\"Radio5\">");
      out.print( pageData.getWord("detail for each month"));
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td valign=\"top\" width=\"34%\">\r\n");
      out.write("\t\t\t\t\t<select name=\"starting_month_monthly\" disabled ID=\"Select10\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"01\" selected>01</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"02\">02</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"03\">03</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"04\">04</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"05\">05</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"06\">06</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"07\">07</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"08\">08</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"09\">09</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<select name=\"starting_year_monthly\" disabled ID=\"Select11\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2004\" selected>2004</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2005\">2005</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2006\">2006</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2007\">2007</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2008\">2008</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2009\">2009</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2010\">2010</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2011\">2011</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2012\">2012</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2013\">2013</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2014\">2014</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2015\">2015</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td valign=\"top\" width=\"38%\">\r\n");
      out.write("\t\t\t\t\t<select name=\"ending_month_monthly\" disabled ID=\"Select12\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"01\" selected>01</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"02\">02</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"03\">03</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"04\">04</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"05\">05</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"06\">06</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"07\">07</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"08\">08</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"09\">09</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<select name=\"ending_year_monthly\" disabled ID=\"Select13\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2004\">2004</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2005\" selected>2005</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2006\">2006</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2007\">2007</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2008\">2008</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2009\">2009</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2010\">2010</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2011\">2011</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2012\">2012</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2013\">2013</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2014\">2014</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2015\">2015</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input name=\"period\" type=\"radio\" value=\"daily\" onClick=\"changeDisabled()\" checked ID=\"Radio6\">");
      out.print( pageData.getWord("detail for each day"));
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td valign=\"top\" width=\"34%\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" size=\"20\" onFocus=\"showCalendar('',this,this,'','Text3',0,30,1);this.blur()\" name=\"startingDateDaily\"\r\n");
      out.write("\t\t\t\t\t\tID=\"Text3\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td valign=\"top\" width=\"38%\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" size=\"20\" onFocus=\"showCalendar('',this,this,'','Text4',0,30,1);this.blur()\" name=\"endingDateDaily\"\r\n");
      out.write("\t\t\t\t\t\tID=\"Text4\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t  <td align=\"left\"></td>\r\n");
      out.write("\t\t\t  <td></td>\r\n");
      out.write("\t\t\t  <td align=\"right\">&nbsp;</td>\r\n");
      out.write("\t\t\t  <td></td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t  <td align=\"left\"><b>");
      out.print( pageData.getWord("Show report order by"));
      out.write(" </b></td>\r\n");
      out.write("\t\t\t  <td><input name=\"adherenceOrder\" type=\"radio\" value=\"desc\"  checked ID=\"Radioa1\">\r\n");
      out.print( pageData.getWord("adherence value descending"));
      out.write(" </td>\r\n");
      out.write("\t\t\t  <td align=\"right\"><div align=\"left\">\r\n");
      out.write("      <input name=\"adherenceOrder\" type=\"radio\" value=\"loginID\"   ID=\"Radioa2\">\r\n");
      out.print( pageData.getWord("agent login ID"));
      out.write(" </div></td>\r\n");
      out.write("\t\t\t  <td></td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t  <td align=\"left\"></td>\r\n");
      out.write("\t\t\t  <td><input name=\"adherenceOrder\" type=\"radio\" value=\"asc\"   ID=\"Radioa3\">\r\n");
      out.write("\t\t      ");
      out.print( pageData.getWord("adherence value ascending"));
      out.write("</td>\r\n");
      out.write("\t\t\t  <td align=\"right\"><div align=\"left\">\r\n");
      out.write("\t\t\t    <input name=\"adherenceOrder\" type=\"radio\" value=\"agtname\"   ID=\"Radioa4\">\r\n");
      out.print( pageData.getWord("agent name"));
      out.write(" </div></td>\r\n");
      out.write("\t\t\t  <td></td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"left\"></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td align=\"right\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"left\" width=\"155\" height=\"40\">\r\n");
      out.write("\t\t\t<input id=\"submit\" type=\"button\" value='");
      out.print( pageData.getWord("Submit"));
      out.write("' onClick=\"getRequestedReport()\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<script>setDefaultValue();</script>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</body>\r\n");
 pageData.closeConnection(); 
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
