package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.lang.*;
import aheevaManager.ressources.*;
import aheevaManager.ressources.*;

public final class agentGroup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/aheevaManager/Resources_pages/agentGroupFunctions_labels.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

response.setHeader("Pragma", "no-cache");
response.setHeader("Cache-Control", "no-cache");
response.setDateHeader("Expires", 0);

      out.write('\r');
      out.write('\n');

	beanManagerData pageGrpData = new beanManagerData();
	if( session.getAttribute("USER_LANGUAGE") != null )
		pageGrpData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));

	String currentUserDbid = (String)session.getAttribute("CURRENT_USER_DBID");
	String agentGroupDbid = request.getParameter("dbid");
	String tenantDbid = request.getParameter("tenant_dbid");
	
	String userAssignedTenants = "(SELECT USER_DBID FROM cfg_user_authorize_ressources WHERE RESSOURCE_TYPE='TENANT' AND RESSOURCE_DBID='"+tenantDbid+"')";
	String userAssignedAgentGroups = "(SELECT USER_DBID FROM cfg_user_authorize_ressources WHERE RESSOURCE_TYPE='AGENTGROUP' AND RESSOURCE_DBID='"+agentGroupDbid+"')";
	String listAllowedUsersQuery = "SELECT U.DBID AS USER_DBID, USERNAME FROM cfg_user_authorize_ressources, cfg_user U "+
		"WHERE RESSOURCE_TYPE='AGENTGROUP' AND U.DBID = USER_DBID AND RESSOURCE_DBID='"+agentGroupDbid+"' ORDER BY USERNAME";
	String listNotAllowedUsersQuery = "SELECT DBID AS USER_DBID, USERNAME FROM cfg_user WHERE ALLOW_AGENT_GROUPS_MANAGEMENT='yes' AND state='1' "+
		"AND DBID NOT IN "+userAssignedAgentGroups+" AND DBID IN "+userAssignedTenants+" ORDER BY USERNAME";
	String userRightsQuery = "SELECT USERNAME, ALLOW_USER_MANAGEMENT, ALLOW_AGENT_GROUPS_MANAGEMENT,ALLOW_MESSAGE_CENTER_MANAGEMENT, ALLOW_MANAGER_SCREEN_MONITORING , ALLOW_MANAGER_AUDIO_MONITORING FROM cfg_user WHERE DBID='"+currentUserDbid+"'";

	String agentGroupSoftDataQuery = "SELECT BT_TRANSF_STATE,BT_CONF_STATE, ADD_PREFIX_TO_CALL, CALL_PREFIX,AGENT_MAX_LINES, REC_DEFAULT_CLIENT,REC_DEFAULT_CAMPAIGN, USE_ENCRYPTION, SCREEN_RECORDING "+
								" FROM cfg_agent_group WHERE TENANT_DBID='"+tenantDbid +"' AND DBID='"+agentGroupDbid+"' LIMIT 0,1";
							
	

	pageGrpData.openConnection();
	pageGrpData.executeFromString(listAllowedUsersQuery);
	Vector <HashMap> listAllowedUsersDataResult = pageGrpData.CreateVectorFromBean();
	pageGrpData.executeFromString(listNotAllowedUsersQuery);
	Vector <HashMap> listNotAllowedUsersDataResult =pageGrpData.CreateVectorFromBean();
	pageGrpData.executeFromString(userRightsQuery);
	Vector <HashMap> userRightsDataResult = pageGrpData.CreateVectorFromBean();
	
	pageGrpData.executeFromString(agentGroupSoftDataQuery);
	Vector <HashMap> agentGroupSoftDataResult = pageGrpData.CreateVectorFromBean();	
	

	String currentUserName = (String)userRightsDataResult.elementAt(0).get("USERNAME");
	boolean userManagementAllowed = pageGrpData.userHasRight(userRightsDataResult, "ALLOW_USER_MANAGEMENT");
	boolean isNewResource = agentGroupDbid.compareTo("") == 0;
	if(!pageGrpData.userHasRight(userRightsDataResult, "ALLOW_AGENT_GROUPS_MANAGEMENT"))
	{ 
      out.write("\r\n");
      out.write("\t\t");
      if (true) {
        _jspx_page_context.forward("forbidden.jsp");
        return;
      }
      out.write('\n');
	} 
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"tab_luna.css\" />\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style_2.css\" />\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style.css\" />\r\n");
      out.write("<LINK href=\"livestats.css\" \trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<meta http-equiv=\"Content-Language\" content=\"en-us\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t100px;\r\n");
      out.write("}\r\n");
      out.write("html, body {\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("form {\r\n");
      out.write("\tmargin:\t\t0;\r\n");
      out.write("\tpadding:\t0;\r\n");
      out.write("}\r\n");
      out.write("/* over ride styles from webfxlayout */\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:\t\t10px;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("\theight:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 {\r\n");
      out.write("\ttext-align:\tcenter;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 a {\r\n");
      out.write("\tdisplay:\tinline;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control a:hover {\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write('\r');
      out.write('\n');

beanManagerData pageGrpFData = new beanManagerData();
pageGrpFData.openConnection();
if( session.getAttribute("USER_LANGUAGE") != null )
	pageGrpFData.setDefaultLanguage( (String)session.getAttribute("USER_LANGUAGE") );


      out.write("\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/javascript\">\r\n");
      out.write("var GrpF= new Array();\r\n");
      out.write("GrpF[0]=\"");
      out.print(pageGrpFData.getWord("Save") );
      out.write("\";\r\n");
      out.write("GrpF[1]=\"");
      out.print(pageGrpFData.getWord("AGERR Length") );
      out.write("\";\r\n");
      out.write("GrpF[2]=\"");
      out.print(pageGrpFData.getWord("AGERR Char") );
      out.write("\";\r\n");
      out.write("GrpF[3]=\"");
      out.print(pageGrpFData.getWord("You must enter a GROUP NAME") );
      out.write("\";\r\n");
      out.write("GrpF[4]=\"");
      out.print(pageGrpFData.getWord("Invalid use of character") );
      out.write("\";\r\n");
      out.write("GrpF[5]=\"");
      out.print(pageGrpFData.getWord("Group name") );
      out.write("\";\r\n");
      out.write("GrpF[6]=\"");
      out.print(pageGrpFData.getWord("You must enter a GROUP QUEUE") );
      out.write("\";\r\n");
      out.write("GrpF[7]=\"");
      out.print(pageGrpFData.getWord("Queue name") );
      out.write("\";\r\n");
      out.write("GrpF[8]=\"");
      out.print(pageGrpFData.getWord("Your description should be filled. Use valid characters.") );
      out.write("\";\r\n");
      out.write("GrpF[9]=\"");
      out.print(pageGrpFData.getWord("The maximum wrap up time must be in seconds") );
      out.write("\";\r\n");
      out.write("GrpF[10]=\"");
      out.print(pageGrpFData.getWord("The maximum wrap up time must be less than 99999 seconds") );
      out.write("\";\r\n");
      out.write("GrpF[11]=\"");
      out.print(pageGrpFData.getWord("The maximum wrap up time must be at least 1 second") );
      out.write("\";\r\n");
      out.write("GrpF[12]=\"");
      out.print(pageGrpFData.getWord("The maximum wrap up time that does not affect productivity must be in seconds") );
      out.write("\";\r\n");
      out.write("GrpF[13]=\"");
      out.print(pageGrpFData.getWord("This QUEUE is already assigned. You must enter a NEW QUEUE") );
      out.write("\";\r\n");
      out.write("GrpF[14]=\"");
      out.print(pageGrpFData.getWord("You must enter the encryption server IP or uncheck the encryption box") );
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("GrpF[15]=\"");
      out.print(pageGrpFData.getWord("You must enter the encryption method or uncheck the encryption box") );
      out.write("\";\r\n");
      out.write("GrpF[16]=\"");
      out.print(pageGrpFData.getWord("Agent group already exists") );
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("GrpF[17]=\"");
      out.print(pageGrpFData.getWord("Minimum recording time must be smaller than maximum recording time") );
      out.write("\";\r\n");
      out.write("GrpF[18]=\"");
      out.print(pageGrpFData.getWord("Are you sure you wish to delete this group?") );
      out.write("\";\r\n");
      out.write("GrpF[19]=\"");
      out.print(pageGrpFData.getWord("A running campaign uses this group! You can't delete it") );
      out.write("\";\r\n");
      out.write("GrpF[20]=\"");
      out.print(pageGrpFData.getWord("Delete") );
      out.write("\";\r\n");
      out.write("GrpF[21]=\"");
      out.print(pageGrpFData.getWord("There is no active non-global not-ready-reason in the system.") );
      out.write("\";\r\n");
      out.write("GrpF[22]=\"");
      out.print(pageGrpFData.getWord("You cannot select a reason several times") );
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 pageGrpFData.closeConnection(); 
      out.write("\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jsUtil.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"tabpane.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"agentGroupFunctions.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("var currentUserDbid = ");
      out.print(currentUserDbid);
      out.write(";\r\n");
      out.write("var agentGroupDbid = \"");
      out.print(agentGroupDbid);
      out.write("\";\r\n");
      out.write("var isNewResource = ");
      out.print(isNewResource);
      out.write(";\r\n");
      out.write("var agentGrpDBID       \t= '';\r\n");
      out.write("var groupname          \t= normalizeString(QueryString('grpName'));\r\n");
      out.write("var lastName           \t= '';\r\n");
      out.write("var firstName          \t= '';\r\n");
      out.write("var tenant_dbid\t\t= \"NULL\";\r\n");
      out.write("var recordingRight      = '';\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var nrows = 1 ;\r\n");
      out.write("var maxrow = 1;\r\n");
      out.write("var mopID = \"\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// Statistiques\r\n");
      out.write("var sTring = String( appletObj.getAgentGroupsStats( normalizeString(QueryString('grpName')) ) );\r\n");
      out.write("sTringArray = sTring.split(\",\");\r\n");
      out.write("\r\n");
      out.write("var grp_Name \t\t= sTringArray[0];\r\n");
      out.write("var grpCallHandled \t= sTringArray[1];\r\n");
      out.write("var grpCallInbound \t= sTringArray[2];\r\n");
      out.write("var grpCallOutbound = sTringArray[3];\r\n");
      out.write("var grpLoginAgents \t= sTringArray[4];\r\n");
      out.write("var grpTotalNotReady= sTringArray[5];\r\n");
      out.write("var grpTotalReady \t= sTringArray[6];\r\n");
      out.write("var grpTotalWaiting = sTringArray[7];\r\n");
      out.write("var grpTotalWrapUp \t= sTringArray[8];\r\n");
      out.write("var grpTotalDialing = sTringArray[9];\r\n");
      out.write("var grpTotalHold\t= sTringArray[10];\r\n");
      out.write("var grpTotalConference = sTringArray[11];\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//Softphone settings\r\n");
      out.write("var btTransfState='';\r\n");
      out.write("var btConfState='';\r\n");
      out.write("var addPref='';\r\n");
      out.write("var Prefix='';\r\n");
      out.write("var agmaxlines='';\r\n");
      out.write("var recdefcl='';\r\n");
      out.write("var recdefcmp='';\r\n");
      out.write("\r\n");
      out.write("if(normalizeString(QueryString('grpName'))!='')\r\n");
      out.write("{\r\n");
      out.write("\tbtTransfState='");
if(agentGroupSoftDataResult.size()!=0) out.write((String)agentGroupSoftDataResult.elementAt(0).get("BT_TRANSF_STATE"));
      out.write("';\r\n");
      out.write("\tbtConfState='");
if(agentGroupSoftDataResult.size()!=0) out.write((String)agentGroupSoftDataResult.elementAt(0).get("BT_CONF_STATE"));
      out.write("';\r\n");
      out.write("\taddPref='");
if(agentGroupSoftDataResult.size()!=0) out.write((String)agentGroupSoftDataResult.elementAt(0).get("ADD_PREFIX_TO_CALL"));
      out.write("';\r\n");
      out.write("\tPrefix='");
if(agentGroupSoftDataResult.size()!=0) out.write((String)agentGroupSoftDataResult.elementAt(0).get("CALL_PREFIX"));
      out.write("';\r\n");
      out.write("\tagmaxlines='");
if(agentGroupSoftDataResult.size()!=0) out.write((String)agentGroupSoftDataResult.elementAt(0).get("AGENT_MAX_LINES"));
      out.write("';\r\n");
      out.write("\trecdefcl ='");
if(agentGroupSoftDataResult.size()!=0) out.write((String)agentGroupSoftDataResult.elementAt(0).get("REC_DEFAULT_CLIENT"));
      out.write("';\r\n");
      out.write("\trecdefcmp='");
if(agentGroupSoftDataResult.size()!=0) out.write((String)agentGroupSoftDataResult.elementAt(0).get("REC_DEFAULT_CAMPAIGN"));
      out.write("';\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("    // Associate a default button with pressing the Enter key\r\n");
      out.write("\tfunction KeyDownHandler(btn)\r\n");
      out.write("    {\r\n");
      out.write("        // process only the Enter key\r\n");
      out.write("        if (event.keyCode == 13)\r\n");
      out.write("        {\r\n");
      out.write("            // cancel the default submit\r\n");
      out.write("            event.returnValue=false;\r\n");
      out.write("            event.cancel = true;\r\n");
      out.write("            // submit the form by programmatically clicking the specified button\r\n");
      out.write("            btn.click();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("  function enableEncOpt() {\r\n");
      out.write("        if(!appletObj.getIsEncryptionServerAllowed()) {\r\n");
      out.write("                document.getElementById(\"encryptionEnable\").checked  = false;\r\n");
      out.write("                document.getElementById(\"encryptionEnable\").disabled = true;\r\n");
      out.write("        }\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"age_gr_body\" onLoad=\"displayAgentGroupInfo()\">\r\n");
      out.write("<div class=\"tab-pane\" id=\"tabPane1\">\r\n");
      out.write("<form name=\"agentGroup\" onKeyDown=\"KeyDownHandler(update)\">\r\n");
 if(agentGroupDbid != ""){ 
      out.write("\r\n");
      out.write("\t<input type=\"hidden\" name=\"contentUseEnc\" id=\"contentUseEnc\" value=\"");
 out.write((String)agentGroupSoftDataResult.elementAt(0).get("USE_ENCRYPTION")); 
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"contentUseEncRec\" id=\"contentUseEncRec\" value=\"");
 out.write((String)agentGroupSoftDataResult.elementAt(0).get("SCREEN_RECORDING")); 
      out.write("\">\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t<input type=\"hidden\" name=\"contentUseEnc\" id=\"contentUseEnc\" value=\"0\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"contentUseEncRec\" id=\"contentUseEncRec\" value=\"0\">\r\n");
 }
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("tp1 = new WebFXTabPane( document.getElementById( \"tabPane1\" ) );\r\n");
      out.write("</script>\r\n");
      out.write("\t<div class=\"tab-page\" id=\"tabGeneral\">\r\n");
      out.write("\t\t<h2 class=\"tab\">");
      out.print( pageGrpData.getWord("General"));
      out.write("</h2>\n");
      out.write("\t\t<script type=\"text/javascript\">tp1.addTabPage( document.getElementById( \"tabGeneral\" ) );</script>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>");
      out.print( pageGrpData.getWord("General settings"));
      out.write("</legend>\n");
      out.write("            <table border=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td><label for=\"grpName\">");
      out.print( pageGrpData.getWord("Group name"));
      out.write("</label></td>\n");
      out.write("                <td align=\"left\"><input type=\"text\" name=\"grpName\" id=\"grpName\" onChange=\"enableUpdateButton()\" size=\"20\"></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td><label for=\"grpDescription\">");
      out.print( pageGrpData.getWord("Description"));
      out.write("</label></td>\n");
      out.write("                <td><textarea rows=\"3\" name=\"grpDescription\" id=\"grpDescription\" cols=\"41\" onChange=\"enableUpdateButton()\"></textarea></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td><label for=\"grpQueue\">");
      out.print( pageGrpData.getWord("Associated queue"));
      out.write("</label></td>\n");
      out.write("                <td><input type=\"text\" name=\"grpQueue\" id=\"grpQueue\" onChange=\"enableUpdateButton()\"></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td colspan=\"2\" align=\"left\">\r\n");
      out.write("\t\t\t\t\t<table align=\"left\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"wrapUpTimeOut\">");
      out.print( pageGrpData.getWord("Wrap-up time out"));
      out.write("</label>\n");
      out.write("                    \t\t\t<input name=\"wrapUpTimeOut\" type=\"checkbox\" id=\"wrapUpTimeOut\" onClick=\"enableUpdateButton(); changeSecondWrapUpStatus()\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"2%\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"maxWrapUpTime\" id=\"maxWrapUpTime\" type=\"text\" onChange=\"enableUpdateButton()\" size=\"5\" disabled>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("seconds"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"2%\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"ActionAfterTimeOut\" id=\"ActionAfterTimeOut\" onChange=\"enableUpdateButton()\" disabled>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"NOT_READY\">");
      out.print( pageGrpData.getWord("Not ready"));
      out.write("</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"READY\">");
      out.print( pageGrpData.getWord("Ready"));
      out.write("</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"LOGGED_OUT\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("Action after Time out"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                ");
      out.print( pageGrpData.getWord("Max Wrap-up time For Productivity"));
      out.write("\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("                <td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"maxWrapTimeForProductivity\" name=\"maxWrapTimeForProductivity\" onChange=\"enableUpdateButton()\" size=\"5\">&nbsp;\r\n");
      out.write("\t\t\t\t\t");
      out.print( pageGrpData.getWord("seconds"));
      out.write("\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"25\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<label for=\"grpState\">");
      out.print( pageGrpData.getWord("Active"));
      out.write("</label>\n");
      out.write("                    <input id=\"grpState\" type=\"checkbox\" name=\"grpState\" value=\"ON\" onClick=\"enableUpdateButton()\" checked>\r\n");
      out.write("                </td>\t\t\t\t\r\n");
      out.write("              </tr>\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t  \t<td colspan=\"2\">\t\r\n");
      out.write("\t\t\t  \t\t");

					String buttonTicket = "";
					if (agentGroupDbid != null && agentGroupDbid.length() > 0){
						 buttonTicket = "Update";
					}else{
						buttonTicket = "Save";
					}
					
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input id=\"update\" name=\"updateInfo\" type=\"button\" value=\"");
      out.print( pageGrpData.getWord(buttonTicket) );
      out.write("\" onClick=\"validateInfo()\">\n");
      out.write("\t\t\t\t<input name=\"deleteAgtGrp\" type=\"button\" value=\"");
      out.print( pageGrpData.getWord("Delete"));
      out.write("\" onClick=\"askDelete()\">\n");
      out.write("\t\t\t\t</td>\t\t\t\t\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"tab-page\" id=\"tabAgents\">\r\n");
      out.write("\t\t<h2 class=\"tab\">");
      out.print( pageGrpData.getWord("Agents"));
      out.write("</h2>\n");
      out.write("\t\t<script type=\"text/javascript\">tp1.addTabPage( document.getElementById( \"tabAgents\" ) );</script>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t<legend>");
      out.print( pageGrpData.getWord("Agents configuration"));
      out.write("</legend>\n");
      out.write("\t\t<table border=\"0\">\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<table border=\"0\" width=\"100%\" height=\"58\" cellspacing=\"0\" cellpadding=\"0\" bordercolor=\"#c0c0c0\" style=\"BORDER-COLLAPSE: collapse\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\" valign=\"middle\" ><script>document.write(\"");
      out.print( pageGrpData.getWord("Agents assigned to "));
      out.write("\" + groupname);</script></td>\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\" valign=\"middle\">");
      out.print( pageGrpData.getWord("View agents from "));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Ici on doit ajouter un select box pour lister les agent groups -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<select size=\"1\" name=\"AgentGroupSelection\" onChange=\"filterGroupAgents();enableUpdateButton();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- -->\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr height=\"10\">\r\n");
      out.write("\t\t\t\t<td width=\"197\" height=\"25\">\r\n");
      out.write("\t\t\t\t\t<input id=\"agtlist\" type=\"checkbox\" name=\"orderView\" value=\"ON\" onClick=\"changeAgentListView(); enableUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t");
      out.print( pageGrpData.getWord("Show agent by ID"));
      out.write("\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"43%\" height=\"52\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select style=\"FONT-WEIGHT: bold; FONT-SIZE: 8pt; WIDTH: 250px\" name=\"availableAgentInGroup\" size=\"10\" multiple>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"11%\" valign=middle height=\"52\" bordercolordark=\"#c0c0c0\" nowrap align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;<img src=\"../img/left_to_right.gif\" style=\"cursor:pointer \" onClick=\"chkAndAddAgentToGroup()\" />&nbsp;<br><br><br><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;<img src=\"../img/right_to_left.gif\"  style=\"cursor:pointer \" onClick=\"chkAndDropAgentFromGroup()\"/>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"288%\" height=\"52\" bordercolor=\"#000000\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select width=\"200\" style=\"FONT-WEIGHT: bold; FONT-SIZE: 8pt; WIDTH: 250px\" name=\"nonConfiguredAgents\" size=\"10\" multiple>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"tab-page\" id=\"tabNRR\">\r\n");
      out.write("\t\t<h2 class=\"tab\">");
      out.print( pageGrpData.getWord("Not-ready reasons"));
      out.write("</h2>\n");
      out.write("\t\t<script type=\"text/javascript\">tp1.addTabPage( document.getElementById( \"tabNRR\" ) );</script>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t<legend>");
      out.print( pageGrpData.getWord("Not-ready reasons configuration"));
      out.write("</legend>\n");
      out.write("\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t<input id=\"addNRR\" name=\"addRowButton\" type=\"button\" value=\"");
      out.print( pageGrpData.getWord("Add a new reason"));
      out.write("\" onClick=\"addMyNotGlobalRow();enableUpdateButton()\">\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;</td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"NRR_items\" style=\"MARGIN: 0px 5px\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t\t<br><input id=\"update\" name=\"updateInfo\" type=\"button\" value=\"");
      out.print( pageGrpData.getWord("Update") );
      out.write("\" onClick=\"validateInfo()\">\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"tab-page\" id=\"tabStarphone\">\r\n");
      out.write("\t\t<h2 class=\"tab\">");
      out.print( pageGrpData.getWord("SoftPhone"));
      out.write("</h2>\n");
      out.write("\t\t<script type=\"text/javascript\">tp1.addTabPage( document.getElementById( \"tabStarphone\" ) );</script>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t<legend>");
      out.print( pageGrpData.getWord("Softphone Settings"));
      out.write("</legend>\n");
      out.write("\t\t\t<table border=\"0\">           \r\n");
      out.write("\t\t\t  <tr>\t\t\t  \r\n");
      out.write("                <td height=\"10\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<label for=\"grpEnableDialing\">");
      out.print( pageGrpData.getWord("Enable Dialing"));
      out.write("</label>\n");
      out.write("                    <input id=\"grpEnableDialing\" type=\"checkbox\" name=\"grpEnableDialing\" value=\"ON\" onClick=\"enableDial();enableUpdateButton()\" checked>\r\n");
      out.write("                </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td height=\"10\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"grpReadyButtonState\">");
      out.print( pageGrpData.getWord("Be ready after login"));
      out.write("</label>\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<input id=\"grpReadyButtonState\" type=\"checkbox\" name=\"grpReadyButtonState\" value=\"OFF\" onClick=\"enableUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t</td>\t\t\t\t\t\r\n");
      out.write("              </tr>\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t<td height=\"10\">\r\n");
      out.write("\t\t\t\t\t<label for=\"callPrefix\">");
      out.print( pageGrpData.getWord("Prefix manual calls with"));
      out.write("</label>\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input id=\"callPrefix\" name=\"callPrefix\" maxlength=\"10\" size=\"10\" onChange=\"enableUpdateButton();\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t </tr>\r\n");
      out.write("\t\t\t <tr>\r\n");
      out.write("\t\t\t \t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend>");
      out.print( pageGrpData.getWord("AheevaPhone Settings"));
      out.write("</legend>\n");
      out.write("\t\t\t\t\t\t<table>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td height=\"10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"nbMaxLines\">");
      out.print( pageGrpData.getWord("Maximum lines per agent"));
      out.write("</label>\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"nbMaxLines\" name=\"nbMaxLines\" style=\"width:60\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"6\">6</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"7\">7</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"9\">8</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"9\">9</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"-1\">");
      out.print( pageGrpData.getWord("Unlimited"));
      out.write("</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t </select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td height=\"10\" colspan=\"2\" width=\"100%\"><!--Enable conference initiation and/or transfer-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("Enable"));
      out.write(":&nbsp;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"enTransf\">");
      out.print( pageGrpData.getWord("Transfer"));
      out.write("</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"enTransf\" name=\"enTransf\" checked=\"checked\" onClick=\"enableDial();enableUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"enConf\">");
      out.print( pageGrpData.getWord("Initiate Conference"));
      out.write("</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"enConf\" name=\"enConf\" checked=\"checked\" onClick=\"enableDial();enableUpdateButton()\">&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</td>\t\t\t  \r\n");
      out.write("\t\t\t</tr>\t\t\t\r\n");
      out.write("\t\t</table>\t\t\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("<input id=\"update\" name=\"updateInfo\" type=\"button\" value=\"");
      out.print( pageGrpData.getWord("Update") );
      out.write("\" onClick=\"validateInfo()\">\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"tab-page\" id=\"tabRecording\">\r\n");
      out.write("\t\t<h2 class=\"tab\">");
      out.print( pageGrpData.getWord("Recordings"));
      out.write("</h2>\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\trecordingRight = normalizeString(QueryString('recordingRight'));\r\n");
      out.write("\t\t\tif( recordingRight != 'false')\r\n");
      out.write("\t\t\t\ttp1.addTabPage( document.getElementById( \"tabRecording\" ) );\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t<legend>");
      out.print( pageGrpData.getWord("Recording options"));
      out.write("</legend>\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<fieldset style=\"width:300px; height:180px\">\r\n");
      out.write("\t\t\t\t\t<legend align=\"center\">");
      out.print( pageGrpData.getWord("Audio recording options"));
      out.write("</legend>\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("Enable audio recording"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"recording\" type=\"checkbox\" name=\"recordingsState\" value=\"ON\" onClick=\"enableUpdateButton();validateRecordings()\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr height=\"10\"><td>&nbsp;&nbsp;</td></tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("Audio recordings stay local"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"local\" type=\"checkbox\" name=\"localRecording\" value=\"ON\" onClick=\"enableUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("Encode audio recordings to MP3"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"mp3\" type=\"checkbox\" name=\"mp3Encoding\" value=\"ON\" onClick=\"enableUpdateButton();enableMp3Quality()\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("Low quality MP3(smaller files)"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"mp3Quality\" value=\"low\" onClick=\"enableUpdateButton()\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("High quality MP3(bigger files)"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"mp3Quality\" value=\"high\" onClick=\"enableUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>&nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<fieldset style=\"width:300px; height:180px\">\r\n");
      out.write("\t\t\t\t\t<legend align=\"center\">");
      out.print( pageGrpData.getWord("Screen capture options"));
      out.write("</legend>\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("Enable screen capture"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t ");
   
							     if(pageGrpData.userHasRight(userRightsDataResult, "ALLOW_MANAGER_SCREEN_MONITORING")) {
                                                        
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id='screenRecording' type='checkbox' name='screenRecording' value='ON' onClick='enableUpdateButton();validateRecordings();updateScreenCaptureBox()' > \r\n");
      out.write("\t\t\t\t\t\t\t");

							      }else{
							 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t <input id='screenRecording' type='checkbox' name='screenRecording' value='' disabled>\r\n");
      out.write("\t\t\t\t\t\t\t ");
  } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr height=\"10\"><td>&nbsp;&nbsp;</td></tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("Recording percentage"));
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 
									if( pageGrpData.userHasRight(userRightsDataResult, "ALLOW_MANAGER_SCREEN_MONITORING")) {
								
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select name='screenRecPer' onChange='enableUpdateButton()'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value='5'>5 %</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value='10'>10 %</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value='20'>20 %</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value='25'>25 %</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value='30'>30 %</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value='35'>35 %</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value='40'>40 %</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value='45'>45 %</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value='50' selected>50 %</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value='55'>55 %</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value='60'>60 %</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value='65'>65 %</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value='70'>70 %</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value='75'>75 %</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value='80'>80 %</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value='85'>85 %</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 
									}else{
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name='screenRecPer' disabled>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='0'></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='5'>5 %</option>\r\n");
      out.write("                                                                                <option value='10'>10 %</option>\r\n");
      out.write("                                                                                <option value='20'>20 %</option>\r\n");
      out.write("                                                                                <option value='25'>25 %</option>\r\n");
      out.write("                                                                                <option value='30'>30 %</option>\r\n");
      out.write("                                                                                <option value='35'>35 %</option>\r\n");
      out.write("                                                                                <option value='40'>40 %</option>\r\n");
      out.write("                                                                                <option value='45'>45 %</option>\r\n");
      out.write("                                                                                <option value='50'>50 %</option>\r\n");
      out.write("                                                                                <option value='55'>55 %</option>\r\n");
      out.write("                                                                                <option value='60'>60 %</option>\r\n");
      out.write("                                                                                <option value='65'>65 %</option>\r\n");
      out.write("                                                                                <option value='70'>70 %</option>\r\n");
      out.write("                                                                                <option value='75'>75 %</option>\r\n");
      out.write("                                                                                <option value='80'>80 %</option>\r\n");
      out.write("                                                                                <option value='85'>85 %</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\t\r\n");
      out.write("\t\t\t\t\t\t\t \t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<tr><td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("Compression level"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td><td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t ");

                                                                        if(pageGrpData.userHasRight(userRightsDataResult, "ALLOW_MANAGER_SCREEN_MONITORING")) {
                                                                
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name='screenRecCompression' onChange='enableUpdateButton()'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='0'>0</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value='1'>1</option>\r\n");
      out.write("                                                                      \t\t<option value='2'>2</option>\r\n");
      out.write("\t                                                                      \t<option value='3'>3</option>\r\n");
      out.write("                                                                      \t\t<option value='4'>4</option>\r\n");
      out.write("                                                                      \t\t<option value='5'>5</option>\r\n");
      out.write("                                                                      \t\t<option value='6'>6</option>\r\n");
      out.write("                                                                      \t\t<option value='7'>7</option>\r\n");
      out.write("                                                                      \t\t<option value='8'>8</option>\r\n");
      out.write("                                                                      \t\t<option value='9'>9</option>\r\n");
      out.write("                                                                 \t</select>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name='screenRecCompression' disabled>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=''></option>\r\n");
      out.write("                                                                                <option value='1'>1</option>\r\n");
      out.write("                                                                                <option value='2'>2</option>\r\n");
      out.write("                                                                                <option value='3'>3</option>\r\n");
      out.write("                                                                                <option value='4'>4</option>\r\n");
      out.write("                                                                                <option value='5'>5</option>\r\n");
      out.write("                                                                                <option value='6'>6</option>\r\n");
      out.write("                                                                                <option value='7'>7</option>\r\n");
      out.write("                                                                                <option value='8'>8</option>\r\n");
      out.write("                                                                                <option value='9'>9</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <script>\r\n");
      out.write("                                \t\t\t\tif(!appletObj.getIsScreenCaptureAllowed()) {\r\n");
      out.write("\t\t\t\t\t\t\t\t   \tdocument.write(\"<select name='screenRecCompression' disabled><option value='0'></option></select>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t\t\t\t   document.write(\"<select name='screenRecCompression' onChange='enableUpdateButton()'>\");\r\n");
      out.write("                                                                      document.write(\"<option value='0'>0</option>\");\r\n");
      out.write("                                                                      document.write(\"<option value='1'>1</option>\");\r\n");
      out.write("                                                                      document.write(\"<option value='2'>2</option>\");\r\n");
      out.write("                                                                      document.write(\"<option value='3'>3</option>\");\r\n");
      out.write("                                                                      document.write(\"<option value='4'>4</option>\");\r\n");
      out.write("                                                                      document.write(\"<option value='5'>5</option>\");\r\n");
      out.write("                                                                      document.write(\"<option value='6'>6</option>\");\r\n");
      out.write("                                                                      document.write(\"<option value='7'>7</option>\");\r\n");
      out.write("                                                                      document.write(\"<option value='8'>8</option>\");\r\n");
      out.write("                                                                      document.write(\"<option value='9'>9</option>\");\r\n");
      out.write("                                                                  document.write(\"</select>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t</script> -->\r\n");
      out.write("\t\t\t\t\t\t\t</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t\t\t\t<tr><td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script>document.write(MultiArray[\"Colors\"][lang]);</script>\r\n");
      out.write("\t\t\t\t\t\t\t</td><td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"screenRecColors\" onChange=\"enableUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"16b\">16bits</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"32b\">24bits</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td></tr> -->\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"10\"><td>&nbsp;&nbsp;</td></tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t<fieldset style=\"width:610px\">\r\n");
      out.write("\t\t\t\t\t<legend align=\"center\">");
      out.print( pageGrpData.getWord("Audio and screen recording options"));
      out.write("</legend>\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("Enable encryption"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t <script>\r\n");
      out.write("                                    if(appletObj.getIsEncryptionServerAllowed()) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write( \" <input id='encryption' type='checkbox' name='encryptionEnable' value='ON' \" + \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t \t \"  onClick='enableUpdateButton(); updateEncServerBox() '> \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t       \t       );\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \tdocument.write( \" <input id='encryption' type='checkbox' name='encryptionEnable' value='' disabled> \"); \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("Encryption server"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

                                                                        if(pageGrpData.userHasRight(userRightsDataResult, "ALLOW_MANAGER_AUDIO_MONITORING")) {
                                                                
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select name=\"encServer\" onChange=\"enableUpdateButton()\" disabled></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select name=\"encServer\" disabled><option value=''></option></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 }  
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("Encryption method"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 
									//if(pageData.userHasRight(userRightsDataResult, "ALLOW_MANAGER_AUDIO_MONITORING")) {
								
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select name=\"encMethod\" onChange=\"enableUpdateButton()\" disabled>\r\n");
      out.write("                                                                        \t\t<option value=\"\" selected> </option>\r\n");
      out.write("                                                                        \t\t<option value=\"AES\">AES</option>\r\n");
      out.write("                                                                        \t\t<!-- <option value=\"MyAES\"  disabled=\"disabled\">MyAES</option> -->\r\n");
      out.write("                                                                        \t\t<!-- <option value=\"DES3\" disabled=\"disabled\">DES3</option> -->\r\n");
      out.write("                                                                \t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								//	}else {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- \t\t <select name=\"encMethod\"  disabled><option value=''></option></select> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								 //     }
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!--\t<select name=\"encMethod\" onChange=\"enableUpdateButton()\" disabled>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\" selected> </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"AES\">AES</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"MyAES\"  disabled=\"disabled\">MyAES</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"DES3\" disabled=\"disabled\">DES3</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>  -->\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("Minimum Recording Time"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"minRecTime\" onChange=\"enableUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"0\">0 sec</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"5\">5 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10\">10 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"15\">15 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"20\">20 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"25\">25 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"30\" selected>30 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"35\">35 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"40\">40 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"45\">45 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"50\">50 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"55\">55 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"60\">60 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"65\">65 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"70\">70 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"75\">75 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"80\">80 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"85\">85 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"90\">90 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"95\">95 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"100\">100 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"105\">105 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"110\">110 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"115\">115 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"120\">120 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"125\">125 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"130\">130 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"135\">135 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"140\">140 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"145\">145 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"150\">150 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"155\">155 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"160\">160 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"165\">165 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"170\">170 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"175\">175 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"180\">180 secs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("Maximum Recording Time"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"maxRecTime\" onChange=\"enableUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"5\">5 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10\">10 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"15\">15 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"20\">20 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"25\">25 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"30\" selected>30 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"35\">35 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"40\">40 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"45\">45 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"50\">50 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"55\">55 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"60\">60 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"65\">65 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"70\">70 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"75\">75 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"80\">80 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"85\">85 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"90\">90 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"95\">95 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"100\">100 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"105\">105 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"110\">110 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"115\">115 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"120\">120 mins</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td><strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("Recordings prefix name"));
      out.write("</strong>\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("Campaign name"));
      out.write(" &nbsp;\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"default_campaign_name\" id=\"default_campaign_name\" value=\"Campaign\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( pageGrpData.getWord("Client name"));
      out.write("&nbsp;\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"default_client_name_inbound\" id=\"default_client_name_inbound\" value=\"Client\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input style=\"visibility:hidden\" name=\"default_client_name_outbound\" id=\"default_client_name_outbound\" value=\"ClientOutbound\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"10\"><td>&nbsp;&nbsp;</td></tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t<input id=\"update\" name=\"updateInfo\" type=\"button\" value=\"");
      out.print( pageGrpData.getWord("Update") );
      out.write("\" onClick=\"validateInfo()\">\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"10\"><td>&nbsp;&nbsp;</td></tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<script>\r\n");
      out.write("if(userHasRight(\"ALLOW_WORK_FORCE_MANAGEMENT\"))\r\n");
      out.write("{\r\n");
      out.write("\tdocument.write('<div class=\"tab-page\" id=\"tabPage5\">');\r\n");
      out.write("\t\tdocument.write('<h2 class=\"tab\">');\t\t\r\n");
      out.write("\t\tdocument.write(\"");
      out.print( pageGrpData.getWord( "Methods Of Payment"));
      out.write("\");\n");
      out.write("\t\tdocument.write('</h2>');\r\n");
      out.write("\t\ttp1.addTabPage( document.getElementById( \"tabPage5\" ) );\r\n");
      out.write("\t\tdocument.write('<fieldset>');\r\n");
      out.write("\t\tdocument.write('<legend>');\r\n");
      out.write("\t\tdocument.write(\"");
      out.print( pageGrpData.getWord( "Methods Of Payment info"));
      out.write("\");\n");
      out.write("\t\tdocument.write('</legend>');\r\n");
      out.write("\t\t\tdocument.write('<table border=\"0\">');\r\n");
      out.write("\t\t\t  document.write('<tr>');\r\n");
      out.write("\t\t\t  \tdocument.write('<td colspan=\"2\" width=\"394\" height=\"50\">');\r\n");
      out.write("\t\t\t\t\tdocument.write('<select onChange=\"enableUpdateButton()\" name=\"MopSelection\" >');\r\n");
      out.write("\t\t\t\t\t\tdocument.write('<option value=\"\">');\r\n");
      out.write("\t\t\t\t\t\tdocument.write(\"");
      out.print( pageGrpData.getWord( "Select MOP"));
      out.write("\");\n");
      out.write("\t\t\t\t\t\tdocument.write('</option>');\r\n");
      out.write("\t\t\t\t\tdocument.write('</select>');\r\n");
      out.write("\t\t\t\tdocument.write('</td>');\r\n");
      out.write("\t\t\t  document.write('</tr>');\r\n");
      out.write("\t\t\t  document.write('<tr>');\r\n");
      out.write("\t\t\t   document.write('<td width=\"197\" height=\"50\">');\t\t\t\t\r\n");
      out.write("\t\t\t\tdocument.write('</td>');\r\n");
      out.write("\t\t\t\t  document.write('<td width=\"197\" height=\"50\">');\t\t\t\t\r\n");
      out.write("\t\t\t\t\t document.write('</td>');\r\n");
      out.write("\t\t\t  document.write('</tr>');\r\n");
      out.write("\t\t\tdocument.write('</table>');\r\n");
      out.write("\t\tdocument.write('</fieldset>');\r\n");
      out.write("\t\tdocument.write('<br>');\r\n");
      out.write("\t\tdocument.write(\"<input id=\\\"update\\\" name=\\\"updateInfo\\\" type=\\\"button\\\" value=\\\"");
      out.print( pageGrpData.getWord("Update"));
      out.write("\\\" onClick=\\\"validateInfo()\\\">\");\n");
      out.write("\tdocument.write('</div>');\r\n");
      out.write("}\t\r\n");
      out.write("</script>\r\n");
      out.write("\t");
 if(userManagementAllowed) { 
      out.write("\r\n");
      out.write("\t<div class=\"tab-page\" id=\"tabSecurity\">\r\n");
      out.write("\t\t<h2 class=\"tab\">");
      out.print( pageGrpData.getWord( "Security"));
      out.write("</h2>\n");
      out.write("\t\t<script type=\"text/javascript\">tp1.addTabPage( document.getElementById( \"tabSecurity\" ) );</script>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t<legend>");
      out.print( pageGrpData.getWord( "Security settings"));
      out.write("</legend>\n");
      out.write("\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( pageGrpData.getWord("Not allowed users"));
      out.write("</td>\n");
      out.write("\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( pageGrpData.getWord("Allowed users"));
      out.write("</td>\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t<select id=\"notAllowedUsers\" style=\"FONT-WEIGHT: bold; FONT-SIZE: 8pt; WIDTH: 120px\" name=\"notAllowedUsers\" size=\"5\" multiple=\"multiple\">\r\n");
      out.write("\t\t\t\t\t");
for(int i = 0; i < listNotAllowedUsersDataResult.size(); i++)
					{
						String userDbid = (String)listNotAllowedUsersDataResult.elementAt(i).get("USER_DBID");
						String userName = (String)listNotAllowedUsersDataResult.elementAt(i).get("USERNAME");
						if(userDbid.compareTo(currentUserDbid) != 0)
						{
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(userDbid);
      out.write('"');
      out.write('>');
      out.print(userName);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t");
	}
					} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td valign=middle>\r\n");
      out.write("\t\t\t\t\t&nbsp;<img src=\"../img/left_to_right.gif\" style=\"cursor:pointer \" onClick=\"switchOptionsFromSelectBoxes('notAllowedUsers', 'allowedUsers');enableUpdateButton()\"/>&nbsp;<br>\r\n");
      out.write("\t\t\t\t\t&nbsp;<img src=\"../img/right_to_left.gif\" style=\"cursor:pointer \" onClick=\"switchOptionsFromSelectBoxes('allowedUsers', 'notAllowedUsers');enableUpdateButton()\"/>&nbsp;\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t<select id=\"allowedUsers\" style=\"FONT-WEIGHT: bold; FONT-SIZE: 8pt; WIDTH: 120px\" name=\"allowedUsers\" size=\"5\" multiple=\"multiple\">\r\n");
      out.write("\t\t\t\t\t");
for(int i = 0; i < listAllowedUsersDataResult.size(); i++)
					{
						String userDbid = (String)listAllowedUsersDataResult.elementAt(i).get("USER_DBID");
						String userName = (String)listAllowedUsersDataResult.elementAt(i).get("USERNAME");
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(userDbid);
      out.write('"');
      out.write('>');
      out.print(userName);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t");
}	
					if(isNewResource)
					{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(currentUserDbid);
      out.write('"');
      out.write('>');
      out.print(currentUserName);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t");
}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<input id=\"update\" name=\"updateInfo\" type=\"button\" value=\"");
      out.print( pageGrpData.getWord("Update") );
      out.write("\" onClick=\"validateInfo()\">\n");
      out.write("\t</div>\r\n");
      out.write("\t");
 } 
      out.write("\t\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
 pageGrpData.closeConnection(); 
      out.write("\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
