package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import aheevaManager.ressources.*;
import java.util.*;
import java.text.*;
import aheevaManager.schedule.*;
import aheevaManager.ressources.*;
import java.util.*;
import jxl.*;
import aheevaManager.ressources.*;

public final class blackListNumberInCampaign1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(2);
    _jspx_dependants.add("/aheevaManager/Resources_pages/xc2_default_labels.jsp");
    _jspx_dependants.add("/aheevaManager/Resources_pages/blackListNumberInCampaignFunctions_labels.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
    pageData.openConnection();

      out.write("\r\n");
      out.write("<title>Record Picker11</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"xc2_default.css\" type=\"text/css\">\r\n");
      out.write("<LINK href=\"livestats.css\" \trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" >\r\n");
      out.write("\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"tab_luna.css\" />\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style_2.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\" href=\"slider/css/luna.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pagexc2Data = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pagexc2Data.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
pagexc2Data.openConnection();
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("// variables of labels;// \r\n");
      out.write("var phrase= new Array();\r\n");
      out.write("phrase[0]=\"");
      out.print( pagexc2Data.getWord("January"));
      out.write("\";\r\n");
      out.write("phrase[1]=\"");
      out.print( pagexc2Data.getWord("February"));
      out.write("\";\r\n");
      out.write("phrase[2]=\"");
      out.print( pagexc2Data.getWord("March"));
      out.write("\";\r\n");
      out.write("phrase[3]=\"");
      out.print( pagexc2Data.getWord("April"));
      out.write("\";\r\n");
      out.write("phrase[4]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";         \r\n");
      out.write("phrase[5]=\"");
      out.print( pagexc2Data.getWord("June"));
      out.write("\";\r\n");
      out.write("phrase[6]=\"");
      out.print( pagexc2Data.getWord("July"));
      out.write("\";\r\n");
      out.write("phrase[7]=\"");
      out.print( pagexc2Data.getWord("August"));
      out.write("\";\r\n");
      out.write("phrase[8]=\"");
      out.print( pagexc2Data.getWord("September"));
      out.write("\";\r\n");
      out.write("phrase[9]=\"");
      out.print( pagexc2Data.getWord("October"));
      out.write("\";\r\n");
      out.write("phrase[10]=\"");
      out.print( pagexc2Data.getWord("November"));
      out.write("\";\r\n");
      out.write("phrase[11]=\"");
      out.print( pagexc2Data.getWord("December"));
      out.write("\";\r\n");
      out.write("phrase[12]=\"");
      out.print( pagexc2Data.getWord("Jan"));
      out.write("\";\r\n");
      out.write("phrase[13]=\"");
      out.print( pagexc2Data.getWord("Feb"));
      out.write("\";\r\n");
      out.write("phrase[14]=\"");
      out.print( pagexc2Data.getWord("Mar"));
      out.write("\";\r\n");
      out.write("phrase[15]=\"");
      out.print( pagexc2Data.getWord("Apr"));
      out.write("\";\r\n");
      out.write("phrase[16]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";\r\n");
      out.write("phrase[17]=\"");
      out.print( pagexc2Data.getWord("Jun"));
      out.write("\";\r\n");
      out.write("phrase[18]=\"");
      out.print( pagexc2Data.getWord("Jul"));
      out.write("\";\r\n");
      out.write("phrase[19]=\"");
      out.print( pagexc2Data.getWord("Aug"));
      out.write("\";\r\n");
      out.write("phrase[20]=\"");
      out.print( pagexc2Data.getWord("Sep"));
      out.write("\";\r\n");
      out.write("phrase[21]=\"");
      out.print( pagexc2Data.getWord("Oct"));
      out.write("\";\r\n");
      out.write("phrase[22]=\"");
      out.print( pagexc2Data.getWord("Nov"));
      out.write("\";\r\n");
      out.write("phrase[23]=\"");
      out.print( pagexc2Data.getWord("Dec"));
      out.write("\";\r\n");
      out.write("phrase[24]=\"");
      out.print( pagexc2Data.getWord("Sunday"));
      out.write("\";\r\n");
      out.write("phrase[25]=\"");
      out.print( pagexc2Data.getWord("Monday"));
      out.write("\";\r\n");
      out.write("phrase[26]=\"");
      out.print( pagexc2Data.getWord("Tuesday"));
      out.write("\";\r\n");
      out.write("phrase[27]=\"");
      out.print( pagexc2Data.getWord("Wednesday"));
      out.write("\";\r\n");
      out.write("phrase[28]=\"");
      out.print( pagexc2Data.getWord("Thursday"));
      out.write("\";\r\n");
      out.write("phrase[29]=\"");
      out.print( pagexc2Data.getWord("Friday"));
      out.write("\";\r\n");
      out.write("phrase[30]=\"");
      out.print( pagexc2Data.getWord("Saturday"));
      out.write("\";\r\n");
      out.write("phrase[31]=\"");
      out.print( pagexc2Data.getWord("Sun"));
      out.write("\";\r\n");
      out.write("phrase[32]=\"");
      out.print( pagexc2Data.getWord("Mon"));
      out.write("\";\r\n");
      out.write("phrase[33]=\"");
      out.print( pagexc2Data.getWord("Tue"));
      out.write("\";\r\n");
      out.write("phrase[34]=\"");
      out.print( pagexc2Data.getWord("Wed"));
      out.write("\";\r\n");
      out.write("phrase[35]=\"");
      out.print( pagexc2Data.getWord("Thu"));
      out.write("\";\r\n");
      out.write("phrase[36]=\"");
      out.print( pagexc2Data.getWord("Fri"));
      out.write("\";\r\n");
      out.write("phrase[37]=\"");
      out.print( pagexc2Data.getWord("Sat"));
      out.write("\";\r\n");
      out.write("phrase[38]=\"");
      out.print( pagexc2Data.getWord("Su"));
      out.write("\";\r\n");
      out.write("phrase[39]=\"");
      out.print( pagexc2Data.getWord("Mo"));
      out.write("\";\r\n");
      out.write("phrase[40]=\"");
      out.print( pagexc2Data.getWord("Tu"));
      out.write("\";\r\n");
      out.write("phrase[41]=\"");
      out.print( pagexc2Data.getWord("We"));
      out.write("\";\r\n");
      out.write("phrase[42]=\"");
      out.print( pagexc2Data.getWord("Th"));
      out.write("\";\r\n");
      out.write("phrase[43]=\"");
      out.print( pagexc2Data.getWord("Fr"));
      out.write("\";\r\n");
      out.write("phrase[44]=\"");
      out.print( pagexc2Data.getWord("Sa"));
      out.write("\";\r\n");
      out.write("phrase[45]=\"");
      out.print( pagexc2Data.getWord(" Today "));
      out.write("\";\r\n");
      out.write("phrase[46]=\"");
      out.print( pagexc2Data.getWord("Clear"));
      out.write("\";\r\n");
      out.write("phrase[47]=\"");
      out.print( pagexc2Data.getWord("Back"));
      out.write("\";\r\n");
      out.write("phrase[48]=\"");
      out.print( pagexc2Data.getWord("Close"));
      out.write("\";\r\n");
      out.write("phrase[49]=\"");
      out.print( pagexc2Data.getWord("Reset"));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 pagexc2Data.closeConnection(); 
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

beanManagerData pageBlaklata = new beanManagerData();
pageBlaklata.openConnection();
if( session.getAttribute("USER_LANGUAGE") != null )
	pageBlaklata.setDefaultLanguage( (String)session.getAttribute("USER_LANGUAGE") );


      out.write("\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/javascript\">\r\n");
      out.write("var Blakl= new Array();\r\n");
      out.write("\r\n");
      out.write("Blakl[0]=\"");
      out.print( pageBlaklata.getWord("The number must be numeric") );
      out.write("\";\r\n");
      out.write("Blakl[1]=\"");
      out.print( pageBlaklata.getWord("This number cannot be reached for these campaigns") );
      out.write("\";\r\n");
      out.write("Blakl[2]=\"");
      out.print( pageBlaklata.getWord("This number is not assigned to any campaign") );
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 pageBlaklata.closeConnection(); 
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\" src=\"jsUtil.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"xc2_default.js\"></script>\r\n");
      out.write("<script language=\"javascript\">xcAutoHide=1000;</script>\r\n");
      out.write("<script language=\"javascript\" src=\"xc2_inpage.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" />-->\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("var NS4 = document.layers ? 1:0\r\n");
      out.write("var IE4 = document.all ? 1:0\r\n");
      out.write("var IE5 = document.getElementById&&document.all ? 1:0\r\n");
      out.write("var NS6 = document.getElementById&&!document.all ? 1:0\r\n");
      out.write("\r\n");
      out.write("var x=0;\r\n");
      out.write("var y=0;\r\n");
      out.write("var closetable = \"</TD></TR></TABLE></TD></TR></TABLE>\";\t\r\n");
      out.write("if(!IE4) {\r\n");
      out.write("\tdocument.captureEvents(Event.MOUSEMOVE);\r\n");
      out.write("\tdocument.onmousemove = GetPos;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("function Desc(text ) {\r\n");
      out.write(" \tvar opentable = \"<TABLE BGCOLOR='#000000' BORDER=0 CELLPADDING=0 CELLSPACING=1 WIDTH=140><TR><TD ALIGN=center><TABLE BGCOLOR='#FFFFE1' BORDER=0 CELLPADDING=3 CELLSPACING=1 WIDTH=138><TR><TD VALIGN=top style='font-size:10px; font-family:Tahoma' align=left><IMG SRC='../img/help.gif' HEIGHT=24 WIDTH=30 VSPACE=0 HSPACE=0 ALIGN=left>\";\r\n");
      out.write("\t \r\n");
      out.write("\tif(NS6) {\r\n");
      out.write("\t\tdocument.getElementById(\"Description\").innerHTML  = opentable+text+closetable;\r\n");
      out.write("\t\tdocument.getElementById(\"Description\").style.left = x-12;\r\n");
      out.write("\t\tdocument.getElementById(\"Description\").style.top  = y+10;\r\n");
      out.write("\t\tdocument.getElementById(\"Description\").style.visibility = \"visible\";\r\n");
      out.write("\t}\r\n");
      out.write(" \tif(IE4) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.all[\"Description\"].innerHTML = opentable+text+closetable;\r\n");
      out.write("\t\tDescription.style.pixelLeft = event.clientX-12;\r\n");
      out.write("\t\tDescription.style.posTop  = document.body.scrollTop+event.clientY+16;\r\n");
      out.write("\t\tDescription.style.visibility = \"visible\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse {\r\n");
      out.write("\t\tvar nets = document.layers[\"Description\"];\r\n");
      out.write("\t\tnets.document.open();\r\n");
      out.write("\t\tnets.document.write(opentable+text+closetable);\r\n");
      out.write("\t\tdocument.Description.left = x-12;\r\n");
      out.write("\t\tdocument.Description.top = y+10;\r\n");
      out.write("\t\tnets.visibility = \"show\";\r\n");
      out.write("\t\tdocument.close();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function GetPos(evnt){\r\n");
      out.write("\tx = evnt.pageX;\r\n");
      out.write("\ty = evnt.pageY;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function noDesc() {\r\n");
      out.write("\r\n");
      out.write("\tif(NS6) {\r\n");
      out.write("\t\tdocument.getElementById(\"Description\").style.visibility = \"hidden\";\r\n");
      out.write("\t}\r\n");
      out.write("\tif(IE4) {\r\n");
      out.write("\t\tDescription.style.visibility = \"hidden\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse {\r\n");
      out.write("\t\tdocument.Description.visibility = \"hidden\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .contentText{\r\n");
      out.write("\tfont:\t\t\t12px Tahoma;\r\n");
      out.write("\tcolor:\t\t\tBlack;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\tclear:\t\t\tboth;\r\n");
      out.write("\tborder:\t\t\t1px solid rgb( 145, 155, 156 );\r\n");
      out.write("\tbackground:\t\trgb( 252, 252, 254 );\r\n");
      out.write("\tz-index:\t\t2;\r\n");
      out.write("\tposition:\t\trelative;\r\n");
      out.write("\ttop:\t\t\t-2px;\r\n");
      out.write("\r\n");
      out.write("\tfont:\t\t\t11px Tahoma;\r\n");
      out.write("\tcolor:\t\t\tBlack;\r\n");
      out.write("\r\n");
      out.write("\tfilter:\t\t\tprogid:DXImageTransform.Microsoft.Gradient(StartColorStr=#fffcfcfe, EndColorStr=#fff4f3ee, GradientType=0)\r\n");
      out.write("\t\t\t\t\tprogid:DXImageTransform.Microsoft.Shadow(Color=#ff919899, Strength=2, Direction=135);\r\n");
      out.write("\t\r\n");
      out.write("\t/* 244, 243, 238 */ \r\n");
      out.write("\t/*145, 155, 156 */\r\n");
      out.write("\tpadding:\t\t10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-row {\r\n");
      out.write("\tz-index:\t\t1;\r\n");
      out.write("\twhite-space:\tnowrap;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(".dynamic-tab-pane-control .tab-row .tab.selected {\r\n");
      out.write("\twidth:\t\t\t\t74px  ;\r\n");
      out.write("\theight:\t\t\t\t18px  ;\r\n");
      out.write("\tbackground-image:\turl( \"tab.active.png\" )  ;\r\n");
      out.write("\tbackground-repaet:\tno-repeat;\r\n");
      out.write("\r\n");
      out.write("\tborder-bottom-width:\t0;\r\n");
      out.write("\tz-index:\t\t3;\r\n");
      out.write("\tpadding:\t\t2px 0 0px 0;\r\n");
      out.write("\tmargin:\t\t\t1px -3px -3px 0px;\r\n");
      out.write("\ttop:\t\t\t-2px;\r\n");
      out.write("\tfont:\t\t\t11px Tahoma;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-row .tab a {\r\n");
      out.write("\tfont:\t\t\t\t11px Tahoma;\r\n");
      out.write("\tcolor:\t\t\t\tBlack;\r\n");
      out.write("\ttext-decoration:\tnone;\r\n");
      out.write("\tcursor:\t\t\t\tdefault;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-row .tab.hover {\r\n");
      out.write("\tfont:\t\t\t\t11px Tahoma;\r\n");
      out.write("\twidth:\t\t\t\t70px;\r\n");
      out.write("\theight:\t\t\t\t16px;\r\n");
      out.write("\tbackground-image:\turl( \"tab.hover.png\" );\r\n");
      out.write("\tbackground-repaet:\tno-repeat;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(".dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("html, body {\r\n");
      out.write("/*\tbackground:\tThreeDFace; */\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("\tmargin:\t\t0;\r\n");
      out.write("\tpadding:\t0;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("/* over ride styles from webfxlayout */\r\n");
      out.write(" \r\n");
      out.write("body {\r\n");
      out.write("\tmargin:\t\t10px;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("\theight:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control h2 {\r\n");
      out.write("\ttext-align:\tcenter;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control h2 a {\r\n");
      out.write("\tdisplay:\tinline;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control a:hover {\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(" .dynamic-tab-pane-control.tab-pane {\r\n");
      out.write("\tposition:\trelative;\r\n");
      out.write("\twidth:\t\t100%;\t\t \r\n");
      out.write("\tmargin-right:\t-2px;\t \r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"blackListNumberInCampaignFunctions.js\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"no_call_act_body\">\r\n");
      out.write("<br />\r\n");
      out.write("<DIV ID=\"Description\" STYLE=\"position:absolute; top:5px; left:5px; visibility:hide; z-index:1; background-color:#FFFFCC;\"></DIV>\r\n");
      out.write("\r\n");
      out.write("<div class=\"dynamic-tab-pane-control\">\r\n");
      out.write("\t<div class=\"tab-pane\" id=\"tabPane1\"> \r\n");
      out.write("\t\r\n");
      out.write(" \t\t\r\n");
      out.write("    \t<div class=\"tab-page\" id=\"general\"> \r\n");
      out.write("      <fieldset>\r\n");
      out.write("      <legend> \r\n");
      out.write("      ");
      out.print(pageData.getWord("Do-not-call list number search"));
      out.write("\r\n");
      out.write("      </legend>\r\n");
      out.write("      <form name=\"theForm\">\r\n");
      out.write("        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\" width=\"100%\">\r\n");
      out.write("          <tr> \r\n");
      out.write("            <td style=\"border-left-style: none; border-left-width: 1; border-top-style: none; border-top-width: 1\" colspan=\"2\">&nbsp;</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr> \r\n");
      out.write("            <td width=\"30%\" align=\"right\" height=\"26\" style=\"border-left-style: none; border-left-width: 1; border-top-style: none; border-top-width: 1\"> \r\n");
      out.write("              ");
      out.print( pageData.getWord("Enter a number"));
      out.write(" \r\n");
      out.write("              &nbsp;&nbsp;</td>\r\n");
      out.write("            <td width=\"70%\" height=\"26\" align=\"left\"> <input type=\"text\" id=\"blacklistNumber\" name=\"blacklistNumber\" size=\"15\"/> \r\n");
      out.write("              &nbsp;<input type=\"button\"  name=\"searchBlacklistNumberInCampaign\" id=\"searchBlacklistNumberInCampaign\" value='");
      out.print( pageData.getWord("Search"));
      out.write("' onClick=\"addRows()\">\r\n");
      out.write("              <!-- &nbsp; <input type=\"button\"  name=\"saveBlacklistCampaign\" id=\"saveBlacklistCampaign\" value='");
      out.print( pageData.getWord("Save"));
      out.write("' onClick=\"removeFromBlacklistCampaign()\"> -->\r\n");
      out.write("              &nbsp; <input type=\"button\"  name=\"refresh_blacklist_number\" id=\"refresh_blacklist_number\" value='");
      out.print( pageData.getWord("Refresh"));
      out.write("' onClick=\"clear_form()\">\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr height=\"40\" colspan=\"2\"> </tr>\r\n");
      out.write("          <tr height=\"40\"> \r\n");
      out.write("            <td colspan=\"2\"> <div id=\"campaign_ranges\"> </div></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("      </form>\r\n");
      out.write("      </fieldset>\r\n");
      out.write("    </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
 pageData.closeConnection(); 
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
