package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.lang.*;
import aheevaManager.ressources.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.*;
import aheevaManager.schedule.*;
import aheevaManager.ressources.*;
import java.util.*;
import jxl.*;
import aheevaManager.ressources.*;

public final class campaign_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(2);
    _jspx_dependants.add("/aheevaManager/Resources_pages/xc2_default_labels.jsp");
    _jspx_dependants.add("/aheevaManager/Resources_pages/campaignFunctions_labels.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	response.setHeader("Pragma", "no-cache");
	response.setHeader("Cache-Control", "no-cache");
	response.setDateHeader("Expires", 0);
	
	PreparedStatement ps;
	ResultSet rs;
	String currentUserDbid = (String)session.getAttribute("CURRENT_USER_DBID");
	String campaignDbid = request.getParameter("dbid");
	String tenantDbid = request.getParameter("tenant_dbid");
	int campaignID = -1;
	int tenantID = 0;
	if(campaignDbid  != null && !campaignDbid.equals("")){
		try{
			campaignID = Integer.parseInt(campaignDbid);
		}catch(NumberFormatException e){
			e.printStackTrace();
		}
	}
	if(tenantDbid != null && !campaignDbid.equals("")){
		try{
			tenantID = Integer.parseInt(tenantDbid);
		}catch(NumberFormatException e){
			e.printStackTrace();
		}
	}

	beanManagerData pageCData = new beanManagerData();
	if( session.getAttribute("USER_LANGUAGE") != null )
		pageCData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));

	

	String userAssignedTenants = "(SELECT USER_DBID FROM cfg_user_authorize_ressources WHERE RESSOURCE_TYPE='TENANT' AND RESSOURCE_DBID='"+tenantDbid+"')";
	String userAssignedCampaigns = "(SELECT USER_DBID FROM cfg_user_authorize_ressources WHERE RESSOURCE_TYPE='CAMPAIGN' AND RESSOURCE_DBID='"+campaignDbid+"')";
	String listAllowedUsersQuery = "SELECT DISTINCT U.DBID AS USER_DBID, USERNAME FROM cfg_user_authorize_ressources, cfg_user U "+
		"WHERE RESSOURCE_TYPE='CAMPAIGN' AND U.DBID = USER_DBID AND RESSOURCE_DBID='"+campaignDbid+"' ORDER BY USERNAME";
	String listNotAllowedUsersQuery = "SELECT DISTINCT DBID AS USER_DBID, USERNAME FROM cfg_user WHERE ALLOW_CAMPAIGN_MANAGEMENT='yes' AND state='1' "+
		"AND DBID NOT IN "+userAssignedCampaigns+" AND DBID IN "+userAssignedTenants+" ORDER BY USERNAME";
	String userRightsQuery = "SELECT USERNAME, ALLOW_USER_MANAGEMENT, ALLOW_CAMPAIGN_MANAGEMENT,ALLOW_CALLING_LIST_MANAGEMENT FROM cfg_user WHERE DBID='"+currentUserDbid+"'";
	String switchConfiguredPorts = "SELECT SUM(IF(NUMBER_OF_LINES < 0, 10000, NUMBER_OF_LINES)) AS NB_CONFIGURED_PORT FROM cfg_switch;";
	String campaignListQry = "SELECT NAME from cfg_campaign WHERE  TENANT_DBID='"+tenantDbid+"'";

	pageCData.openConnection();
	pageCData.executeFromString(listAllowedUsersQuery);
	Vector <HashMap> listAllowedUsersDataResult = pageCData.CreateVectorFromBean();
	pageCData.executeFromString(listNotAllowedUsersQuery);
	Vector <HashMap> listNotAllowedUsersDataResult = pageCData.CreateVectorFromBean();
	pageCData.executeFromString(userRightsQuery);
	Vector <HashMap> userRightsDataResult = pageCData.CreateVectorFromBean();
	pageCData.executeFromString(switchConfiguredPorts);
	Vector <HashMap> switchConfiguredPortsResult = pageCData.CreateVectorFromBean();
	pageCData.executeFromString(campaignListQry);//retrieve list of existing cmps
	Vector <HashMap> campaignListResult = pageCData.CreateVectorFromBean();

	String currentUserName = (String)userRightsDataResult.elementAt(0).get("USERNAME");
	String nbConfiguredPorts = (String)switchConfiguredPortsResult.elementAt(0).get("NB_CONFIGURED_PORT");
	if (nbConfiguredPorts.length() < 1)
	{
		nbConfiguredPorts = "0";
	}
	boolean userManagementAllowed = pageCData.userHasRight(userRightsDataResult, "ALLOW_USER_MANAGEMENT");
	boolean isNewResource = campaignDbid.compareTo("") == 0;
	if(!pageCData.userHasRight(userRightsDataResult, "ALLOW_CAMPAIGN_MANAGEMENT"))
	{ 
      out.write("\r\n");
      out.write("\t\t");
      if (true) {
        _jspx_page_context.forward("forbidden.jsp");
        return;
      }
      out.write('\r');
      out.write('\n');
	} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<HTML>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Add a new campaign</title>\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"tab_luna.css\" />\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style_2.css\" />\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"xc2_default.css\" type=\"text/css\">\r\n");
      out.write("<LINK href=\"livestats.css\" \trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t210px;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t100px;\r\n");
      out.write("}\r\n");
      out.write("html, body { \r\n");
      out.write("/*\tbackground:\tThreeDFace; */\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("form {\r\n");
      out.write("\tmargin:\t\t0;\r\n");
      out.write("\tpadding:\t0;\r\n");
      out.write("}\r\n");
      out.write("/* over ride styles from webfxlayout */\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:\t\t10px;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("\theight:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 {\r\n");
      out.write("\ttext-align:\tcenter;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 a {\r\n");
      out.write("\tdisplay:\tinline;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control a:hover {\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a{\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pagexc2Data = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pagexc2Data.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
pagexc2Data.openConnection();
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("// variables of labels;// \r\n");
      out.write("var phrase= new Array();\r\n");
      out.write("phrase[0]=\"");
      out.print( pagexc2Data.getWord("January"));
      out.write("\";\r\n");
      out.write("phrase[1]=\"");
      out.print( pagexc2Data.getWord("February"));
      out.write("\";\r\n");
      out.write("phrase[2]=\"");
      out.print( pagexc2Data.getWord("March"));
      out.write("\";\r\n");
      out.write("phrase[3]=\"");
      out.print( pagexc2Data.getWord("April"));
      out.write("\";\r\n");
      out.write("phrase[4]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";         \r\n");
      out.write("phrase[5]=\"");
      out.print( pagexc2Data.getWord("June"));
      out.write("\";\r\n");
      out.write("phrase[6]=\"");
      out.print( pagexc2Data.getWord("July"));
      out.write("\";\r\n");
      out.write("phrase[7]=\"");
      out.print( pagexc2Data.getWord("August"));
      out.write("\";\r\n");
      out.write("phrase[8]=\"");
      out.print( pagexc2Data.getWord("September"));
      out.write("\";\r\n");
      out.write("phrase[9]=\"");
      out.print( pagexc2Data.getWord("October"));
      out.write("\";\r\n");
      out.write("phrase[10]=\"");
      out.print( pagexc2Data.getWord("November"));
      out.write("\";\r\n");
      out.write("phrase[11]=\"");
      out.print( pagexc2Data.getWord("December"));
      out.write("\";\r\n");
      out.write("phrase[12]=\"");
      out.print( pagexc2Data.getWord("Jan"));
      out.write("\";\r\n");
      out.write("phrase[13]=\"");
      out.print( pagexc2Data.getWord("Feb"));
      out.write("\";\r\n");
      out.write("phrase[14]=\"");
      out.print( pagexc2Data.getWord("Mar"));
      out.write("\";\r\n");
      out.write("phrase[15]=\"");
      out.print( pagexc2Data.getWord("Apr"));
      out.write("\";\r\n");
      out.write("phrase[16]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";\r\n");
      out.write("phrase[17]=\"");
      out.print( pagexc2Data.getWord("Jun"));
      out.write("\";\r\n");
      out.write("phrase[18]=\"");
      out.print( pagexc2Data.getWord("Jul"));
      out.write("\";\r\n");
      out.write("phrase[19]=\"");
      out.print( pagexc2Data.getWord("Aug"));
      out.write("\";\r\n");
      out.write("phrase[20]=\"");
      out.print( pagexc2Data.getWord("Sep"));
      out.write("\";\r\n");
      out.write("phrase[21]=\"");
      out.print( pagexc2Data.getWord("Oct"));
      out.write("\";\r\n");
      out.write("phrase[22]=\"");
      out.print( pagexc2Data.getWord("Nov"));
      out.write("\";\r\n");
      out.write("phrase[23]=\"");
      out.print( pagexc2Data.getWord("Dec"));
      out.write("\";\r\n");
      out.write("phrase[24]=\"");
      out.print( pagexc2Data.getWord("Sunday"));
      out.write("\";\r\n");
      out.write("phrase[25]=\"");
      out.print( pagexc2Data.getWord("Monday"));
      out.write("\";\r\n");
      out.write("phrase[26]=\"");
      out.print( pagexc2Data.getWord("Tuesday"));
      out.write("\";\r\n");
      out.write("phrase[27]=\"");
      out.print( pagexc2Data.getWord("Wednesday"));
      out.write("\";\r\n");
      out.write("phrase[28]=\"");
      out.print( pagexc2Data.getWord("Thursday"));
      out.write("\";\r\n");
      out.write("phrase[29]=\"");
      out.print( pagexc2Data.getWord("Friday"));
      out.write("\";\r\n");
      out.write("phrase[30]=\"");
      out.print( pagexc2Data.getWord("Saturday"));
      out.write("\";\r\n");
      out.write("phrase[31]=\"");
      out.print( pagexc2Data.getWord("Sun"));
      out.write("\";\r\n");
      out.write("phrase[32]=\"");
      out.print( pagexc2Data.getWord("Mon"));
      out.write("\";\r\n");
      out.write("phrase[33]=\"");
      out.print( pagexc2Data.getWord("Tue"));
      out.write("\";\r\n");
      out.write("phrase[34]=\"");
      out.print( pagexc2Data.getWord("Wed"));
      out.write("\";\r\n");
      out.write("phrase[35]=\"");
      out.print( pagexc2Data.getWord("Thu"));
      out.write("\";\r\n");
      out.write("phrase[36]=\"");
      out.print( pagexc2Data.getWord("Fri"));
      out.write("\";\r\n");
      out.write("phrase[37]=\"");
      out.print( pagexc2Data.getWord("Sat"));
      out.write("\";\r\n");
      out.write("phrase[38]=\"");
      out.print( pagexc2Data.getWord("Su"));
      out.write("\";\r\n");
      out.write("phrase[39]=\"");
      out.print( pagexc2Data.getWord("Mo"));
      out.write("\";\r\n");
      out.write("phrase[40]=\"");
      out.print( pagexc2Data.getWord("Tu"));
      out.write("\";\r\n");
      out.write("phrase[41]=\"");
      out.print( pagexc2Data.getWord("We"));
      out.write("\";\r\n");
      out.write("phrase[42]=\"");
      out.print( pagexc2Data.getWord("Th"));
      out.write("\";\r\n");
      out.write("phrase[43]=\"");
      out.print( pagexc2Data.getWord("Fr"));
      out.write("\";\r\n");
      out.write("phrase[44]=\"");
      out.print( pagexc2Data.getWord("Sa"));
      out.write("\";\r\n");
      out.write("phrase[45]=\"");
      out.print( pagexc2Data.getWord(" Today "));
      out.write("\";\r\n");
      out.write("phrase[46]=\"");
      out.print( pagexc2Data.getWord("Clear"));
      out.write("\";\r\n");
      out.write("phrase[47]=\"");
      out.print( pagexc2Data.getWord("Back"));
      out.write("\";\r\n");
      out.write("phrase[48]=\"");
      out.print( pagexc2Data.getWord("Close"));
      out.write("\";\r\n");
      out.write("phrase[49]=\"");
      out.print( pagexc2Data.getWord("Reset"));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 pagexc2Data.closeConnection(); 
      out.write("\r\n");
      out.write("<!-- Calendrier début -->\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"xc2_default.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">xcAutoHide=1000;</script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"xc2_inpage.js\"></script>\r\n");
      out.write("<!-- Calendrier fin -->\r\n");
      out.write('\r');
      out.write('\n');

beanManagerData pageCamFData = new beanManagerData();
pageCamFData.openConnection();
if( session.getAttribute("USER_LANGUAGE") != null )
	pageCamFData.setDefaultLanguage( (String)session.getAttribute("USER_LANGUAGE") );


      out.write("\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/javascript\">\r\n");
      out.write("var CamF= new Array();\r\n");
      out.write("CamF[0]   = \"");
      out.print(pageCamFData.getWord("Load"));
      out.write("\";\r\n");
      out.write("CamF[1]   = \"");
      out.print(pageCamFData.getWord("Loaded"));
      out.write("\";\r\n");
      out.write("CamF[2]   = \"");
      out.print(pageCamFData.getWord("Unload"));
      out.write("\";\r\n");
      out.write("CamF[3]   = \"");
      out.print(pageCamFData.getWord("Are you sure, you wish to unload this campaign? You should only do this at the end of the day"));
      out.write("\";\r\n");
      out.write("CamF[4]   = \"");
      out.print(pageCamFData.getWord("Not loaded"));
      out.write("\";\r\n");
      out.write("CamF[5]   = \"");
      out.print(pageCamFData.getWord("Start"));
      out.write("\";\r\n");
      out.write("CamF[6]   = \"");
      out.print(pageCamFData.getWord("The total number of ports of started campaigns is higher"));
      out.write("\";\r\n");
      out.write("CamF[7]   = \"");
      out.print(pageCamFData.getWord("than the total configured number of ports."));
      out.write("\";\r\n");
      out.write("CamF[8]   = \"");
      out.print(pageCamFData.getWord("Would you like to continue anyway?"));
      out.write("\";\r\n");
      out.write("CamF[9]   = \"");
      out.print(pageCamFData.getWord("Campaign Started"));
      out.write("\";\r\n");
      out.write("CamF[10]  = \"");
      out.print(pageCamFData.getWord("Stop"));
      out.write("\";\r\n");
      out.write("CamF[11]  = \"");
      out.print(pageCamFData.getWord("Campaign Stopped"));
      out.write("\";\r\n");
      out.write("CamF[12]  = \"");
      out.print(pageCamFData.getWord("Active"));
      out.write("\";\r\n");
      out.write("CamF[13]  = \"");
      out.print(pageCamFData.getWord("Calling list name"));
      out.write("\";\r\n");
      out.write("CamF[14]  = \"");
      out.print(pageCamFData.getWord("Weight"));
      out.write("\";\r\n");
      out.write("CamF[15]  = \"");
      out.print(pageCamFData.getWord("Save"));
      out.write("\";\r\n");
      out.write("CamF[16]  = \"");
      out.print(pageCamFData.getWord("Campaign Loaded"));
      out.write("\";\r\n");
      out.write("CamF[17]  = \"");
      out.print(pageCamFData.getWord("Campaign Running"));
      out.write("\";\r\n");
      out.write("CamF[18]  = \"");
      out.print(pageCamFData.getWord("All calling lists have been updated from Do-not-call lists"));
      out.write("\";\r\n");
      out.write("CamF[19]  = \"");
      out.print(pageCamFData.getWord("Click OK to continue"));
      out.write("\";\r\n");
      out.write("CamF[20]  = \"");
      out.print(pageCamFData.getWord("Campaign cannot be deactivated while it is loaded."));
      out.write("\";\r\n");
      out.write("CamF[21]  = \"");
      out.print(pageCamFData.getWord("The total number of ports of started campaigns is higher"));
      out.write("\";\r\n");
      out.write("CamF[22]  = \"");
      out.print(pageCamFData.getWord("than the total configured number of ports."));
      out.write("\";\r\n");
      out.write("CamF[23]  = \"");
      out.print(pageCamFData.getWord("Invalid use of character"));
      out.write("\";\r\n");
      out.write("CamF[24]  = \"");
      out.print(pageCamFData.getWord("CallerID should be like \\\"CallerName\\\" <(514) 222-2222>"));
      out.write("\";\r\n");
      out.write("CamF[25]  = \"");
      out.print(pageCamFData.getWord("The caller id cannot be more than 100 characters"));
      out.write("\";\r\n");
      out.write("CamF[26]  = \"");
      out.print(pageCamFData.getWord("Campaign already exists"));
      out.write("\";\r\n");
      out.write("CamF[27]  = \"");
      out.print(pageCamFData.getWord("Please Unload/Stop the campaign before deleting it"));
      out.write("\";\r\n");
      out.write("CamF[28]  = \"");
      out.print(pageCamFData.getWord("Are you sure, you wish to delete this campaign"));
      out.write("\";\r\n");
      out.write("CamF[29]  = \"");
      out.print(pageCamFData.getWord(""));
      out.write("\";\r\n");
      out.write("CamF[30]  = \"");
      out.print(pageCamFData.getWord("You must select a routing script"));
      out.write("\";\r\n");
      out.write("CamF[31]  = \"");
      out.print(pageCamFData.getWord("Please wait while applying blacklists to calling list. Do not close your browser !!!"));
      out.write("\";\r\n");
      out.write("CamF[32]  = \"");
      out.print(pageCamFData.getWord("Campaign's name must be provided"));
      out.write("\";\r\n");
      out.write("CamF[33]  = \"");
      out.print(pageCamFData.getWord("You must select a Timeout abandon"));
      out.write("\";\r\n");
      out.write("CamF[34]  = \"");
      out.print(pageCamFData.getWord("You must enter a Recorded message"));
      out.write("\";\r\n");
      out.write("</script>\r\n");
pageCamFData.closeConnection(); 
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"tabpane.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jsUtil.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"trim.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"campaignFunctions.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("var currentUserDbid = ");
      out.print(currentUserDbid);
      out.write(";\r\n");
      out.write("var numberOfPortsAvailable = ");
      out.print(nbConfiguredPorts);
      out.write(";\r\n");
      out.write("var this_cmpName = normalizeString(QueryString('campaign_name'));\r\n");
      out.write("var campaignDbid = normalizeString(QueryString('dbid'));\r\n");
      out.write("var isNewResource = ");
      out.print(isNewResource);
      out.write(";\r\n");
      out.write("var cmpName\t= '';\r\n");
      out.write("var cmpDBID\t= '';\r\n");
      out.write("var tenant_dbid = \"NULL\";\r\n");
      out.write("\r\n");
      out.write("var sTring = String( appletObj.getCampaignStats(this_cmpName) );\r\n");
      out.write("sTringArray = sTring.split(\",\");\r\n");
      out.write("\r\n");
      out.write("var cmpTotalAnswers = sTringArray[1];\r\n");
      out.write("var cmpTotalNoAnswers = sTringArray[2];\r\n");
      out.write("var cmpTotalAbandonned = sTringArray[3];\r\n");
      out.write("var cmpTotalAnswerMachine = sTringArray[4];\r\n");
      out.write("var cmpTotalSIT = sTringArray[5];\r\n");
      out.write("var cmpTotalBusy = sTringArray[6];\r\n");
      out.write("var cmpTotalFax = sTringArray[7];\r\n");
      out.write("var cmpTotalDials = parseInt(cmpTotalAnswers) + \r\n");
      out.write("\t\t\t\t\tparseInt(cmpTotalNoAnswers) + \r\n");
      out.write("\t\t\t\t\tparseInt(cmpTotalAbandonned) + \r\n");
      out.write("\t\t\t\t\tparseInt(cmpTotalAnswerMachine) + \r\n");
      out.write("\t\t\t\t\tparseInt(cmpTotalSIT) + \r\n");
      out.write("\t\t\t\t\tparseInt(cmpTotalBusy) + \r\n");
      out.write("\t\t\t\t\tparseInt(cmpTotalFax);\r\n");
      out.write("\r\n");
      out.write("//get the list of existing cmps\t\t\t\t\t\r\n");
      out.write("var campaignList = new Array();\r\n");
      out.write("var cur_jsCp = \"\";\r\n");
 
for(int i=0; i<campaignListResult.size();i++)
{
	String curCp = (String)campaignListResult.elementAt(i).get("NAME");

      out.write("\r\n");
      out.write("\tcur_jsCp = \"");
      out.print(curCp);
      out.write("\";\r\n");
      out.write("\tcampaignList.push(cur_jsCp);\r\n");

}

      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("    // Associate a default button with pressing the Enter key\r\n");
      out.write("\tfunction KeyDownHandler(btn)\r\n");
      out.write("    {\r\n");
      out.write("        // process only the Enter key\r\n");
      out.write("        if (event.keyCode == 13)\r\n");
      out.write("        {\r\n");
      out.write("            // cancel the default submit\r\n");
      out.write("            event.returnValue=false;\r\n");
      out.write("            event.cancel = true;\r\n");
      out.write("            // submit the form by programmatically clicking the specified button\r\n");
      out.write("            btn.click();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"cam_body\" text=\"#000000\" vLink=\"#666666\" link=\"#000066\" onload=\"displayCampaignInfo();setDialingMode();\">\r\n");
      out.write("\t<div class=\"tab-pane\" id=\"tabPane1\">\r\n");
      out.write("\t\t<form name=\"campaign\" onKeyDown=\"KeyDownHandler(update)\">\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\ttp1 = new WebFXTabPane( document.getElementById( \"tabPane1\" ) );\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<div class=\"tab-page\" id=\"tabGeneral\">\r\n");
      out.write("\t\t\t\t<h2 class=\"tab\">");
      out.print(	pageCData.getWord("General"));
      out.write("</h2>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">tp1.addTabPage( document.getElementById( \"tabGeneral\" ) );</script>\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend>");
      out.print(	pageCData.getWord("General information"));
      out.write("</legend>\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td valign=\"top\" align=\"left\">");
      out.print(pageCData.getWord("Campaign name"));
      out.write("&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td valign=\"top\"><input type=\"text\" onChange=\"enableUpdateButton()\" onKeyUp=\"enableUpdateButton()\" size=\"28\" name=\"campaignName\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td valign=\"top\">");
      out.print(pageCData.getWord("Description"));
      out.write("&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td valign=\"top\"><textarea name=\"cmpDescription\" rows=\"4\" cols=\"52\" onChange=\"enableUpdateButton()\" >&nbsp;</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td valign=\"top\">");
      out.print(pageCData.getWord("Number of ports"));
      out.write("&nbsp;&nbsp; </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td valign=\"top\"><input type=\"text\" onChange=\"enableUpdateButton()\" size=\"8\" name=\"cmp_NbrPorts\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td valign=\"top\">");
      out.print(pageCData.getWord("Caller ID"));
      out.write("&nbsp;&nbsp; </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td valign=\"top\"><input type=\"text\" onChange=\"enableUpdateButton()\" size=\"54\" name=\"callerID\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(pageCData.getWord("Caller ID format"));
      out.write(':');
      out.write('"');
      out.write(' ');
      out.print(pageCData.getWord("Caller ID name"));
      out.write("\" &lt;(514) 555-5555&gt;\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td valign=\"top\" align=\"left\">");
      out.print(pageCData.getWord("Active"));
      out.write("&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<input onClick=\"enableUpdateButton()\" type=\"checkbox\" value=\"ON\" name=\"cmpState\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"tab-page\" id=\"tabCallingList\">\r\n");
      out.write("\t\t\t\t<h2 class=\"tab\">");
      out.print(	pageCData.getWord("Calling lists"));
      out.write("</h2>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">tp1.addTabPage( document.getElementById( \"tabCallingList\" ) );</script>\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend>");
      out.print(	pageCData.getWord("Associated calling lists"));
      out.write("</legend>\r\n");
      out.write("\t\t\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td vAlign=\"top\" align=\"left\" width=\"25%\" height=\"61\">");
      out.print(	pageCData.getWord("Available calling lists"));
      out.write("&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td vAlign=\"top\" height=\"61\"><div style=\"width: 400px; height: 175px; overflow: auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table id=\"availableCallingList\" cellSpacing=\"0\" cellPadding=\"0\" width=\"331\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td id=\"availableCallingListTD\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"1\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"45\" bgColor=\"#cccccc\"><b>");
      out.print(	pageCData.getWord("Active"));
      out.write("</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"226\" bgColor=\"#cccccc\"><b>");
      out.print(pageCData.getWord("Calling list name"));
      out.write("</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"56\" bgColor=\"#cccccc\"><b>");
      out.print(	pageCData.getWord("Weight"));
      out.write("</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
 
ps = pageCData.buildPreparedStatement("SELECT name, IF(campaign_dbid=?, 1, 0) AS active, weight, dbid FROM cfg_calling_list "
															+ " WHERE TENANT_DBID=? AND state=TRUE AND campaign_dbid IN(?, 0) ORDER BY name");
ps.setInt(1, campaignID);
ps.setInt(2, tenantID);
ps.setInt(3, campaignID);
rs = ps.executeQuery();
while(rs.next()){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr id=\"availableCallingListTR\" listName=\"");
      out.print( rs.getString(1) );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"45\" align=\"center\">\r\n");
      out.write("\t");
if(rs.getBoolean(2)){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input id='");
      out.print( rs.getString(1) );
      out.write("_check' type=\"checkbox\" name=\"");
      out.print( rs.getString(1) );
      out.write("_check\" value=\"ON\"  onClick=\"enableUpdateButton()\" checked='checked'>\t\t\t\t\r\n");
      out.write("\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input id='");
      out.print( rs.getString(1) );
      out.write("_check' type=\"checkbox\" name=\"");
      out.print( rs.getString(1) );
      out.write("_check\" value=\"ON\"  onClick=\"enableUpdateButton()\">\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"226\">\r\n");
      out.write("\t");
 if( pageCData.userHasRight(userRightsDataResult, "ALLOW_CALLING_LIST_MANAGEMENT") ){ 
		String linkCallingList  =  "modifyCallingList.jsp?dbid="+ rs.getInt(4)+ "&callinglistName="+ rs.getString(1)+ "&tenant_dbid="+ tenantDbid ;
		out.println( "<a href="+linkCallingList + " color='#000000'>" + rs.getString(1) + "</a>" );

	}else{
		out.print( rs.getString(1) );
	}
	
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"56\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input id='");
      out.print( rs.getString(1) );
      out.write("_weight' type=\"text\" name=\"");
      out.print( rs.getString(1) );
      out.write("_weight\" size=\"3\" value=\"");
      out.print( rs.getString(3) );
      out.write("\"  onChange=\"enableUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\t\t\r\n");
}	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"tab-page\" id=\"tabBlackList\">\r\n");
      out.write("\t\t\t\t<h2 class=\"tab\">");
      out.print(	pageCData.getWord("Do-not-call lists"));
      out.write("</h2>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">tp1.addTabPage( document.getElementById( \"tabBlackList\" ) );</script>\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend>");
      out.print(	pageCData.getWord("Associated Do-not-call lists"));
      out.write("</legend>\r\n");
      out.write("\t\t\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td vAlign=\"top\" height=\"61\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table id=\"availableBlackList\" cellSpacing=\"0\" cellPadding=\"0\" width=\"331\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td height=\"21\" align=\"center\">");
      out.print(	pageCData.getWord("Available blacklist groups"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">");
      out.print(	pageCData.getWord("Selected blacklist groups"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"200\" height=\"138\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select id=\"availableBlackListGroups\" width=\"200\" style=\"FONT-WEIGHT: bold; FONT-SIZE: 8pt; WIDTH: 200px\" name=\"availableBlackListGroups\" size=\"10\" multiple onchange=\"enabledAddButton()\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"115\" height=\"138\" bordercolordark=\"#c0c0c0\" nowrap align=\"center\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button name=\"addButton\"  disabled onclick=\"switchOptionsFromSelectBoxes('availableBlackListGroups', 'selectedBlackListGroups');enableUpdateButton()\" style=\"width:40px; height:26px; margin-top:25px; margin-bottom:25px;\" type=button> &gt;&gt; </button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button name=\"dropButton\" disabled onclick=\"switchOptionsFromSelectBoxes('selectedBlackListGroups', 'availableBlackListGroups');enableUpdateButton()\" style=\"WIDTH: 40px; HEIGHT: 26px\" type=button> &lt;&lt; </button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"200\" height=\"138\" bordercolor=\"#000000\" align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select id=\"selectedBlackListGroups\" width=\"200\" style=\"FONT-WEIGHT: bold; FONT-SIZE: 8pt; WIDTH: 200px\" name=\"selectedBlackListGroups\" size=\"10\" multiple onChange=\"enabledDropButton()\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"tab-page\" id=\"tabHours\">\r\n");
      out.write("\t\t\t\t<h2 class=\"tab\">");
      out.print(	pageCData.getWord("Hours"));
      out.write("</h2>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">tp1.addTabPage( document.getElementById( \"tabHours\" ) );</script>\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend>");
      out.print(	pageCData.getWord("Campaign daily hours"));
      out.write("</legend>\r\n");
      out.write("\t\t\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td vAlign=\"top\" align=\"left\" >");
      out.print(	pageCData.getWord("Daily hours"));
      out.write("&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td vAlign=\"top\" height=\"80\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(	pageCData.getWord("Monday"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(	pageCData.getWord("Tuesday"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(	pageCData.getWord("Wednesday"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(	pageCData.getWord("Thursday"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(	pageCData.getWord("Friday"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(	pageCData.getWord("Saturday"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(	pageCData.getWord("Sunday"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(	pageCData.getWord("From"));
      out.write("&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select onchange=\"enableUpdateButton()\" name=\"daily_from_monday\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0200\">24h</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0100\">");
      out.print(	pageCData.getWord("Close"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0000\">00:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0100\">01:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0200\">02:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0300\">03:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0400\">04:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0500\">05:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0600\">06:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0700\">07:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0800\">08:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0900\" selected>09:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1000\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1100\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1200\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1300\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1400\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1500\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1600\">16:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1700\">17:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1800\">18:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1900\">19:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2000\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2100\">21:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2200\">22:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2300\">23:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select onChange=\"enableUpdateButton()\" name=\"daily_from_tuesday\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0200\">24h</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0100\">");
      out.print(pageCData.getWord("Close"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0000\">00:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0100\">01:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0200\">02:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0300\">03:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0400\">04:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0500\">05:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0600\">06:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0700\">07:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0800\">08:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0900\" selected>09:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1000\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1100\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1200\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1300\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1400\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1500\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1600\">16:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1700\">17:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1800\">18:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1900\">19:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2000\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2100\">21:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2200\">22:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2300\">23:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select onchange=\"enableUpdateButton()\" name=\"daily_from_wednesday\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0200\">24h</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0100\">");
      out.print(pageCData.getWord("Close"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0000\">00:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0100\">01:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0200\">02:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0300\">03:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0400\">04:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0500\">05:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0600\">06:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0700\">07:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0800\">08:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0900\" selected>09:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1000\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1100\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1200\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1300\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1400\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1500\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1600\">16:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1700\">17:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1800\">18:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1900\">19:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2000\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2100\">21:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2200\">22:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2300\">23:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select onchange=\"enableUpdateButton()\" name=\"daily_from_thursday\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0200\">24h</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0100\">");
      out.print(pageCData.getWord("Close"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0000\">00:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0100\">01:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0200\">02:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0300\">03:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0400\">04:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0500\">05:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0600\">06:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0700\">07:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0800\">08:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0900\" selected>09:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1000\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1100\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1200\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1300\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1400\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1500\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1600\">16:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1700\">17:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1800\">18:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1900\">19:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2000\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2100\">21:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2200\">22:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2300\">23:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select onchange=\"enableUpdateButton()\" name=\"daily_from_friday\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0200\">24h</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0100\">");
      out.print(pageCData.getWord("Close"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0000\">00:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0100\">01:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0200\">02:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0300\">03:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0400\">04:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0500\">05:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0600\">06:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0700\">07:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0800\">08:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0900\" selected>09:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1000\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1100\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1200\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1300\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1400\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1500\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1600\">16:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1700\">17:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1800\">18:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1900\">19:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2000\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2100\">21:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2200\">22:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2300\">23:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select onchange=\"enableUpdateButton()\" name=\"daily_from_saturday\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0200\">24h</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0100\">");
      out.print(pageCData.getWord("Close"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0000\">00:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0100\">01:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0200\">02:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0300\">03:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0400\">04:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0500\">05:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0600\">06:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0700\">07:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0800\">08:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0900\" selected>09:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1000\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1100\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1200\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1300\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1400\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1500\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1600\">16:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1700\">17:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1800\">18:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1900\">19:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2000\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2100\">21:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2200\">22:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2300\">23:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select onchange=\"enableUpdateButton()\" name=\"daily_from_sunday\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0200\">24h</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0100\">");
      out.print(pageCData.getWord("Close"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0000\">00:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0100\">01:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0200\">02:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0300\">03:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0400\">04:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0500\">05:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0600\">06:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0700\">07:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0800\">08:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0900\" selected>09:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1000\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1100\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1200\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1300\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1400\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1500\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1600\">16:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1700\">17:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1800\">18:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1900\">19:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2000\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2100\">21:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2200\">22:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2300\">23:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(pageCData.getWord("to"));
      out.write("&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select onchange=\"enableUpdateButton()\" name=\"daily_to_monday\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0100\">");
      out.print(pageCData.getWord("Close"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0000\">00:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0100\">01:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0200\">02:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0300\">03:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0400\">04:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0500\">05:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0600\">06:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0700\">07:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0800\">08:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0900\">09:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1000\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1100\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1200\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1300\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1400\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1500\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1600\">16:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1700\">17:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1800\">18:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1900\">19:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2000\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2100\" selected>21:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2200\">22:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2300\">23:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2500\">24h</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select onchange=\"enableUpdateButton()\" name=\"daily_to_tuesday\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0100\">");
      out.print(pageCData.getWord("Close"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0000\">00:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0100\">01:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0200\">02:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0300\">03:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0400\">04:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0500\">05:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0600\">06:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0700\">07:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0800\">08:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0900\">09:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1000\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1100\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1200\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1300\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1400\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1500\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1600\">16:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1700\">17:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1800\">18:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1900\">19:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2000\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2100\" selected>21:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2200\">22:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2300\">23:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2500\">24h</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select onchange=\"enableUpdateButton()\" name=\"daily_to_wednesday\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0100\">");
      out.print(pageCData.getWord("Close"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0000\">00:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0100\">01:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0200\">02:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0300\">03:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0400\">04:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0500\">05:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0600\">06:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0700\">07:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0800\">08:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0900\">09:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1000\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1100\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1200\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1300\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1400\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1500\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1600\">16:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1700\">17:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1800\">18:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1900\">19:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2000\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2100\" selected>21:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2200\">22:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2300\">23:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2500\">24h</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select onchange=\"enableUpdateButton()\" name=\"daily_to_thursday\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0100\">");
      out.print(pageCData.getWord("Close"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0000\">00:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0100\">01:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0200\">02:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0300\">03:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0400\">04:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0500\">05:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0600\">06:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0700\">07:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0800\">08:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0900\">09:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1000\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1100\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1200\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1300\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1400\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1500\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1600\">16:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1700\">17:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1800\">18:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1900\">19:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2000\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2100\" selected>21:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2200\">22:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2300\">23:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2500\">24h</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select onchange=\"enableUpdateButton()\" name=\"daily_to_friday\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0100\">");
      out.print(pageCData.getWord("Close"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0000\">00:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0100\">01:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0200\">02:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0300\">03:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0400\">04:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0500\">05:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0600\">06:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0700\">07:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0800\">08:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0900\">09:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1000\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1100\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1200\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1300\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1400\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1500\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1600\">16:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1700\">17:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1800\">18:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1900\">19:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2000\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2100\" selected>21:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2200\">22:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2300\">23:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2500\">24h</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select onchange=\"enableUpdateButton()\" name=\"daily_to_saturday\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0100\">");
      out.print(pageCData.getWord("Close"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0000\">00:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0100\">01:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0200\">02:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0300\">03:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0400\">04:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0500\">05:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0600\">06:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0700\">07:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0800\">08:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0900\">09:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1000\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1100\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1200\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1300\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1400\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1500\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1600\">16:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1700\">17:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1800\">18:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1900\">19:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2000\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2100\" selected>21:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2200\">22:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2300\">23:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2500\">24h</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select onchange=\"enableUpdateButton()\" name=\"daily_to_sunday\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-0100\">");
      out.print(pageCData.getWord("Close"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0000\">00:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0100\">01:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0200\">02:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0300\">03:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0400\">04:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0500\">05:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0600\">06:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0700\">07:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0800\">08:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0900\">09:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1000\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1100\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1200\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1300\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1400\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1500\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1600\">16:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1700\">17:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1800\">18:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1900\">19:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2000\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2100\" selected>21:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2200\">22:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2300\">23:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2500\">24h</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"tab-page\" id=\"tabMode\">\r\n");
      out.write("\t\t\t\t<h2 class=\"tab\">");
      out.print(pageCData.getWord("Mode"));
      out.write("</h2>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">tp1.addTabPage( document.getElementById( \"tabMode\" ) );</script>\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend>");
      out.print(pageCData.getWord("Dialing Mode"));
      out.write("</legend>\r\n");
      out.write("\t\t\t\t\t<table border=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"routing_script_div\" style=\"margin: 0px 0px 0px 0px;display:;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td width=\"224\">");
      out.print(pageCData.getWord("Associated routing script"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"routing_script\" style=\"margin-bottom:2px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"agent_group_div\" style=\"margin: 0px 0px 0px 0px;display:; \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td width=\"224\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(pageCData.getWord("Agent group"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select onchange=\"enableUpdateButton()\" size=\"1\" name=\"AgentGroupSelection\" style=\"margin-bottom:2px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td vAlign=\"top\" width=\"220\">");
      out.print(pageCData.getWord("Dialing Mode"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td vAlign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select onchange=\"setDialingMode()\" size=\"1\" name=\"dialingMode\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"PREVIEW\">");
      out.print(pageCData.getWord("Preview mode"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"PROGRESSIVE\">");
      out.print(pageCData.getWord("Progressive mode"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"PREDICTIVE\" selected>");
      out.print(pageCData.getWord("Predictive mode"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"BROADCAST\">");
      out.print(pageCData.getWord("Broadcast mode"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td vAlign=\"top\" width=\"220\">");
      out.print(pageCData.getWord("Optimization parameter"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td vAlign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select onchange=\"modifyTargetValue(this.value)\" size=\"1\" name=\"OptimizationParameter\" style=\"margin-right:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"0\">");
      out.print(pageCData.getWord("Agent Busy Factor"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\" selected>");
      out.print(pageCData.getWord("Overdial Rate"));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp; ");
      out.print(pageCData.getWord("Target"));
      out.write(" &nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" maxLength=\"100\" size=\"3\" value=\"10\" name=\"TargetValue\"><b>%</b>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"220\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(pageCData.getWord("Abandon rate"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<INPUT type=\"text\" maxLength=\"3\" size=\"3\" value=\"5\" name=\"AbandonRate\"><b>%</b>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td vAlign=\"top\" align=\"left\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(pageCData.getWord("Answering Machine Detection"));
      out.write(" &nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" onClick=\"enableUpdateButton();checkAnswerMachine()\" checked=\"checked\" name=\"AMD\" id=\"AMD\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td vAlign=\"top\" align=\"left\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"leave_message_div\" style=\"margin: 0px 0px 0px 0px;display:;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(pageCData.getWord("Leave a message if answering machine is detected"));
      out.write("&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" onClick=\"enableUpdateButton()\" id=\"leave_message\" name=\"leave_message\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
 if(userManagementAllowed) { 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"tab-page\" id=\"tabSecurity\">\r\n");
      out.write("\t\t\t\t<h2 class=\"tab\">");
      out.print(pageCData.getWord("Security"));
      out.write("</h2>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">tp1.addTabPage( document.getElementById( \"tabSecurity\" ) );</script>\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend>");
      out.print(pageCData.getWord("Security settings"));
      out.write("</legend>\r\n");
      out.write("\t\t\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(pageCData.getWord("Not allowed users"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(pageCData.getWord("Allowed users"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"notAllowedUsers\" style=\"FONT-WEIGHT: bold; FONT-SIZE: 8pt; WIDTH: 120px\" name=\"notAllowedUsers\" size=\"5\" multiple=\"multiple\">\r\n");
      out.write("\t");
for(int i = 0; i < listNotAllowedUsersDataResult.size(); i++) {
		String userDbid = (String)listNotAllowedUsersDataResult.elementAt(i).get("USER_DBID");
		String userName = (String)listNotAllowedUsersDataResult.elementAt(i).get("USERNAME");
		if(userDbid.compareTo(currentUserDbid) != 0) {
	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(userDbid);
      out.write('"');
      out.write('>');
      out.print(userName);
      out.write("</option>\r\n");
      out.write("\t");
	}
	} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td valign=middle>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;<img src=\"../img/left_to_right.gif\" style=\"cursor:pointer \" onClick=\"switchOptionsFromSelectBoxes('notAllowedUsers', 'allowedUsers');enableUpdateButton()\"/>&nbsp;<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;<img src=\"../img/right_to_left.gif\" style=\"cursor:pointer \" onClick=\"switchOptionsFromSelectBoxes('allowedUsers', 'notAllowedUsers');enableUpdateButton()\"/>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"allowedUsers\" style=\"FONT-WEIGHT: bold; FONT-SIZE: 8pt; WIDTH: 120px\" name=\"allowedUsers\" size=\"5\" multiple=\"multiple\">\r\n");
      out.write("\t");
for(int i = 0; i < listAllowedUsersDataResult.size(); i++) {
		String userDbid = (String)listAllowedUsersDataResult.elementAt(i).get("USER_DBID");
		String userName = (String)listAllowedUsersDataResult.elementAt(i).get("USERNAME");
	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(userDbid);
      out.write('"');
      out.write('>');
      out.print(userName);
      out.write("</option>\r\n");
      out.write("\t");
}	
	if(isNewResource) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(currentUserDbid);
      out.write('"');
      out.write('>');
      out.print(currentUserName);
      out.write("</option>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
 } 
      out.write("\t\t\r\n");
      out.write("\t\t\t<input disabled  size=\"18\" name=\"status\" type=\"text\" value=\"");
      out.print(pageCData.getWord("Not loaded"));
      out.write("\" >\t\r\n");
      out.write("\t\t\t<input disabled name=\"load\" type=\"button\" value=\"");
      out.print(pageCData.getWord("Load"));
      out.write("\" onClick=\"clickLoadButton()\">\r\n");
      out.write("\t\t\t<input disabled name=\"start\" type=\"button\" value=\"");
      out.print(pageCData.getWord("Start"));
      out.write("\" onClick=\"clickStartButton()\">\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br><br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<input id=\"update\" disabled name=\"updateInfo\" type=\"button\" value=\"");
      out.print(pageCData.getWord("Update"));
      out.write("\" onClick=\"validateInfo()\">\r\n");
      out.write("\t\t\t<input name=\"deleteCmp\" type=\"button\" value=\"");
      out.print(pageCData.getWord("Delete"));
      out.write("\" onClick=\"askDelete()\">\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\t\tthis_cmpName = normalizeString(QueryString('campaign_name'));\r\n");
      out.write("\t\tselectObject(document.campaign.daily_from_monday, String( appletObj.getCampaignHour(this_cmpName, 0) ) );\r\n");
      out.write("\t\tselectObject(document.campaign.daily_from_tuesday,  String( appletObj.getCampaignHour(this_cmpName, 1) ));\r\n");
      out.write("\t\tselectObject(document.campaign.daily_from_wednesday,  String( appletObj.getCampaignHour(this_cmpName, 2) ));\r\n");
      out.write("\t\tselectObject(document.campaign.daily_from_thursday,  String( appletObj.getCampaignHour(this_cmpName, 3) ));\r\n");
      out.write("\t\tselectObject(document.campaign.daily_from_friday,  String( appletObj.getCampaignHour(this_cmpName, 4) ));\r\n");
      out.write("\t\tselectObject(document.campaign.daily_from_saturday,  String( appletObj.getCampaignHour(this_cmpName, 5) ));\r\n");
      out.write("\t\tselectObject(document.campaign.daily_from_sunday,  String( appletObj.getCampaignHour(this_cmpName, 6) ));\r\n");
      out.write("\t\tselectObject(document.campaign.daily_to_monday,  String( appletObj.getCampaignHour(this_cmpName, 7) ) );\r\n");
      out.write("\t\tselectObject(document.campaign.daily_to_tuesday, String(  appletObj.getCampaignHour(this_cmpName, 8) ));\r\n");
      out.write("\t\tselectObject(document.campaign.daily_to_wednesday,  String( appletObj.getCampaignHour(this_cmpName, 9) ));\r\n");
      out.write("\t\tselectObject(document.campaign.daily_to_thursday,  String( appletObj.getCampaignHour(this_cmpName, 10) ));\r\n");
      out.write("\t\tselectObject(document.campaign.daily_to_friday,  String( appletObj.getCampaignHour(this_cmpName, 11) ));\r\n");
      out.write("\t\tselectObject(document.campaign.daily_to_saturday,  String( appletObj.getCampaignHour(this_cmpName, 12) ));\r\n");
      out.write("\t\tselectObject(document.campaign.daily_to_sunday,  String( appletObj.getCampaignHour(this_cmpName, 13) ));\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div class=\"TempMessages\" id=\"TempMessages\"> \r\n");
      out.write("\t\t<table border=\"0\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" height=\"100%\">\r\n");
      out.write("\t\t\t<tr> \r\n");
      out.write("\t\t\t\t<td width=\"100%\" id=\"TempMsg\" align=\"center\" class=\"TempMsg\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
pageCData.closeConnection(); 
      out.write("\r\n");
      out.write("</HTML>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
