package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import aheevaManager.ressources.*;
import java.text.*;
import aheevaManager.schedule.*;
import aheevaManager.ressources.*;
import java.util.*;
import jxl.*;

public final class conversationRecPicker1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/aheevaManager/Resources_pages/xc2_default_labels.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Record Picker</title>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
    pageData.openConnection();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"xc2_default.css\" type=\"text/css\">\r\n");
      out.write("<LINK href=\"livestats.css\" \trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pagexc2Data = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pagexc2Data.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
pagexc2Data.openConnection();
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("// variables of labels;// \r\n");
      out.write("var phrase= new Array();\r\n");
      out.write("phrase[0]=\"");
      out.print( pagexc2Data.getWord("January"));
      out.write("\";\r\n");
      out.write("phrase[1]=\"");
      out.print( pagexc2Data.getWord("February"));
      out.write("\";\r\n");
      out.write("phrase[2]=\"");
      out.print( pagexc2Data.getWord("March"));
      out.write("\";\r\n");
      out.write("phrase[3]=\"");
      out.print( pagexc2Data.getWord("April"));
      out.write("\";\r\n");
      out.write("phrase[4]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";         \r\n");
      out.write("phrase[5]=\"");
      out.print( pagexc2Data.getWord("June"));
      out.write("\";\r\n");
      out.write("phrase[6]=\"");
      out.print( pagexc2Data.getWord("July"));
      out.write("\";\r\n");
      out.write("phrase[7]=\"");
      out.print( pagexc2Data.getWord("August"));
      out.write("\";\r\n");
      out.write("phrase[8]=\"");
      out.print( pagexc2Data.getWord("September"));
      out.write("\";\r\n");
      out.write("phrase[9]=\"");
      out.print( pagexc2Data.getWord("October"));
      out.write("\";\r\n");
      out.write("phrase[10]=\"");
      out.print( pagexc2Data.getWord("November"));
      out.write("\";\r\n");
      out.write("phrase[11]=\"");
      out.print( pagexc2Data.getWord("December"));
      out.write("\";\r\n");
      out.write("phrase[12]=\"");
      out.print( pagexc2Data.getWord("Jan"));
      out.write("\";\r\n");
      out.write("phrase[13]=\"");
      out.print( pagexc2Data.getWord("Feb"));
      out.write("\";\r\n");
      out.write("phrase[14]=\"");
      out.print( pagexc2Data.getWord("Mar"));
      out.write("\";\r\n");
      out.write("phrase[15]=\"");
      out.print( pagexc2Data.getWord("Apr"));
      out.write("\";\r\n");
      out.write("phrase[16]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";\r\n");
      out.write("phrase[17]=\"");
      out.print( pagexc2Data.getWord("Jun"));
      out.write("\";\r\n");
      out.write("phrase[18]=\"");
      out.print( pagexc2Data.getWord("Jul"));
      out.write("\";\r\n");
      out.write("phrase[19]=\"");
      out.print( pagexc2Data.getWord("Aug"));
      out.write("\";\r\n");
      out.write("phrase[20]=\"");
      out.print( pagexc2Data.getWord("Sep"));
      out.write("\";\r\n");
      out.write("phrase[21]=\"");
      out.print( pagexc2Data.getWord("Oct"));
      out.write("\";\r\n");
      out.write("phrase[22]=\"");
      out.print( pagexc2Data.getWord("Nov"));
      out.write("\";\r\n");
      out.write("phrase[23]=\"");
      out.print( pagexc2Data.getWord("Dec"));
      out.write("\";\r\n");
      out.write("phrase[24]=\"");
      out.print( pagexc2Data.getWord("Sunday"));
      out.write("\";\r\n");
      out.write("phrase[25]=\"");
      out.print( pagexc2Data.getWord("Monday"));
      out.write("\";\r\n");
      out.write("phrase[26]=\"");
      out.print( pagexc2Data.getWord("Tuesday"));
      out.write("\";\r\n");
      out.write("phrase[27]=\"");
      out.print( pagexc2Data.getWord("Wednesday"));
      out.write("\";\r\n");
      out.write("phrase[28]=\"");
      out.print( pagexc2Data.getWord("Thursday"));
      out.write("\";\r\n");
      out.write("phrase[29]=\"");
      out.print( pagexc2Data.getWord("Friday"));
      out.write("\";\r\n");
      out.write("phrase[30]=\"");
      out.print( pagexc2Data.getWord("Saturday"));
      out.write("\";\r\n");
      out.write("phrase[31]=\"");
      out.print( pagexc2Data.getWord("Sun"));
      out.write("\";\r\n");
      out.write("phrase[32]=\"");
      out.print( pagexc2Data.getWord("Mon"));
      out.write("\";\r\n");
      out.write("phrase[33]=\"");
      out.print( pagexc2Data.getWord("Tue"));
      out.write("\";\r\n");
      out.write("phrase[34]=\"");
      out.print( pagexc2Data.getWord("Wed"));
      out.write("\";\r\n");
      out.write("phrase[35]=\"");
      out.print( pagexc2Data.getWord("Thu"));
      out.write("\";\r\n");
      out.write("phrase[36]=\"");
      out.print( pagexc2Data.getWord("Fri"));
      out.write("\";\r\n");
      out.write("phrase[37]=\"");
      out.print( pagexc2Data.getWord("Sat"));
      out.write("\";\r\n");
      out.write("phrase[38]=\"");
      out.print( pagexc2Data.getWord("Su"));
      out.write("\";\r\n");
      out.write("phrase[39]=\"");
      out.print( pagexc2Data.getWord("Mo"));
      out.write("\";\r\n");
      out.write("phrase[40]=\"");
      out.print( pagexc2Data.getWord("Tu"));
      out.write("\";\r\n");
      out.write("phrase[41]=\"");
      out.print( pagexc2Data.getWord("We"));
      out.write("\";\r\n");
      out.write("phrase[42]=\"");
      out.print( pagexc2Data.getWord("Th"));
      out.write("\";\r\n");
      out.write("phrase[43]=\"");
      out.print( pagexc2Data.getWord("Fr"));
      out.write("\";\r\n");
      out.write("phrase[44]=\"");
      out.print( pagexc2Data.getWord("Sa"));
      out.write("\";\r\n");
      out.write("phrase[45]=\"");
      out.print( pagexc2Data.getWord(" Today "));
      out.write("\";\r\n");
      out.write("phrase[46]=\"");
      out.print( pagexc2Data.getWord("Clear"));
      out.write("\";\r\n");
      out.write("phrase[47]=\"");
      out.print( pagexc2Data.getWord("Back"));
      out.write("\";\r\n");
      out.write("phrase[48]=\"");
      out.print( pagexc2Data.getWord("Close"));
      out.write("\";\r\n");
      out.write("phrase[49]=\"");
      out.print( pagexc2Data.getWord("Reset"));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 pagexc2Data.closeConnection(); 
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"xc2_default.js\"></script>\r\n");
      out.write("<script language=\"javascript\">xcAutoHide=1000;</script>\r\n");
      out.write("<script language=\"javascript\" src=\"xc2_inpage.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\" src=\"jsUtil.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" />-->\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("var NS4 = document.layers ? 1:0\r\n");
      out.write("var IE4 = document.all ? 1:0\r\n");
      out.write("var IE5 = document.getElementById&&document.all ? 1:0\r\n");
      out.write("var NS6 = document.getElementById&&!document.all ? 1:0\r\n");
      out.write("\r\n");
      out.write("var x=0;\r\n");
      out.write("var y=0;\r\n");
      out.write("var closetable = \"</TD></TR></TABLE></TD></TR></TABLE>\";\t\r\n");
      out.write("if(!IE4) {\r\n");
      out.write("\tdocument.captureEvents(Event.MOUSEMOVE);\r\n");
      out.write("\tdocument.onmousemove = GetPos;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("function Desc(text ) {\r\n");
      out.write(" \tvar opentable = \"<TABLE BGCOLOR='#000000' BORDER=0 CELLPADDING=0 CELLSPACING=1 WIDTH=140><TR><TD ALIGN=center><TABLE BGCOLOR='#FFFFE1' BORDER=0 CELLPADDING=3 CELLSPACING=1 WIDTH=138><TR><TD VALIGN=top style='font-size:10px; font-family:Tahoma' align=left><IMG SRC='../img/help.gif' HEIGHT=24 WIDTH=30 VSPACE=0 HSPACE=0 ALIGN=left>\";\r\n");
      out.write("\t \r\n");
      out.write("\tif(NS6) {\r\n");
      out.write("\t\tdocument.getElementById(\"Description\").innerHTML  = opentable+text+closetable;\r\n");
      out.write("\t\tdocument.getElementById(\"Description\").style.left = x-12;\r\n");
      out.write("\t\tdocument.getElementById(\"Description\").style.top  = y+10;\r\n");
      out.write("\t\tdocument.getElementById(\"Description\").style.visibility = \"visible\";\r\n");
      out.write("\t}\r\n");
      out.write(" \tif(IE4) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.all[\"Description\"].innerHTML = opentable+text+closetable;\r\n");
      out.write("\t\tDescription.style.pixelLeft = event.clientX-12;\r\n");
      out.write("\t\tDescription.style.posTop  = document.body.scrollTop+event.clientY+16;\r\n");
      out.write("\t\tDescription.style.visibility = \"visible\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse {\r\n");
      out.write("\t\tvar nets = document.layers[\"Description\"];\r\n");
      out.write("\t\tnets.document.open();\r\n");
      out.write("\t\tnets.document.write(opentable+text+closetable);\r\n");
      out.write("\t\tdocument.Description.left = x-12;\r\n");
      out.write("\t\tdocument.Description.top = y+10;\r\n");
      out.write("\t\tnets.visibility = \"show\";\r\n");
      out.write("\t\tdocument.close();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function GetPos(evnt){\r\n");
      out.write("\tx = evnt.pageX;\r\n");
      out.write("\ty = evnt.pageY;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function noDesc() {\r\n");
      out.write("\r\n");
      out.write("\tif(NS6) {\r\n");
      out.write("\t\tdocument.getElementById(\"Description\").style.visibility = \"hidden\";\r\n");
      out.write("\t}\r\n");
      out.write("\tif(IE4) {\r\n");
      out.write("\t\tDescription.style.visibility = \"hidden\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse {\r\n");
      out.write("\t\tdocument.Description.visibility = \"hidden\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .contentText{\r\n");
      out.write("\tfont:\t\t\t12px Tahoma;\r\n");
      out.write("\tcolor:\t\t\tBlack;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\tclear:\t\t\tboth;\r\n");
      out.write("\tborder:\t\t\t1px solid rgb( 145, 155, 156 );\r\n");
      out.write("\tbackground:\t\trgb( 252, 252, 254 );\r\n");
      out.write("\tz-index:\t\t2;\r\n");
      out.write("\tposition:\t\trelative;\r\n");
      out.write("\ttop:\t\t\t-2px;\r\n");
      out.write("\r\n");
      out.write("\tfont:\t\t\t11px Tahoma;\r\n");
      out.write("\tcolor:\t\t\tBlack;\r\n");
      out.write("\r\n");
      out.write("\tfilter:\t\t\tprogid:DXImageTransform.Microsoft.Gradient(StartColorStr=#fffcfcfe, EndColorStr=#fff4f3ee, GradientType=0)\r\n");
      out.write("\t\t\t\t\tprogid:DXImageTransform.Microsoft.Shadow(Color=#ff919899, Strength=2, Direction=135);\r\n");
      out.write("\t\r\n");
      out.write("\t/* 244, 243, 238 */ \r\n");
      out.write("\t/*145, 155, 156 */\r\n");
      out.write("\tpadding:\t\t10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-row {\r\n");
      out.write("\tz-index:\t\t1;\r\n");
      out.write("\twhite-space:\tnowrap;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(".dynamic-tab-pane-control .tab-row .tab.selected {\r\n");
      out.write("\twidth:\t\t\t\t74px  ;\r\n");
      out.write("\theight:\t\t\t\t18px  ;\r\n");
      out.write("\tbackground-image:\turl( \"tab.active.png\" )  ;\r\n");
      out.write("\tbackground-repaet:\tno-repeat;\r\n");
      out.write("\r\n");
      out.write("\tborder-bottom-width:\t0;\r\n");
      out.write("\tz-index:\t\t3;\r\n");
      out.write("\tpadding:\t\t2px 0 0px 0;\r\n");
      out.write("\tmargin:\t\t\t1px -3px -3px 0px;\r\n");
      out.write("\ttop:\t\t\t-2px;\r\n");
      out.write("\tfont:\t\t\t11px Tahoma;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-row .tab a {\r\n");
      out.write("\tfont:\t\t\t\t11px Tahoma;\r\n");
      out.write("\tcolor:\t\t\t\tBlack;\r\n");
      out.write("\ttext-decoration:\tnone;\r\n");
      out.write("\tcursor:\t\t\t\tdefault;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-row .tab.hover {\r\n");
      out.write("\tfont:\t\t\t\t11px Tahoma;\r\n");
      out.write("\twidth:\t\t\t\t70px;\r\n");
      out.write("\theight:\t\t\t\t16px;\r\n");
      out.write("\tbackground-image:\turl( \"tab.hover.png\" );\r\n");
      out.write("\tbackground-repaet:\tno-repeat;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(".dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("html, body {\r\n");
      out.write("/*\tbackground:\tThreeDFace; */\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("\tmargin:\t\t0;\r\n");
      out.write("\tpadding:\t0;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("/* over ride styles from webfxlayout */\r\n");
      out.write(" \r\n");
      out.write("body {\r\n");
      out.write("\tmargin:\t\t10px;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("\theight:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control h2 {\r\n");
      out.write("\ttext-align:\tcenter;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control h2 a {\r\n");
      out.write("\tdisplay:\tinline;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control a:hover {\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(" .dynamic-tab-pane-control.tab-pane {\r\n");
      out.write("\tposition:\trelative;\r\n");
      out.write("\twidth:\t\t100%;\t\t \r\n");
      out.write("\tmargin-right:\t-2px;\t \r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write(" \r\n");
      out.write("<script type=\"text/javascript\" >\r\n");
      out.write("var tenant_dbid  = normalizeString(QueryString('tenant_dbid'));\r\n");
      out.write("\r\n");
      out.write("function sortSelect(o)\r\n");
      out.write("{\r\n");
      out.write("\t/*var o = new Array();\r\n");
      out.write("\tif (obj.options==null) { return; }\r\n");
      out.write("\tfor (var i=0; i<obj.options.length; i++) {\r\n");
      out.write("\t\to[o.length] = new Option( obj.options[i].text, obj.options[i].value, obj.options[i].defaultSelected, obj.options[i].selected) ;\r\n");
      out.write("\t\t}*/\r\n");
      out.write("\tif (o.length==0) { return; }\r\n");
      out.write("\r\n");
      out.write("\tif(viewckbox.checked == false){\r\n");
      out.write("\t\to = o.sort(\r\n");
      out.write("\t\t\tfunction(a,b) {\r\n");
      out.write("\t\t\t\tif ((a.text+\"\") < (b.text+\"\")) { return -1; }\r\n");
      out.write("\t\t\t\tif ((a.text+\"\") > (b.text+\"\")) { return 1; }\r\n");
      out.write("\t\t\t\treturn 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\to = o.sort(\r\n");
      out.write("\t\t\tfunction(a,b) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (parseInt(a.value) < parseInt(b.value)) { return -1; }\r\n");
      out.write("\t\t\t\t\tif (parseInt(a.value) > parseInt(b.value)) { return 1; }\r\n");
      out.write("\t\t\t\t\treturn 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t}\r\n");
      out.write("\t/*for (var i=0; i<o.length; i++) {\r\n");
      out.write("\t\tobj.options[i] = new Option(o[i].text, o[i].value, o[i].defaultSelected, o[i].selected);\r\n");
      out.write("\t\t}*/\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fillObjectCombo()\r\n");
      out.write("{\r\n");
      out.write("\tif(objects.options.length <= 1 ) {\r\n");
      out.write("\t\t/*Fill agents combo box with agents name*/\r\n");
      out.write("        var agents = String( appletObj.getAgentsByName(tenant_dbid) ),\r\n");
      out.write("\t\t\tjsAgents = agents + \"\",\r\n");
      out.write("\t\t\tarrayAgents = jsAgents.split(\"|\"), \r\n");
      out.write("\t\t\to = new Array();\r\n");
      out.write("       \r\n");
      out.write("\t   //Fill agents combobox\r\n");
      out.write("    \tif(agents.length > 0 ){\r\n");
      out.write("    \t\tfor (j = 0; j <arrayAgents.length; j++){\r\n");
      out.write("    \t\t\tvar iStartPos = arrayAgents[j].indexOf('['),\r\n");
      out.write("    \t\t\t \tiEndPos   = arrayAgents[j].indexOf(']'),\r\n");
      out.write("    \t\t\t \tlogin\t  = arrayAgents[j].substr(iStartPos+1,iEndPos-iStartPos-1),\r\n");
      out.write("\t\t\t\t \tname = login + '[' + arrayAgents[j].substr(0,iStartPos) + ']';\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\tmyOption = ( viewckbox.checked == false) ? new Option(arrayAgents[j],login) \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t : new Option(name,login);\t// show agents name as : firstname, lastname[login]\t\t\t\t\r\n");
      out.write("\t\t\t\to.push(myOption);\r\n");
      out.write("    \t\t}//end of for (j = 0; j <arrayAgents.length; j++)\r\n");
      out.write("\t\t}//end of if(agents.length > 0 ){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\to.sort(sortOptionsByText);//Sort by agents name\r\n");
      out.write("\t\tfor (var i=0, j=1; i<o.length; i++, j++) {\r\n");
      out.write("\t\t\tobjects.options[j] = new Option(o[i].text, o[i].value, o[i].defaultSelected, o[i].selected);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(agtGrp.options.length <= 1 ) {\t\r\n");
      out.write("        /*Fill agents group combo box with agent group name*/\r\n");
      out.write("        var agentGroups = String( appletObj.getAgentGroupDbidAndName(tenant_dbid)),\r\n");
      out.write("         \tjsAgentGroups = agentGroups + \"\";\r\n");
      out.write(" \t\t\to = new Array();\r\n");
      out.write("    \tarrayGroups = jsAgentGroups.split(\"|\");\r\n");
      out.write("    \tfor (j = 0; j <arrayGroups.length; j++){\r\n");
      out.write("\t\t\tvar jsgroupinfos = String(arrayGroups[j]).split(\",\");\t\t\t\r\n");
      out.write("    \t\to.push(new Option(jsgroupinfos[1], jsgroupinfos[0]));\t\t\t\r\n");
      out.write("    \t}\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\to.sort(sortOptionsByText);//Sort by groups name\r\n");
      out.write("\t\tfor (var i=0, j=1; i<o.length; i++, j++) {\r\n");
      out.write("\t\t\tagtGrp.options[j] = new Option(o[i].text, o[i].value, o[i].defaultSelected, o[i].selected);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t }\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("function changeAgentListView(){\r\n");
      out.write("\tvar agents;\r\n");
      out.write("\tvar name=\"\";\r\n");
      out.write("\tvar o = new Array();\r\n");
      out.write("\tobjects.length = 0;\r\n");
      out.write("    var defaultvalue =  \"- All Agents -\" ;\r\n");
      out.write("\tmyOption = new Option(defaultvalue,\"AllAgents\")\r\n");
      out.write("\t//optionPos = objects.options.length\r\n");
      out.write("\to[o.length]=myOption\r\n");
      out.write(" \r\n");
      out.write("\tif(agtGrp.value == 'AllGroups')\r\n");
      out.write("\t\tagents = String( appletObj.getAgentsByNameActif(tenant_dbid) );\r\n");
      out.write("\telse\r\n");
      out.write("\t\tagents = String( appletObj.getAvailableAgentListInGroupByStatus(agtGrp[agtGrp.selectedIndex].text,1) );\t\t\r\n");
      out.write("\r\n");
      out.write("    var jsAgents = agents + \"\";\r\n");
      out.write("    arrayAgents = jsAgents.split(\"|\");\r\n");
      out.write("    for (j = 0; j <arrayAgents.length; j++){\r\n");
      out.write("\t\t  var iStartPos = arrayAgents[j].indexOf('[');\r\n");
      out.write("\t\t  var iEndPos   = arrayAgents[j].indexOf(']');\r\n");
      out.write("\t\t  var login\t  = arrayAgents[j].substr(iStartPos+1,iEndPos-iStartPos-1);\r\n");
      out.write("\t\t  name = login+'['+arrayAgents[j].substr(0,iStartPos)+']'\r\n");
      out.write("\t\t  if ( viewckbox.checked == false)  // show agents name as : firstname, lastname[login]\r\n");
      out.write("\t\t\tmyOption = new Option(arrayAgents[j],login);  // show agents name as : login[firstname, lastname]\r\n");
      out.write("\t\t  else\r\n");
      out.write("\t\t\tmyOption = new Option(name,login);\r\n");
      out.write("\t\t  //optionPos = objects.options.length;\r\n");
      out.write("\t\t  o[o.length]=myOption\r\n");
      out.write("\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   sortSelect(o);\r\n");
      out.write("\r\n");
      out.write("\tfor (var i=0; i<o.length; i++) {\r\n");
      out.write("\t\tobjects.options[i] = new Option(o[i].text, o[i].value, o[i].defaultSelected, o[i].selected);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getAgentsInGroup()\r\n");
      out.write("{\r\n");
      out.write("\tvar o = new Array();\r\n");
      out.write("\tif(agtGrp.value =='AllGroups')\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//Empty the agent group combo box\r\n");
      out.write("\t\tagtGrp.options.length=1;\r\n");
      out.write("\t\tobjects.length = 0;\r\n");
      out.write("        var defaultvalue =  \"- All Agents -\" ;\r\n");
      out.write("\t\tmyOption = new Option(defaultvalue,\"AllAgents\")\r\n");
      out.write("\t\toptionPos = objects.options.length\r\n");
      out.write("\t\tobjects.options[optionPos]=myOption\r\n");
      out.write("\r\n");
      out.write("\t\tfillObjectCombo();\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar agents = String( appletObj.getAvailableAgentListInGroupByStatus(agtGrp[agtGrp.selectedIndex].text,1) );\r\n");
      out.write("\t\tvar jsAgents = agents + \"\";\r\n");
      out.write("\t\t// Remove all agents from agents option field\r\n");
      out.write("\t\tvar i=objects.options.length;\r\n");
      out.write("        if (i>0){\r\n");
      out.write("              objects.length = 0;\r\n");
      out.write("        }\r\n");
      out.write("        var defaultvalue =  \"-All agents-\" ;\r\n");
      out.write("\t\tmyOption = new Option(defaultvalue,\"AllAgents\")\r\n");
      out.write("\t\t//optionPos = objects.options.length\r\n");
      out.write("\t\t//objects.options[optionPos]=myOption\r\n");
      out.write("\t\to[o.length]= myOption;\r\n");
      out.write("\r\n");
      out.write("\t\tif(agents.length > 0 ){\r\n");
      out.write("\t\t\tarrayAgents = jsAgents.split(\"|\");\r\n");
      out.write("    \t\tfor (j = 0; j <arrayAgents.length; j++){\r\n");
      out.write("    \t\t\tvar iStartPos = arrayAgents[j].indexOf('[');\r\n");
      out.write("    \t\t\tvar iEndPos   = arrayAgents[j].indexOf(']');\r\n");
      out.write("    \t\t\tvar login\t  = arrayAgents[j].substr(iStartPos+1,iEndPos-iStartPos-1);\r\n");
      out.write("    \t\t\t//myOption = new Option(arrayAgents [j],login)\r\n");
      out.write("\t\t\t\tvar name = login+'['+arrayAgents[j].substr(0,iStartPos)+']';\r\n");
      out.write("\t\t\t\tif ( viewckbox.checked == false)\t  \t\t// show agents name as : firstname, lastname[login]\r\n");
      out.write("      \t\t\t\tmyOption = new Option(arrayAgents[j],login)\r\n");
      out.write("\t\t\t\telse\t\t\t\t\t\t\t\t\t// show agents name as : login[firstname, lastname]\r\n");
      out.write("\t\t\t\t\tmyOption = new Option(name,login)\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t//optionPos = objects.options.length\r\n");
      out.write("\t\t\t\t//objects.options[optionPos]=myOption\r\n");
      out.write("\t\t\t\to[o.length]= myOption;\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tsortSelect(o);\r\n");
      out.write("\r\n");
      out.write("\tfor (var i=0; i<o.length; i++) {\r\n");
      out.write("\t\tobjects.options[i] = new Option(o[i].text, o[i].value, o[i].defaultSelected, o[i].selected);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\treturn;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getSelectedObjects()\r\n");
      out.write("{\r\n");
      out.write("\tselectedAgents = new Array()\r\n");
      out.write("\tfor (i=objects.selectedIndex;i<objects.options.length;i++) {\r\n");
      out.write("  \t\tif (objects.options[i].selected) {\r\n");
      out.write("  \t\t\tselectedAgents[selectedAgents.length]=objects.options[i].value;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t}\r\n");
      out.write("\tvar url = '';\r\n");
      out.write("\tif (selectedAgents.length > 0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\turl= escape(selectedAgents.join('/'))\r\n");
      out.write("\t}\r\n");
      out.write("\treturn url;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function checkSelectedPeriod()\r\n");
      out.write("{ \r\n");
      out.write("\tvar startdate = document.theForm.startingDate.value;\r\n");
      out.write("\tvar enddate = document.theForm.endingDate.value;\r\n");
      out.write("\tvar numdays = checkSelectedPeriod.arguments[0]; \r\n");
      out.write("\t\t\r\n");
      out.write("\tif (startdate.length <1) {\r\n");
      out.write("\t\talert('");
      out.print( pageData.getWord("You must set up the start date"));
      out.write("');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif (enddate.length <1) {\r\n");
      out.write("\t\talert('");
      out.print( pageData.getWord("You must set up the end date"));
      out.write("');\r\n");
      out.write("\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar month = parseInt(startdate.substring(0,2)-1,10);\r\n");
      out.write("\tvar date  = parseInt(startdate.substring(3,5),10);\r\n");
      out.write("\tvar year  = parseInt(startdate.substring(6),10);\r\n");
      out.write("\tvar stDate=new Date();\r\n");
      out.write("\tstDate.setFullYear(year,month,date)\t;\r\n");
      out.write("\t\r\n");
      out.write("\tmonth = parseInt(enddate.substring(0,2)-1,10);\r\n");
      out.write("\tdate  = parseInt(enddate.substring(3,5),10);\r\n");
      out.write("\tyear  = parseInt(enddate.substring(6),10);\r\n");
      out.write("\teDate=new Date();\r\n");
      out.write("\teDate.setFullYear(year,month,date);\r\n");
      out.write("\r\n");
      out.write("\tif (stDate>eDate){\r\n");
      out.write("\t\talert('");
      out.print( pageData.getWord("The end date cannot be smaller than the start date"));
      out.write("');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t \r\n");
      out.write("\tif (eDate.getTime()-stDate.getTime()>numdays*86400*1000) { //86400 secondes per day\r\n");
      out.write("\t\talert('");
      out.print( pageData.getWord("You cannot select a period more than 7 days"));
      out.write("');\t\t\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function EnableSelect(){\r\n");
      out.write("\r\n");
      out.write("if (call_length.checked){\r\n");
      out.write("\t  min.disabled = false;\r\n");
      out.write("\t  max.disabled = false;\r\n");
      out.write("\t  }\r\n");
      out.write("else{\t  \r\n");
      out.write("\tmin.disabled = true;\r\n");
      out.write("\tmax.disabled = true;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getRequestedReport()\r\n");
      out.write("{\r\n");
      out.write("   //var cur_user = String(appletObj.getCurrentUserDBID());\r\n");
      out.write("\tvar phone =  phoneNumber.value;\r\n");
      out.write(" \t//var dnis =  dnid.value;\r\n");
      out.write("\tvar destination = '';\r\n");
      out.write("\r\n");
      out.write("\tif(phone.length == 0){\r\n");
      out.write("\t\tif(dateChecker() == false)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif(checkSelectedPeriod(7) == false)\r\n");
      out.write("\t\t{\t\t\t\t\t\r\n");
      out.write("\t\t\treturn;\t\t\t\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tvar get_listened = '0';\r\n");
      out.write("\tvar get_not_listened = '0';\r\n");
      out.write("\tvar get_sales = '0';\r\n");
      out.write("\tvar get_no_sales ='0';\r\n");
      out.write("\tvar get_qm ='0';\r\n");
      out.write("\tvar get_audio ='0';\r\n");
      out.write("\tvar get_video ='0';\r\n");
      out.write("\tvar get_call_length ='0';\r\n");
      out.write("\tvar selectedGroups = agtGrp.value;\r\n");
      out.write("\t\r\n");
      out.write("\t/*if(validation(document.theForm.phoneNumber.value)==0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"You cannot use ~ or ^ or | !!!\");\r\n");
      out.write("\t\tdocument.theForm.phoneNumber.focus();\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}*/\r\n");
      out.write("\r\n");
      out.write("\tdestination = \"../jsp/conversationRecording.jsp\"\r\n");
      out.write("\tdestination += \"?startingDate=\"\r\n");
      out.write("\tdestination += document.theForm.startingDate.value;\r\n");
      out.write("\tdestination +=\"&endingDate=\";\r\n");
      out.write("\tdestination += document.theForm.endingDate.value;\r\n");
      out.write("\tdestination +=\"&phoneNumber=\";\r\n");
      out.write("\tdestination += escape(phoneNumber.value);\r\n");
      out.write("\t//alert(escape(phoneNumber.value));\r\n");
      out.write("\tdestination +=\"&page=\";\r\n");
      out.write("\tdestination += \"1\";\r\n");
      out.write("\tdestination +=\"&limit=\";\r\n");
      out.write("\tdestination += limit.value;\r\n");
      out.write("\t\r\n");
      out.write("\tdestination +=\"&min=\";\r\n");
      out.write("\tdestination += min.value;\r\n");
      out.write("\tdestination +=\"&max=\";\r\n");
      out.write("\tdestination += max.value;\r\n");
      out.write("\t\r\n");
      out.write("\tif((min.value > max.value) && call_length.checked){\r\n");
      out.write("\t\talert(\"");
      out.print(pageData.getWord("Your Max time cannot be smaller than your Min time"));
      out.write("\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tdestination +=\"&numpages=\";\r\n");
      out.write("\tdestination +=\"&firstload=true\";\t\r\n");
      out.write("\tdestination +=\"&agentGrp=\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tif(agtGrp.value == 'AllGroups' && objects.value =='AllAgents' && phone.length == 0)\r\n");
      out.write("\t{\t \r\n");
      out.write("\t\t alert(\"");
      out.print(pageData.getWord("Please select a group or an agent"));
      out.write("\");\r\n");
      out.write("\t\t return false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(agtGrp.value == 'AllGroups'){\r\n");
      out.write("\t\tselectedGroups = selectedGroups + '/';\r\n");
      out.write("\t\tvar i;\r\n");
      out.write("\t\tfor(i=1; i<agtGrp.options.length; i++){\r\n");
      out.write("\t\t\t selectedGroups = selectedGroups + agtGrp.options[i].value + '!';\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\tif(agtGrp.options.length > 1)\r\n");
      out.write("\t\t\t selectedGroups = selectedGroups.substring(0,selectedGroups.length-1);\t\t\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\tdestination += selectedGroups;\r\n");
      out.write("\tdestination +=\"&agents=\";\r\n");
      out.write("\tdestination += getSelectedObjects();\r\n");
      out.write("\t\r\n");
      out.write("\tif( call_length.checked)\r\n");
      out.write("\t\tget_call_length ='1';\r\n");
      out.write("\t\t\r\n");
      out.write("\tdestination +=\"&call_length=\";\r\n");
      out.write("\tdestination +=get_call_length;\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write(" \tif( sales.checked)\r\n");
      out.write("\t\tget_sales ='1';\r\n");
      out.write("\tif( no_sales.checked)\r\n");
      out.write("\t\tget_no_sales='1';\r\n");
      out.write(" \tdestination +=\"&option_not_listened=\";\r\n");
      out.write("\tdestination += get_not_listened;\r\n");
      out.write("\tdestination +=\"&option_listened=\";\r\n");
      out.write("\tdestination += get_listened;\r\n");
      out.write("\tdestination +=\"&sales=\";\r\n");
      out.write("\tdestination +=get_sales;\r\n");
      out.write("\tdestination +=\"&no_sales=\";\r\n");
      out.write("\tdestination += get_no_sales;\r\n");
      out.write("\tdestination +=\"&qm=\";\r\n");
      out.write("\tdestination += get_qm;\r\n");
      out.write("\t\r\n");
      out.write("\tif( document.theForm.Audio.checked)\r\n");
      out.write("\t\tget_audio ='1';\r\n");
      out.write("\tif( document.theForm.Video.checked)\r\n");
      out.write("\t\tget_video='1';\r\n");
      out.write("\tdestination +=\"&audio=\";\r\n");
      out.write("\tdestination += get_audio;\r\n");
      out.write("\tdestination +=\"&video=\";\r\n");
      out.write("\tdestination += get_video;\r\n");
      out.write("\tdestination +=\"&tenant=\";\r\n");
      out.write("\tdestination +=tenant_dbid;\r\n");
      out.write("\t//alert(destination);\r\n");
      out.write("\t//alert(window.top.main.rbottom.bottom.location.href)\r\n");
      out.write("\t//window.top.main.rbottom.bottom.location.href = destination;\r\n");
      out.write("\t//alert(window.top.bottom.location.href)\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.location = destination;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function dateChecker()\r\n");
      out.write("{\r\n");
      out.write("\tvar startDate=new Date(document.theForm.startingDate.value);\r\n");
      out.write("\tvar endDate = new Date(document.theForm.endingDate.value);\r\n");
      out.write("\r\n");
      out.write("\tif(endDate < startDate)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert('");
      out.print( pageData.getWord("Your ending date cannnot be smaller than your starting date"));
      out.write("');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function toggleLayer(whichLayer)\r\n");
      out.write("{\r\n");
      out.write("\tif (document.getElementById)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t// this is the way the standards work\r\n");
      out.write("\t\tvar style2 = document.getElementById(whichLayer).style;\r\n");
      out.write("\t\tstyle2.display = style2.display? \"\":\"none\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse if (document.all)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t// this is the way old msie versions work\r\n");
      out.write("\t\tvar style2 = document.all[whichLayer].style;\r\n");
      out.write("\t\tstyle2.display = style2.display? \"\":\"none\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse if (document.layers)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t// this is the way nn4 works\r\n");
      out.write("\t\tvar style2 = document.layers[whichLayer].style;\r\n");
      out.write("\t\tstyle2.display = style2.display? \"\":\"none\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write("function validateRecordingsType()\r\n");
      out.write("{\r\n");
      out.write("\t//option du audio recordings\r\n");
      out.write("\tif(document.theForm.Audio.checked && document.theForm.Video.checked)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.theForm.AudioAndVideo.checked = true;\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.theForm.AudioAndVideo.checked = false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("/*function validateRecordingsTypeBoth()\r\n");
      out.write("{\r\n");
      out.write("\t//option du audio recordings\r\n");
      out.write("\tif(document.theForm.AudioAndVideo.checked )\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.theForm.Audio.checked = true;\r\n");
      out.write("\t\tdocument.theForm.Video.checked = true;\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.theForm.Audio.checked = false;\r\n");
      out.write("\t\tdocument.theForm.Video.checked = false;\r\n");
      out.write("\t}\r\n");
      out.write("}*/\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"q_m_body\">\r\n");
      out.write("<br />\r\n");
      out.write("<DIV ID=\"Description\" STYLE=\"position:absolute; top:5px; left:5px; visibility:hide; z-index:1; background-color:#FFFFCC;\"></DIV>\r\n");
      out.write("\r\n");
      out.write("<div class=\"dynamic-tab-pane-control\">\r\n");
      out.write("\t<div class=\"tab-pane\" id=\"tabPane1\"> \r\n");
      out.write("\t\t\r\n");
      out.write("    <div class=\"tab-page\" id=\"general\"> \r\n");
      out.write("      <fieldset>\r\n");
      out.write("      \t<legend> \r\n");
      out.write("      \t\t");
      out.print( pageData.getWord("Recordings selection") );
      out.write("\r\n");
      out.write("      \t</legend>\r\n");
      out.write("      \t<form name=\"theForm\" >\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"6\">&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"6\"><strong>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Recordings type") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Audio") );
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"50\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"Audio\" type=\"checkbox\" name=\"Audio\" value=\"ON\"  onclick=\"validateRecordingsType()\" checked>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Video") );
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"50\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"Video\" type=\"checkbox\" name=\"Video\" value=\"ON\"  onclick=\"validateRecordingsType()\" checked>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<!-- <td>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Both") );
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"50\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"AudioAndVideo\" type=\"checkbox\" name=\"AudioAndVideo\" value=\"ON\"  onclick=\"validateRecordingsTypeBoth()\" checked>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t -->\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\">&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\"><strong>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Call time (Max. 7 days)") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("From") );
      out.write(":&nbsp;\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"id_startingDate\" type=\"text\" size=\"18\" onfocus=\"showCalendar('',this,this,'','id_startingDate',0,30,1);this.blur()\" name=\"startingDate\" class=\"contentText\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;&nbsp;");
      out.print( pageData.getWord("To") );
      out.write(":&nbsp;\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"id_endingDate\" type=\"text\" size=\"20\" onfocus=\"showCalendar('',this,this,'','id_endingDate',0,30,1);this.blur()\" name=\"endingDate\" class=\"contentText\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"4\">&nbsp;\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\">&nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t");
      out.print( pageData.getWord("Agent group") );
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t  \t\t<td colspan=\"2\"> \r\n");
      out.write("\t\t\t\t\t<select name=\"agtGrp\" onChange=\"getAgentsInGroup()\" class=\"contentText\">\r\n");
      out.write("\t\t\t  \t\t\t<option value=\"AllGroups\">- \r\n");
      out.write("\t\t\t  \t\t\t\t");
      out.print( pageData.getWord("Select a group") );
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t-</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t");
      out.print( pageData.getWord("Agents") );
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<select name=\"objects\" class=\"contentText\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"AllAgents\">-\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( pageData.getWord("All agents") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t-</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;");
      out.print( pageData.getWord("Show agent by ID") );
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"viewckbox\" onClick=\"changeAgentListView()\" ID=\"Checkbox2\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr> \r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t");
      out.print( pageData.getWord("Phone number") );
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t  \t\t<input type=\"text\" name=\"phoneNumber\" class=\"contentText\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td> \r\n");
      out.write("\t\t\t  \t\t<a style=\"color:#400040 \"  onMouseover=\"Desc('Would you like to list all the records which dnid contains the string 5678, write  %5678% in the box as search criteria' );\" onMouseout=\"noDesc();\" > \r\n");
      out.write("\t\t\t  \t\t<script>//document.write(MultiArray[\"You may use (%Phonenumber%)\"][lang])</script>\r\n");
      out.write("\t\t\t  \t\t</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t");
      out.print( pageData.getWord("Records/page") );
      out.write(" \r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t  \t\t<td colspan=\"2\"> \r\n");
      out.write("\t\t\t\t\t<select name=\"limit\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"20\">20</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"50\">50</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"100\">100</option>\r\n");
      out.write("\t\t\t \t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t");
      out.print( pageData.getWord("Call length") );
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t  \t\t<td > \r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"call_length\" value=\"0\" Onclick =\"EnableSelect()\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t");
      out.print( pageData.getWord("Min") );
      out.write("&nbsp;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<select name=\"min\" disabled>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">0s</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"15\">15s</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"30\">30s</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"45\">45s</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"60\">60s</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"90\">1:30</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"120\">2:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"150\">2:30</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"180\">3:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"240\">4:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"300\">5:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"360\">6:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"420\">7:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"480\">8:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"540\">9:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"600\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"900\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1200\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1500\">25:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1800\">30:00</option>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t \t\t</select>\r\n");
      out.write("\t\t\t\t </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td > \r\n");
      out.write("\t\t\t");
      out.print( pageData.getWord("Max") );
      out.write("\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t\t<select name=\"max\" disabled>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"15\">15s</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"30\">30s</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"45\">45s</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"60\">60s</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"90\">1:30</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"120\">2:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"150\">2:30</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"180\">3:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"240\">4:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"300\">5:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"360\">6:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"420\">7:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"480\">8:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"540\">9:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"600\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"900\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1200\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1500\">25:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1800\">30:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3600\">1h</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"7200\">2h</option>\r\n");
      out.write("\t\t\t \t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t");
      out.print( pageData.getWord("Sales"));
      out.write(" \r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t  \t\t<td colspan=\"2\"> \r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"sales\" value=\"0\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t");
      out.print( pageData.getWord("No sales"));
      out.write("  \r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t  \t\t<td colspan=\"2\"> \r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"no_sales\" value=\"0\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\">&nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\"> \r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value='");
      out.print( pageData.getWord("Submit"));
      out.write(" ' onClick=\"getRequestedReport()\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("      </fieldset>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("  \r\n");
      out.write("<script type=\"text/javascript\">  \r\n");
      out.write("fillObjectCombo(); \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
 pageData.closeConnection(); 
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
