package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import aheevaManager.ressources.*;

public final class filter1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
    pageData.openConnection();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<LINK href=\"livestats.css\" \trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"tab_luna.css\" />\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style_2.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\" href=\"slider/css/luna.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t100px;\r\n");
      out.write("}\r\n");
      out.write("html, body {\r\n");
      out.write("\t/*background:\tThreeDFace;*/\r\n");
      out.write("}\r\n");
      out.write("form {\r\n");
      out.write("\tmargin:\t\t0;\r\n");
      out.write("\tpadding:\t0;\r\n");
      out.write("}\r\n");
      out.write("/* over ride styles from webfxlayout */\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:\t\t10px;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("\theight:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 {\r\n");
      out.write("\ttext-align:\tcenter;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 a {\r\n");
      out.write("\tdisplay:\tinline;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control a:hover {\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\" src=\"jsUtil.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"tabpane.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("var filterName          = '';\r\n");
      out.write("var filterDBID \t\t= '';\r\n");
      out.write("var tenant_dbid \t= \"NULL\"\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function enabledUpdateButton()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.filter.updateInfo.disabled = false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function enableReload()\r\n");
      out.write("{\r\n");
      out.write("      appletObj.fReloadMenu = true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function displayFilterInfo()\r\n");
      out.write("{\r\n");
      out.write("    ourCaption   \t= document.getElementById(\"caption\");\r\n");
      out.write("\tfilterName   \t= normalizeString(QueryString('filter_name'));\r\n");
      out.write("\ttenant_dbid \t= normalizeString(QueryString('tenant_dbid'));\r\n");
      out.write("\tvar myForm   \t= document.filter;\r\n");
      out.write("        //alert('filterName:');\r\n");
      out.write("\r\n");
      out.write("\tif (filterName== '')\r\n");
      out.write("\t{\r\n");
      out.write("\t\tourCaption.innerHTML = \"");
      out.print( pageData.getWord("Add a new filter"));
      out.write("\";\r\n");
      out.write("\t\t//document.getElementById(\"deleteAgt\").disabled=true;\r\n");
      out.write("\t\tdocument.filter.updateInfo.value = \"");
      out.print( pageData.getWord("Save"));
      out.write("\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("                //alert('In else:');\r\n");
      out.write("\t\tourCaption.innerHTML = \"");
      out.print( pageData.getWord("Modify existing filter information"));
      out.write("\";\r\n");
      out.write("   \t\tdocument.filter.filterName.value = filterName;\r\n");
      out.write("                var filterDetails =  String( appletObj.getFilterInfo(filterName) );\r\n");
      out.write("\r\n");
      out.write("        // parse info received\r\n");
      out.write("        var jsDetails = filterDetails + \"\";\r\n");
      out.write("        arrayDetails = jsDetails.split(\"|\");\r\n");
      out.write("        //alert(arayDetails);\r\n");
      out.write("\r\n");
      out.write("\t   \tfor (i = 0; i <arrayDetails.length; i++)\r\n");
      out.write("\t   \t{\r\n");
      out.write("\t\t\tif(i == 0){\r\n");
      out.write("\t\t\t\tfilterDBID = arrayDetails[i];\r\n");
      out.write("\t\t\t}else if(i == 1){ // description\r\n");
      out.write("\t\t\t\tdocument.filter.filterDescription.value\t\t= arrayDetails[i];\r\n");
      out.write("\t\t\t}else if(i == 2) { // where\r\n");
      out.write("\t\t\t\tdocument.filter.filterWhereClause.value \t= arrayDetails[i];\r\n");
      out.write("\t\t\t}else if(i == 3) { // order by clause\r\n");
      out.write("\t\t\t\tdocument.filter.filterOrderByClause.value\t= arrayDetails[i];\r\n");
      out.write("\t\t\t}else if (i == 4) { // state\r\n");
      out.write("\t\t\t\tif(arrayDetails[i] == '1')\r\n");
      out.write("\t\t\t\t\tdocument.filter.filterState.checked = true;\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t\tdocument.filter.filterState.checked = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t  \t}\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validateInfo()\r\n");
      out.write("{\r\n");
      out.write("\tvar state = '';\r\n");
      out.write("    // Verify that the filter name is set\r\n");
      out.write("    if (document.filter.filterName.value =='')\r\n");
      out.write("    \talert (\"");
      out.print( pageData.getWord("You must enter a FILTER NAME"));
      out.write("\");\r\n");
      out.write("    else if(document.filter.filterWhereClause.value.length==0 && document.filter.filterOrderByClause.value.length==0)\r\n");
      out.write("        alert (\"");
      out.print( pageData.getWord("You must enter a criteria or order by clause"));
      out.write("\");\r\n");
      out.write("\telse if(validation(document.filter.filterName.value)==0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert (\"");
      out.print( pageData.getWord("Invalid use of character"));
      out.write("\");\r\n");
      out.write("\t\tdocument.filter.filterName.focus();\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(validation(document.filter.filterDescription.value)==0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert (\"");
      out.print( pageData.getWord("Invalid use of character"));
      out.write("\");\r\n");
      out.write("\t\tdocument.filter.filterDescription.focus();\t\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(validation(document.filter.filterWhereClause.value)==0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert (\"");
      out.print( pageData.getWord("Invalid use of character"));
      out.write("\");\r\n");
      out.write("\t\tdocument.filter.filterWhereClause.focus();\t\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(validation(document.filter.filterOrderByClause.value)==0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert (\"");
      out.print( pageData.getWord("Invalid use of character"));
      out.write("\");\r\n");
      out.write("\t\tdocument.filter.filterOrderByClause.focus();\t\r\n");
      out.write("\t}\r\n");
      out.write("    else {\r\n");
      out.write("    \t// save filter details\r\n");
      out.write("\t    if(document.filter.filterState.checked)\r\n");
      out.write("\t\t\tstate = 1;\r\n");
      out.write("        else\r\n");
      out.write("\t\t\tstate = 0;\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar alReadyExist = false;\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t   var filters = appletObj.getFiltersByName(tenant_dbid);\r\n");
      out.write("\t   jsfilters = filters.split(\"|\");\r\n");
      out.write("\t   \r\n");
      out.write("\t   for(q = 0; q < jsfilters.length; q++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\tif( document.filter.filterName.value == jsfilters[q] && filterName != document.filter.filterName.value) //le groupe existe deja\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\talReadyExist = true;\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tif(alReadyExist)\r\n");
      out.write("\t\t\talert ('");
      out.print( pageData.getWord("Filter already exists"));
      out.write("');\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\tappletObj.saveFilter(filterDBID,\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttenant_dbid,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdocument.filter.filterName.value,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdocument.filter.filterDescription.value,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdocument.filter.filterWhereClause.value,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdocument.filter.filterOrderByClause.value,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstate);\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t// reset the button to disabled\r\n");
      out.write("\t\t\tdocument.filter.updateInfo.disabled=true;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//document.location.href = \"../defaultpage.htm\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function askDelete()\r\n");
      out.write("{\r\n");
      out.write("\tanswer = confirm(\"");
      out.print( pageData.getWord("Are you sure, you wish to delete this filter?"));
      out.write("\");\r\n");
      out.write("\tif(answer){\r\n");
      out.write("\t\tappletObj.deleteFilter(filterDBID);\r\n");
      out.write("\t\t// refresh the current page\r\n");
      out.write("\t\t//document.location = \"./filter.htm?filter_name=&tenant_dbid=\"+tenant_dbid;\r\n");
      out.write("        document.location.href = \"../defaultpage.htm\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checkOnUnload()\r\n");
      out.write("{\r\n");
      out.write("  //alert('checkOnUnload:');\r\n");
      out.write("\r\n");
      out.write(" return\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<title>");
      out.print( pageData.getWord("Add a filter"));
      out.write("</title>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("    // Associate a default button with pressing the Enter key\r\n");
      out.write("\tfunction KeyDownHandler(btn)\r\n");
      out.write("    {\r\n");
      out.write("        // process only the Enter key\r\n");
      out.write("        if (event.keyCode == 13)\r\n");
      out.write("        {\r\n");
      out.write("            // cancel the default submit\r\n");
      out.write("            event.returnValue=false;\r\n");
      out.write("            event.cancel = true;\r\n");
      out.write("            // submit the form by programmatically clicking the specified button\r\n");
      out.write("            btn.click();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"fil_body\" onLoad=\"displayFilterInfo()\" onUnload=\" return checkOnUnload()\">\r\n");
      out.write("<!--        <control:slider ID=\"oSlider\" STYLE= \"position:relative;backgroundColor:#C0C0C0\" >\r\n");
      out.write("\t\t\t</control:slider>\r\n");
      out.write(" -->\r\n");
      out.write("<div class=\"tab-pane\" id=\"tabPane1\">\r\n");
      out.write("\t<form name=\"filter\" onKeyDown=\"KeyDownHandler(save)\">\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\ttp1 = new WebFXTabPane( document.getElementById( \"tabPane1\" ) );\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<div class=\"tab-page\" id=\"tabGeneral\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend id=\"caption\"></legend>\r\n");
      out.write("\t\t\t\t<table  cellpadding=\"0\" cellspacing=\"0\" id=\"AutoNumber2\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t<table  cellspacing=\"0\" id=\"AutoNumber1\"  cellpadding=\"0\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"left\" valign=\"top\" style=\"padding-bottom:12px; padding-top:30px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span style=\"padding-left:5px; padding-right:5px; width:95px;\">");
      out.print(pageData.getWord("Filter name"));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"filterName\" size=\"25\" onClick=\"enabledUpdateButton()\" style=\"font-weight: bold\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"left\" valign=\"top\" style=\"padding-bottom:12px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span style=\"padding-left:5px; padding-right:5px; width:95px;\">");
      out.print(pageData.getWord("Description"));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea rows=\"2\" name=\"filterDescription\" cols=\"52\" onClick=\"enabledUpdateButton()\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"left\" valign=\"top\" style=\"padding-bottom:12px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span style=\"padding-left:5px; padding-right:5px; width:95px;\">");
      out.print(pageData.getWord("Criteria"));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea rows=\"3\" name=\"filterWhereClause\" cols=\"52\" onClick=\"enabledUpdateButton()\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"left\" valign=\"top\" style=\"padding-bottom:16px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span style=\"padding-left:5px; padding-right:5px; width:95px;\">");
      out.print(pageData.getWord("Order by"));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea rows=\"3\" name=\"filterOrderByClause\" cols=\"52\" onClick=\"enabledUpdateButton()\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"left\" valign=\"top\" style=\"padding-bottom:5px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input disabled=\"true\" id=\"save\" name=\"updateInfo\" type=\"button\" value='");
      out.print( pageData.getWord("Update"));
      out.write("' onClick=\"validateInfo()\" style=\"margin-left:100px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<script language=\"JavaScript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar filterName = normalizeString(QueryString('filter_name'));\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tif (filterName== '')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('&nbsp;') \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdocument.write(\"<input id=\\\"deleteAgt\\\" name=\\\"deleteAgt\\\" onclick=\\\"askDelete()\\\"  value=\\\"");
      out.print( pageData.getWord("Delete"));
      out.write("\\\"  type=\\\"button\\\">\");         \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span style=\"padding-left:100px; padding-right:5px;\">");
      out.print( pageData.getWord("Active"));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"filterState\" value=\"ON\" onClick=\"enableReload();enabledUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
 pageData.closeConnection(); 
      out.write("\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
