package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.*;
import aheevaManager.ressources.*;
import java.text.*;
import aheevaManager.schedule.*;
import aheevaManager.ressources.*;
import java.util.*;
import jxl.*;

public final class generalConfigDemo1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/aheevaManager/Resources_pages/generalConfigDemoFunctions_labels.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageGenCData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageGenCData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
pageGenCData.openConnection();
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("var configDemo= new Array();\r\n");
      out.write("configDemo[0]=\"");
      out.print(pageGenCData.getWord("Login time") );
      out.write("\";\r\n");
      out.write("configDemo[1]=\"");
      out.print(pageGenCData.getWord("Tolerance") );
      out.write("\";\r\n");
      out.write("configDemo[2]=\"");
      out.print(pageGenCData.getWord("This duration is numeric, please change") );
      out.write("\";\r\n");
      out.write("configDemo[3]=\"");
      out.print(pageGenCData.getWord("Invalid use of character") );
      out.write("\";\r\n");
      out.write("configDemo[4]=\"");
      out.print(pageGenCData.getWord("Please fill all duration fields") );
      out.write("\";\r\n");
      out.write("configDemo[5]=\"");
      out.print(pageGenCData.getWord("Duration") );
      out.write("\";\r\n");
      out.write("configDemo[6]=\"");
      out.print(pageGenCData.getWord("Delete") );
      out.write("\";\r\n");
      out.write("configDemo[7]=\"");
      out.print(pageGenCData.getWord("This tolerance is numeric, please change") );
      out.write("\";\r\n");
      out.write("configDemo[8]=\"");
      out.print(pageGenCData.getWord("Please fill all tolerance fields") );
      out.write("\";\r\n");
      out.write("configDemo[9]=\"");
      out.print(pageGenCData.getWord("Agent group") );
      out.write("\";\r\n");
      out.write("configDemo[10]=\"");
      out.print(pageGenCData.getWord("Paid time formula") );
      out.write("\";\r\n");
      out.write("configDemo[11]=\"");
      out.print(pageGenCData.getWord("Billable time formula") );
      out.write("\";\r\n");
      out.write("configDemo[12]=\"");
      out.print(pageGenCData.getWord("Not-ready reasons") );
      out.write("\";\r\n");
      out.write("configDemo[13]=\"");
      out.print(pageGenCData.getWord("Paid time") );
      out.write("\";\r\n");
      out.write("configDemo[14]=\"");
      out.print(pageGenCData.getWord("Billable time") );
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 pageGenCData.closeConnection(); 
      out.write('\r');
      out.write('\n');

////open connection to database///////
beanManagerData pageData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
    pageData.openConnection();

      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"tab_luna.css\" />\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style_2.css\" />\r\n");
      out.write("<LINK href=\"livestats.css\" \trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" >\r\n");
      out.write("<meta http-equiv=\"Content-Language\" content=\"en-us\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t100px;\r\n");
      out.write("}\r\n");
      out.write("html, body {\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("form {\r\n");
      out.write("\tmargin:\t\t0;\r\n");
      out.write("\tpadding:\t0;\r\n");
      out.write("}\r\n");
      out.write("/* over ride styles from webfxlayout */\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:\t\t10px;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("\theight:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 {\r\n");
      out.write("\ttext-align:\tcenter;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 a {\r\n");
      out.write("\tdisplay:\tinline;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control a:hover {\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jsUtil.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"tabpane.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"generalConfigDemoFunctions.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("var agentGrpDBID       \t= '';\r\n");
      out.write("var groupName          \t= '';\r\n");
      out.write("var lastName           \t= '';\r\n");
      out.write("var firstName          \t= '';\r\n");
      out.write("//var recordingRight      = '';\r\n");
      out.write("\r\n");
      out.write("var nrows = 1 ;\r\n");
      out.write("var maxrow = 1;\r\n");
      out.write("/*\r\n");
      out.write("var mopID = \"\";\r\n");
      out.write("\r\n");
      out.write("// Statistiques\r\n");
      out.write("\r\n");
      out.write("var sTring = String( appletObj.getAgentGroupsStats( normalizeString(QueryString('grpName')) ) );\r\n");
      out.write("sTringArray = sTring.split(\",\");\r\n");
      out.write("\r\n");
      out.write("var grp_Name \t\t= sTringArray[0];\r\n");
      out.write("var grpCallHandled \t= sTringArray[1];\r\n");
      out.write("var grpCallInbound \t= sTringArray[2];\r\n");
      out.write("var grpCallOutbound = sTringArray[3];\r\n");
      out.write("var grpLoginAgents \t= sTringArray[4];\r\n");
      out.write("var grpTotalNotReady= sTringArray[5];\r\n");
      out.write("var grpTotalReady \t= sTringArray[6];\r\n");
      out.write("var grpTotalWaiting = sTringArray[7];\r\n");
      out.write("var grpTotalWrapUp \t= sTringArray[8];\r\n");
      out.write("var grpTotalDialing = sTringArray[9];\r\n");
      out.write("var grpTotalHold\t= sTringArray[10];\r\n");
      out.write("var grpTotalConference = sTringArray[11];\r\n");
      out.write("*/\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"f_i_conf_body\" onLoad=\"displayGeneralConfigurationInfo()\">\r\n");
      out.write("<div class=\"tab-pane\" id=\"tabPane1\">\r\n");
      out.write("<form name=\"generalConfiguration\" >\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("tp1 = new WebFXTabPane( document.getElementById( \"tabPane1\" ) );\r\n");
      out.write("</script>\r\n");
      out.write("\t<div class=\"tab-page\" id=\"tabGeneralSetup\">\r\n");
      out.write("\t\t<h2 class=\"tab\">");
      out.print( pageData.getWord("General setup"));
      out.write("</h2>\r\n");
      out.write("\t\t<script type=\"text/javascript\">tp1.addTabPage( document.getElementById( \"tabGeneralSetup\" ) );</script>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t<legend>");
      out.print( pageData.getWord("Define work periods"));
      out.write("</legend>\r\n");
      out.write("\t\t\t<table width=\"1001\" border=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t  <td width=\"354\">\r\n");
      out.write("\t\t\t\t  \t\t<input  id=\"addWorkPeriod\"  name=\"addWorkPeriod\" type=\"button\" value='");
      out.print( pageData.getWord("Add a new work period"));
      out.write("' onClick=\"addMyRow();\"></td>\r\n");
      out.write("\t\t\t\t\t<td width=\"637\">\r\n");
      out.write("\t\t\t\t\t\t&nbsp;<input disabled  id=\"saveWorkPeriod\"  name=\"saveWorkPeriod\" type=\"button\" value='");
      out.print( pageData.getWord("Save work periods"));
      out.write("' onClick=\"javascript:saveWorkPeriodInfo();\">\r\n");
      out.write("\t\t\t\t\t    &nbsp;<input disabled  id=\"defineDurations\"  name=\"defineDurations\" type=\"button\" value='");
      out.print( pageData.getWord("Define durations for NRR"));
      out.write("' onClick=\"javascript:toggleLayer('configFields');\">\r\n");
      out.write("\t\t\t\t\t   &nbsp;<input disabled  id=\"updateInfo\"  name=\"updateInfo\" type=\"button\" value='");
      out.print( pageData.getWord("Save durations for NRR"));
      out.write("' onClick=\"saveGlobalNRRDurations()\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<!--<td>&nbsp;<INPUT id=Button2 onclick=javascript:save() type=button value=\"Save\" name=saveRowButton></TD>-->\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"workperiod_items\" style=\"MARGIN: 0px 5px\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t\t<fieldset id=\"configFields\" style=\"display:none \">\r\n");
      out.write("\t\t\t<legend>");
      out.print( pageData.getWord("Configure durations for NRR"));
      out.write("</legend>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"tab-page\" id=\"paidNRR\">\r\n");
      out.write("\t\t<h2 class=\"tab\">");
      out.print( pageData.getWord("Paid NRR"));
      out.write("</h2>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t//recordingRight = normalizeString(QueryString('recordingRight'));\r\n");
      out.write("\t\t\t//if( recordingRight != 'false')\r\n");
      out.write("\t\t\t\ttp1.addTabPage( document.getElementById( \"paidNRR\" ) );\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>");
      out.print( pageData.getWord("Select an agent group"));
      out.write("</legend>\r\n");
      out.write("\t\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("                          <select id=\"agentGroups\" name=\"agentGroups\" onChange=\"getNRRInfoForAgentGroup(this.value)\">\r\n");
      out.write("                            <option value=\"\">");
      out.print( pageData.getWord("Select agent group"));
      out.write("</option>\r\n");
      out.write("                          </select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t\t<fieldset id=\"configPaidNRR\">\r\n");
      out.write("\t\t\t<legend>");
      out.print( pageData.getWord("Associated not-ready reasons"));
      out.write("</legend>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"nrrDetails\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t    <input style=\"visibility:hidden;\"  id=\"savePaidConfig\"  name=\"savePaidConfig\" type=\"button\" value='");
      out.print( pageData.getWord("Save payable NRR for this agent group"));
      out.write("' onClick=\"savePayableOrBillableConfig(document.getElementById('agentGroups').value);refresh();\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!--\t\r\n");
      out.write("\t<div class=\"tab-page\" id=\"activity\">\r\n");
      out.write("\t\t<h2 class=\"tab\">Activities</h2>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t//recordingRight = normalizeString(QueryString('recordingRight'));\r\n");
      out.write("\t\t\t//if( recordingRight != 'false')\r\n");
      out.write("\t\t\t\ttp1.addTabPage( document.getElementById( \"activity\" ) );\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"50%\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend>Create an activity</legend>\r\n");
      out.write("\t\t\t\t\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"activity_name\" name=\"activity_name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"400\" align=\"center\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" id=\"addActivity\" name=\"addActivity\" value=\"Add an activity\" onClick=\"saveActivity()\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"50%\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend>Already created activities</legend>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"alreadyCreatedActivities\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("-->\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"tab-page\" id=\"summary\">\r\n");
      out.write("\t\t<h2 class=\"tab\">");
      out.print( pageData.getWord("Associated formulas"));
      out.write("</h2>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t//recordingRight = normalizeString(QueryString('recordingRight'));\r\n");
      out.write("\t\t\t//if( recordingRight != 'false')\r\n");
      out.write("\t\t\t\ttp1.addTabPage( document.getElementById( \"summary\" ) );\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t<legend>");
      out.print( pageData.getWord("Associated formulas"));
      out.write("</legend>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--<input name=\"deleteAgtGrp\" onClick=\"askDelete()\" type=\"button\" value=\"Delete\">-->\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t//displayActivities();\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
 pageData.closeConnection(); 
      out.write("\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
