package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.*;
import aheevaManager.csvinterface.*;
import aheevaManager.ressources.*;
import java.text.*;
import aheevaManager.schedule.*;
import aheevaManager.ressources.*;
import java.util.*;
import jxl.*;

public final class groupReport1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/aheevaManager/Resources_pages/xc2_default_labels.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
    pageData.openConnection();

      out.write("\r\n");
      out.write("<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"xc2_default.css\" type=\"text/css\">\r\n");
      out.write("<LINK href=\"livestats.css\" \trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Start Tab pane -->\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"tab_luna.css\" />\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style_2.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\" href=\"slider/css/luna.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t100px;\r\n");
      out.write("}\r\n");
      out.write("html, body {\r\n");
      out.write("\t/*background:\tThreeDFace;*/\r\n");
      out.write("}\r\n");
      out.write("form {\r\n");
      out.write("\tmargin:\t\t0;\r\n");
      out.write("\tpadding:\t0;\r\n");
      out.write("}\r\n");
      out.write("/* over ride styles from webfxlayout */\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:\t\t10px;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("\theight:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 {\r\n");
      out.write("\ttext-align:\tcenter;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 a {\r\n");
      out.write("\tdisplay:\tinline;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control a:hover {\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../Resources_pages/tabpane.js\"></script>\r\n");
      out.write("<!-- End Tab Pane -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Calendrier début -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pagexc2Data = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pagexc2Data.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
pagexc2Data.openConnection();
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("// variables of labels;// \r\n");
      out.write("var phrase= new Array();\r\n");
      out.write("phrase[0]=\"");
      out.print( pagexc2Data.getWord("January"));
      out.write("\";\r\n");
      out.write("phrase[1]=\"");
      out.print( pagexc2Data.getWord("February"));
      out.write("\";\r\n");
      out.write("phrase[2]=\"");
      out.print( pagexc2Data.getWord("March"));
      out.write("\";\r\n");
      out.write("phrase[3]=\"");
      out.print( pagexc2Data.getWord("April"));
      out.write("\";\r\n");
      out.write("phrase[4]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";         \r\n");
      out.write("phrase[5]=\"");
      out.print( pagexc2Data.getWord("June"));
      out.write("\";\r\n");
      out.write("phrase[6]=\"");
      out.print( pagexc2Data.getWord("July"));
      out.write("\";\r\n");
      out.write("phrase[7]=\"");
      out.print( pagexc2Data.getWord("August"));
      out.write("\";\r\n");
      out.write("phrase[8]=\"");
      out.print( pagexc2Data.getWord("September"));
      out.write("\";\r\n");
      out.write("phrase[9]=\"");
      out.print( pagexc2Data.getWord("October"));
      out.write("\";\r\n");
      out.write("phrase[10]=\"");
      out.print( pagexc2Data.getWord("November"));
      out.write("\";\r\n");
      out.write("phrase[11]=\"");
      out.print( pagexc2Data.getWord("December"));
      out.write("\";\r\n");
      out.write("phrase[12]=\"");
      out.print( pagexc2Data.getWord("Jan"));
      out.write("\";\r\n");
      out.write("phrase[13]=\"");
      out.print( pagexc2Data.getWord("Feb"));
      out.write("\";\r\n");
      out.write("phrase[14]=\"");
      out.print( pagexc2Data.getWord("Mar"));
      out.write("\";\r\n");
      out.write("phrase[15]=\"");
      out.print( pagexc2Data.getWord("Apr"));
      out.write("\";\r\n");
      out.write("phrase[16]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";\r\n");
      out.write("phrase[17]=\"");
      out.print( pagexc2Data.getWord("Jun"));
      out.write("\";\r\n");
      out.write("phrase[18]=\"");
      out.print( pagexc2Data.getWord("Jul"));
      out.write("\";\r\n");
      out.write("phrase[19]=\"");
      out.print( pagexc2Data.getWord("Aug"));
      out.write("\";\r\n");
      out.write("phrase[20]=\"");
      out.print( pagexc2Data.getWord("Sep"));
      out.write("\";\r\n");
      out.write("phrase[21]=\"");
      out.print( pagexc2Data.getWord("Oct"));
      out.write("\";\r\n");
      out.write("phrase[22]=\"");
      out.print( pagexc2Data.getWord("Nov"));
      out.write("\";\r\n");
      out.write("phrase[23]=\"");
      out.print( pagexc2Data.getWord("Dec"));
      out.write("\";\r\n");
      out.write("phrase[24]=\"");
      out.print( pagexc2Data.getWord("Sunday"));
      out.write("\";\r\n");
      out.write("phrase[25]=\"");
      out.print( pagexc2Data.getWord("Monday"));
      out.write("\";\r\n");
      out.write("phrase[26]=\"");
      out.print( pagexc2Data.getWord("Tuesday"));
      out.write("\";\r\n");
      out.write("phrase[27]=\"");
      out.print( pagexc2Data.getWord("Wednesday"));
      out.write("\";\r\n");
      out.write("phrase[28]=\"");
      out.print( pagexc2Data.getWord("Thursday"));
      out.write("\";\r\n");
      out.write("phrase[29]=\"");
      out.print( pagexc2Data.getWord("Friday"));
      out.write("\";\r\n");
      out.write("phrase[30]=\"");
      out.print( pagexc2Data.getWord("Saturday"));
      out.write("\";\r\n");
      out.write("phrase[31]=\"");
      out.print( pagexc2Data.getWord("Sun"));
      out.write("\";\r\n");
      out.write("phrase[32]=\"");
      out.print( pagexc2Data.getWord("Mon"));
      out.write("\";\r\n");
      out.write("phrase[33]=\"");
      out.print( pagexc2Data.getWord("Tue"));
      out.write("\";\r\n");
      out.write("phrase[34]=\"");
      out.print( pagexc2Data.getWord("Wed"));
      out.write("\";\r\n");
      out.write("phrase[35]=\"");
      out.print( pagexc2Data.getWord("Thu"));
      out.write("\";\r\n");
      out.write("phrase[36]=\"");
      out.print( pagexc2Data.getWord("Fri"));
      out.write("\";\r\n");
      out.write("phrase[37]=\"");
      out.print( pagexc2Data.getWord("Sat"));
      out.write("\";\r\n");
      out.write("phrase[38]=\"");
      out.print( pagexc2Data.getWord("Su"));
      out.write("\";\r\n");
      out.write("phrase[39]=\"");
      out.print( pagexc2Data.getWord("Mo"));
      out.write("\";\r\n");
      out.write("phrase[40]=\"");
      out.print( pagexc2Data.getWord("Tu"));
      out.write("\";\r\n");
      out.write("phrase[41]=\"");
      out.print( pagexc2Data.getWord("We"));
      out.write("\";\r\n");
      out.write("phrase[42]=\"");
      out.print( pagexc2Data.getWord("Th"));
      out.write("\";\r\n");
      out.write("phrase[43]=\"");
      out.print( pagexc2Data.getWord("Fr"));
      out.write("\";\r\n");
      out.write("phrase[44]=\"");
      out.print( pagexc2Data.getWord("Sa"));
      out.write("\";\r\n");
      out.write("phrase[45]=\"");
      out.print( pagexc2Data.getWord(" Today "));
      out.write("\";\r\n");
      out.write("phrase[46]=\"");
      out.print( pagexc2Data.getWord("Clear"));
      out.write("\";\r\n");
      out.write("phrase[47]=\"");
      out.print( pagexc2Data.getWord("Back"));
      out.write("\";\r\n");
      out.write("phrase[48]=\"");
      out.print( pagexc2Data.getWord("Close"));
      out.write("\";\r\n");
      out.write("phrase[49]=\"");
      out.print( pagexc2Data.getWord("Reset"));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 pagexc2Data.closeConnection(); 
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"xc2_default.js\"></script>\r\n");
      out.write("<script language=\"javascript\">xcAutoHide=1000;</script>\r\n");
      out.write("<script language=\"javascript\" src=\"xc2_inpage.js\"></script>\r\n");
      out.write("<!-- Calendrier fin -->\r\n");
      out.write("<script language=\"JavaScript\" src=\"jsUtil.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Browser.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var vValue = normalizeString(QueryString('type'));\r\n");
      out.write("var tenant_dbid = normalizeString(QueryString('tenant_dbid'));\r\n");
      out.write("//alert(\"vValue\"+vValue);\r\n");
      out.write("var doingSearch = 0; // shows if a search is being performed\r\n");
      out.write("\r\n");
      out.write("function fillObjectCombo()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById(\"noresult\").style.visibility=\"hidden\";\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("    if((vValue=='GroupForecast') || (vValue=='GroupSummary') )\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar searchFull = new RegExp(document.getElementById(\"searchfullname\").value, \"gi\");\r\n");
      out.write("\t\tvar searchPart = new RegExp(document.getElementById(\"searchpartname\").value, \"gi\");\r\n");
      out.write("\t\tvar agentGroups = String( appletObj.getAgentGroupByDBIDandName(tenant_dbid) );\r\n");
      out.write("\t\tvar jsAgentGroups = agentGroups + \"\";\r\n");
      out.write("    \tarrayGroups = jsAgentGroups.split(\"|\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.theForm.objects.options.length=0; //remove 'loading' text\r\n");
      out.write("\t\tif(searchFull!=\"//ig\" && doingSearch==1) { // if full name search\r\n");
      out.write("\t\t\tdoingSearch=0;\r\n");
      out.write("\t\t\tfor (j = 0; j <arrayGroups.length; j++){\r\n");
      out.write("\t\t\t\tif(arrayGroups[j].search(searchFull)==0) {\r\n");
      out.write("\t\t\t\t\tvar groups = arrayGroups[j].split(\",\");\r\n");
      out.write("\t\t\t\t\tmyOption = new Option(groups[0],arrayGroups[j])\r\n");
      out.write("\t\t\t\t\toptionPos = document.theForm.objects.options.length\r\n");
      out.write("\t\t\t\t\tdocument.theForm.objects.options[optionPos]=myOption\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else if(searchPart!=\"//ig\" && doingSearch==1) { // if partial name search\r\n");
      out.write("\t\t\tdoingSearch=0;\r\n");
      out.write("\t\t\tfor (j = 0; j <arrayGroups.length; j++){\r\n");
      out.write("\t\t\t\tif(arrayGroups[j].search(searchPart)!=-1) {\r\n");
      out.write("\t\t\t\t\tvar groups = arrayGroups[j].split(\",\");\r\n");
      out.write("\t\t\t\t\tmyOption = new Option(groups[0],arrayGroups[j])\r\n");
      out.write("\t\t\t\t\toptionPos = document.theForm.objects.options.length\r\n");
      out.write("\t\t\t\t\tdocument.theForm.objects.options[optionPos]=myOption\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tfor (j = 0; j <arrayGroups.length; j++){\r\n");
      out.write("\t\t\t\tvar groups = arrayGroups[j].split(\",\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tmyOption = new Option(groups[0],arrayGroups[j])\r\n");
      out.write("\t\t\t\toptionPos = document.theForm.objects.options.length\r\n");
      out.write("\t\t\t\tdocument.theForm.objects.options[optionPos]=myOption\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.theForm.objects.options.length==0) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"noresult\").style.visibility=\"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\tformObjectsResize();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function formObjectsResize() {\r\n");
      out.write("\tif(document.theForm.objects.options.length >= 7)\r\n");
      out.write("\t   \tdocument.theForm.objects.size = 7;\r\n");
      out.write("\telse if(document.theForm.objects.options.length < 3)\r\n");
      out.write("\t\tdocument.theForm.objects.size = 3;\r\n");
      out.write("\telse\r\n");
      out.write("\t\tdocument.theForm.objects.size = document.theForm.objects.options.length+1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function selectAll()\r\n");
      out.write("{\r\n");
      out.write("  for (j = 0; j <document.theForm.objects.options.length; j++)\r\n");
      out.write("\t  document.theForm.objects.options[j].selected = true;  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function unSelectAll()\r\n");
      out.write("{\r\n");
      out.write("  for (j = 0; j <document.theForm.objects.options.length; j++)\r\n");
      out.write("\t  document.theForm.objects.options[j].selected = false;  \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function KeyDownHandler(btn){\r\n");
      out.write("\t\r\n");
      out.write("\t// process only the Enter key\r\n");
      out.write("\tif (event.keyCode == 13){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (document.activeElement) { // for ie\r\n");
      out.write("\t\t\tif(document.activeElement.id==\"searchfirst\" || document.activeElement.id==\"searchlast\" || document.activeElement.id==\"searchid\" || document.activeElement.id==\"searchfullname\" || document.activeElement.id==\"searchpartname\") {\r\n");
      out.write("\t\t\t\tsearchFor();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t// cancel the default submit\r\n");
      out.write("\t\t\t\tevent.returnValue=false;\r\n");
      out.write("\t\t\t\tevent.cancel = true;\r\n");
      out.write("\t\t\t\t// submit the form by programmatically clicking the specified button\r\n");
      out.write("\t\t\t\tbtn.click();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{ // for firefox\r\n");
      out.write("\t\t\tif(document.focusNode.id==\"searchfirst\" || document.focusNode.id==\"searchlast\" || document.focusNode.id==\"searchid\" || document.focusNode.id==\"searchfullname\" || document.focusNode.id==\"searchpartname\") {\r\n");
      out.write("\t\t\t\tsearchFor();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t// cancel the default submit\r\n");
      out.write("\t\t\t\tevent.returnValue=false;\r\n");
      out.write("\t\t\t\tevent.cancel = true;\r\n");
      out.write("\t\t\t\t// submit the form by programmatically clicking the specified button\r\n");
      out.write("\t\t\t\tbtn.click();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function searchFor() { // varify text search\r\n");
      out.write("\r\n");
      out.write("\tvar thisSearch1 = document.getElementById(\"searchfullname\").value;\r\n");
      out.write("\tvar thisSearch2 = document.getElementById(\"searchpartname\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("\tif (thisSearch1.match(/\\?/) || thisSearch1.match(/\\*/) || thisSearch1.match(/\\(/) || thisSearch1.match(/\\)/) || thisSearch1.match(/\\+/) || thisSearch1.match(/\\[/) || thisSearch1.match(/\\]/) || thisSearch1.match(/\\</) || thisSearch1.match(/\\>/) || thisSearch1.match(/\\|/) || thisSearch1.match(/\\./) || thisSearch2.match(/\\?/) || thisSearch2.match(/\\*/) || thisSearch2.match(/\\(/) || thisSearch2.match(/\\)/) || thisSearch2.match(/\\+/) || thisSearch2.match(/\\[/) || thisSearch2.match(/\\]/) || thisSearch2.match(/\\</) || thisSearch2.match(/\\>/) || thisSearch2.match(/\\|/) || thisSearch2.match(/\\./)) { // disallowed characters\r\n");
      out.write("\t\talert(\"");
      out.print(pageData.getWord("Search query cannot contain"));
      out.write(" '?', '*', '.', '+', '(', ')', '[', ']', '<', '>' ");
      out.print(pageData.getWord("or"));
      out.write(" '|'\");\r\n");
      out.write("\t}else if (document.getElementById(\"searchfullname\").value!=\"\" && document.getElementById(\"searchpartname\").value!=\"\"){\r\n");
      out.write("\t\talert(\"");
      out.print(pageData.getWord("Search for either"));
      out.write("\\n\\n'");
      out.print(pageData.getWord("Name"));
      out.write("'\\n(");
      out.print(pageData.getWord("can be the full name or the begining of the name"));
      out.write(')');
      out.write('\\');
      out.write('n');
      out.print(pageData.getWord("or"));
      out.write(' ');
      out.write('\'');
      out.print(pageData.getWord("Name includes"));
      out.write("'\\n(");
      out.print(pageData.getWord("search for text that is included anywhere in the name"));
      out.write(")\\n\\n");
      out.print(pageData.getWord("but not both"));
      out.write(".\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tdoingSearch=1;\r\n");
      out.write("\t\tfillObjectCombo();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function resetResults() {\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById(\"searchfullname\").value=\"\";\r\n");
      out.write("\tdocument.getElementById(\"searchpartname\").value=\"\";\r\n");
      out.write("\tfillObjectCombo();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getSelectedObjects()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\tselectedObjects = new Array()\r\n");
      out.write("\tfor (i=document.theForm.objects.selectedIndex;i<document.theForm.objects.options.length;i++) {\r\n");
      out.write("  \t\tif (document.theForm.objects.options[i].selected) {\r\n");
      out.write("  \t\t\tselectedObjects[selectedObjects.length]=document.theForm.objects.options[i].value;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t}\r\n");
      out.write("        var url = '';\r\n");
      out.write("\tif (selectedObjects.length > 0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\turl= escape(selectedObjects.join('/'))\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\treturn url;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getRequestedReport()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\tvar destination = '';\r\n");
      out.write("\tif(document.theForm.objects.selectedIndex == -1)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("Please select at least one object"));
      out.write("\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif( vValue=='GroupForecast' )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(document.theForm.startingDateDaily.value.length == 0)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\talert(\"");
      out.print( pageData.getWord("Please enter a date for report"));
      out.write("\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if( vValue=='GroupSummary' )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(document.theForm.startingDateDaily.value.length == 0)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"");
      out.print( pageData.getWord("Please enter a starting date"));
      out.write("\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(document.theForm.endingDateDaily.value.length == 0)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"");
      out.print( pageData.getWord("Please enter an ending date"));
      out.write("\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tif(vValue == 'GroupForecast')\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdestination = \"../jsp/groupForecastReports.jsp\"\r\n");
      out.write("\t}\r\n");
      out.write("\telse if( vValue=='GroupSummary' )\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdestination = \"../jsp/groupSummaryReports.jsp\"\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tdestination += \"?lang=\"+lang;\r\n");
      out.write("\tdestination += \"&startingDateDaily=\"\r\n");
      out.write("\tdestination += document.theForm.startingDateDaily.value;\r\n");
      out.write("\tif( vValue=='GroupSummary' ){\r\n");
      out.write("\t\tdestination +=\"&endingDateDaily=\";\r\n");
      out.write("\t\tdestination += document.theForm.endingDateDaily.value;\t\r\n");
      out.write("\t}\t\r\n");
      out.write("\tif(vValue == 'GroupForecast')\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdestination +=\"&interval=\";\r\n");
      out.write("\t\tdestination +=document.theForm.interval.value;\r\n");
      out.write("\t}\r\n");
      out.write("\tdestination +=\"&objects=\";\r\n");
      out.write("\tdestination += getSelectedObjects();\r\n");
      out.write("\tdestination +=\"&prec=-1&suiv=1&current=0&all_obj=0\";\t\r\n");
      out.write("\t\r\n");
      out.write("\twindow.open(destination);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write(".style1 {\r\n");
      out.write("    font-family:Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"rep_body\" onLoad=\"fillObjectCombo()\">\r\n");
      out.write("\t<div class=\"tab-pane\" id=\"tabPane1\">\r\n");
      out.write("\t\t<form name=\"theForm\" onKeyDown=\"KeyDownHandler(submit)\">\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\ttp1 = new WebFXTabPane( document.getElementById( \"tabPane1\" ) );\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<div class=\"tab-page\" id=\"tabGeneral\">\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend id=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t<script language=\"JavaScript\">\r\n");
      out.write("\t\t\t\t\t\tvar vValue = normalizeString(QueryString('type'));\r\n");
      out.write("\t\t\t\t\t\tif (vValue == 'GroupForecast'){\r\n");
      out.write("\t\t\t  \t\t\t\tdocument.write(\"");
      out.print( pageData.getWord("Group Forecast Daily Report"));
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\telse if( vValue=='GroupSummary' )\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tdocument.write(\"");
      out.print( pageData.getWord("Group Summary Reports"));
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t</legend>\r\n");
      out.write("\t\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\"  width=\"70%\">\r\n");
      out.write("\t  \t\t\t\t\t\t\t\t<tr height=\"45\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<script language=\"JavaScript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar vValue = normalizeString(QueryString('type'));\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif (vValue != '')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('<td valign=\"top\" style=\"border-left-style:none; border-left-width:1; border-top-style:none; border-top-width:1;\" >')\r\n");
      out.write("\t\t\t    \t\t\t\t\t\t\t\tdocument.write('<br>')\r\n");
      out.write("\t\t\t    \t\t\t\t\t\t\t\tdocument.write('<select id=\"objects\" name=\"objects\" multiple>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('<option value=\"\">&nbsp;</option>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('<option value=\"\">&nbsp;&nbsp;");
      out.print(pageData.getWord("Loading"));
      out.write("...</option>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('<option value=\"\">&nbsp;&nbsp;");
      out.print(pageData.getWord("Please wait"));
      out.write(".</option>')\r\n");
      out.write("\t\t\t    \t\t\t\t\t\t\t\tdocument.write('</select>')\r\n");
      out.write("\t\t\t    \t\t\t\t\t\t\t\tdocument.write('</td>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tif((vValue == 'GroupForecast') ||( vValue=='GroupSummary' ) )\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('<td valign=\"top\" style=\"padding-left:15px;\">')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\t\t\t\tdocument.write('<div style=\"width:450px;\">')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\t\t\t\tdocument.write('<div style=\"padding-top:8px; padding-bottom:4px;\">");
      out.print(pageData.getWord("Search for either"));
      out.write(":</div>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\t\t\t\tdocument.write('<span style=\"width:130px\">");
      out.print(pageData.getWord("Name"));
      out.write("</span>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\t\t\t\tdocument.write('<span style=\"width:130px\">");
      out.print(pageData.getWord("Name includes"));
      out.write("</span>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\t\t\t\tdocument.write('<br>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\t\t\t\tdocument.write('<span style=\"width:130px\"><input id=\"searchfullname\" type=\"text\" value=\"\" size=\"16\" name=\"searchfullname\" /></span>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\t\t\t\tdocument.write('<span style=\"width:130px\"><input id=\"searchpartname\" type=\"text\" value=\"\" size=\"16\" name=\"searchpartname\" /></span>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\t\t\t\tdocument.write('<button id=\"searchbut\" onClick=\"searchFor()\" style=\"cursor:pointer\">");
      out.print(pageData.getWord("Search"));
      out.write("</button>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\t\t\t\tdocument.write('<br>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\t\t\t\tdocument.write('<button name=\\\"selectAllButton\\\" onClick=\\\"selectAll()\\\" ID=\"Button1\" style=\"cursor:pointer; margin-right:5px; margin-top:15px;\">");
      out.print(pageData.getWord("Select all"));
      out.write("</button>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\t\t\t\tdocument.write('<button name=\\\"unSelectButton\\\" onClick=\\\"unSelectAll()\\\" ID=\"Button2\" style=\"cursor:pointer; margin-right:30px; margin-top:15px;\">");
      out.print(pageData.getWord("Select none"));
      out.write("</button>');\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\t\t\t\tdocument.write('<button onClick=\"resetResults()\" style=\"cursor:pointer; margin-top:15px;\">");
      out.print(pageData.getWord("show full list"));
      out.write("</button>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\t\t\t\tdocument.write('</div>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\t\t\t\tdocument.write('</td>')\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t\t\t\tdocument.write('<td>&nbsp;</td>')\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t\t\t\tdocument.write('<td>&nbsp;</td>')\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t\t\t\tdocument.write('<td>&nbsp;</td>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t<td width=\"28%\" valign=\"top\" style=\"border-right-style: none; border-right-width: 1; border-top-style: none; border-top-width: 1\" >\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t  \t\t\t\t\t\t</tr>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td height=\"20\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\"  width=\"100%\" align=\"left\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif( vValue=='GroupForecast'){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('<td id=\\\"id_startingDateDaily\\\" valign=\\\"top\\\" width=\\\"50%\\\" style=\\\"border-left-style: none; border-left-width: 1; border-bottom-style:none; border-bottom-width:1\\\">');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('&nbsp;&nbsp;&nbsp;');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write(\"");
      out.print( pageData.getWord("Daily Report For"));
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('&nbsp;&nbsp;&nbsp;');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.writeln(\"<input type=\\\"text\\\" size=\\\"20\\\" onFocus=\\\"showCalendar('',this,this,'','id_startingDateDaily',0,30,1);this.blur()\\\" name=\\\"startingDateDaily\\\" />\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('</td>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}else if( vValue=='GroupSummary'){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('<td id=\\\"id_startingDateDaily\\\" valign=\\\"top\\\" width=\\\"50%\\\" style=\\\"border-left-style: none; border-left-width: 1; border-bottom-style:none; border-bottom-width:1\\\">');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('&nbsp;&nbsp;&nbsp;');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write(\"");
      out.print( pageData.getWord("Daily Report From"));
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('&nbsp;&nbsp;&nbsp;');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.writeln(\"<input type=\\\"text\\\" size=\\\"20\\\" onFocus=\\\"showCalendar('',this,this,'','id_startingDateDaily',0,30,1);this.blur()\\\" name=\\\"startingDateDaily\\\" />\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('</td>');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('<td id=\\\"id_endingDateDaily\\\" valign=\\\"top\\\" width=\\\"50%\\\" style=\\\"border-bottom-style: none; border-bottom-width: 1\\\" align=\\\"left\"\\>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('&nbsp;&nbsp;&nbsp;');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write(\"");
      out.print( pageData.getWord("To"));
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('&nbsp;&nbsp;&nbsp;');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.writeln(\"<input type=\\\"text\\\" size=\\\"20\\\" onFocus=\\\"showCalendar('',this,this,'','id_endingDateDaily',0,30,1);this.blur()\\\" name=\\\"endingDateDaily\\\" />\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('</td>');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td height=\"20\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>  \r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\"  width=\"100%\" align=\"left\" >\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif( vValue=='GroupForecast'){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('<td id=\\\"id_startingDateDaily\\\" valign=\\\"top\\\" width=\\\"50%\\\" style=\\\"border-left-style: none; border-left-width: 1; border-bottom-style:none; border-bottom-width:1\\\">');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('&nbsp;&nbsp;&nbsp;');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write(\"");
      out.print( pageData.getWord("Interval Selection"));
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('&nbsp;&nbsp;&nbsp;');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('<select name=\"interval\">');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('<option value=\"900\">15</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('<option value=\"1800\">30</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument.write('</select></td>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td height=\"20\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>  \t\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\"  width=\"50%\" align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td height=\"20\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t  \t\t\t\t\t\t\t\t\t\t<input id=\"submit\" type=\"button\" value='");
      out.print( pageData.getWord("Submit"));
      out.write("' onClick=\"getRequestedReport()\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"noresult\" style=\"position:absolute; top:60px; left:60px; visibility:hidden\">No match.</div>\r\n");
      out.write("</body>\r\n");
 pageData.closeConnection(); 
      out.write("\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
