package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.*;
import aheevaManager.csvinterface.*;
import aheevaManager.ressources.*;
import java.text.*;
import aheevaManager.schedule.*;
import aheevaManager.ressources.*;
import java.util.*;
import jxl.*;

public final class horaires1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/aheevaManager/Resources_pages/xc2_default_labels.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
    pageData.openConnection();

      out.write("\r\n");
      out.write("<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"xc2_default.css\" type=\"text/css\">\r\n");
      out.write("<LINK href=\"livestats.css\" \trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pagexc2Data = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pagexc2Data.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
pagexc2Data.openConnection();
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("// variables of labels;// \r\n");
      out.write("var phrase= new Array();\r\n");
      out.write("phrase[0]=\"");
      out.print( pagexc2Data.getWord("January"));
      out.write("\";\r\n");
      out.write("phrase[1]=\"");
      out.print( pagexc2Data.getWord("February"));
      out.write("\";\r\n");
      out.write("phrase[2]=\"");
      out.print( pagexc2Data.getWord("March"));
      out.write("\";\r\n");
      out.write("phrase[3]=\"");
      out.print( pagexc2Data.getWord("April"));
      out.write("\";\r\n");
      out.write("phrase[4]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";         \r\n");
      out.write("phrase[5]=\"");
      out.print( pagexc2Data.getWord("June"));
      out.write("\";\r\n");
      out.write("phrase[6]=\"");
      out.print( pagexc2Data.getWord("July"));
      out.write("\";\r\n");
      out.write("phrase[7]=\"");
      out.print( pagexc2Data.getWord("August"));
      out.write("\";\r\n");
      out.write("phrase[8]=\"");
      out.print( pagexc2Data.getWord("September"));
      out.write("\";\r\n");
      out.write("phrase[9]=\"");
      out.print( pagexc2Data.getWord("October"));
      out.write("\";\r\n");
      out.write("phrase[10]=\"");
      out.print( pagexc2Data.getWord("November"));
      out.write("\";\r\n");
      out.write("phrase[11]=\"");
      out.print( pagexc2Data.getWord("December"));
      out.write("\";\r\n");
      out.write("phrase[12]=\"");
      out.print( pagexc2Data.getWord("Jan"));
      out.write("\";\r\n");
      out.write("phrase[13]=\"");
      out.print( pagexc2Data.getWord("Feb"));
      out.write("\";\r\n");
      out.write("phrase[14]=\"");
      out.print( pagexc2Data.getWord("Mar"));
      out.write("\";\r\n");
      out.write("phrase[15]=\"");
      out.print( pagexc2Data.getWord("Apr"));
      out.write("\";\r\n");
      out.write("phrase[16]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";\r\n");
      out.write("phrase[17]=\"");
      out.print( pagexc2Data.getWord("Jun"));
      out.write("\";\r\n");
      out.write("phrase[18]=\"");
      out.print( pagexc2Data.getWord("Jul"));
      out.write("\";\r\n");
      out.write("phrase[19]=\"");
      out.print( pagexc2Data.getWord("Aug"));
      out.write("\";\r\n");
      out.write("phrase[20]=\"");
      out.print( pagexc2Data.getWord("Sep"));
      out.write("\";\r\n");
      out.write("phrase[21]=\"");
      out.print( pagexc2Data.getWord("Oct"));
      out.write("\";\r\n");
      out.write("phrase[22]=\"");
      out.print( pagexc2Data.getWord("Nov"));
      out.write("\";\r\n");
      out.write("phrase[23]=\"");
      out.print( pagexc2Data.getWord("Dec"));
      out.write("\";\r\n");
      out.write("phrase[24]=\"");
      out.print( pagexc2Data.getWord("Sunday"));
      out.write("\";\r\n");
      out.write("phrase[25]=\"");
      out.print( pagexc2Data.getWord("Monday"));
      out.write("\";\r\n");
      out.write("phrase[26]=\"");
      out.print( pagexc2Data.getWord("Tuesday"));
      out.write("\";\r\n");
      out.write("phrase[27]=\"");
      out.print( pagexc2Data.getWord("Wednesday"));
      out.write("\";\r\n");
      out.write("phrase[28]=\"");
      out.print( pagexc2Data.getWord("Thursday"));
      out.write("\";\r\n");
      out.write("phrase[29]=\"");
      out.print( pagexc2Data.getWord("Friday"));
      out.write("\";\r\n");
      out.write("phrase[30]=\"");
      out.print( pagexc2Data.getWord("Saturday"));
      out.write("\";\r\n");
      out.write("phrase[31]=\"");
      out.print( pagexc2Data.getWord("Sun"));
      out.write("\";\r\n");
      out.write("phrase[32]=\"");
      out.print( pagexc2Data.getWord("Mon"));
      out.write("\";\r\n");
      out.write("phrase[33]=\"");
      out.print( pagexc2Data.getWord("Tue"));
      out.write("\";\r\n");
      out.write("phrase[34]=\"");
      out.print( pagexc2Data.getWord("Wed"));
      out.write("\";\r\n");
      out.write("phrase[35]=\"");
      out.print( pagexc2Data.getWord("Thu"));
      out.write("\";\r\n");
      out.write("phrase[36]=\"");
      out.print( pagexc2Data.getWord("Fri"));
      out.write("\";\r\n");
      out.write("phrase[37]=\"");
      out.print( pagexc2Data.getWord("Sat"));
      out.write("\";\r\n");
      out.write("phrase[38]=\"");
      out.print( pagexc2Data.getWord("Su"));
      out.write("\";\r\n");
      out.write("phrase[39]=\"");
      out.print( pagexc2Data.getWord("Mo"));
      out.write("\";\r\n");
      out.write("phrase[40]=\"");
      out.print( pagexc2Data.getWord("Tu"));
      out.write("\";\r\n");
      out.write("phrase[41]=\"");
      out.print( pagexc2Data.getWord("We"));
      out.write("\";\r\n");
      out.write("phrase[42]=\"");
      out.print( pagexc2Data.getWord("Th"));
      out.write("\";\r\n");
      out.write("phrase[43]=\"");
      out.print( pagexc2Data.getWord("Fr"));
      out.write("\";\r\n");
      out.write("phrase[44]=\"");
      out.print( pagexc2Data.getWord("Sa"));
      out.write("\";\r\n");
      out.write("phrase[45]=\"");
      out.print( pagexc2Data.getWord(" Today "));
      out.write("\";\r\n");
      out.write("phrase[46]=\"");
      out.print( pagexc2Data.getWord("Clear"));
      out.write("\";\r\n");
      out.write("phrase[47]=\"");
      out.print( pagexc2Data.getWord("Back"));
      out.write("\";\r\n");
      out.write("phrase[48]=\"");
      out.print( pagexc2Data.getWord("Close"));
      out.write("\";\r\n");
      out.write("phrase[49]=\"");
      out.print( pagexc2Data.getWord("Reset"));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 pagexc2Data.closeConnection(); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Start Tab pane -->\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"tab_luna.css\" />\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style_2.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\" href=\"slider/css/luna.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t100px;\r\n");
      out.write("}\r\n");
      out.write("html, body {\r\n");
      out.write("\t/*background:\tThreeDFace;*/\r\n");
      out.write("}\r\n");
      out.write("form {\r\n");
      out.write("\tmargin:\t\t0;\r\n");
      out.write("\tpadding:\t0;\r\n");
      out.write("}\r\n");
      out.write("/* over ride styles from webfxlayout */\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:\t\t10px;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("\theight:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 {\r\n");
      out.write("\ttext-align:\tcenter;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 a {\r\n");
      out.write("\tdisplay:\tinline;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control a:hover {\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../Resources_pages/tabpane.js\"></script>\r\n");
      out.write("<!-- End Tab Pane -->\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"xc2_default.js\"></script>\r\n");
      out.write("<script language=\"javascript\">xcAutoHide=1000;</script>\r\n");
      out.write("<script language=\"javascript\" src=\"xc2_inpage.js\"></script>\r\n");
      out.write("<!-- Calendrier fin -->\r\n");
      out.write("<script language=\"JavaScript\" src=\"jsUtil.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Browser.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var vValue = normalizeString(QueryString('type'));\r\n");
      out.write("var tenant_dbid = normalizeString(QueryString('tenant_dbid'));\r\n");
      out.write("var complete = normalizeString(QueryString('complete'));\r\n");
      out.write("\r\n");
      out.write("function sortSelect(o)\r\n");
      out.write("{\r\n");
      out.write("\tif (o.length==0) { return; }\r\n");
      out.write("\r\n");
      out.write("\tif(document.theForm.viewckbox.checked == false){\r\n");
      out.write("\t\to = o.sort(\r\n");
      out.write("\t\t\tfunction(a,b) {\r\n");
      out.write("\t\t\t\tif ((a.text+\"\") < (b.text+\"\")) { return -1; }\r\n");
      out.write("\t\t\t\tif ((a.text+\"\") > (b.text+\"\")) { return 1; }\r\n");
      out.write("\t\t\t\treturn 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\to = o.sort(\r\n");
      out.write("\t\t\tfunction(a,b) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (parseInt(a.value) < parseInt(b.value)) { return -1; }\r\n");
      out.write("\t\t\t\t\tif (parseInt(a.value) > parseInt(b.value)) { return 1; }\r\n");
      out.write("\t\t\t\t\treturn 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sortSelect2(obj)\r\n");
      out.write("{\r\n");
      out.write("\tvar o = new Array();\r\n");
      out.write("\tif (obj.options==null) { return; }\r\n");
      out.write("\tfor (var i=0; i<obj.options.length; i++) {\r\n");
      out.write("\t\to[o.length] = new Option( obj.options[i].text, obj.options[i].value, obj.options[i].defaultSelected, obj.options[i].selected) ;\r\n");
      out.write("\t\t}\r\n");
      out.write("\tif (o.length==0) { return; }\r\n");
      out.write("\r\n");
      out.write("\tif(document.theForm.viewckbox.checked == false){\r\n");
      out.write("\t\to = o.sort(\r\n");
      out.write("\t\t\tfunction(a,b) {\r\n");
      out.write("\t\t\t\tif ((a.text+\"\") < (b.text+\"\")) { return -1; }\r\n");
      out.write("\t\t\t\tif ((a.text+\"\") > (b.text+\"\")) { return 1; }\r\n");
      out.write("\t\t\t\treturn 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\to = o.sort(\r\n");
      out.write("\t\t\tfunction(a,b) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (parseInt(a.value) < parseInt(b.value)) { return -1; }\r\n");
      out.write("\t\t\t\t\tif (parseInt(a.value) > parseInt(b.value)) { return 1; }\r\n");
      out.write("\t\t\t\t\treturn 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t}\r\n");
      out.write("\tfor (var i=0; i<o.length; i++) {\r\n");
      out.write("\t\tobj.options[i] = new Option(o[i].text, o[i].value, o[i].defaultSelected, o[i].selected);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function fillObjectCombo()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tvar agentGroups = String( appletObj.getAgentGroupByDBIDandName(tenant_dbid) );\r\n");
      out.write("\t\tvar jsAgentGroups = agentGroups + \"\";\r\n");
      out.write("\r\n");
      out.write("    \t        arrayGroups = jsAgentGroups.split(\"|\");\r\n");
      out.write("\t\tfor (j = 0; j <arrayGroups.length; j++){\r\n");
      out.write("                  var groups = arrayGroups[j].split(\",\");\r\n");
      out.write("\r\n");
      out.write("    \t\t\tmyOption = new Option(groups[0],arrayGroups[j])\r\n");
      out.write("\t\t\toptionPos = document.theForm.objects.options.length\r\n");
      out.write("\t\t\tdocument.theForm.objects.options[optionPos]=myOption\r\n");
      out.write("    \t\t}\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    if(document.theForm.objects.options.length >= 10)\r\n");
      out.write("\t   \tdocument.theForm.objects.size = 10;\r\n");
      out.write("\telse\r\n");
      out.write("\t\tdocument.theForm.objects.size = document.theForm.objects.options.length;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function selectAll()\r\n");
      out.write("{\r\n");
      out.write("  for (j = 0; j <document.theForm.objects.options.length; j++)\r\n");
      out.write("\t  document.theForm.objects.options[j].selected = true;  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function unSelectAll()\r\n");
      out.write("{\r\n");
      out.write("  for (j = 0; j <document.theForm.objects.options.length; j++)\r\n");
      out.write("\t  document.theForm.objects.options[j].selected = false;  \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getSelectedObjects()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\tselectedObjects = new Array()\r\n");
      out.write("\tfor (i=document.theForm.objects.selectedIndex;i<document.theForm.objects.options.length;i++) {\r\n");
      out.write("  \t\tif (document.theForm.objects.options[i].selected) {\r\n");
      out.write("  \t\t\tselectedObjects[selectedObjects.length]=document.theForm.objects.options[i].value;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t}\r\n");
      out.write("        var url = '';\r\n");
      out.write("\tif (selectedObjects.length > 0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\turl= escape(selectedObjects.join('/'))\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\treturn url;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getSelectedTeams(){\r\n");
      out.write("\t\tvar url = '';\r\n");
      out.write("\r\n");
      out.write("\t\tselectedTeams = new Array()\r\n");
      out.write("\t\tfor (i=teams.selectedIndex;i<teams.options.length;i++) {\r\n");
      out.write("  \t\t\tif (teams.options[i].selected) {\r\n");
      out.write("  \t\t\t\tselectedTeams[selectedTeams.length]=teams.options[i].value;\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t}\r\n");
      out.write("\t\tif (selectedObjects.length > 0){\r\n");
      out.write("\t\t\turl= escape(selectedObjects.join('/'))\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn url;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getRequestedPeriod()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\tvar destination = '';\r\n");
      out.write("\r\n");
      out.write("\t\tif(document.theForm.startingDateDaily.value.length == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"");
      out.print( pageData.getWord("Please enter a starting date"));
      out.write("\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.theForm.endingDateDaily.value.length == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"");
      out.print( pageData.getWord("Please enter an ending date"));
      out.write("\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(dateChecker() == false)\r\n");
      out.write("\t{\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("   \r\n");
      out.write("if (complete ==\"no\" ){\r\n");
      out.write("\tdestination = \"../jsp/horaires.jsp\"\r\n");
      out.write("}else if (complete ==\"yes\"){\r\n");
      out.write("\tdestination = \"../jsp/publishedHoraires.jsp\" \r\n");
      out.write("}else{\r\n");
      out.write("\tdestination = \"../jsp/report.jsp\" \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\tdestination += \"?startingDateDaily=\"\r\n");
      out.write("\tdestination += document.theForm.startingDateDaily.value;\r\n");
      out.write("\tdestination +=\"&endingDateDaily=\";\r\n");
      out.write("\tdestination += document.theForm.endingDateDaily.value;\r\n");
      out.write("\tdestination +=\"&group=\";\r\n");
      out.write("\tdestination += getSelectedObjects();\r\n");
      out.write("\t\r\n");
      out.write("    destination += \"&lang=\"+lang;\r\n");
      out.write("\t//window.open(destination);\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.location = destination;//ouverture locale\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function dateChecker()\r\n");
      out.write("{\r\n");
      out.write("\tvar temp = document.theForm.startingDateDaily.value;\r\n");
      out.write("\tvar start = new Date();\r\n");
      out.write("\tstart.setDate(temp.substring(3, 5));\r\n");
      out.write("\tstart.setMonth(temp.substring(0, 2) - 1);\r\n");
      out.write("\tstart.setYear(temp.substring(6, 10));\r\n");
      out.write("\t\r\n");
      out.write("\tvar end = Date(document.theForm.endingDateDaily.value);\t\r\n");
      out.write("\tif(start.getDay() != 0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("Report starting date must be Sunday!"));
      out.write("\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\ttemp = document.theForm.endingDateDaily.value;\r\n");
      out.write("\tvar end = new Date();\r\n");
      out.write("\tend.setDate(temp.substring(3, 5));\r\n");
      out.write("\tend.setMonth(temp.substring(0, 2) - 1);\r\n");
      out.write("\tend.setYear(temp.substring(6, 10));\r\n");
      out.write("\r\n");
      out.write("\tif(end.getDay() != 6)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("Report ending date must be Saturday!"));
      out.write("\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (start > end)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("Starting date must be prior to ending date"));
      out.write("\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tif (end.getTime() - start.getTime() > 518400000)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("You cannot extract data for more than one week"));
      out.write("\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function changeDisabled(){\r\n");
      out.write("\r\n");
      out.write("\t\tdocument.theForm.startingDateDaily.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.endingDateDaily.disabled = true;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* \r\n");
      out.write(" * StringParse(): Take a list of key-value as string and transform them to an array. ex: abcd=4&efgh=80  ==> stringElements[abcd]=4; stringElements[efgh]=80 \r\n");
      out.write(" * Parameters: tobeParsed. The string that will be parse\r\n");
      out.write(" * Return value: an associative array key-value\r\n");
      out.write(" */\r\n");
      out.write("function StringParse(tobeParsed)\r\n");
      out.write("{\r\n");
      out.write("\tstringElements = new Array();\r\n");
      out.write("\t\r\n");
      out.write("\tvar pairs = tobeParsed.split(\"&\");\t//split by the token\r\n");
      out.write("\t\r\n");
      out.write("\tfor (var i=0;i<pairs.length;i++)\t//For each pair, split by the =\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar pos = pairs[i].indexOf('=');\r\n");
      out.write("\t\tif (pos >= 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar argname = pairs[i].substring(0,pos);\r\n");
      out.write("\t\t\tvar value = pairs[i].substring(pos+1);\r\n");
      out.write("\t\t\tstringElements[argname] = value;\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\t\r\n");
      out.write("\treturn stringElements;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getRoutingScriptAndQueues(tenant_id)\r\n");
      out.write("{\r\n");
      out.write("\tvar rArray = new Array();\r\n");
      out.write("\tvar jsRSCripts = String( appletObj.getRoutingScripts(tenant_id, \"1\")  );\r\n");
      out.write("\tvar jsRSCRIPTArray = jsRSCripts.split(\"|\");\r\n");
      out.write("\tfor(var i = 0; i < jsRSCRIPTArray.length; i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(jsRSCRIPTArray[i].length != 0) \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tthisRScript = jsRSCRIPTArray[i].split(\",\");\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\trArray.push(thisRScript[1]);\r\n");
      out.write("\t\t\t//Get virtual queues in this script...\r\n");
      out.write("\t\t\tvar thisScriptText = String( appletObj.getRoutingScript(thisRScript[0]) );\r\n");
      out.write("\t\t\tsplitedString = thisScriptText.split('^');\r\n");
      out.write("\t\t\t//var rootNoddle;\r\n");
      out.write("\t\t\tfor(var j = 0; j < splitedString.length; j++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar curElement = splitedString[j];\t\t\r\n");
      out.write("\t\t\t\tmyElementTable = StringParse(curElement);\r\n");
      out.write("\t\t\t\tif(myElementTable['TYPE'] == 'AGENTPICKUP')\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\trArray.push(myElementTable['queueName']);\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//alert(rArray);\r\n");
      out.write("\treturn rArray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write(".style1 {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("    // Associate a default button with pressing the Enter key\r\n");
      out.write("\tfunction KeyDownHandler(btn)\r\n");
      out.write("    {\r\n");
      out.write("        // process only the Enter key\r\n");
      out.write("        if (event.keyCode == 13)\r\n");
      out.write("        {\r\n");
      out.write("            // cancel the default submit\r\n");
      out.write("            event.returnValue=false;\r\n");
      out.write("            event.cancel = true;\r\n");
      out.write("            // submit the form by programmatically clicking the specified button\r\n");
      out.write("            btn.click();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"sched_body\" onLoad=\"fillObjectCombo()\">\r\n");
      out.write("\t<div class=\"tab-pane\" id=\"tabPane1\">\r\n");
      out.write("\t<form name=\"theForm\" onKeyDown=\"KeyDownHandler(submit)\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\ttp1 = new WebFXTabPane( document.getElementById( \"tabPane1\" ) );\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<div class=\"tab-page\" id=\"tabGeneral\">\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend>\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\tvar vComplete =  normalizeString(QueryString('complete'));\r\n");
      out.write("\t\t\t\t\t\t\t//var vReport   =  normalizeString(QueryString('report');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tif (vComplete == 'no') {\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write(\"");
      out.print( pageData.getWord("Assign schedule"));
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\t\t}else if (vComplete ==  'yes'){\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write(\"");
      out.print( pageData.getWord("Review published schedule"));
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\t\t}else if(normalizeString(QueryString('report') ==  'yes')) {\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write(\"");
      out.print( pageData.getWord("Scheduled agents' report"));
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t</legend><br>\r\n");
      out.write("\r\n");
      out.write("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\"  width=\"69%\"  >\r\n");
      out.write("  <tr >\r\n");
      out.write("    <td valign=\"top\" width=\"28%\" style=\"border-right-style: none; border-right-width: 1; border-top-style: none; border-top-width: 1\" colspan=\"3\">\r\n");
      out.write("      <div>\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("\t<b>");
      out.print( pageData.getWord("Choose group"));
      out.write("</b>\r\n");
      out.write("    <br><br>    \r\n");
      out.write("    \r\n");
      out.write("      </div>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr height=\"45\">\r\n");
      out.write("  <script language=\"JavaScript\">\r\n");
      out.write("  var vValue = normalizeString(QueryString('type'));\r\n");
      out.write("\r\n");
      out.write("    document.write('<td width=\"34%\" valign=\"top\" style=\"border-left-style: none; border-left-width: 1; border-top-style: none; border-top-width: 1\" >')\r\n");
      out.write("    document.write('<select name=\"objects\">')\r\n");
      out.write("    document.write('</select>')\r\n");
      out.write("    document.write('</td>')\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write(" <td width=\"28%\" valign=\"top\" style=\"border-right-style: none; border-right-width: 1; border-top-style: none; border-top-width: 1\" >\r\n");
      out.write(" </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("\r\n");
      out.write("  <tr ><td height=\"20\">&nbsp;</td><td height=\"20\">&nbsp;</td><td height=\"20\">&nbsp;</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr height=\"26\" valign=\"top\" >\r\n");
      out.write("    \r\n");
      out.write("    <td width=\"38%\" style=\"border-top-style: none; border-top-width: 1\" >\r\n");
      out.write("     ");
      out.print( pageData.getWord("Starting date"));
      out.write("\r\n");
      out.write("    </td>\r\n");
      out.write("    <td width=\"28%\" style=\"border-right-style: none; border-right-width: 1; border-top-style: none; border-top-width: 1\" >\r\n");
      out.write("     ");
      out.print( pageData.getWord("Ending date"));
      out.write("\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write(" \r\n");
      out.write("  <tr>\r\n");
      out.write("   \r\n");
      out.write("   <td id=\"id_startingDateDaily\" valign=\"top\" width=\"34%\" style=\"border-left-style: none; border-left-width: 1; border-bottom-style:none; border-bottom-width:1\" >\r\n");
      out.write("   \t <input type=\"text\" size=\"20\" onFocus=\"showCalendar('',this,this,'','id_startingDateDaily',0,30,1);this.blur()\" name=\"startingDateDaily\" />\r\n");
      out.write("\r\n");
      out.write("    </td>\r\n");
      out.write("    <td id=\"id_endingDateDaily\" valign=\"top\" width=\"38%\" style=\"border-bottom-style: none; border-bottom-width: 1\">\r\n");
      out.write("     \t<input type=\"text\" size=\"20\" onFocus=\"showCalendar('',this,this,'','id_endingDateDaily',0,30,1);this.blur()\" name=\"endingDateDaily\"/>\r\n");
      out.write("    </td>\r\n");
      out.write("  <tr>\r\n");
      out.write("\r\n");
      out.write("   <td  style=\"border-left-style: none; border-left-width: 1; border-bottom-style: none; border-bottom-width: 1; border-top-style:none; border-top-width:1\" >&nbsp;\r\n");
      out.write("   </td>\r\n");
      out.write("   <td  style=\"border-bottom-style: none; border-bottom-width: 1; border-top-style:none; border-top-width:1\">&nbsp;\r\n");
      out.write("   </td>\r\n");
      out.write("   <td  valign\"top\"  align=\"right\" >\r\n");
      out.write("\t <input id=\"submit\" type=\"button\" value='");
      out.print( pageData.getWord("Submit"));
      out.write("' onClick=\"getRequestedPeriod()\">\r\n");
      out.write("\t \r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
 pageData.closeConnection(); 
      out.write("\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
