package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.*;
import aheevaManager.csvinterface.*;
import aheevaManager.ressources.*;
import java.text.*;
import aheevaManager.schedule.*;
import aheevaManager.ressources.*;
import java.util.*;
import jxl.*;

public final class inboundCalls1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/aheevaManager/Resources_pages/xc2_default_labels.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
    pageData.openConnection();

      out.write("\r\n");
      out.write("<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"xc2_default.css\" type=\"text/css\">\r\n");
      out.write("<LINK href=\"livestats.css\" \trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pagexc2Data = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pagexc2Data.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
pagexc2Data.openConnection();
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("// variables of labels;// \r\n");
      out.write("var phrase= new Array();\r\n");
      out.write("phrase[0]=\"");
      out.print( pagexc2Data.getWord("January"));
      out.write("\";\r\n");
      out.write("phrase[1]=\"");
      out.print( pagexc2Data.getWord("February"));
      out.write("\";\r\n");
      out.write("phrase[2]=\"");
      out.print( pagexc2Data.getWord("March"));
      out.write("\";\r\n");
      out.write("phrase[3]=\"");
      out.print( pagexc2Data.getWord("April"));
      out.write("\";\r\n");
      out.write("phrase[4]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";         \r\n");
      out.write("phrase[5]=\"");
      out.print( pagexc2Data.getWord("June"));
      out.write("\";\r\n");
      out.write("phrase[6]=\"");
      out.print( pagexc2Data.getWord("July"));
      out.write("\";\r\n");
      out.write("phrase[7]=\"");
      out.print( pagexc2Data.getWord("August"));
      out.write("\";\r\n");
      out.write("phrase[8]=\"");
      out.print( pagexc2Data.getWord("September"));
      out.write("\";\r\n");
      out.write("phrase[9]=\"");
      out.print( pagexc2Data.getWord("October"));
      out.write("\";\r\n");
      out.write("phrase[10]=\"");
      out.print( pagexc2Data.getWord("November"));
      out.write("\";\r\n");
      out.write("phrase[11]=\"");
      out.print( pagexc2Data.getWord("December"));
      out.write("\";\r\n");
      out.write("phrase[12]=\"");
      out.print( pagexc2Data.getWord("Jan"));
      out.write("\";\r\n");
      out.write("phrase[13]=\"");
      out.print( pagexc2Data.getWord("Feb"));
      out.write("\";\r\n");
      out.write("phrase[14]=\"");
      out.print( pagexc2Data.getWord("Mar"));
      out.write("\";\r\n");
      out.write("phrase[15]=\"");
      out.print( pagexc2Data.getWord("Apr"));
      out.write("\";\r\n");
      out.write("phrase[16]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";\r\n");
      out.write("phrase[17]=\"");
      out.print( pagexc2Data.getWord("Jun"));
      out.write("\";\r\n");
      out.write("phrase[18]=\"");
      out.print( pagexc2Data.getWord("Jul"));
      out.write("\";\r\n");
      out.write("phrase[19]=\"");
      out.print( pagexc2Data.getWord("Aug"));
      out.write("\";\r\n");
      out.write("phrase[20]=\"");
      out.print( pagexc2Data.getWord("Sep"));
      out.write("\";\r\n");
      out.write("phrase[21]=\"");
      out.print( pagexc2Data.getWord("Oct"));
      out.write("\";\r\n");
      out.write("phrase[22]=\"");
      out.print( pagexc2Data.getWord("Nov"));
      out.write("\";\r\n");
      out.write("phrase[23]=\"");
      out.print( pagexc2Data.getWord("Dec"));
      out.write("\";\r\n");
      out.write("phrase[24]=\"");
      out.print( pagexc2Data.getWord("Sunday"));
      out.write("\";\r\n");
      out.write("phrase[25]=\"");
      out.print( pagexc2Data.getWord("Monday"));
      out.write("\";\r\n");
      out.write("phrase[26]=\"");
      out.print( pagexc2Data.getWord("Tuesday"));
      out.write("\";\r\n");
      out.write("phrase[27]=\"");
      out.print( pagexc2Data.getWord("Wednesday"));
      out.write("\";\r\n");
      out.write("phrase[28]=\"");
      out.print( pagexc2Data.getWord("Thursday"));
      out.write("\";\r\n");
      out.write("phrase[29]=\"");
      out.print( pagexc2Data.getWord("Friday"));
      out.write("\";\r\n");
      out.write("phrase[30]=\"");
      out.print( pagexc2Data.getWord("Saturday"));
      out.write("\";\r\n");
      out.write("phrase[31]=\"");
      out.print( pagexc2Data.getWord("Sun"));
      out.write("\";\r\n");
      out.write("phrase[32]=\"");
      out.print( pagexc2Data.getWord("Mon"));
      out.write("\";\r\n");
      out.write("phrase[33]=\"");
      out.print( pagexc2Data.getWord("Tue"));
      out.write("\";\r\n");
      out.write("phrase[34]=\"");
      out.print( pagexc2Data.getWord("Wed"));
      out.write("\";\r\n");
      out.write("phrase[35]=\"");
      out.print( pagexc2Data.getWord("Thu"));
      out.write("\";\r\n");
      out.write("phrase[36]=\"");
      out.print( pagexc2Data.getWord("Fri"));
      out.write("\";\r\n");
      out.write("phrase[37]=\"");
      out.print( pagexc2Data.getWord("Sat"));
      out.write("\";\r\n");
      out.write("phrase[38]=\"");
      out.print( pagexc2Data.getWord("Su"));
      out.write("\";\r\n");
      out.write("phrase[39]=\"");
      out.print( pagexc2Data.getWord("Mo"));
      out.write("\";\r\n");
      out.write("phrase[40]=\"");
      out.print( pagexc2Data.getWord("Tu"));
      out.write("\";\r\n");
      out.write("phrase[41]=\"");
      out.print( pagexc2Data.getWord("We"));
      out.write("\";\r\n");
      out.write("phrase[42]=\"");
      out.print( pagexc2Data.getWord("Th"));
      out.write("\";\r\n");
      out.write("phrase[43]=\"");
      out.print( pagexc2Data.getWord("Fr"));
      out.write("\";\r\n");
      out.write("phrase[44]=\"");
      out.print( pagexc2Data.getWord("Sa"));
      out.write("\";\r\n");
      out.write("phrase[45]=\"");
      out.print( pagexc2Data.getWord(" Today "));
      out.write("\";\r\n");
      out.write("phrase[46]=\"");
      out.print( pagexc2Data.getWord("Clear"));
      out.write("\";\r\n");
      out.write("phrase[47]=\"");
      out.print( pagexc2Data.getWord("Back"));
      out.write("\";\r\n");
      out.write("phrase[48]=\"");
      out.print( pagexc2Data.getWord("Close"));
      out.write("\";\r\n");
      out.write("phrase[49]=\"");
      out.print( pagexc2Data.getWord("Reset"));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 pagexc2Data.closeConnection(); 
      out.write("\r\n");
      out.write("<!-- Start Tab pane -->\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"tab_luna.css\" />\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style_2.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\" href=\"slider/css/luna.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t100px;\r\n");
      out.write("}\r\n");
      out.write("html, body {\r\n");
      out.write("\t/*background:\tThreeDFace;*/\r\n");
      out.write("}\r\n");
      out.write("form {\r\n");
      out.write("\tmargin:\t\t0;\r\n");
      out.write("\tpadding:\t0;\r\n");
      out.write("}\r\n");
      out.write("/* over ride styles from webfxlayout */\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:\t\t10px;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("\theight:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 {\r\n");
      out.write("\ttext-align:\tcenter;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 a {\r\n");
      out.write("\tdisplay:\tinline;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control a:hover {\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../Resources_pages/tabpane.js\"></script>\r\n");
      out.write("<!-- End Tab Pane -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Calendrier début -->\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"xc2_default.js\"></script>\r\n");
      out.write("<script language=\"javascript\">xcAutoHide=1000;</script>\r\n");
      out.write("<script language=\"javascript\" src=\"xc2_inpage.js\"></script>\r\n");
      out.write("<!-- Calendrier fin -->\r\n");
      out.write("<script language=\"JavaScript\" src=\"jsUtil.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var vValue = normalizeString(QueryString('type'));\r\n");
      out.write("  var tenant_dbid = normalizeString(QueryString('tenant_dbid'));\r\n");
      out.write("\r\n");
      out.write("function loadAgent(){\r\n");
      out.write("\r\n");
      out.write("  while(document.theForm.objects.length > 0){\r\n");
      out.write("    document.theForm.objects.options[0]= null;\r\n");
      out.write("  }\r\n");
      out.write("  var jsAgents;\r\n");
      out.write("  var myOption;\r\n");
      out.write("  if (ckbox.checked == true)\r\n");
      out.write("  {\r\n");
      out.write("    //Get all agents name\r\n");
      out.write("    var agents = String( appletObj.getAgentsByName(tenant_dbid) );\r\n");
      out.write("    jsAgents = agents + \"\";\r\n");
      out.write("    arrayAgents = jsAgents.split(\"|\");\r\n");
      out.write("    for (j = 0; j <arrayAgents.length; j++){\r\n");
      out.write("\t\tvar iStartPos = arrayAgents[j].indexOf('[');\r\n");
      out.write("\t\tvar iEndPos   = arrayAgents[j].indexOf(']');\r\n");
      out.write("\t\tvar login\t  = arrayAgents[j].substr(iStartPos+1,iEndPos-iStartPos-1);\r\n");
      out.write("\t\tvar name = login+'['+arrayAgents[j].substr(0,iStartPos)+']';\r\n");
      out.write("\t\tif (document.theForm.viewckbox.checked == false)\t  \t\t// show agents name as : firstname, lastname[login]\r\n");
      out.write("      \t\tmyOption = new Option(arrayAgents [j],login)\r\n");
      out.write("\t\telse\t\t\t\t\t\t\t\t\t// show agents name as : login[firstname, lastname]\r\n");
      out.write("\t\t\tmyOption = new Option(name,login)\r\n");
      out.write("\t\tvar optionPos = document.theForm.objects.options.length;\r\n");
      out.write("\t\tdocument.theForm.objects.options[optionPos]= myOption;\r\n");
      out.write("    }\r\n");
      out.write("  } else {\r\n");
      out.write("    //Get all active Agents by Name\r\n");
      out.write("    var agents = String( appletObj.getAgentsByNameActif(tenant_dbid) );\r\n");
      out.write("    jsAgents = agents + \"\";\r\n");
      out.write("    arrayAgents = jsAgents.split(\"|\");\r\n");
      out.write("    for (j = 0; j <arrayAgents.length; j++){\r\n");
      out.write("      var iStartPos = arrayAgents[j].indexOf('[');\r\n");
      out.write("      var iEndPos   = arrayAgents[j].indexOf(']');\r\n");
      out.write("      var login\t  = arrayAgents[j].substr(iStartPos+1,iEndPos-iStartPos-1);\r\n");
      out.write("\t  var name = login+'['+arrayAgents[j].substr(0,iStartPos)+']';\r\n");
      out.write("\t  if (document.theForm.viewckbox.checked == false)\r\n");
      out.write("      \tmyOption = new Option(arrayAgents [j],login)\r\n");
      out.write("\t  else\r\n");
      out.write("\t    myOption = new Option(name,login)\r\n");
      out.write("     var optionPos = document.theForm.objects.options.length;\r\n");
      out.write("      document.theForm.objects.options[optionPos]= myOption;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("  //alert(jsAgents)\r\n");
      out.write("  sortSelect(document.theForm.objects);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sortSelect(obj)\r\n");
      out.write("{\r\n");
      out.write("\tvar o = new Array();\r\n");
      out.write("\tif (obj.options==null) { return; }\r\n");
      out.write("\tfor (var i=0; i<obj.options.length; i++) {\r\n");
      out.write("\t\to[o.length] = new Option( obj.options[i].text, obj.options[i].value, obj.options[i].defaultSelected, obj.options[i].selected) ;\r\n");
      out.write("\t\t}\r\n");
      out.write("\tif (o.length==0) { return; }\r\n");
      out.write("\tif(document.theForm.viewckbox.checked == false){\r\n");
      out.write("\t\to = o.sort(\r\n");
      out.write("\t\t\tfunction(a,b) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif ((a.text+\"\") < (b.text+\"\")) { return -1; }\r\n");
      out.write("\t\t\t\t\tif ((a.text+\"\") > (b.text+\"\")) { return 1; }\r\n");
      out.write("\t\t\t\t\treturn 0;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("     }\r\n");
      out.write("    else{\r\n");
      out.write("\t\to = o.sort(\r\n");
      out.write("\t\t\tfunction(a,b) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (parseInt(a.value) < parseInt(b.value)) { return -1; }\r\n");
      out.write("\t\t\t\t\tif (parseInt(a.value) > parseInt(b.value)) { return 1; }\r\n");
      out.write("\t\t\t\t\treturn 0;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("    }\r\n");
      out.write("\tfor (var i=0; i<o.length; i++) {\r\n");
      out.write("\t\tobj.options[i] = new Option(o[i].text, o[i].value, o[i].defaultSelected, o[i].selected);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function changeAgentListView()\r\n");
      out.write("{\r\n");
      out.write("  var textvalue,iStartPos,iEndPos,login,name,newtextvalue;\r\n");
      out.write("  var o = new Array();\r\n");
      out.write("  if (document.theForm.viewckbox.checked == true)\r\n");
      out.write("  {\r\n");
      out.write("    for (j = 0; j <document.theForm.objects.options.length; j++){\r\n");
      out.write("\t  textvalue = document.theForm.objects.options[j].text\r\n");
      out.write("\t  //alert(textvalue + '..'+objects.options[j].value)\r\n");
      out.write("\t  if(textvalue.length > 0){\r\n");
      out.write("\t\t   iStartPos = textvalue.indexOf('[');\r\n");
      out.write("\t\t   iEndPos   = textvalue.indexOf(']');\r\n");
      out.write("\t\t   login\t = textvalue.substr(iStartPos+1,iEndPos-iStartPos-1);\r\n");
      out.write("\t\t   name      = textvalue.substr(0,iStartPos);\r\n");
      out.write("\t   }\r\n");
      out.write("\t   newtextvalue = login +'['+name +']'\r\n");
      out.write("       document.theForm.objects.options[j].text=newtextvalue\r\n");
      out.write("\t   //alert(document.theForm.objects.options[j].text)\r\n");
      out.write("\t   document.theForm.objects.options[j] = new Option( newtextvalue, login, document.theForm.objects.options[j].defaultSelected, document.theForm.objects.options[j].selected) ;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("  } else {\r\n");
      out.write("    for (j = 0; j <document.theForm.objects.options.length; j++){\r\n");
      out.write("\t  textvalue = document.theForm.objects.options[j].text\r\n");
      out.write("\t  //alert(textvalue + '..'+document.theForm.objects.options[j].value)\r\n");
      out.write("\t  if(textvalue.length > 0){\r\n");
      out.write("\t\t   iStartPos = textvalue.indexOf('[');\r\n");
      out.write("\t\t   iEndPos   = textvalue.indexOf(']');\r\n");
      out.write("\t\t   name\t = textvalue.substr(iStartPos+1,iEndPos-iStartPos-1);\r\n");
      out.write("\t\t   login      = textvalue.substr(0,iStartPos);\r\n");
      out.write("\t   }\r\n");
      out.write("\t   newtextvalue = name +'['+login +']'\r\n");
      out.write("       document.theForm.objects.options[j].text=newtextvalue\r\n");
      out.write("\t   //alert(document.theForm.objects.options[j].text)\r\n");
      out.write("\t   document.theForm.objects.options[j] = new Option( newtextvalue, login, document.theForm.objects.options[j].defaultSelected, document.theForm.objects.options[j].selected) ;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  sortSelect(document.theForm.objects);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fillObjectCombo()\r\n");
      out.write("{\r\n");
      out.write("     if(vValue=='Inbound'){\r\n");
      out.write("\t \tvar agentGroups = String( appletObj.getAgentGroupByName(tenant_dbid) );\r\n");
      out.write("\t\tvar jsAgentGroups = agentGroups + \"\";\r\n");
      out.write("    \tarrayGroups = jsAgentGroups.split(\"|\");\r\n");
      out.write("    \tfor (j = 0; j <arrayGroups.length; j++)\r\n");
      out.write("\t\t{\r\n");
      out.write("    \t\tmyOption = new Option(arrayGroups[j],arrayGroups[j])\r\n");
      out.write("\t\t\toptionPos = document.theForm.objects.options.length\t\t\t\t\r\n");
      out.write("\t\t\tdocument.theForm.objects.options[optionPos]=myOption\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if(document.theForm.objects.options.length >= 10)\r\n");
      out.write("\t   \tdocument.theForm.objects.size = 10;\r\n");
      out.write("\telse\r\n");
      out.write("\t\tdocument.theForm.objects.size = document.theForm.objects.options.length;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getSelectedObjects()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\tselectedObjects = new Array()\r\n");
      out.write("\tfor (i=0;i<document.theForm.objects.options.length;i++) {\r\n");
      out.write("  \t\tif (document.theForm.objects.options[i].selected) {\r\n");
      out.write("  \t\t\tselectedObjects[selectedObjects.length]=document.theForm.objects.options[i].value;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t}\r\n");
      out.write("    var url = '';\r\n");
      out.write("\tif (selectedObjects.length > 0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\turl= escape(selectedObjects.join('/'))\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\treturn url;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getSelectedTeams(){\r\n");
      out.write("var url = '';\r\n");
      out.write("\r\n");
      out.write("\t\tselectedTeams = new Array()\r\n");
      out.write("\t\tfor (i=teams.selectedIndex;i<teams.options.length;i++) {\r\n");
      out.write("  \t\t\tif (teams.options[i].selected) {\r\n");
      out.write("  \t\t\t\tselectedTeams[selectedTeams.length]=teams.options[i].value;\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t}\r\n");
      out.write("\t\tif (selectedObjects.length > 0){\r\n");
      out.write("\t\t\turl= escape(selectedObjects.join('/'))\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn url;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function saveAdhViewData()\r\n");
      out.write("{\r\n");
      out.write("\tvar selectObjects;\r\n");
      out.write("\tif(document.theForm.objects.selectedIndex == -1)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//alert(\"Please select at least one object\");\r\n");
      out.write("\t\t//return false;\r\n");
      out.write("\t\tselectObjects='All';\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t  selectObjects = getSelectedObjects();\r\n");
      out.write("\t//appletObj.m_firstLoad = true;\r\n");
      out.write("        appletObj.updateRTAViewInfo(document.theForm.startTime.value, document.theForm.endTime.value, document.theForm.spacing.value,selectObjects);\r\n");
      out.write("\tif(document.theForm.saveButton.disabled == false)\r\n");
      out.write("\t\tdocument.theForm.saveButton.disabled = true;\r\n");
      out.write("\twindow.top.main.rtop.stats.firstLoad = true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sendRTAStartRequest()\r\n");
      out.write("{\r\n");
      out.write("\tvar selectObjects;\r\n");
      out.write("\tif(document.theForm.objects.selectedIndex == -1)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//alert(\"Please select at least one object\");\r\n");
      out.write("\t\t//return false;\r\n");
      out.write("\t\tselectObjects='All';\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t  selectObjects = getSelectedObjects();\r\n");
      out.write("\tappletObj.sendRTAStartReq(tenant_dbid,selectObjects);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sendRTAStopRequest()\r\n");
      out.write("{\r\n");
      out.write("   \tvar selectObjects;\r\n");
      out.write("\tif(document.theForm.objects.selectedIndex == -1)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//alert(\"Please select at least one object\");\r\n");
      out.write("\t\t//return false;\r\n");
      out.write("\t\tselectObjects='All';\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t  selectObjects = getSelectedObjects();\r\n");
      out.write("\tappletObj.sendRTAStopReq(tenant_dbid,selectObjects);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updateStartButton()\r\n");
      out.write("{\r\n");
      out.write("\t if(document.theForm.startButton.disabled == true){\r\n");
      out.write("\t\tdocument.theForm.startButton.disabled = false;\r\n");
      out.write("\t\tdocument.theForm.stopButton.disabled = true;\r\n");
      out.write("\t  }\r\n");
      out.write("\t else{\r\n");
      out.write("\t\tdocument.theForm.startButton.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.stopButton.disabled = false;\r\n");
      out.write("\t }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updateStopButton()\r\n");
      out.write("{\r\n");
      out.write(" \tif(document.theForm.stopButton.disabled == true){\r\n");
      out.write("\t\tdocument.theForm.startButton.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.stopButton.disabled = false;\r\n");
      out.write("\t }\r\n");
      out.write(" else{\r\n");
      out.write("\t\tdocument.theForm.startButton.disabled = false;\r\n");
      out.write("\t\tdocument.theForm.stopButton.disabled = true;\r\n");
      out.write("\t }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function selectAll()\r\n");
      out.write("{\r\n");
      out.write("  for (j = 0; j <document.theForm.objects.options.length; j++)\r\n");
      out.write("\t  document.theForm.objects.options[j].selected = true;  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function unSelectAll()\r\n");
      out.write("{\r\n");
      out.write("  for (j = 0; j <document.theForm.objects.options.length; j++)\r\n");
      out.write("\t  document.theForm.objects.options[j].selected = false;  \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getRequestedReport()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\tvar destination = '';\r\n");
      out.write("\tif(document.theForm.period[1].checked){\r\n");
      out.write("\t\tif(document.theForm.startingDateDaily.value.length == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"");
      out.print( pageData.getWord("Please enter a starting date"));
      out.write("\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.theForm.endingDateDaily.value.length == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"");
      out.print( pageData.getWord("Please enter an ending date"));
      out.write("\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t/*\r\n");
      out.write("\tif(document.theForm.objects.selectedIndex == -1)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Please select at least one object\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t*/\r\n");
      out.write("\tif(dateChecker() == false)\r\n");
      out.write("\t{\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(!IsPhoneNumber(document.theForm.phoneNumber.value))\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("Please enter a valid phone number"));
      out.write("\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tif(validation(document.theForm.phoneNumber.value)==0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("Invalid use of character"));
      out.write("\");\r\n");
      out.write("\t\tdocument.theForm.phoneNumber.focus();\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write(" \tif(vValue == 'Inbound'){\r\n");
      out.write("\t\tdestination = \"../jsp/inbound.jsp\"\r\n");
      out.write("\t}\r\n");
      out.write("\tdestination += \"?startingDateDaily=\"\r\n");
      out.write("\tdestination += document.theForm.startingDateDaily.value;\r\n");
      out.write("\tdestination +=\"&endingDateDaily=\";\r\n");
      out.write("\tdestination += document.theForm.endingDateDaily.value;\r\n");
      out.write(" \tdestination +=\"&spacing=\";\r\n");
      out.write("\tdestination += document.theForm.spacing.value;\r\n");
      out.write("\tdestination +=\"&dnis=\";\r\n");
      out.write("\tdestination += document.theForm.phoneNumber.value;\r\n");
      out.write("\r\n");
      out.write("\tdestination +=\"&starting_month_monthly=\";\r\n");
      out.write("\tdestination += document.theForm.starting_month_monthly.value\r\n");
      out.write("\tdestination +=\"&starting_year_monthly=\";\r\n");
      out.write("\tdestination += document.theForm.starting_year_monthly.value\r\n");
      out.write("\t//destination +=\"&ending_month_monthly=\";\r\n");
      out.write("\t//destination += document.theForm.ending_month_monthly.value\r\n");
      out.write("\t//destination +=\"&ending_year_monthly=\";\r\n");
      out.write("\t//destination += document.theForm.ending_year_monthly.value\r\n");
      out.write("\r\n");
      out.write("\tdestination +=\"&reportType=\";\r\n");
      out.write("\t if(document.theForm.period[0].checked){\r\n");
      out.write("\t\tdestination += \"Monthly\";\r\n");
      out.write("\t } else if(document.theForm.period[1].checked){\r\n");
      out.write("\t\tdestination += \"Daily\";\r\n");
      out.write("\t }\r\n");
      out.write("     destination += \"&lang=\"+lang;\r\n");
      out.write("    //alert(\"before open window !!!\");\r\n");
      out.write("\t//alert(destination);\r\n");
      out.write("\t window.open(destination);\r\n");
      out.write("\t//document.location = destination;\r\n");
      out.write("}\r\n");
      out.write("function dateChecker()\r\n");
      out.write("{\r\n");
      out.write("\tif(document.theForm.period[1].checked){// daily\r\n");
      out.write("\t\tvar startDate=new Date(document.theForm.startingDateDaily.value);\r\n");
      out.write("\t\tvar endDate = new Date(document.theForm.endingDateDaily.value);\r\n");
      out.write("\t\tif(endDate < startDate)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"");
      out.print( pageData.getWord("Your ending date cannnot be smaller than your starting date"));
      out.write("\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("  else if (document.theForm.period[0].checked)\r\n");
      out.write("  { // monthly\r\n");
      out.write("\t\tvar startDate='01-'+ document.theForm.starting_month_monthly.value + '-' + document.theForm.starting_year_monthly.value;\r\n");
      out.write("\t\tstartDate = new Date(startDate);\r\n");
      out.write("\t\t//var endDate ='01-'+  document.theForm.starting_month_monthly.value+ '-' + document.theForm.starting_year_monthly.value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//endDate = new Date(endDate);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//var endDate ='01-'+  document.theForm.ending_month_monthly.value+ '-' + document.theForm.ending_year_monthly.value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//endDate = new Date(endDate);\r\n");
      out.write("\r\n");
      out.write("\t\t//if(endDate < startDate || endDate > startDate)*/\r\n");
      out.write("\t\t/*if(endDate < startDate)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(MultiArray[\"Your ending month-year must be the same as your starting month-year!\"][lang]);\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}*/\r\n");
      out.write("\r\n");
      out.write("}/*else if (period[0].checked){// yearly\r\n");
      out.write("    var startDate=starting_year_yearly.value ;\r\n");
      out.write("\tvar endDate = ending_year_yearly.value ;\r\n");
      out.write("\r\n");
      out.write("\tif(endDate < startDate)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Your ending date cannnot be smaller than your starting date!!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}*/\r\n");
      out.write("\r\n");
      out.write("return true;\r\n");
      out.write("}\r\n");
      out.write("/*-------- 2006-16-06\r\n");
      out.write("function setEndingMonth()\r\n");
      out.write("{\r\n");
      out.write("\tif(document.theForm.period[0].checked)\r\n");
      out.write("\t{\r\n");
      out.write("\t  for (i=0; i<ending_month_monthly.options.length; i++)\r\n");
      out.write("\t\t  if(ending_month_monthly.options[i].value == starting_month_monthly.value)\r\n");
      out.write("\t\t\tending_month_monthly.options[i].selected = true;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("*/\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function changeDisabled(){\r\n");
      out.write("\tif(document.theForm.period[0].checked){\r\n");
      out.write("\t\tdocument.theForm.startingDateDaily.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.endingDateDaily.disabled = true;\r\n");
      out.write("\t\t/*starting_year_yearly.disabled = false;\r\n");
      out.write("\t\tending_year_yearly.disabled = false;*/\r\n");
      out.write("\t\tdocument.theForm.starting_month_monthly.disabled = false;\r\n");
      out.write("\t\tdocument.theForm.starting_year_monthly.disabled = false;\r\n");
      out.write("\t\t//document.theForm.ending_month_monthly.disabled = false;\r\n");
      out.write("\t\t//document.theForm.ending_year_monthly.disabled = false;\r\n");
      out.write("\t}/* else if(period[1].checked){\r\n");
      out.write("\t\tstartingDateDaily.disabled = true;\r\n");
      out.write("\t\tendingDateDaily.disabled = true;\r\n");
      out.write("\t\tstarting_year_yearly.disabled = true;\r\n");
      out.write("\t\tending_year_yearly.disabled = true;\r\n");
      out.write("\t\tstarting_month_monthly.disabled = false;\r\n");
      out.write("\t\tstarting_year_monthly.disabled = false;\r\n");
      out.write("\t\tending_month_monthly.disabled = false;\r\n");
      out.write("\t\tending_year_monthly.disabled = false;\r\n");
      out.write("\t} else*/\r\n");
      out.write("\tif(document.theForm.period[1].checked){\r\n");
      out.write("\t\tdocument.theForm.startingDateDaily.disabled = false;\r\n");
      out.write("\t\tdocument.theForm.endingDateDaily.disabled = false;\r\n");
      out.write("\t\t/*starting_year_yearly.disabled = true;\r\n");
      out.write("\t\tending_year_yearly.disabled = true;*/\r\n");
      out.write("\t\tdocument.theForm.starting_month_monthly.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.starting_year_monthly.disabled = true;\r\n");
      out.write("\t\t//document.theForm.ending_month_monthly.disabled = true;\r\n");
      out.write("\t\t//document.theForm.ending_year_monthly.disabled = true;\r\n");
      out.write("\t}\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(" function enableUpdateButton()\r\n");
      out.write(" {\r\n");
      out.write("     var vValue = normalizeString(QueryString('type'));\r\n");
      out.write(" \t if (vValue == 'AgentGroupsRTA'){\r\n");
      out.write("\t    document.theForm.saveButton.value = 'Update';\r\n");
      out.write("\t\tdocument.theForm.saveButton.disabled = false;\r\n");
      out.write("\t }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write(" function setDefaultValue()\r\n");
      out.write(" {\r\n");
      out.write("     var vValue = normalizeString(QueryString('type'));\r\n");
      out.write("\r\n");
      out.write(" \t if (vValue == 'AgentGroupsRTA' || vValue == 'Agents'){\r\n");
      out.write("\t \r\n");
      out.write("        \tfor (j = 0; j <document.theForm.startTime.length; j++){\r\n");
      out.write("\t\t   \t\tif(document.theForm.startTime.options[j].value == String( appletObj.m_adh_start_time ) )\r\n");
      out.write("\t\t\t\t\t{document.theForm.startTime.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\t break;}\r\n");
      out.write("        \t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor (j = 0; j <document.theForm.endTime.length; j++){\r\n");
      out.write("\t\t   \t\tif(document.theForm.endTime.options[j].value == String( appletObj.m_adh_end_time ) )\r\n");
      out.write("\t\t\t\t\t{document.theForm.endTime.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\t break;\r\n");
      out.write("\t\t\t\t\t }\r\n");
      out.write("        \t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor (j = 0; j <document.theForm.spacing.length; j++){\r\n");
      out.write("\t\t   \t\tif(document.theForm.spacing.options[j].value == String( appletObj.m_adh_spacing ))\r\n");
      out.write("\t\t\t\t\t{document.theForm.spacing.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\t break;\r\n");
      out.write("\t\t\t\t\t }\r\n");
      out.write("        \t}        \t\r\n");
      out.write("\t\t\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\tif(vValue == 'Agents'){\r\n");
      out.write("\t\tvar thetime =new Date();\r\n");
      out.write("\t\tvar thisYear = thetime.getYear();\r\n");
      out.write("\t\tvar thisMonth =thetime.getMonth()+1;\r\n");
      out.write("\t    \r\n");
      out.write("\t\tfor (j = 0; j <document.theForm.starting_year_monthly.length; j++){\r\n");
      out.write("\t\t\tif(document.theForm.starting_year_monthly.options[j].value == thisYear)\r\n");
      out.write("\t\t\t\t{document.theForm.starting_year_monthly.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfor (j = 0; j <document.theForm.starting_month_monthly.length; j++){\r\n");
      out.write("\t\t\tif(document.theForm.starting_month_monthly.options[j].value == thisMonth)\r\n");
      out.write("\t\t\t\t{document.theForm.starting_month_monthly.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t    \r\n");
      out.write("\t\tfor (j = 0; j <document.theForm.ending_year_monthly.length; j++){\r\n");
      out.write("\t\t\tif(document.theForm.ending_year_monthly.options[j].value == thisYear)\r\n");
      out.write("\t\t\t\t{document.theForm.ending_year_monthly.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("/*------- 2006-16-06    \r\n");
      out.write("\t\tfor (j = 0; j <document.theForm.ending_month_monthly.length; j++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(document.theForm.ending_month_monthly.options[j].value == thisMonth)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\tdocument.theForm.ending_month_monthly.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("*/\t\t\r\n");
      out.write("\t}\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write(".style1 {\r\n");
      out.write("    font-family:Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("    // Associate a default button with pressing the Enter key\r\n");
      out.write("\tfunction KeyDownHandler(btn)\r\n");
      out.write("    {\r\n");
      out.write("        // process only the Enter key\r\n");
      out.write("        if (event.keyCode == 13)\r\n");
      out.write("        {\r\n");
      out.write("            // cancel the default submit\r\n");
      out.write("            event.returnValue=false;\r\n");
      out.write("            event.cancel = true;\r\n");
      out.write("            // submit the form by programmatically clicking the specified button\r\n");
      out.write("            btn.click();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<!-- onLoad=\"fillObjectCombo()\"-->\r\n");
      out.write("<body  class=\"rep_body\">\r\n");
      out.write("\t<div class=\"tab-pane\" id=\"tabPane1\">\r\n");
      out.write("<form name=\"theForm\" onKeyDown=\"KeyDownHandler(submit)\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\ttp1 = new WebFXTabPane( document.getElementById( \"tabPane1\" ) );\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<div class=\"tab-page\" id=\"tabGeneral\">\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t<legend id=\"caption\">\r\n");
      out.write("\t\t\t\t\t<script language=\"JavaScript\">\r\n");
      out.write("    \t\t\t\tvar vValue = normalizeString(QueryString('type'));\r\n");
      out.write("    \t\t\t\tif (vValue == 'Inbound'){\r\n");
      out.write("       \t\t\t\t\tdocument.write(\"");
      out.print( pageData.getWord("Inbound call report"));
      out.write("\");\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t\t</script>\r\n");
      out.write("\t\t\t\t</legend>\r\n");
      out.write("\r\n");
      out.write("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse; margin-top:10px;\"  width=\"75%\" align=\"left\">\r\n");
      out.write("  \r\n");
      out.write("   <tr>\r\n");
      out.write("     <td  style=\"border-left-style: none; border-left-width: 1; border-bottom-style: none; border-bottom-width: 1; border-top-style:none; border-top-width:1\" >&nbsp;&nbsp;&nbsp;");
      out.print( pageData.getWord("Phone number"));
      out.write(" </td>\r\n");
      out.write("     <td  style=\"border-bottom-style: none; border-bottom-width: 1; border-top-style:none; border-top-width:1\">\r\n");
      out.write("     <input type=\"text\" name=\"phoneNumber\" size=\"20\"> </td>\r\n");
      out.write("     <td colspan=\"2\"  style=\"border-left-style: none; border-left-width: 1; border-bottom-style: none; border-bottom-width: 1; border-top-style:none; border-top-width:1\" ></td>\r\n");
      out.write("     <td  style=\"border-bottom-style: none; border-bottom-width: 1; border-top-style:none; border-top-width:1\"></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr><td height=\"20\">&nbsp;</td>\r\n");
      out.write("   <tr>\r\n");
      out.write("     <td  style=\"border-left-style: none; border-left-width: 1; border-bottom-style: none; border-bottom-width: 1; border-top-style:none; border-top-width:1\" >&nbsp;&nbsp;&nbsp;");
      out.print( pageData.getWord("Spacing (min)"));
      out.write("</td>\r\n");
      out.write("     <td  style=\"border-bottom-style: none; border-bottom-width: 1; border-top-style:none; border-top-width:1\">\r\n");
      out.write("\t <select name=\"spacing\" onChange=\"enableUpdateButton()\" >\r\n");
      out.write("       <!--<option value=\"\"></option>-->     \r\n");
      out.write("      <option value=\"15\">15</option>\r\n");
      out.write("       <option value=\"30\" selected>30</option>\r\n");
      out.write("       <option value=\"60\">60</option>\r\n");
      out.write("       <!--<option value=\"120\">120</option>--> \r\n");
      out.write("     </select></td>\r\n");
      out.write("     <td colspan=\"2\"  style=\"border-left-style: none; border-left-width: 1; border-bottom-style: none; border-bottom-width: 1; border-top-style:none; border-top-width:1\" ></td>\r\n");
      out.write("     <td  style=\"border-bottom-style: none; border-bottom-width: 1; border-top-style:none; border-top-width:1\"></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   \r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr height=\"20\" valign=\"top\" >\r\n");
      out.write("     <td >&nbsp;</td>\r\n");
      out.write("   </tr>\r\n");
      out.write("  <tr >\r\n");
      out.write("    <td width=\"34%\" style=\"border-left-style: none; border-left-width: 1; border-top-style: none; border-top-width: 1\" >\r\n");
      out.write("     <b>&nbsp;&nbsp;&nbsp;");
      out.print( pageData.getWord("Report type"));
      out.write("</b>\r\n");
      out.write("    </td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("  <tr>\r\n");
      out.write("   <td>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("   \t<input name=\"period\" type=\"radio\" value=\"monthly\" onClick=\"changeDisabled()\">&nbsp;");
      out.print( pageData.getWord("Monthly"));
      out.write("\r\n");
      out.write("   </td>\r\n");
      out.write("   <td valign=\"top\" width=\"34%\" style=\"border-left-style: none; border-left-width: 1; border-bottom-style:none; border-bottom-width:1\" >\r\n");
      out.write("     <select name=\"starting_month_monthly\" disabled=\"true\">\r\n");
      out.write("    \t\t<option value=\"01\">01</option>\r\n");
      out.write("    \t\t<option value=\"02\">02</option>\r\n");
      out.write("    \t\t<option value=\"03\">03</option>\r\n");
      out.write("\t\t\t<option value=\"04\">04</option>\r\n");
      out.write("\t\t\t<option value=\"05\">05</option>\r\n");
      out.write("\t\t\t<option value=\"06\">06</option>\r\n");
      out.write("\t\t\t<option value=\"07\">07</option>\r\n");
      out.write("\t\t\t<option value=\"08\">08</option>\r\n");
      out.write("\t\t\t<option value=\"09\">09</option>\r\n");
      out.write("\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("    </select>\r\n");
      out.write("\t <select name=\"starting_year_monthly\" disabled=\"true\">\r\n");
      out.write("\t\t<option value=\"2004\">2004</option>\r\n");
      out.write("\t\t<option value=\"2005\">2005</option>\r\n");
      out.write("\t\t<option value=\"2006\">2006</option>\r\n");
      out.write("\t\t<option value=\"2007\">2007</option>\r\n");
      out.write("\t\t<option value=\"2008\" selected>2008</option>\r\n");
      out.write("\t\t<option value=\"2009\">2009</option>\r\n");
      out.write("\t\t<option value=\"2010\">2010</option>\r\n");
      out.write("\t\t<option value=\"2011\">2011</option>\r\n");
      out.write("\t\t<option value=\"2012\">2012</option>\r\n");
      out.write("\t\t<option value=\"2013\">2013</option>\r\n");
      out.write("\t\t<option value=\"2014\">2014</option>\r\n");
      out.write("\t\t<option value=\"2015\">2015</option>\r\n");
      out.write("    </select>\r\n");
      out.write("\t</td> \r\n");
      out.write("\t<!--\r\n");
      out.write("    <td valign=\"top\" width=\"38%\" style=\"border-bottom-style: none; border-bottom-width: 1\">\r\n");
      out.write("     <select name=\"ending_month_monthly\" disabled=\"false\">\r\n");
      out.write("    \t\t<option value=\"01\">01</option>\r\n");
      out.write("    \t\t<option value=\"02\">02</option>\r\n");
      out.write("    \t\t<option value=\"03\">03</option>\r\n");
      out.write("\t\t\t<option value=\"04\">04</option>\r\n");
      out.write("\t\t\t<option value=\"05\">05</option>\r\n");
      out.write("\t\t\t<option value=\"06\">06</option>\r\n");
      out.write("\t\t\t<option value=\"07\">07</option>\r\n");
      out.write("\t\t\t<option value=\"08\">08</option>\r\n");
      out.write("\t\t\t<option value=\"09\">09</option>\r\n");
      out.write("\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("    </select>\r\n");
      out.write("\t <select name=\"ending_year_monthly\" disabled=\"false\">\r\n");
      out.write("    \t\t<option value=\"2004\">2004</option>\r\n");
      out.write("    \t\t<option value=\"2005\">2005</option>\r\n");
      out.write("    \t\t<option value=\"2006\" selected>2006</option>\r\n");
      out.write("\t\t\t<option value=\"2007\">2007</option>\r\n");
      out.write("\t\t\t<option value=\"2008\">2008</option>\r\n");
      out.write("\t\t\t<option value=\"2009\">2009</option>\r\n");
      out.write("\t\t\t<option value=\"2010\">2010</option>\r\n");
      out.write("\t\t\t<option value=\"2011\">2011</option>\r\n");
      out.write("\t\t\t<option value=\"2012\">2012</option>\r\n");
      out.write("\t\t\t<option value=\"2013\">2013</option>\r\n");
      out.write("\t\t\t<option value=\"2014\">2014</option>\r\n");
      out.write("\t\t\t<option value=\"2015\">2015</option>\r\n");
      out.write("    </select> \r\n");
      out.write("    </td> -->\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write(" \t<td width=\"34%\" style=\"border-left-style: none; border-left-width: 1; border-top-style: none; border-top-width: 1\" >\r\n");
      out.write("     <b>&nbsp;&nbsp;&nbsp;</b>\r\n");
      out.write("    </td> \r\n");
      out.write("    <td width=\"38%\" style=\"border-top-style: none; border-top-width: 1\" >\r\n");
      out.write("     <b>");
      out.print( pageData.getWord("Starting date"));
      out.write("</b>   \r\n");
      out.write("    </td>\r\n");
      out.write("    <td width=\"28%\" style=\"border-right-style: none; border-right-width: 1; border-top-style: none; border-top-width: 1\" >\r\n");
      out.write("     <b><");
      out.print( pageData.getWord("Ending date"));
      out.write("</b>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("   <td>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("    <input name=\"period\" type=\"radio\" value=\"daily\"  onClick=\"changeDisabled()\" checked>&nbsp;");
      out.print( pageData.getWord("Daily"));
      out.write("\r\n");
      out.write("   </td>\r\n");
      out.write("   <td id=\"id_startingDateDaily\" valign=\"top\" width=\"34%\" style=\"border-left-style: none; border-left-width: 1; border-bottom-style:none; border-bottom-width:1\" >\r\n");
      out.write("   \t <input type=\"text\" size=\"20\" onFocus=\"showCalendar('',this,this,'','id_startingDateDaily',0,30,1);this.blur()\" name=\"startingDateDaily\" />\r\n");
      out.write("\r\n");
      out.write("    </td>\r\n");
      out.write("    <td id=\"id_endingDateDaily\" valign=\"top\" width=\"38%\" style=\"border-bottom-style: none; border-bottom-width: 1\">\r\n");
      out.write("     \t<input type=\"text\" size=\"20\" onFocus=\"showCalendar('',this,this,'','id_endingDateDaily',0,30,1);this.blur()\" name=\"endingDateDaily\"/>\r\n");
      out.write("    </td>\r\n");
      out.write("  <tr>\r\n");
      out.write("\r\n");
      out.write("  <tr>\r\n");
      out.write("\t<td colspan=\"2\"  style=\"border-left-style: none; border-left-width: 1; border-bottom-style: none; border-bottom-width: 1; border-top-style:none; border-top-width:1\" >&nbsp;</td>\r\n");
      out.write("\t<td  style=\"border-bottom-style: none; border-bottom-width: 1; border-top-style:none; border-top-width:1\">&nbsp;</td>\r\n");
      out.write("\t<td  valign=\"top\"  align=\"right\" >\r\n");
      out.write("\t<input id=\"submit\" type=\"button\" value='");
      out.print( pageData.getWord("Submit"));
      out.write("' onClick=\"getRequestedReport()\">\r\n");
      out.write("\t</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\tdocument.writeln(\"\t<td  valign=\\\"top\\\"  align=\\\"left\\\" ></td>\");\r\n");
      out.write("\tdocument.writeln(\"\t<td  style=\\\"border-bottom-width: 1; border-top-width:1\\\">&nbsp;</td>\");\r\n");
      out.write("\tdocument.writeln(\"\t<td  style=\\\"border-bottom-width: 1;  border-top-width:1\\\">&nbsp; </td>\");\r\n");
      out.write("\tdocument.writeln(\"\t<td  valign=\\\"top\\\"  align=\\\"right\\\" >&nbsp;</td>\");\r\n");
      out.write("\tdocument.writeln(\"\t<td  valign=\\\"top\\\"  align=\\\"right\\\" >&nbsp;</td> \");\r\n");
      out.write("\tdocument.writeln(\"</tr>\");\r\n");
      out.write("\r\n");
      out.write("  </script>\r\n");
      out.write("</table>\r\n");
      out.write(" <script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write(" setDefaultValue();\r\n");
      out.write(" </script>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
 pageData.closeConnection(); 
      out.write("\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
