package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.*;
import aheevaManager.csvinterface.*;
import aheevaManager.ressources.*;
import java.text.*;
import aheevaManager.schedule.*;
import aheevaManager.ressources.*;
import java.util.*;
import jxl.*;

public final class listenRecPicker1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/aheevaManager/Resources_pages/xc2_default_labels.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
    pageData.openConnection();

      out.write("\r\n");
      out.write("<title>Record Picker</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"xc2_default.css\" type=\"text/css\">\r\n");
      out.write("<LINK href=\"livestats.css\" \trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pagexc2Data = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pagexc2Data.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
pagexc2Data.openConnection();
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("// variables of labels;// \r\n");
      out.write("var phrase= new Array();\r\n");
      out.write("phrase[0]=\"");
      out.print( pagexc2Data.getWord("January"));
      out.write("\";\r\n");
      out.write("phrase[1]=\"");
      out.print( pagexc2Data.getWord("February"));
      out.write("\";\r\n");
      out.write("phrase[2]=\"");
      out.print( pagexc2Data.getWord("March"));
      out.write("\";\r\n");
      out.write("phrase[3]=\"");
      out.print( pagexc2Data.getWord("April"));
      out.write("\";\r\n");
      out.write("phrase[4]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";         \r\n");
      out.write("phrase[5]=\"");
      out.print( pagexc2Data.getWord("June"));
      out.write("\";\r\n");
      out.write("phrase[6]=\"");
      out.print( pagexc2Data.getWord("July"));
      out.write("\";\r\n");
      out.write("phrase[7]=\"");
      out.print( pagexc2Data.getWord("August"));
      out.write("\";\r\n");
      out.write("phrase[8]=\"");
      out.print( pagexc2Data.getWord("September"));
      out.write("\";\r\n");
      out.write("phrase[9]=\"");
      out.print( pagexc2Data.getWord("October"));
      out.write("\";\r\n");
      out.write("phrase[10]=\"");
      out.print( pagexc2Data.getWord("November"));
      out.write("\";\r\n");
      out.write("phrase[11]=\"");
      out.print( pagexc2Data.getWord("December"));
      out.write("\";\r\n");
      out.write("phrase[12]=\"");
      out.print( pagexc2Data.getWord("Jan"));
      out.write("\";\r\n");
      out.write("phrase[13]=\"");
      out.print( pagexc2Data.getWord("Feb"));
      out.write("\";\r\n");
      out.write("phrase[14]=\"");
      out.print( pagexc2Data.getWord("Mar"));
      out.write("\";\r\n");
      out.write("phrase[15]=\"");
      out.print( pagexc2Data.getWord("Apr"));
      out.write("\";\r\n");
      out.write("phrase[16]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";\r\n");
      out.write("phrase[17]=\"");
      out.print( pagexc2Data.getWord("Jun"));
      out.write("\";\r\n");
      out.write("phrase[18]=\"");
      out.print( pagexc2Data.getWord("Jul"));
      out.write("\";\r\n");
      out.write("phrase[19]=\"");
      out.print( pagexc2Data.getWord("Aug"));
      out.write("\";\r\n");
      out.write("phrase[20]=\"");
      out.print( pagexc2Data.getWord("Sep"));
      out.write("\";\r\n");
      out.write("phrase[21]=\"");
      out.print( pagexc2Data.getWord("Oct"));
      out.write("\";\r\n");
      out.write("phrase[22]=\"");
      out.print( pagexc2Data.getWord("Nov"));
      out.write("\";\r\n");
      out.write("phrase[23]=\"");
      out.print( pagexc2Data.getWord("Dec"));
      out.write("\";\r\n");
      out.write("phrase[24]=\"");
      out.print( pagexc2Data.getWord("Sunday"));
      out.write("\";\r\n");
      out.write("phrase[25]=\"");
      out.print( pagexc2Data.getWord("Monday"));
      out.write("\";\r\n");
      out.write("phrase[26]=\"");
      out.print( pagexc2Data.getWord("Tuesday"));
      out.write("\";\r\n");
      out.write("phrase[27]=\"");
      out.print( pagexc2Data.getWord("Wednesday"));
      out.write("\";\r\n");
      out.write("phrase[28]=\"");
      out.print( pagexc2Data.getWord("Thursday"));
      out.write("\";\r\n");
      out.write("phrase[29]=\"");
      out.print( pagexc2Data.getWord("Friday"));
      out.write("\";\r\n");
      out.write("phrase[30]=\"");
      out.print( pagexc2Data.getWord("Saturday"));
      out.write("\";\r\n");
      out.write("phrase[31]=\"");
      out.print( pagexc2Data.getWord("Sun"));
      out.write("\";\r\n");
      out.write("phrase[32]=\"");
      out.print( pagexc2Data.getWord("Mon"));
      out.write("\";\r\n");
      out.write("phrase[33]=\"");
      out.print( pagexc2Data.getWord("Tue"));
      out.write("\";\r\n");
      out.write("phrase[34]=\"");
      out.print( pagexc2Data.getWord("Wed"));
      out.write("\";\r\n");
      out.write("phrase[35]=\"");
      out.print( pagexc2Data.getWord("Thu"));
      out.write("\";\r\n");
      out.write("phrase[36]=\"");
      out.print( pagexc2Data.getWord("Fri"));
      out.write("\";\r\n");
      out.write("phrase[37]=\"");
      out.print( pagexc2Data.getWord("Sat"));
      out.write("\";\r\n");
      out.write("phrase[38]=\"");
      out.print( pagexc2Data.getWord("Su"));
      out.write("\";\r\n");
      out.write("phrase[39]=\"");
      out.print( pagexc2Data.getWord("Mo"));
      out.write("\";\r\n");
      out.write("phrase[40]=\"");
      out.print( pagexc2Data.getWord("Tu"));
      out.write("\";\r\n");
      out.write("phrase[41]=\"");
      out.print( pagexc2Data.getWord("We"));
      out.write("\";\r\n");
      out.write("phrase[42]=\"");
      out.print( pagexc2Data.getWord("Th"));
      out.write("\";\r\n");
      out.write("phrase[43]=\"");
      out.print( pagexc2Data.getWord("Fr"));
      out.write("\";\r\n");
      out.write("phrase[44]=\"");
      out.print( pagexc2Data.getWord("Sa"));
      out.write("\";\r\n");
      out.write("phrase[45]=\"");
      out.print( pagexc2Data.getWord(" Today "));
      out.write("\";\r\n");
      out.write("phrase[46]=\"");
      out.print( pagexc2Data.getWord("Clear"));
      out.write("\";\r\n");
      out.write("phrase[47]=\"");
      out.print( pagexc2Data.getWord("Back"));
      out.write("\";\r\n");
      out.write("phrase[48]=\"");
      out.print( pagexc2Data.getWord("Close"));
      out.write("\";\r\n");
      out.write("phrase[49]=\"");
      out.print( pagexc2Data.getWord("Reset"));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 pagexc2Data.closeConnection(); 
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"xc2_default.js\"></script>\r\n");
      out.write("<script language=\"javascript\">xcAutoHide=1000;</script>\r\n");
      out.write("<script language=\"javascript\" src=\"xc2_inpage.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\" src=\"jsUtil.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" />-->\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("var NS4 = document.layers ? 1:0\r\n");
      out.write("var IE4 = document.all ? 1:0\r\n");
      out.write("var IE5 = document.getElementById&&document.all ? 1:0\r\n");
      out.write("var NS6 = document.getElementById&&!document.all ? 1:0\r\n");
      out.write("\r\n");
      out.write("var x=0;\r\n");
      out.write("var y=0;\r\n");
      out.write("var closetable = \"</TD></TR></TABLE></TD></TR></TABLE>\";\t\r\n");
      out.write("if(!IE4) {\r\n");
      out.write("\tdocument.captureEvents(Event.MOUSEMOVE);\r\n");
      out.write("\tdocument.onmousemove = GetPos;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("function Desc(text ) {\r\n");
      out.write(" \tvar opentable = \"<TABLE BGCOLOR='#000000' BORDER=0 CELLPADDING=0 CELLSPACING=1 WIDTH=140><TR><TD ALIGN=center><TABLE BGCOLOR='#FFFFE1' BORDER=0 CELLPADDING=3 CELLSPACING=1 WIDTH=138><TR><TD VALIGN=top style='font-size:10px; font-family:Tahoma' align=left><IMG SRC='../img/help.gif' HEIGHT=24 WIDTH=30 VSPACE=0 HSPACE=0 ALIGN=left>\";\r\n");
      out.write("\t \r\n");
      out.write("\tif(NS6) {\r\n");
      out.write("\t\tdocument.getElementById(\"Description\").innerHTML  = opentable+text+closetable;\r\n");
      out.write("\t\tdocument.getElementById(\"Description\").style.left = x-12;\r\n");
      out.write("\t\tdocument.getElementById(\"Description\").style.top  = y+10;\r\n");
      out.write("\t\tdocument.getElementById(\"Description\").style.visibility = \"visible\";\r\n");
      out.write("\t}\r\n");
      out.write(" \tif(IE4) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.all[\"Description\"].innerHTML = opentable+text+closetable;\r\n");
      out.write("\t\tDescription.style.pixelLeft = event.clientX-12;\r\n");
      out.write("\t\tDescription.style.posTop  = document.body.scrollTop+event.clientY+16;\r\n");
      out.write("\t\tDescription.style.visibility = \"visible\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse {\r\n");
      out.write("\t\tvar nets = document.layers[\"Description\"];\r\n");
      out.write("\t\tnets.document.open();\r\n");
      out.write("\t\tnets.document.write(opentable+text+closetable);\r\n");
      out.write("\t\tdocument.Description.left = x-12;\r\n");
      out.write("\t\tdocument.Description.top = y+10;\r\n");
      out.write("\t\tnets.visibility = \"show\";\r\n");
      out.write("\t\tdocument.close();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function GetPos(evnt){\r\n");
      out.write("\tx = evnt.pageX;\r\n");
      out.write("\ty = evnt.pageY;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function noDesc() {\r\n");
      out.write("\r\n");
      out.write("\tif(NS6) {\r\n");
      out.write("\t\tdocument.getElementById(\"Description\").style.visibility = \"hidden\";\r\n");
      out.write("\t}\r\n");
      out.write("\tif(IE4) {\r\n");
      out.write("\t\tDescription.style.visibility = \"hidden\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse {\r\n");
      out.write("\t\tdocument.Description.visibility = \"hidden\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .contentText{\r\n");
      out.write("\tfont:\t\t\t12px Tahoma;\r\n");
      out.write("\tcolor:\t\t\tBlack;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\tclear:\t\t\tboth;\r\n");
      out.write("\tborder:\t\t\t1px solid rgb( 145, 155, 156 );\r\n");
      out.write("\tbackground:\t\trgb( 252, 252, 254 );\r\n");
      out.write("\tz-index:\t\t2;\r\n");
      out.write("\tposition:\t\trelative;\r\n");
      out.write("\ttop:\t\t\t-2px;\r\n");
      out.write("\r\n");
      out.write("\tfont:\t\t\t11px Tahoma;\r\n");
      out.write("\tcolor:\t\t\tBlack;\r\n");
      out.write("\r\n");
      out.write("\tfilter:\t\t\tprogid:DXImageTransform.Microsoft.Gradient(StartColorStr=#fffcfcfe, EndColorStr=#fff4f3ee, GradientType=0)\r\n");
      out.write("\t\t\t\t\tprogid:DXImageTransform.Microsoft.Shadow(Color=#ff919899, Strength=2, Direction=135);\r\n");
      out.write("\t\r\n");
      out.write("\t/* 244, 243, 238 */ \r\n");
      out.write("\t/*145, 155, 156 */\r\n");
      out.write("\tpadding:\t\t10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-row {\r\n");
      out.write("\tz-index:\t\t1;\r\n");
      out.write("\twhite-space:\tnowrap;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(".dynamic-tab-pane-control .tab-row .tab.selected {\r\n");
      out.write("\twidth:\t\t\t\t74px  ;\r\n");
      out.write("\theight:\t\t\t\t18px  ;\r\n");
      out.write("\tbackground-image:\turl( \"tab.active.png\" )  ;\r\n");
      out.write("\tbackground-repaet:\tno-repeat;\r\n");
      out.write("\r\n");
      out.write("\tborder-bottom-width:\t0;\r\n");
      out.write("\tz-index:\t\t3;\r\n");
      out.write("\tpadding:\t\t2px 0 0px 0;\r\n");
      out.write("\tmargin:\t\t\t1px -3px -3px 0px;\r\n");
      out.write("\ttop:\t\t\t-2px;\r\n");
      out.write("\tfont:\t\t\t11px Tahoma;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-row .tab a {\r\n");
      out.write("\tfont:\t\t\t\t11px Tahoma;\r\n");
      out.write("\tcolor:\t\t\t\tBlack;\r\n");
      out.write("\ttext-decoration:\tnone;\r\n");
      out.write("\tcursor:\t\t\t\tdefault;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-row .tab.hover {\r\n");
      out.write("\tfont:\t\t\t\t11px Tahoma;\r\n");
      out.write("\twidth:\t\t\t\t70px;\r\n");
      out.write("\theight:\t\t\t\t16px;\r\n");
      out.write("\tbackground-image:\turl( \"tab.hover.png\" );\r\n");
      out.write("\tbackground-repaet:\tno-repeat;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(".dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("html, body {\r\n");
      out.write("/*\tbackground:\tThreeDFace; */\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("\tmargin:\t\t0;\r\n");
      out.write("\tpadding:\t0;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("/* over ride styles from webfxlayout */\r\n");
      out.write(" \r\n");
      out.write("body {\r\n");
      out.write("\tmargin:\t\t10px;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("\theight:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control h2 {\r\n");
      out.write("\ttext-align:\tcenter;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control h2 a {\r\n");
      out.write("\tdisplay:\tinline;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control a:hover {\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(" .dynamic-tab-pane-control.tab-pane {\r\n");
      out.write("\tposition:\trelative;\r\n");
      out.write("\twidth:\t\t100%;\t\t \r\n");
      out.write("\tmargin-right:\t-2px;\t \r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write(" \r\n");
      out.write("<script type=\"text/javascript\" >\r\n");
      out.write("var tenant_dbid  = normalizeString(QueryString('tenant_dbid'));\r\n");
      out.write("\r\n");
      out.write("function sortSelect(o)\r\n");
      out.write("{\r\n");
      out.write(" \tif (o.length==0) { return; }\r\n");
      out.write("\r\n");
      out.write("\tif(viewckbox.checked == false){\r\n");
      out.write("\t\to = o.sort(\r\n");
      out.write("\t\t\tfunction(a,b) {\r\n");
      out.write("\t\t\t\tif ((a.text+\"\") < (b.text+\"\")) { return -1; }\r\n");
      out.write("\t\t\t\tif ((a.text+\"\") > (b.text+\"\")) { return 1; }\r\n");
      out.write("\t\t\t\treturn 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\to = o.sort(\r\n");
      out.write("\t\t\tfunction(a,b) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (parseInt(a.value) < parseInt(b.value)) { return -1; }\r\n");
      out.write("\t\t\t\t\tif (parseInt(a.value) > parseInt(b.value)) { return 1; }\r\n");
      out.write("\t\t\t\t\treturn 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t}\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fillObjectCombo()\r\n");
      out.write("{\r\n");
      out.write(" \tif(document.theForm.user.options.length <= 1 ) {\t\r\n");
      out.write("        /*Fill agents group combo box with agent group name*/\r\n");
      out.write("        var users = String( appletObj.getUsers() );\r\n");
      out.write("\t\t//alert(\"users = \" + users);\r\n");
      out.write("        var jsUsers = users + \"\";\r\n");
      out.write("    \tarrayUsers = jsUsers.split(\"|\");\r\n");
      out.write("    \tfor (j = 0; j <arrayUsers.length; j++){\r\n");
      out.write("\t\t    var jsuserData = (arrayUsers[j]).split(\",\");\r\n");
      out.write("\t\t\tvar dbid =  jsuserData[0];\r\n");
      out.write("\t\t\tvar tenant =  jsuserData[1];\r\n");
      out.write("\t\t\tvar name =  jsuserData[2];\r\n");
      out.write("\t\t\t//if(tenant == tenant_dbid){\r\n");
      out.write("\t\t\t\tmyOption = new Option(name,dbid)\r\n");
      out.write("\t\t\t\toptionPos = document.theForm.user.options.length\r\n");
      out.write("\t\t\t\tdocument.theForm.user.options[optionPos]=myOption\r\n");
      out.write("\t\t\t//}\r\n");
      out.write("    \t}\r\n");
      out.write("\t\t//sortSelect(objects);\r\n");
      out.write("\t }\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getSelectedObjects()\r\n");
      out.write("{\r\n");
      out.write("\tselectedAgents = new Array()\r\n");
      out.write("\tfor (i=objects.selectedIndex;i<objects.options.length;i++) {\r\n");
      out.write("  \t\tif (objects.options[i].selected) {\r\n");
      out.write("  \t\t\tselectedAgents[selectedAgents.length]=objects.options[i].value;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t}\r\n");
      out.write("\tvar url = '';\r\n");
      out.write("\tif (selectedAgents.length > 0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\turl= escape(selectedAgents.join('/'))\r\n");
      out.write("\t}\r\n");
      out.write("\treturn url;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getRequestedReport()\r\n");
      out.write("{\r\n");
      out.write("\t\tv = true;\t\r\n");
      out.write("\tif(\tdocument.theForm.ip.value.length > 1){\r\n");
      out.write("\t\tvar ipParts = document.theForm.ip.value.split(\".\");\r\n");
      out.write("\t\r\n");
      out.write("\t\tif(ipParts.length != 4 || document.theForm.ip.value.length > 15)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"");
      out.print( pageData.getWord("The IP adress should be like: 192.168.100.100"));
      out.write("\");\r\n");
      out.write("\t\t\t\tv = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\tfor(j = 0; j < 4; j++)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\tif( !IsNumeric(ipParts[j]) )\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\talert(\"");
      out.print( pageData.getWord("The IP adress should be like: 192.168.100.100"));
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\tv=false;\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("       }\r\n");
      out.write("    if(v == false)\r\n");
      out.write("\t  return false;\r\n");
      out.write("\t  \r\n");
      out.write("\tvar destination = '';\r\n");
      out.write("\r\n");
      out.write("\tif(dateChecker() == false)\r\n");
      out.write("\t{\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write(" \tvar selectedUsers = document.theForm.user.value;\r\n");
      out.write(" \tdestination = \"../jsp/listenRecording.jsp\"\r\n");
      out.write("\tdestination += \"?startingDate=\"\r\n");
      out.write("\tdestination += document.theForm.startingDate.value;\r\n");
      out.write("\tdestination +=\"&endingDate=\";\r\n");
      out.write("\tdestination += document.theForm.endingDate.value;\r\n");
      out.write("\tdestination +=\"&ip=\";\r\n");
      out.write("\tdestination += document.theForm.ip.value;\r\n");
      out.write("\tdestination +=\"&user=\";\r\n");
      out.write("\r\n");
      out.write("\tif(document.theForm.user.value == 'AllUsers')\r\n");
      out.write("\t{\r\n");
      out.write("\t  selectedUsers = selectedUsers + '/';\r\n");
      out.write("\t  var i;\r\n");
      out.write("\t  for(i=1; i<document.theForm.user.options.length; i++){\r\n");
      out.write("\t\t selectedUsers = selectedUsers + document.theForm.user.options[i].value + '!';\r\n");
      out.write("\t   }\r\n");
      out.write("\t  if(document.theForm.user.options.length > 1)\r\n");
      out.write("\t\t selectedUsers = selectedUsers.substring(0,selectedUsers.length-1);\r\n");
      out.write("\t}\r\n");
      out.write("\tdestination += selectedUsers;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tvar fonlyeval = 0;\r\n");
      out.write("\r\n");
      out.write("\tif (document.theForm.check.checked ==true)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tfonlyeval = 1;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tdestination +=\"&feval=\";\r\n");
      out.write("\tdestination += fonlyeval;\r\n");
      out.write("  \t//alert(destination);\r\n");
      out.write(" \tdocument.location = destination;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function dateChecker()\r\n");
      out.write("{\r\n");
      out.write("\tvar startDate=new Date(document.theForm.startingDate.value);\r\n");
      out.write("\tvar endDate = new Date(document.theForm.endingDate.value);\r\n");
      out.write("\r\n");
      out.write("\tif(endDate < startDate)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("Your ending date cannnot be smaller than your starting date"));
      out.write("\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function toggleLayer(whichLayer)\r\n");
      out.write("{\r\n");
      out.write("\tif (document.getElementById)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t// this is the way the standards work\r\n");
      out.write("\t\tvar style2 = document.getElementById(whichLayer).style;\r\n");
      out.write("\t\tstyle2.display = style2.display? \"\":\"none\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse if (document.all)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t// this is the way old msie versions work\r\n");
      out.write("\t\tvar style2 = document.all[whichLayer].style;\r\n");
      out.write("\t\tstyle2.display = style2.display? \"\":\"none\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse if (document.layers)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t// this is the way nn4 works\r\n");
      out.write("\t\tvar style2 = document.layers[whichLayer].style;\r\n");
      out.write("\t\tstyle2.display = style2.display? \"\":\"none\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"q_m_body\">\r\n");
      out.write("<br />\r\n");
      out.write("<DIV ID=\"Description\" STYLE=\"position:absolute; top:5px; left:5px; visibility:hide; z-index:1; background-color:#FFFFCC;\"></DIV>\r\n");
      out.write("\r\n");
      out.write("<div class=\"dynamic-tab-pane-control\">\r\n");
      out.write("\t<div class=\"tab-pane\" id=\"tabPane1\">\r\n");
      out.write(" \t\t\r\n");
      out.write("    <div class=\"tab-page\" id=\"general\"> \r\n");
      out.write("      <fieldset>\r\n");
      out.write("      <legend> \r\n");
      out.write("      ");
      out.print( pageData.getWord("Record parameters"));
      out.write("\r\n");
      out.write("      </legend>\r\n");
      out.write("      <form name=\"theForm\">\r\n");
      out.write("        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\" width=\"650\">\r\n");
      out.write("          <tr> \r\n");
      out.write("            <td style=\"border-left-style: none; border-left-width: 1; border-top-style: none; border-top-width: 1\"\r\n");
      out.write("\t\t\t\t\t\t\tcolspan=\"5\">&nbsp;</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr> \r\n");
      out.write("            <td width=\"136\" style=\"border-left-style: none; border-left-width: 1; border-top-style: none; border-top-width: 1\"> \r\n");
      out.write("              ");
      out.print( pageData.getWord("IP"));
      out.write("</td>\r\n");
      out.write("            <td width=\"30\" style=\"border-top-style: none; border-top-width: 1\">&nbsp; \r\n");
      out.write("            </td>\r\n");
      out.write("            <td width=\"156\" style=\"border-top-style: none; border-top-width: 1\" colspan=\"\">&nbsp; \r\n");
      out.write("              <input type=\"text\" name=\"ip\" class=\"contentText\"  /> </td>\r\n");
      out.write("            <td width=\"313\" style=\"border-top-style: none; border-top-width: 1\"><a style=\"color:#400040 \"  onMouseover=\"Desc('Would you like to list all the records which phone number contains the string 5678, write  %5678% in the box as search criteria' );\" onMouseout=\"noDesc();\" > \r\n");
      out.write("              (e.g : 192.168.10.100) </a></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr> \r\n");
      out.write("            <td height=\"26\" style=\"border-left-style: none; border-left-width: 1; border-top-style: none; border-top-width: 1\"> \r\n");
      out.write("              ");
      out.print( pageData.getWord("Listen time"));
      out.write("</td>\r\n");
      out.write("            <td height=\"26\" colspan=\"2\" style=\"border-top-style: none; border-top-width: 1\"> \r\n");
      out.write("              ");
      out.print( pageData.getWord("From"));
      out.write(" <input id=\"id_startingDate\" type=\"text\" size=\"20\" onFocus=\"showCalendar('',this,this,'','id_startingDate',0,30,1);this.blur()\" class=\"contentText\" name=\"startingDate\" /></td>\r\n");
      out.write("            <td height=\"26\" colspan=\"2\" style=\"border-top-style: none; border-top-width: 1;border-right-style: none; border-right-width: 1\"> \r\n");
      out.write("              ");
      out.print( pageData.getWord("To"));
      out.write(" &nbsp; <input id=\"id_endingDate\" type=\"text\" size=\"20\" onFocus=\"showCalendar('',this,this,'','id_endingDate',0,30,1);this.blur()\" class=\"contentText\" name=\"endingDate\" /> \r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr> \r\n");
      out.write("            <td style=\"border-left-style: none; border-left-width: 1; border-top-style: none; border-top-width: 1\">");
      out.print( pageData.getWord("User"));
      out.write("</td>\r\n");
      out.write("            <td style=\"border-top-style: none; border-top-width: 1\">&nbsp;</td>\r\n");
      out.write("            <td style=\"border-top-style: none; border-top-width: 1\" colspan=\"\"> \r\n");
      out.write("              <select name=\"user\"  class=\"contentText\">\r\n");
      out.write("                <option value=\"AllUsers\">- \r\n");
      out.write("                ");
      out.print( pageData.getWord("All Users"));
      out.write("\r\n");
      out.write("                -</option>\r\n");
      out.write("              </select> </td>\r\n");
      out.write("              <td><input type=\"checkbox\" name=\"check\" value=\"1\">&nbsp;");
      out.print( pageData.getWord("Show only evaluated"));
      out.write("\r\n");
      out.write("              </td>\r\n");
      out.write("            <td style=\"border-top-style: none; border-top-width: 1\"><a style=\"color:#400040 \"  onmouseover=\"Desc('Would you like to list all the records which IP address contains the string 5678, write  %5678% in the box as search criteria' );\" onmouseout=\"noDesc();\" > \r\n");
      out.write(" </a></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr> \r\n");
      out.write("            <td style=\"border-left-style: none; border-left-width: 1; border-top-style: none; border-top-width: 1\">&nbsp;</td>\r\n");
      out.write("            <td style=\"border-top-style: none; border-top-width: 1\">&nbsp;</td>\r\n");
      out.write("            <td style=\"border-top-style: none; border-top-width: 1\" colspan=\"\">&nbsp;</td>\r\n");
      out.write("            <td style=\"border-top-style: none; border-top-width: 1\">&nbsp;</td>\r\n");
      out.write("            <td width=\"15\" style=\"border-left-style: none; border-left-width: 1; border-bottom-style: none; border-bottom-width: 1; border-top-style:none; border-top-width:1\"> \r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("      </form>\r\n");
      out.write("      </fieldset>\r\n");
      out.write("    </div>\r\n");
      out.write(" \t  <div>\r\n");
      out.write("\t  \t <table border=\"0\" height=\"40\" cellpadding=\"0\" cellspacing=\"0\">\t\r\n");
      out.write("\t\t\t<tr valign=\"top\">\r\n");
      out.write("\t\t\t\t<td width=\"165\" height=\"40\" style=\"border-right-style: none; border-right-width: 1; border-bottom-style: none; border-bottom-width: 1; border-top-style:none; border-top-width:1\" align=\"left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"");
      out.print( pageData.getWord("Submit"));
      out.write("\" onClick=\"getRequestedReport()\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"border-left-style: none; border-left-width: 1; border-bottom-style: none; border-bottom-width: 1; border-top-style:none; border-top-width:1\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"border-bottom-style: none; border-bottom-width: 1; border-top-style:none; border-top-width:1\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("  \t    </table>\t\r\n");
      out.write("\t  </div> \r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("  \r\n");
      out.write("<script type=\"text/javascript\">  \r\n");
      out.write("fillObjectCombo(); \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
 pageData.closeConnection(); 
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
