package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.*;
import aheevaManager.ressources.*;

public final class modifyStarPhoneSettings1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
    pageData.openConnection();

      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"tab_luna.css\" />\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style_2.css\" />\r\n");
      out.write("<LINK href=\"livestats.css\" \trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html, body {\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("\tmargin:\t\t0;\r\n");
      out.write("\tpadding:\t0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* over ride styles from webfxlayout */\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:\t\t10px;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("\theight:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control h2 {\r\n");
      out.write("\ttext-align:\tcenter;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control h2 a {\r\n");
      out.write("\tdisplay:\tinline;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control a:hover {\r\n");
      out.write("\tbackground: transparent; \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<title>AheevaCCS - StarPhone Settings</title>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"jsUtil.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"tabpane.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function validateIP(IP)\r\n");
      out.write("{\r\n");
      out.write("\tvar ipParts = IP.split(\".\");\r\n");
      out.write("\t\r\n");
      out.write("\tif(ipParts.length != 4 || IP.length > 15)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("The IP adress should be like: 192.168.100.100"));
      out.write("\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\tfor(j = 0; j < 4; j++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(!IsNumeric(ipParts[j]) || ipParts[j].length > 3)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"");
      out.print( pageData.getWord("The IP adress should be like: 192.168.100.100"));
      out.write("\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validateInfo()\r\n");
      out.write("{\r\n");
      out.write("\tvalid = true;\r\n");
      out.write("\t\r\n");
      out.write("\tif(document.fstarphone_settings.update_enabled.checked)\r\n");
      out.write("\t\tupdate_enabled = \"1\";\r\n");
      out.write("\telse\r\n");
      out.write("\t\tupdate_enabled = \"0\";\r\n");
      out.write("\t\r\n");
      out.write("\tif(!validateIP(document.fstarphone_settings.url.value))\r\n");
      out.write("\t{\t\t\r\n");
      out.write("\t\tdocument.fstarphone_settings.url.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(!validateIP(document.fstarphone_settings.ext_url.value))\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.fstarphone_settings.ext_url.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(document.fstarphone_settings.port.value == \"\" || !IsNumeric(document.fstarphone_settings.port.value)) \r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("The internal port should be numeric"));
      out.write("\");\t\t\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(document.fstarphone_settings.ext_port.value == \"\" || !IsNumeric(document.fstarphone_settings.ext_port.value)) \r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("The external port should be numeric"));
      out.write("\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(validation(document.fstarphone_settings.port.value)==0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("Invalid use of character"));
      out.write("\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(document.fstarphone_settings.SiteSelection.value.length == 0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("You must select a site."));
      out.write("\");\t\r\n");
      out.write("\t\tvalid = false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(validation(document.fstarphone_settings.path.value)==0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("Invalid use of character"));
      out.write("\");\r\n");
      out.write("\t\tvalid = false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(validation(document.fstarphone_settings.url.value)==0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("Invalid use of character"));
      out.write("\");\r\n");
      out.write("\t\tvalid = false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(validation(document.fstarphone_settings.ext_url.value) == 0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("Invalid use of character"));
      out.write("\");\r\n");
      out.write("\t\tvalid = false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(validation(document.fstarphone_settings.ext_port.value) == 0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("Invalid use of character"));
      out.write("\");\r\n");
      out.write("\t\tvalid = false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t// --- if the form is valid\r\n");
      out.write("\tif(valid)\r\n");
      out.write("\t{ \t\t\r\n");
      out.write("\t\tappletObj.saveStarPhoneAutoUpdateSettings(update_enabled, document.fstarphone_settings.url.value, \r\n");
      out.write("\t\t\t\tdocument.fstarphone_settings.port.value, document.fstarphone_settings.path.value,\r\n");
      out.write("\t\t\t\tdocument.fstarphone_settings.ext_url.value, document.fstarphone_settings.ext_port.value,\r\n");
      out.write("\t\t\t\tdocument.fstarphone_settings.SiteSelection.value);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.fstarphone_settings.updateInfo.disabled = true;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function setValues() \r\n");
      out.write("{\r\n");
      out.write("\tvar values = String( appletObj.getStarPhoneAutoUpdateSettings() );\r\n");
      out.write("\tloadSitesCombo();\r\n");
      out.write("\tvar valuesArray = values.split(\"^\");\r\n");
      out.write("\tfor(i = 0; i < valuesArray.length; i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(i == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(valuesArray[i] == \"1\")\r\n");
      out.write("\t\t\t\tdocument.fstarphone_settings.update_enabled.checked = true;\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\tdocument.fstarphone_settings.update_enabled.checked = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(i == 1)\r\n");
      out.write("\t\t{\t\r\n");
      out.write("\t\t\tif(valuesArray[i] != \"NULL\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdocument.fstarphone_settings.url.value = valuesArray[i];\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(i == 2)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(valuesArray[i] != \"NULL\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdocument.fstarphone_settings.port.value = valuesArray[i];\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(i == 3)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(valuesArray[i] != \"NULL\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdocument.fstarphone_settings.path.value = valuesArray[i];\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(i == 4)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(valuesArray[i] != \"NULL\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdocument.fstarphone_settings.ext_url.value = valuesArray[i];\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(i == 5)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(valuesArray[i] != \"NULL\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdocument.fstarphone_settings.ext_port.value = valuesArray[i];\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(i == 6)\r\n");
      out.write("\t\t\tselectObject(document.fstarphone_settings.SiteSelection, valuesArray[i]);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("function enableUpdateButton()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.fstarphone_settings.updateInfo.disabled = false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function loadSitesCombo()\r\n");
      out.write("{\r\n");
      out.write("\t//Getting the list of sites from ComApplet\r\n");
      out.write("\tvar allSites = String(appletObj.getAllSites());\r\n");
      out.write("\t\r\n");
      out.write("\t//Creating an empty option\r\n");
      out.write("\tmyOption = new Option(\"\", \"\");\r\n");
      out.write("\tdocument.fstarphone_settings.SiteSelection.options[0] = myOption;\r\n");
      out.write("\r\n");
      out.write("\t//Parsing the received string   DBID^SiteName|DBID^SiteName|...\r\n");
      out.write("\tvar jsSites = allSites  + \"\";\r\n");
      out.write("\tarraySites = jsSites.split(\"|\");\r\n");
      out.write("\tfor (j = 0; j <arraySites.length; j++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tarrSiteInfo = arraySites[j].split(\"^\");\r\n");
      out.write("\t\tfor (p = 0; p < arrSiteInfo.length; p++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(p == 0)\r\n");
      out.write("\t\t\t\tsite_dbid = arrSiteInfo[p];\r\n");
      out.write("\t\t\telse if(p == 1)\r\n");
      out.write("\t\t\t\tsite_name = arrSiteInfo[p];\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(site_dbid.length > 0 && site_name.length > 0)\t\t//If not all infos was sent, we don't add it in the list\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tmyOption = new Option(site_name, site_dbid);\r\n");
      out.write("\t\t\toptionPos = document.fstarphone_settings.SiteSelection.options.length;\r\n");
      out.write("\t\t\tdocument.fstarphone_settings.SiteSelection.options[optionPos]=myOption;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("    // Associate a default button with pressing the Enter key\r\n");
      out.write("\tfunction KeyDownHandler(btn)\r\n");
      out.write("    {\r\n");
      out.write("        // process only the Enter key\r\n");
      out.write("        if (event.keyCode == 13)\r\n");
      out.write("        {\r\n");
      out.write("            // cancel the default submit\r\n");
      out.write("            event.returnValue=false;\r\n");
      out.write("            event.cancel = true;\r\n");
      out.write("            // submit the form by programmatically clicking the specified button\r\n");
      out.write("            btn.click();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"a_phone_body\" onLoad=\"setValues()\">\r\n");
      out.write("<div class=\"tab-pane\" id=\"tabPane1\">\r\n");
      out.write("<form name=\"fstarphone_settings\" method=\"get\" onKeyDown=\"KeyDownHandler(save)\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("tp1 = new WebFXTabPane( document.getElementById( \"tabPane1\" ) );\r\n");
      out.write("</script>\r\n");
      out.write("\t<div class=\"tab-page\" id=\"tabPage1\">\r\n");
      out.write("\t<h2 class=\"tab\">");
      out.print( pageData.getWord("Auto update"));
      out.write("</h2>\r\n");
      out.write("\t<script type=\"text/javascript\">tp1.addTabPage( document.getElementById( \"tabPage1\" ) );</script>\r\n");
      out.write("\t<fieldset>\r\n");
      out.write("\t<legend>");
      out.print( pageData.getWord("Modify Auto update Settings"));
      out.write("</legend>\r\n");
      out.write("\t<table border=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print( pageData.getWord("Enable Auto update"));
      out.write("</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input name=\"n_dbid\" disabled  type=\"hidden\">\r\n");
      out.write("\t\t\t\t<input name=\"update_enabled\" type=\"checkbox\" value=\"ON\" onClick=\"enableUpdateButton()\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print( pageData.getWord("Internal IP"));
      out.write("</td>\r\n");
      out.write("\t\t\t<td><input name=\"url\" type=\"text\" value=\"\" onChange=\"enableUpdateButton()\"></td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print( pageData.getWord("Internal port:"));
      out.write("</td>\r\n");
      out.write("\t\t\t<td><input name=\"port\" type=\"text\" value=\"\" onChange=\"enableUpdateButton()\" size=\"5\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print( pageData.getWord("External IP"));
      out.write("</td>\r\n");
      out.write("\t\t\t<td><input name=\"ext_url\" type=\"text\" value=\"\" onChange=\"enableUpdateButton()\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print( pageData.getWord("External port:"));
      out.write("</td>\r\n");
      out.write("\t\t\t<td><input name=\"ext_port\" type=\"text\" value=\"\" onChange=\"enableUpdateButton()\" size=\"5\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print( pageData.getWord("Path (relative to WEB ROOT)"));
      out.write("</td>\r\n");
      out.write("\t\t\t<td><input name=\"path\" type=\"text\" value=\"\" onChange=\"enableUpdateButton()\" size=\"30\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print( pageData.getWord("Site"));
      out.write("</td>\r\n");
      out.write("\t\t\t<td><select size=\"1\" name=\"SiteSelection\" onChange=\"enableUpdateButton()\"></select></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t<input disabled id=\"save\" name=\"updateInfo\" type=\"button\" value='");
      out.print( pageData.getWord("Update"));
      out.write("' onClick=\"validateInfo()\">\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
 pageData.closeConnection(); 
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
