package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import aheevaManager.ressources.*;
import java.text.*;
import aheevaManager.schedule.*;
import aheevaManager.ressources.*;

public final class mop1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/aheevaManager/Resources_pages/mopFunctions_labels.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
    pageData.openConnection();

      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"tab_luna.css\" />\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style_2.css\" />\r\n");
      out.write("<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" >\r\n");
      out.write("<LINK href=\"livestats.css\" \trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<meta http-equiv=\"Content-Language\" content=\"en-us\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t100px;\r\n");
      out.write("}\r\n");
      out.write("html, body {\r\n");
      out.write("/*\tbackground:\tThreeDFace; */\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("form {\r\n");
      out.write("\tmargin:\t\t0;\r\n");
      out.write("\tpadding:\t0;\r\n");
      out.write("}\r\n");
      out.write("/* over ride styles from webfxlayout */\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:\t\t10px;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("\theight:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 {\r\n");
      out.write("\ttext-align:\tcenter;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 a {\r\n");
      out.write("\tdisplay:\tinline;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control a:hover {\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageMopFData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageMopFData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
pageMopFData.openConnection();
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("var mop= new Array();\r\n");
      out.write("mop[0]=\"");
      out.print( pageMopFData.getWord("You can select only one treatment for this mop !! Please drop the selected treatment and select another one"));
      out.write("\";\r\n");
      out.write("mop[1]=\"");
      out.print( pageMopFData.getWord("Save"));
      out.write("\";\r\n");
      out.write("mop[2]=\"");
      out.print( pageMopFData.getWord("You must enter a Mop name"));
      out.write("\";\r\n");
      out.write("mop[3]=\"");
      out.print( pageMopFData.getWord("Invalid use of character"));
      out.write("\";\r\n");
      out.write("mop[4]=\"");
      out.print( pageMopFData.getWord("Are you sure, you wish to delete this method of payment? ** (Please check the agent groups which uses this MOP)"));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 pageMopFData.closeConnection(); 
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jsUtil.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"tabpane.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"mopFunctions.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function askHelp(URL) {\r\n");
      out.write("day = new Date();\r\n");
      out.write("id = day.getTime();\r\n");
      out.write("eval(\"page\" + id + \" = window.open(URL, '\" + id + \"', 'toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width=500,height=300');\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("    // Associate a default button with pressing the Enter key\r\n");
      out.write("\tfunction KeyDownHandler(btn)\r\n");
      out.write("    {\r\n");
      out.write("        // process only the Enter key\r\n");
      out.write("        if (event.keyCode == 13)\r\n");
      out.write("        {\r\n");
      out.write("            // cancel the default submit\r\n");
      out.write("            event.returnValue=false;\r\n");
      out.write("            event.cancel = true;\r\n");
      out.write("            // submit the form by programmatically clicking the specified button\r\n");
      out.write("            btn.click();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"mop_body\" onLoad=\"displayMopInfo()\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"tab-pane\" id=\"tabPane1\">\r\n");
      out.write("<form name=\"mop_form\" onKeyDown=\"KeyDownHandler(save)\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("tp1 = new WebFXTabPane( document.getElementById( \"tabPane1\" ) );\r\n");
      out.write("</script>\r\n");
      out.write("\t<div class=\"tab-page\" id=\"tabGeneral\">\r\n");
      out.write("\t\t<h2 class=\"tab\">");
      out.print( pageData.getWord("General"));
      out.write("</h2>\r\n");
      out.write("\t\t<script type=\"text/javascript\">tp1.addTabPage( document.getElementById( \"tabGeneral\" ) );</script>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>");
      out.print( pageData.getWord("General settings"));
      out.write("</legend>\r\n");
      out.write("\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t   <td height=\"21\">&nbsp;\t\t\t   </td>\r\n");
      out.write("\t\t\t   <td>\t\t\t   </td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"197\" height=\"22\">");
      out.print( pageData.getWord("Method of payment"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"292\" height=\"22\" align=\"left\"><input type=\"text\" name=\"mopName\" onClick=\"enabledUpdateButton()\" size=\"20\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"197\" height=\"24\">");
      out.print( pageData.getWord("Description"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"292\"height=\"50\"><textarea rows=\"3\" name=\"mopDescription\" cols=\"41\" onChange=\"enabledUpdateButton()\"></textarea></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"197\" height=\"25\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Active"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input id=\"mopStatus\" type=\"checkbox\" name=\"mopStatus\" value=\"ON\" onClick=\"enabledUpdateButton()\" checked>\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"tab-page\" id=\"tabCodes\">\r\n");
      out.write("\t\t<h2 class=\"tab\">");
      out.print( pageData.getWord("Codes"));
      out.write("</h2>\r\n");
      out.write("\t\t<script type=\"text/javascript\">tp1.addTabPage( document.getElementById( \"tabCodes\" ) );</script>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t<legend>");
      out.print( pageData.getWord("MOP Codes"));
      out.write("</legend>\r\n");
      out.write("\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t   <td height=\"21\">&nbsp;\t\t\t   </td>\r\n");
      out.write("\t\t\t   <td>\t\t\t   </td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"197\" height=\"36\">");
      out.print( pageData.getWord("Training Code"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td  width=\"293\" height=\"36\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" maxlength=\"5\" size=\"5\" name=\"trainingCode\" onClick=\"enabledUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Hours"));
      out.write("<input type=\"radio\" name=\"trainingCodeTag\" value=\"1\" checked>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Dollars"));
      out.write("<input type=\"radio\" name=\"trainingCodeTag\" value=\"2\" disabled>\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"197\" height=\"36\">");
      out.print( pageData.getWord("Integration Code"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td  width=\"293\" height=\"36\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" maxlength=\"5\" size=\"5\" name=\"integrationCode\" onClick=\"enabledUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Hours"));
      out.write("<input type=\"radio\" name=\"integrationCodeTag\" value=\"1\" checked>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Dollars"));
      out.write("<input type=\"radio\" name=\"integrationCodeTag\" value=\"2\" disabled>\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"197\" height=\"36\">");
      out.print( pageData.getWord("Production Code"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td  width=\"293\" height=\"36\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" maxlength=\"5\" size=\"5\" name=\"productionCode\" onClick=\"enabledUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Hours"));
      out.write("<input type=\"radio\" name=\"productionCodeTag\" value=\"1\" checked>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Dollars"));
      out.write("<input type=\"radio\" name=\"productionCodeTag\" value=\"2\" disabled>\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"197\" height=\"36\">");
      out.print( pageData.getWord("Overtime Code"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td  width=\"293\" height=\"36\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" maxlength=\"5\" size=\"5\" name=\"overtimeCode\" onClick=\"enabledUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Hours"));
      out.write("<input type=\"radio\" name=\"overtimeCodeTag\" value=\"1\" checked>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Dollars"));
      out.write("<input type=\"radio\" name=\"overtimeCodeTag\" value=\"2\" disabled>\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"197\" height=\"36\">");
      out.print( pageData.getWord("Commission Code"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td  width=\"293\" height=\"36\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" maxlength=\"5\" size=\"5\" name=\"commissionCode\" onClick=\"enabledUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Hours"));
      out.write("<input type=\"radio\" name=\"commissionCodeTag\" value=\"1\" disabled>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Dollars"));
      out.write("<input type=\"radio\" name=\"commissionCodeTag\" value=\"2\" checked>\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"197\" height=\"36\">");
      out.print( pageData.getWord("Continuing training Code"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td  width=\"293\" height=\"36\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" maxlength=\"5\" size=\"5\" name=\"continuingTrainingCode\" onClick=\"enabledUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Hours"));
      out.write("<input type=\"radio\" name=\"continuingTrainingCodeTag\" value=\"1\" checked>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Dollars"));
      out.write("<input type=\"radio\" name=\"continuingTrainingCodeTag\" value=\"2\" disabled>\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</fieldset>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"tab-page\" id=\"tabTreats\">\r\n");
      out.write("\t\t<h2 class=\"tab\"> ");
      out.print( pageData.getWord("Commissions"));
      out.write("</h2>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tif(QueryString('mopName') != null)\r\n");
      out.write("\t\t\t\ttp1.addTabPage( document.getElementById( \"tabTreats\" ) );\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t<legend>");
      out.print( pageData.getWord("Select a MOP commission"));
      out.write("</legend>\r\n");
      out.write("\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t   <td height=\"21\" align=\"center\"><b>");
      out.print( pageData.getWord("Available commissions"));
      out.write("</b>\r\n");
      out.write("\t\t\t   </td>\r\n");
      out.write("\t\t\t   <td>\r\n");
      out.write("\t\t\t   </td>\r\n");
      out.write("\t\t\t   <td align=\"center\"><b>");
      out.print( pageData.getWord("Selected commissions"));
      out.write("</b></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t<td width=\"43%\" height=\"138\" align=\"center\">\r\n");
      out.write("\t\t\t\t <select width=\"200\" style=\"FONT-WEIGHT: bold; FONT-SIZE: 8pt; WIDTH: 200px\" name=\"availableTreatments\" size=\"10\" multiple onChange=\"enabledAddButton()\">\r\n");
      out.write("\t\t\t\t </select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"11%\" height=\"138\" bordercolordark=\"#c0c0c0\" nowrap align=\"center\">\r\n");
      out.write("\t\t\t\t <p> </p>\r\n");
      out.write("\t\t\t\t <p>\r\n");
      out.write("\t\t\t\t <button name=\"addButton\"  disabled onClick=\"chkAndAddTreatmentToMop()\" style=\"WIDTH: 40px; HEIGHT: 26px\" type=button> &gt;&gt; </button></p>\r\n");
      out.write("\t\t\t\t <button name=\"dropButton\" disabled onClick=\"chkAndDropTreatmentFromMop()\" style=\"WIDTH: 40px; HEIGHT: 26px\" type=button> &lt;&lt; </button>\r\n");
      out.write("\t\t\t\t <p>&nbsp;</p>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"288%\" height=\"138\" bordercolor=\"#000000\" align=\"center\">\r\n");
      out.write("\t\t\t\t <select width=\"200\" style=\"FONT-WEIGHT: bold; FONT-SIZE: 8pt; WIDTH: 200px\" name=\"selectedTreatments\" size=\"10\" multiple onChange=\"enabledDropButton()\">\r\n");
      out.write("\t\t\t\t </select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t   </tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</fieldset>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("<!--\r\n");
      out.write("\t<div class=\"tab-page\" id=\"tabHolidays\">\r\n");
      out.write("\t\t<h2 class=\"tab\">Holidays</h2>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tif(QueryString('mopName') != null)\r\n");
      out.write("\t\t\t\ttp1.addTabPage( document.getElementById( \"tabHolidays\" ) );\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t<legend>Holidays</legend>\r\n");
      out.write("\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t   <td height=\"21\">&nbsp;\r\n");
      out.write("\t\t\t   </td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"197\" height=\"36\"><b>Select a date</b></td>\r\n");
      out.write("\t\t\t\t\t<td  width=\"293\" height=\"36\">\r\n");
      out.write("\t\t\t\t\t\t<input onClick=\"\" type=\"text\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</fieldset>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("-->\t\r\n");
      out.write("\t<div class=\"tab-page\" id=\"tabOvertime\">\r\n");
      out.write("\t\t<h2 class=\"tab\">");
      out.print( pageData.getWord("Overtime"));
      out.write("</h2>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\ttp1.addTabPage( document.getElementById( \"tabOvertime\" ) );\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t<legend>");
      out.print( pageData.getWord("Overtime properties"));
      out.write("</legend>\r\n");
      out.write("\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t   <td height=\"21\">&nbsp;\r\n");
      out.write("\t\t\t   </td>\r\n");
      out.write("\t\t\t   <td>\r\n");
      out.write("\t\t\t   </td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"197\" height=\"36\">");
      out.print( pageData.getWord("Number of weekly hours"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td  width=\"293\" height=\"36\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" maxlength=\"5\" size=\"10\" name=\"weeklyHours\" onKeyPress=\"enabledUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<!--<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"197\" height=\"36\"><b>Multiplicative factor</b><br>(in overtime)</td>\r\n");
      out.write("\t\t\t\t\t<td  width=\"293\" height=\"36\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" maxlength=\"5\" size=\"10\" name=\"multFactor\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>-->\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("      <p>&nbsp;</p>\r\n");
      out.write("      </fieldset>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"tab-page\" id=\"tabHelp\">\r\n");
      out.write("\t\t<h2 class=\"tab\">");
      out.print( pageData.getWord("Help"));
      out.write("</h2>\r\n");
      out.write("\t\t<script type=\"text/javascript\">tp1.addTabPage( document.getElementById( \"tabHelp\" ) );</script>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>");
      out.print( pageData.getWord("Help for methods of payment"));
      out.write("</legend>\r\n");
      out.write("\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t   <td height=\"21\">&nbsp;\t\t\t   </td>\r\n");
      out.write("\t\t\t   <td>\t\t\t   </td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"600\" >\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t     <b>");
      out.print( pageData.getWord("General"));
      out.write("</b><br>\r\n");
      out.write("\t\t     ");
      out.print( pageData.getWord("This tab allows you to set a name(mandatory) for your MOP. You can also set a description and a status (active by default) for your MOP."));
      out.write("\r\n");
      out.write("\t\t\t<br><br>\r\n");
      out.write("\t\t\t<b>");
      out.print( pageData.getWord("Codes"));
      out.write("</b><br>\r\n");
      out.write("\t\t\t");
      out.print( pageData.getWord("This tab allows you to set some codes for different activities. These activities are training, integration, production, commission and continuing training. These codes represent hourly rates(by default) or amount of money."));
      out.write("\r\n");
      out.write("\t\t\t<br><br>\r\n");
      out.write("\t\t\t<!-- <b><script>document.write(MultiArray[\"Commissions\"][lang])</script> </b><br>\r\n");
      out.write("\t\t\t<script>document.write(MultiArray[\"This tab allows you to choose a treatment for your MOP. You cannot choose more than one treatment.\"][lang])</script> \r\n");
      out.write("\t\t\t<br><br>  -->\r\n");
      out.write("\t\t\t<b>");
      out.print( pageData.getWord("Overtime"));
      out.write("</b><br>\r\n");
      out.write("\t\t\t");
      out.print( pageData.getWord("This tab allows you to set a limit from which overtime hours will be counted. You can also set the multiplicative factor for overtime hours."));
      out.write("\r\n");
      out.write("\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t   <td align=\"center\">\r\n");
      out.write("\t   \r\n");
      out.write("\t   <input disabled id=\"save\" name=\"updateInfo\" type=\"button\" value='");
      out.print( pageData.getWord("Update"));
      out.write("'onClick=\"validateInfo()\">\r\n");
      out.write("\t\t<input name=\"deleteMop\" type=\"button\" value='");
      out.print( pageData.getWord("Delete"));
      out.write("' onClick=\"askDelete()\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("        </td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
 pageData.closeConnection(); 
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
