package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.*;
import aheevaManager.ressources.*;
import java.text.*;
import aheevaManager.schedule.*;
import aheevaManager.ressources.*;

public final class mopTreatment1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/aheevaManager/Resources_pages/mopTreatmentsFunctions_labels.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
    pageData.openConnection();

      out.write("\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("\t\t<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"tab_luna.css\">\r\n");
      out.write("\t\t\t<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style_2.css\">\r\n");
      out.write("\t\t\t\t<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t\t\t\t<LINK href=\"livestats.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t\t\t\t\t<meta http-equiv=\"Content-Language\" content=\"en-us\">\r\n");
      out.write("\t\t\t\t\t\t<style type=\"text/css\"> .dynamic-tab-pane-control .tab-page { height: 100%; overflow: auto; }\r\n");
      out.write("\t.dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page { /*height: 100px; }\r\n");
      out.write("\thtml, body { /* background: ThreeDFace; */ }\r\n");
      out.write("\tform { margin: 0; padding: 0; }\r\n");
      out.write("\t/* over ride styles from webfxlayout */ body { margin: 10px; width: auto; height: auto; }\r\n");
      out.write("\t.dynamic-tab-pane-control h2 { text-align: center; width: auto; }\r\n");
      out.write("\t.dynamic-tab-pane-control h2 a { display: inline; width: auto; }\r\n");
      out.write("\t.dynamic-tab-pane-control a:hover { background: transparent; }\r\n");
      out.write("\t</style>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageMopTrFData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageMopTrFData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
pageMopTrFData.openConnection();
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("var mopTreat= new Array();\r\n");
      out.write("mopTreat[0]=\"");
      out.print( pageMopTrFData.getWord("Save"));
      out.write("\";\r\n");
      out.write("mopTreat[1]=\"");
      out.print( pageMopTrFData.getWord("MOP Fill Fields"));
      out.write("\";\r\n");
      out.write("mopTreat[2]=\"");
      out.print( pageMopTrFData.getWord("MOP Error Max"));
      out.write("\";\r\n");
      out.write("mopTreat[3]=\"");
      out.print( pageMopTrFData.getWord("MOP Error Negative"));
      out.write("\";\r\n");
      out.write("mopTreat[4]=\"");
      out.print( pageMopTrFData.getWord("You must enter a Mop Treatment name"));
      out.write("\";\r\n");
      out.write("mopTreat[5]=\"");
      out.print( pageMopTrFData.getWord("Invalid use of character"));
      out.write("\";\r\n");
      out.write("mopTreat[6]=\"");
      out.print( pageMopTrFData.getWord("MOP Error Max Negative"));
      out.write("\";\r\n");
      out.write("mopTreat[7]=\"");
      out.print( pageMopTrFData.getWord("MOP Change Name"));
      out.write("\";\r\n");
      out.write("mopTreat[8]=\"");
      out.print( pageMopTrFData.getWord("Are you sure you wish to delete this commission?"));
      out.write("\";\r\n");
      out.write("mopTreat[9]=\"");
      out.print( pageMopTrFData.getWord("Delete"));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 pageMopTrFData.closeConnection(); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t<script language=\"JavaScript\" type=\"text/javascript\" src=\"jsUtil.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t<script language=\"javascript\" type=\"text/javascript\" src=\"Browser.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t<script language=\"javascript\" type=\"text/javascript\" src=\"tabpane.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t<script language=\"javascript\" type=\"text/javascript\" src=\"mopTreatmentsFunctions.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t<script language=\"javascript\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("var nrows = 1 ;\r\n");
      out.write("var maxrow = 1;\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("<style type=\"text/css\"> tr.main_line{ vertical-align:top; }\r\n");
      out.write("\ttd.main1{ text-align:center; width:33%; }\r\n");
      out.write("\ttd.main2{ text-align:center; width:25%; }\r\n");
      out.write("\ttd.main3{ text-align:center; /*prend le width restant*/ }\r\n");
      out.write("\ttd.element_right{ text-align:right; }\r\n");
      out.write("\ttd.element_center{ text-align:center; }\r\n");
      out.write("\ttable.main_line_case{ display:\"none\"; }\r\n");
      out.write("\ta.delete{ text-decoration:underline; color:000000; }\r\n");
      out.write("\ta.delete:hover{ text-decoration:underline; color:000000; }\r\n");
      out.write("\ta.delete:active{ text-decoration:underline; color:000000; }\r\n");
      out.write("\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body class=\"f_i_com_body\" onLoad=\"displayMopTreatmentInfo()\">\r\n");
      out.write("\t\t<div class=\"tab-pane\" id=\"tabPane1\">\r\n");
      out.write("\t\t\t<form name=\"mop_treatment_form\" onKeyDown=\"KeyDownHandler(save)\">\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("tp1 = new WebFXTabPane( document.getElementById( \"tabPane1\" ) );\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t<div class=\"tab-page\" id=\"tabGeneral\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"tab\">");
      out.print( pageData.getWord("General"));
      out.write("</h2>\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( pageData.getWord("General settings"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</legend>\r\n");
      out.write("\t\t\t\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td height=\"22\">&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"197\" height=\"22\">");
      out.print( pageData.getWord("Commission name"));
      out.write("<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print( pageData.getWord("(associated to a MOP)"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"292\" height=\"22\" align=\"left\"><input type=\"text\" name=\"mopTreatmentName\" onClick=\"enabledUpdateButton()\" size=\"20\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"197\" height=\"24\">");
      out.print( pageData.getWord("Description"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"292\" height=\"50\"><textarea rows=\"3\" name=\"mopTreatmentDescription\" cols=\"41\" onClick=\"enabledUpdateButton()\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"197\" height=\"25\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print( pageData.getWord("Max commission value"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"maxCommissionValue\" type=\"text\" name=\"maxCommissionValue\" size=\"10\" value=\"0.00\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonClick=\"enabledUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print( pageData.getWord("per work hour"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"197\" height=\"25\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print( pageData.getWord("Active"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"mopTreatmentStatus\" type=\"checkbox\" name=\"mopTreatmentStatus\" value=\"ON\" onClick=\"enabledUpdateButton()\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tchecked>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!------------ TAB COMMISSION ----------------------------\r\n");
      out.write("\t\t\t\t-Fixed commission\r\n");
      out.write("\t\t\t\t-Sales-based commission:-Average sales per hour\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t-Sales per week\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t-Sales per unit\r\n");
      out.write("\t\t\t\t-Commission based on group average:\t-Net conversion rate\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t-Sales per week\r\n");
      out.write("\t\t\t\t-Performance-based commission:\t-Net conversion rate\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t-Sales per week\r\n");
      out.write("\t\t\t\t-->\r\n");
      out.write("\t\t\t\t<div class=\"tab-page\" id=\"tabCommissions\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"tab\">");
      out.print( pageData.getWord("Commissions"));
      out.write("</h2>\r\n");
      out.write("\t\t\t\t\t<fieldset id=\"FIELDSET2\">\r\n");
      out.write("\t\t\t\t\t\t<legend>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( pageData.getWord("Commissions settings"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</legend>\r\n");
      out.write("\t\t\t\t\t\t<table border=\"0\" width=\"100%\" height=\"100%\" ID=\"Table1\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"main_line\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"main1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tPremier field set: Choose commission type\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<legend>");
      out.print( pageData.getWord("Step"));
      out.write(" #1</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>");
      out.print( pageData.getWord("Choose commission type"));
      out.write("</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table  class=\"main_line_case2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" height=\"21\">");
      out.print( pageData.getWord("Fixed commission"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"Radio1.1\" type=\"radio\" name=\"Radio1\" value=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tonClick=\"javascript:toggleLayer('fixed')\" onChange=\"enabledUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" height=\"20\">");
      out.print( pageData.getWord("Sales-based commissions"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"Radio1.2\" type=\"radio\" name=\"Radio1\" value=\"2\" onClick=\"javascript:toggleLayer('sales')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tonChange=\"enabledUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" height=\"20\">");
      out.print( pageData.getWord("Commissions based on group average"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"Radio1.3\" type=\"radio\" name=\"Radio1\" value=\"3\" onClick=\"javascript:toggleLayer('group')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tonChange=\"enabledUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" height=\"20\">");
      out.print( pageData.getWord("Performance-based commission"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"Radio1.4\" type=\"radio\" name=\"Radio1\" value=\"4\" onClick=\"javascript:toggleLayer('group')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tonChange=\"enabledUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"main2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t\t\t\t\t2è fieldset: Contient toutes les options relatives au choix du premier field set\r\n");
      out.write("\t\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<legend>");
      out.print( pageData.getWord("Step"));
      out.write("#2</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table id=\"Sales-based_table\" class=\"main_line_case\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"element_center\"><b>");
      out.print( pageData.getWord("Based on"));
      out.write("</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"element_right\">");
      out.print( pageData.getWord("Average sales per hour"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"Radio2.1.1\" type=\"radio\" name=\"Radio2_1\" value=\"1\" onChange=\"enabledUpdateButton()\" onClick=\"javascript:toggleLayer('range')\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"element_right\">");
      out.print( pageData.getWord("Sales per week"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"Radio2.1.2\" type=\"radio\" name=\"Radio2_1\" value=\"2\" onChange=\"enabledUpdateButton()\" onClick=\"javascript:toggleLayer('range')\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"element_right\">");
      out.print( pageData.getWord("Sales per unit"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"Radio2.1.3\" type=\"radio\" name=\"Radio2_1\" value=\"3\" onChange=\"enabledUpdateButton()\" onClick=\"javascript:toggleLayer('unit')\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table id=\"group_average\" class=\"main_line_case\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"element_center\"><b>");
      out.print( pageData.getWord("Based on"));
      out.write("</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"element_right\">");
      out.print( pageData.getWord("Net conversion rate"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"Radio2.2.1\" type=\"radio\" name=\"Radio2_2\" value=\"1\" onChange=\"enabledUpdateButton()\" onClick=\"javascript:toggleLayer('range')\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"element_right\">");
      out.print( pageData.getWord("Sales per week"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"Radio2.2.2\" type=\"radio\" name=\"Radio2_2\" value=\"2\" onChange=\"enabledUpdateButton()\" onClick=\"javascript:toggleLayer('range')\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td  class=\"main3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t\t\t\t\t3è fieldset: Les box pour entrer les données\r\n");
      out.write("\t\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<legend>");
      out.print( pageData.getWord("Step"));
      out.write(" #3</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table ID=\"field3.1\" class=\"main_line_case\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr><td class=\"element_center\"><b>Set the amount</b></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr><td class=\"element_center\">Pay:<input type=\"text\" size=\"5\" id=\"amount\" NAME=\"amount\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table ID=\"field3.2\" class=\"main_line_case\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"element_center\"><b>");
      out.print( pageData.getWord("Set your ranges"));
      out.write("</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"element_center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"addRowButton4\" name=\"addRowButton4\" type=\"button\" value='");
      out.print( pageData.getWord("Add a new range"));
      out.write("' onClick=\"addMyRow('', '', '');enabledUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"element_center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"ranges\" style=\"MARGIN: 0px 5px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!------------------------------- tab HELP ------------------------------------------->\r\n");
      out.write("\t\t\t\t<div class=\"tab-page\" id=\"tabHelp\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"tab\">");
      out.print( pageData.getWord("Help"));
      out.write("</h2>\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( pageData.getWord("Help for commissions"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</legend>\r\n");
      out.write("\t\t\t\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td height=\"21\">&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"600\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print( pageData.getWord("General"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print( pageData.getWord("This tab allows you to set a name(mandatory) for your MOP treatment. You can also set a description and a status (active by default) for your MOP treatment."));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print( pageData.getWord("Commissions"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print( pageData.getWord("This tab allows you to set the type of commission for your treatment. If your treatment doesn't need a commission, you must select a fixed commission and set its value to 0."));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<input disabled id=\"save\" name=\"updateInfo\" type=\"button\" value='");
      out.print( pageData.getWord("Update"));
      out.write("' onClick=\"validateInfo()\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"delete-button\" name=\"deleteMopTreatment\" type=\"button\" value='");
      out.print( pageData.getWord("Delete"));
      out.write("' onClick=\"askDelete()\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Statistiques -->\r\n");
      out.write("\t\t<script type=\"text/javascript\">tp1.addTabPage( document.getElementById( \"tabGeneral\" ) );</script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tdocument.getElementById( \"tabHelp\" ).style.display = \"none\";\r\n");
      out.write("\t\t\tif(QueryString('mop_treatment_name') != \"\"){\r\n");
      out.write("\t\t\t\ttp1.addTabPage( document.getElementById( \"tabCommissions\" ) );\t\t\r\n");
      out.write("\t\t\t\ttp1.addTabPage( document.getElementById( \"tabHelp\" ) );\r\n");
      out.write("\t\t\tdocument.getElementById( \"tabHelp\" ).style.display = \"block\";\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</body>\r\n");
 pageData.closeConnection(); 
      out.write("\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
