package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.*;
import aheevaManager.ressources.*;

public final class notReadyReason1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
    pageData.openConnection();

      out.write("\r\n");
      out.write("<LINK href=\"style.css\" type=text/css rel=stylesheet >\r\n");
      out.write("<LINK href=\"livestats.css\" \trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<meta http-equiv=Content-Language content=en-us>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<script language=JavaScript src=\"jsUtil.js\"></script>\r\n");
      out.write("<script language=javascript src=\"Browser.js\" type=text/javascript></script>\r\n");
      out.write("\r\n");
      out.write("<script language=javascript type=text/javascript>\r\n");
      out.write("var NRR_DBID       \t= '';\r\n");
      out.write("var NRRName          \t= '';\r\n");
      out.write("var notReadyReasonName\t\t= '';\r\n");
      out.write("var tenant_dbid\t\t= \"NULL\";\r\n");
      out.write("\r\n");
      out.write("function enabledUpdateButton()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById(\"updateInfo\").disabled = false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checkOnUnload()\r\n");
      out.write("{\r\n");
      out.write("\t//document.nrr.updateInfo.disabled = false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function enableReload()\r\n");
      out.write("{\r\n");
      out.write("   appletObj.fReloadMenu = true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/***********************************************************************\r\n");
      out.write("************************************************************************/\r\n");
      out.write("\r\n");
      out.write("function displayNRRInfo()\r\n");
      out.write("{\r\n");
      out.write("\tvar notReadyReasonName;\r\n");
      out.write("\r\n");
      out.write("\ttenant_dbid = normalizeString(QueryString('tenant_dbid'));\r\n");
      out.write("\tnotReadyReasonName   = normalizeString(QueryString('NRR_name'));\r\n");
      out.write("\t//ourCaption  = document.getElementById(\"caption\");\r\n");
      out.write("\r\n");
      out.write("\tif(notReadyReasonName == '')\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//ourCaption.innerHTML = \"<h3>Add new Not Ready Reason</h3>\";\r\n");
      out.write("\t\tdocument.getElementById(\"updateInfo\").value = \"");
      out.print( pageData.getWord("Save"));
      out.write("\";\r\n");
      out.write("\t\tdocument.getElementById(\"deleteNRR\").disabled = true;\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//ourCaption.innerHTML = \"<h3>Modify Not Ready Reason</h3>\";\r\n");
      out.write("\t\tdocument.getElementById(\"NRRName\").value = notReadyReasonName;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar NRRDetails  =  String( appletObj.getNotReadyReasonInfo(notReadyReasonName) );\r\n");
      out.write("\t\t//alert(NRRDetails);\r\n");
      out.write("\t\t// parse info received\r\n");
      out.write("\t\tvar jsDetails = NRRDetails + \"\";\r\n");
      out.write("\t\tarrayDetails = jsDetails.split(\"|\");\r\n");
      out.write("\r\n");
      out.write("\t\tfor (i = 0; i <arrayDetails.length; i++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(i == 0) // DBID\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tNRR_DBID = arrayDetails[i];\r\n");
      out.write("\t\t\t\t//alert(\"id = \"+ NRR_DBID);\r\n");
      out.write("\t\t\t\t//document.getElementById(\"NRRId\").value = NRR_DBID;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(i == 1) //State\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif(arrayDetails[i] == '1')\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"deleteNRR\").disabled = false;\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"state\").checked = true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"deleteNRR\").disabled = false;\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"state\").checked = false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (i == 2)//global\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif (arrayDetails[i] == '1')\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"globalNRR\").checked = true;\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"globalNRR\").checked = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (i == 3)// in_productivity\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif (arrayDetails[i] == '1')\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"in_productivity\").checked = true;\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"in_productivity\").checked = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t//updateStatisticsOptions();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/***********************************************************************\r\n");
      out.write("************************************************************************/\r\n");
      out.write("\r\n");
      out.write("function validateInfo()\r\n");
      out.write("{\r\n");
      out.write("\tvar\tnotReadyReasonName   = normalizeString(QueryString('NRR_name'));\r\n");
      out.write("\t// Verify that the schedule name is set\r\n");
      out.write("\r\n");
      out.write("\tif (document.getElementById(\"NRRName\").value == '')\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("You must enter a not ready reason name"));
      out.write("\");\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(validation(document.getElementById(\"NRRName\").value)==0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("Invalid use of character"));
      out.write("\");\r\n");
      out.write("\t\tdocument.getElementById(\"NRRName\").focus();\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(document.getElementById(\"NRRName\").value.length > 17 ){//NRR exceeds the Starphone maximal value of 17\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("NRR Too Long"));
      out.write("\");\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar alReadyExist = false;\r\n");
      out.write("\t\tvar reasons = String( appletObj.getAllNotReadyReasons(tenant_dbid) );\r\n");
      out.write("\t\tjsReasons = reasons.split(\"|\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor(var q = 0; q < jsReasons.length; q++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tthisReason = jsReasons[q];\r\n");
      out.write("\t\t\t\tthisReasonArray = thisReason.split(\",\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif( document.getElementById(\"NRRName\").value == thisReasonArray[1] && notReadyReasonName != document.getElementById(\"NRRName\").value) //la reason existe deja\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\talReadyExist = true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tif(alReadyExist)\r\n");
      out.write("\t\t\talert(\"");
      out.print( pageData.getWord("Not ready reason already exists!"));
      out.write("\");\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tappletObj.saveNotReadyReason(\tNRR_DBID,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttenant_dbid,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"NRRName\").value,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"state\").checked == true ? '1':'0',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"globalNRR\").checked == true ? '1':'0',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"in_productivity\").checked == true ? '1':'0'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t);\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("\t\t\tNRR_DBID = String(appletObj.getNRRDbidByName(document.getElementById(\"NRRName\").value));\r\n");
      out.write("\t\t\t//alert(\"#NRRDbid = \" + NRR_DBID);\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (document.getElementById(\"globalNRR\").checked == true)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t// Lire tous les dbid des agents groups existants\r\n");
      out.write("\t\t\t\tvar allAgentGroups = String(appletObj.getAgentGroups()) + \"\";\r\n");
      out.write("\t\t\t\t//alert(\"agtgroup = \" + allAgentGroups);\r\n");
      out.write("\t\t\t\tvar jsAllAgentGroups = allAgentGroups.split(\"|\");\r\n");
      out.write("\t\t\t\tfor (i = 0; i < jsAllAgentGroups.length; i++)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tvar curAgentGroupInfo = jsAllAgentGroups[i];\r\n");
      out.write("\t\t\t\t\t//alert(\"cur Agt grp = \"+ curAgentGroupInfo)\r\n");
      out.write("\t\t\t\t\tvar jsCurAgentGroupInfo = curAgentGroupInfo.split(\",\");\r\n");
      out.write("\t\t\t\t\tvar group_id = jsCurAgentGroupInfo[0];\r\n");
      out.write("\t\t\t\t\t//alert(group_id);\r\n");
      out.write("\t\t\t\t\t// verifier l existence de l'association de chaque agt_group avec le nrr actuel dans le systeme\r\n");
      out.write("\t\t\t\t\tvar assocExist = Boolean(appletObj.getAssocAgentGroupNRR(NRR_DBID, group_id));\r\n");
      out.write("\t\t\t\t\t// alert(\"asoc exist = \" + assocExist);\r\n");
      out.write("\t\t\t\t\t// si cette association n'existe pas, la creer\r\n");
      out.write("\t\t\t\t\tif (assocExist == false)\r\n");
      out.write("\t\t\t\t\t\t//alert(assocExist);\r\n");
      out.write("\t\t\t\t\t\tappletObj.addGlobalReasonToGroup(document.getElementById(\"NRRName\").value, group_id);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("*/\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\tdocument.getElementById(\"updateInfo\").disabled=true;\t// reset the button to disabled\r\n");
      out.write("\t\t\tdocument.location.href = \"../defaultpage.htm\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/***********************************************************************\r\n");
      out.write("************************************************************************/\r\n");
      out.write("\r\n");
      out.write("function askDelete()\r\n");
      out.write("{\r\n");
      out.write("\tanswer = confirm(\"");
      out.print( pageData.getWord("Are you sure, you wish to delete this Reason? This can affect your reports!"));
      out.write("\");\r\n");
      out.write("\tif(answer)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tappletObj.deleteNotReadyReason(NRR_DBID);\r\n");
      out.write("\t\t// refresh the current page\r\n");
      out.write("\t\tdocument.location = \"../defaultpage.htm\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!--<body BGCOLOR=\"#C0C0C0\" TEXT=\"#000000\" LINK=\"#000066\" VLINK=\"#666666\" onLoad=\"displayCampaignInfo()\" onUnload=\" return checkOnUnload()\"> -->\r\n");
      out.write("<script language=javascript id=clientEventHandlersJS>\r\n");
      out.write("<!--\r\n");
      out.write("//function Checkbox4_onclick() {}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .contentText{\r\n");
      out.write("\tfont:\t\t\t12px Tahoma;\r\n");
      out.write("\tcolor:\t\t\tBlack;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\tclear:\t\t\tboth;\r\n");
      out.write("\tborder:\t\t\t1px solid rgb( 145, 155, 156 );\r\n");
      out.write("\tbackground:\t\trgb( 252, 252, 254 );\r\n");
      out.write("\tz-index:\t\t2;\r\n");
      out.write("\tposition:\t\trelative;\r\n");
      out.write("\ttop:\t\t\t-2px;\r\n");
      out.write("\r\n");
      out.write("\tfont:\t\t\t11px Tahoma;\r\n");
      out.write("\tcolor:\t\t\tBlack;\r\n");
      out.write("\r\n");
      out.write("\tfilter:\t\t\tprogid:DXImageTransform.Microsoft.Gradient(StartColorStr=#fffcfcfe, EndColorStr=#fff4f3ee, GradientType=0)\r\n");
      out.write("\t\t\t\t\tprogid:DXImageTransform.Microsoft.Shadow(Color=#ff919899, Strength=2, Direction=135);\r\n");
      out.write("\r\n");
      out.write("\t/* 244, 243, 238 */\r\n");
      out.write("\t/*145, 155, 156 */\r\n");
      out.write("\tpadding:\t\t10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-row {\r\n");
      out.write("\tz-index:\t\t1;\r\n");
      out.write("\twhite-space:\tnowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-row .tab.selected {\r\n");
      out.write("\twidth:\t\t\t\t74px  ;\r\n");
      out.write("\theight:\t\t\t\t18px  ;\r\n");
      out.write("\tbackground-image:\turl( \"tab.active.png\" )  ;\r\n");
      out.write("\tbackground-repaet:\tno-repeat;\r\n");
      out.write("\r\n");
      out.write("\tborder-bottom-width:\t0;\r\n");
      out.write("\tz-index:\t\t3;\r\n");
      out.write("\tpadding:\t\t2px 0 0px 0;\r\n");
      out.write("\tmargin:\t\t\t1px -3px -3px 0px;\r\n");
      out.write("\ttop:\t\t\t-2px;\r\n");
      out.write("\tfont:\t\t\t11px Tahoma;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-row .tab a {\r\n");
      out.write("\tfont:\t\t\t\t11px Tahoma;\r\n");
      out.write("\tcolor:\t\t\t\tBlack;\r\n");
      out.write("\ttext-decoration:\tnone;\r\n");
      out.write("\tcursor:\t\t\t\tdefault;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-row .tab.hover {\r\n");
      out.write("\tfont:\t\t\t\t11px Tahoma;\r\n");
      out.write("\twidth:\t\t\t\t70px;\r\n");
      out.write("\theight:\t\t\t\t16px;\r\n");
      out.write("\tbackground-image:\turl( \"tab.hover.png\" );\r\n");
      out.write("\tbackground-repaet:\tno-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html, body {\r\n");
      out.write("/*\tbackground:\tThreeDFace; */\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("\tmargin:\t\t0;\r\n");
      out.write("\tpadding:\t0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* over ride styles from webfxlayout */\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:\t\t10px;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("\theight:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control h2 {\r\n");
      out.write("\ttext-align:\tcenter;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control h2 a {\r\n");
      out.write("\tdisplay:\tinline;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dynamic-tab-pane-control a:hover {\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" .dynamic-tab-pane-control.tab-pane {\r\n");
      out.write("\tposition:\trelative;\r\n");
      out.write("\twidth:\t\t100%;\r\n");
      out.write("\tmargin-right:\t-2px;\r\n");
      out.write("/*\theight:\t\t200px;*/\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("    // Associate a default button with pressing the Enter key\r\n");
      out.write("\tfunction KeyDownHandler(btn)\r\n");
      out.write("    {\r\n");
      out.write("        // process only the Enter key\r\n");
      out.write("        if (event.keyCode == 13)\r\n");
      out.write("        {\r\n");
      out.write("            // cancel the default submit\r\n");
      out.write("            event.returnValue=false;\r\n");
      out.write("            event.cancel = true;\r\n");
      out.write("            // submit the form by programmatically clicking the specified button\r\n");
      out.write("            btn.click();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\t<body class=\"no_ready_body\" onLoad=\"displayNRRInfo()\"><!--  onUnload=\" return checkOnUnload()\" -->\r\n");
      out.write("\t<div class=\"dynamic-tab-pane-control\">\r\n");
      out.write("\t\t<div class=\"tab-pane\" id=\"tabPane1\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("    <div class=\"tab-page\" id=\"general\"> \r\n");
      out.write("      <fieldset>\r\n");
      out.write("      <legend> \r\n");
      out.write("      ");
      out.print( pageData.getWord("General"));
      out.write(" \r\n");
      out.write("      </legend>\r\n");
      out.write("      <form name=\"theForm\" onKeyDown=\"KeyDownHandler(Button3)\">\r\n");
      out.write("        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\" width=\"100%\">\r\n");
      out.write("          <tr> \r\n");
      out.write("            <td width='40%' height=25><b> \r\n");
      out.write("              ");
      out.print( pageData.getWord("Not ready reason name"));
      out.write("\r\n");
      out.write("              </b></td>\r\n");
      out.write("            <td align=left width='60%' height=25> <input id=\"NRRName\" type=text onChange=\"enabledUpdateButton()\" onClick=\"enabledUpdateButton()\" size=20 name=\"NRRName\"> \r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr> \r\n");
      out.write("            <td width='40%' height=\"25\"></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr> \r\n");
      out.write("            <td width='40%' height=25><b> \r\n");
      out.write("               ");
      out.print( pageData.getWord("Active"));
      out.write("\r\n");
      out.write("              </b> <input id=\"state\" onClick=\"/*enableReload();*/ enabledUpdateButton()\" type=\"checkbox\" checked value=\"ON\" name=\"state\"> \r\n");
      out.write("              &nbsp;&nbsp;<b> \r\n");
      out.write("              ");
      out.print( pageData.getWord("Global"));
      out.write("\r\n");
      out.write("              </b> <input id=\"globalNRR\" onClick=\"/*enableReload();*/ enabledUpdateButton()\" type=\"checkbox\" checked  value=\"ON\" name=\"globalNRR\"> \r\n");
      out.write("            </td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr> \r\n");
      out.write("            <td width='40%'> <b> \r\n");
      out.write("               ");
      out.print( pageData.getWord("Use this not ready reason in productivity"));
      out.write("\r\n");
      out.write("              </b> <input id=\"in_productivity\" onClick=\"/*enableReload();*/ enabledUpdateButton()\" type=\"checkbox\" checked value=\"ON\" name=\"in_productivity\"> \r\n");
      out.write("            </td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr> \r\n");
      out.write("            <td height=\"10\"></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("      </form>\r\n");
      out.write("      </fieldset>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<table border=\"0\" height=\"40\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t<tr valign=\"top\">\r\n");
      out.write("\t\t\t\t<td align=\"left\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<button id=Button3 style=\"WIDTH: 85px; HEIGHT: 20px\" disabled onclick=validateInfo() name=updateInfo type=button> ");
      out.print( pageData.getWord("Update"));
      out.write("</button> &nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<button id=Button4 style=\"WIDTH: 85px; HEIGHT: 20px\" onclick=askDelete()  name=deleteNRR type=button > ");
      out.print( pageData.getWord("Delete"));
      out.write("</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
 pageData.closeConnection(); 
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
