package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.*;
import aheevaManager.ressources.*;
import java.text.*;
import aheevaManager.schedule.*;
import aheevaManager.ressources.*;
import java.util.*;
import jxl.*;

public final class rta1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/aheevaManager/Resources_pages/xc2_default_labels.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
    pageData.openConnection();

      out.write("\r\n");
      out.write("<LINK href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"xc2_default.css\" type=\"text/css\">\r\n");
      out.write("<LINK href=\"livestats.css\" \trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Start Tab pane -->\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"tab_luna.css\" />\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style_2.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\" href=\"slider/css/luna.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t100px;\r\n");
      out.write("}\r\n");
      out.write("html, body {\r\n");
      out.write("\t/*background:\tThreeDFace;*/\r\n");
      out.write("}\r\n");
      out.write("form {\r\n");
      out.write("\tmargin:\t\t0;\r\n");
      out.write("\tpadding:\t0;\r\n");
      out.write("}\r\n");
      out.write("/* over ride styles from webfxlayout */\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:\t\t10px;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("\theight:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 {\r\n");
      out.write("\ttext-align:\tcenter;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 a {\r\n");
      out.write("\tdisplay:\tinline;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control a:hover {\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../Resources_pages/tabpane.js\"></script>\r\n");
      out.write("<!-- End Tab Pane -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Calendrier début -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pagexc2Data = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pagexc2Data.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
pagexc2Data.openConnection();
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("// variables of labels;// \r\n");
      out.write("var phrase= new Array();\r\n");
      out.write("phrase[0]=\"");
      out.print( pagexc2Data.getWord("January"));
      out.write("\";\r\n");
      out.write("phrase[1]=\"");
      out.print( pagexc2Data.getWord("February"));
      out.write("\";\r\n");
      out.write("phrase[2]=\"");
      out.print( pagexc2Data.getWord("March"));
      out.write("\";\r\n");
      out.write("phrase[3]=\"");
      out.print( pagexc2Data.getWord("April"));
      out.write("\";\r\n");
      out.write("phrase[4]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";         \r\n");
      out.write("phrase[5]=\"");
      out.print( pagexc2Data.getWord("June"));
      out.write("\";\r\n");
      out.write("phrase[6]=\"");
      out.print( pagexc2Data.getWord("July"));
      out.write("\";\r\n");
      out.write("phrase[7]=\"");
      out.print( pagexc2Data.getWord("August"));
      out.write("\";\r\n");
      out.write("phrase[8]=\"");
      out.print( pagexc2Data.getWord("September"));
      out.write("\";\r\n");
      out.write("phrase[9]=\"");
      out.print( pagexc2Data.getWord("October"));
      out.write("\";\r\n");
      out.write("phrase[10]=\"");
      out.print( pagexc2Data.getWord("November"));
      out.write("\";\r\n");
      out.write("phrase[11]=\"");
      out.print( pagexc2Data.getWord("December"));
      out.write("\";\r\n");
      out.write("phrase[12]=\"");
      out.print( pagexc2Data.getWord("Jan"));
      out.write("\";\r\n");
      out.write("phrase[13]=\"");
      out.print( pagexc2Data.getWord("Feb"));
      out.write("\";\r\n");
      out.write("phrase[14]=\"");
      out.print( pagexc2Data.getWord("Mar"));
      out.write("\";\r\n");
      out.write("phrase[15]=\"");
      out.print( pagexc2Data.getWord("Apr"));
      out.write("\";\r\n");
      out.write("phrase[16]=\"");
      out.print( pagexc2Data.getWord("May"));
      out.write("\";\r\n");
      out.write("phrase[17]=\"");
      out.print( pagexc2Data.getWord("Jun"));
      out.write("\";\r\n");
      out.write("phrase[18]=\"");
      out.print( pagexc2Data.getWord("Jul"));
      out.write("\";\r\n");
      out.write("phrase[19]=\"");
      out.print( pagexc2Data.getWord("Aug"));
      out.write("\";\r\n");
      out.write("phrase[20]=\"");
      out.print( pagexc2Data.getWord("Sep"));
      out.write("\";\r\n");
      out.write("phrase[21]=\"");
      out.print( pagexc2Data.getWord("Oct"));
      out.write("\";\r\n");
      out.write("phrase[22]=\"");
      out.print( pagexc2Data.getWord("Nov"));
      out.write("\";\r\n");
      out.write("phrase[23]=\"");
      out.print( pagexc2Data.getWord("Dec"));
      out.write("\";\r\n");
      out.write("phrase[24]=\"");
      out.print( pagexc2Data.getWord("Sunday"));
      out.write("\";\r\n");
      out.write("phrase[25]=\"");
      out.print( pagexc2Data.getWord("Monday"));
      out.write("\";\r\n");
      out.write("phrase[26]=\"");
      out.print( pagexc2Data.getWord("Tuesday"));
      out.write("\";\r\n");
      out.write("phrase[27]=\"");
      out.print( pagexc2Data.getWord("Wednesday"));
      out.write("\";\r\n");
      out.write("phrase[28]=\"");
      out.print( pagexc2Data.getWord("Thursday"));
      out.write("\";\r\n");
      out.write("phrase[29]=\"");
      out.print( pagexc2Data.getWord("Friday"));
      out.write("\";\r\n");
      out.write("phrase[30]=\"");
      out.print( pagexc2Data.getWord("Saturday"));
      out.write("\";\r\n");
      out.write("phrase[31]=\"");
      out.print( pagexc2Data.getWord("Sun"));
      out.write("\";\r\n");
      out.write("phrase[32]=\"");
      out.print( pagexc2Data.getWord("Mon"));
      out.write("\";\r\n");
      out.write("phrase[33]=\"");
      out.print( pagexc2Data.getWord("Tue"));
      out.write("\";\r\n");
      out.write("phrase[34]=\"");
      out.print( pagexc2Data.getWord("Wed"));
      out.write("\";\r\n");
      out.write("phrase[35]=\"");
      out.print( pagexc2Data.getWord("Thu"));
      out.write("\";\r\n");
      out.write("phrase[36]=\"");
      out.print( pagexc2Data.getWord("Fri"));
      out.write("\";\r\n");
      out.write("phrase[37]=\"");
      out.print( pagexc2Data.getWord("Sat"));
      out.write("\";\r\n");
      out.write("phrase[38]=\"");
      out.print( pagexc2Data.getWord("Su"));
      out.write("\";\r\n");
      out.write("phrase[39]=\"");
      out.print( pagexc2Data.getWord("Mo"));
      out.write("\";\r\n");
      out.write("phrase[40]=\"");
      out.print( pagexc2Data.getWord("Tu"));
      out.write("\";\r\n");
      out.write("phrase[41]=\"");
      out.print( pagexc2Data.getWord("We"));
      out.write("\";\r\n");
      out.write("phrase[42]=\"");
      out.print( pagexc2Data.getWord("Th"));
      out.write("\";\r\n");
      out.write("phrase[43]=\"");
      out.print( pagexc2Data.getWord("Fr"));
      out.write("\";\r\n");
      out.write("phrase[44]=\"");
      out.print( pagexc2Data.getWord("Sa"));
      out.write("\";\r\n");
      out.write("phrase[45]=\"");
      out.print( pagexc2Data.getWord(" Today "));
      out.write("\";\r\n");
      out.write("phrase[46]=\"");
      out.print( pagexc2Data.getWord("Clear"));
      out.write("\";\r\n");
      out.write("phrase[47]=\"");
      out.print( pagexc2Data.getWord("Back"));
      out.write("\";\r\n");
      out.write("phrase[48]=\"");
      out.print( pagexc2Data.getWord("Close"));
      out.write("\";\r\n");
      out.write("phrase[49]=\"");
      out.print( pagexc2Data.getWord("Reset"));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 pagexc2Data.closeConnection(); 
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"xc2_default.js\"></script>\r\n");
      out.write("<script language=\"javascript\">xcAutoHide=1000;</script>\r\n");
      out.write("<script language=\"javascript\" src=\"xc2_inpage.js\"></script>\r\n");
      out.write("<!-- Calendrier fin -->\r\n");
      out.write("<script language=\"JavaScript\" src=\"jsUtil.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var vValue = normalizeString(QueryString('type'));\r\n");
      out.write("  var tenant_dbid = normalizeString(QueryString('tenant_dbid'));\r\n");
      out.write("\r\n");
      out.write("function loadAgent(){\r\n");
      out.write("\r\n");
      out.write("  while(document.theForm.objects.length > 0){\r\n");
      out.write("    document.theForm.objects.options[0]= null;\r\n");
      out.write("  }\r\n");
      out.write("  var jsAgents;\r\n");
      out.write("  var myOption;\r\n");
      out.write("  if (document.theForm.ckbox.checked == true)\r\n");
      out.write("  {\r\n");
      out.write("    //Get all agents name\r\n");
      out.write("    var agents = String( appletObj.getAgentsByName(tenant_dbid) );\r\n");
      out.write("    jsAgents = agents + \"\";\r\n");
      out.write("    arrayAgents = jsAgents.split(\"|\");\r\n");
      out.write("    for (j = 0; j <arrayAgents.length; j++){\r\n");
      out.write("\t\tvar iStartPos = arrayAgents[j].indexOf('[');\r\n");
      out.write("\t\tvar iEndPos   = arrayAgents[j].indexOf(']');\r\n");
      out.write("\t\tvar login\t  = arrayAgents[j].substr(iStartPos+1,iEndPos-iStartPos-1);\r\n");
      out.write("\t\tvar name = login+'['+arrayAgents[j].substr(0,iStartPos)+']';\r\n");
      out.write("\t\tif (document.theForm.viewckbox.checked == false)\t  \t\t// show agents name as : firstname, lastname[login]\r\n");
      out.write("      \t\tmyOption = new Option(arrayAgents [j],login)\r\n");
      out.write("\t\telse\t\t\t\t\t\t\t\t\t// show agents name as : login[firstname, lastname]\r\n");
      out.write("\t\t\tmyOption = new Option(name,login)\r\n");
      out.write("\t\tvar optionPos = document.theForm.objects.options.length;\r\n");
      out.write("\t\tdocument.theForm.objects.options[optionPos]= myOption;\r\n");
      out.write("    }\r\n");
      out.write("  } else {\r\n");
      out.write("    //Get all active Agents by Name\r\n");
      out.write("    var agents = String( appletObj.getAgentsByNameActif(tenant_dbid) );\r\n");
      out.write("    jsAgents = agents + \"\";\r\n");
      out.write("    arrayAgents = jsAgents.split(\"|\");\r\n");
      out.write("    for (j = 0; j <arrayAgents.length; j++){\r\n");
      out.write("      var iStartPos = arrayAgents[j].indexOf('[');\r\n");
      out.write("      var iEndPos   = arrayAgents[j].indexOf(']');\r\n");
      out.write("      var login\t  = arrayAgents[j].substr(iStartPos+1,iEndPos-iStartPos-1);\r\n");
      out.write("\t  var name = login+'['+arrayAgents[j].substr(0,iStartPos)+']';\r\n");
      out.write("\t  if (document.theForm.viewckbox.checked == false)\r\n");
      out.write("      \tmyOption = new Option(arrayAgents [j],login)\r\n");
      out.write("\t  else\r\n");
      out.write("\t    myOption = new Option(name,login)\r\n");
      out.write("     var optionPos = document.theForm.objects.options.length;\r\n");
      out.write("      document.theForm.objects.options[optionPos]= myOption;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("  //alert(jsAgents)\r\n");
      out.write("  sortSelect2(document.theForm.objects);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sortSelect(o)\r\n");
      out.write("{\r\n");
      out.write("\tif (o.length==0) { return; }\r\n");
      out.write("\tif(document.theForm.viewckbox.checked == false){\r\n");
      out.write("\t\to = o.sort(\r\n");
      out.write("\t\t\tfunction(a,b) {\r\n");
      out.write("\t\t\t\tif ((a.text+\"\") < (b.text+\"\")) { return -1; }\r\n");
      out.write("\t\t\t\tif ((a.text+\"\") > (b.text+\"\")) { return 1; }\r\n");
      out.write("\t\t\t\treturn 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\to = o.sort(\r\n");
      out.write("\t\t\tfunction(a,b) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (parseInt(a.value) < parseInt(b.value)) { return -1; }\r\n");
      out.write("\t\t\t\t\tif (parseInt(a.value) > parseInt(b.value)) { return 1; }\r\n");
      out.write("\t\t\t\t\treturn 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sortSelect2(obj)\r\n");
      out.write("{\r\n");
      out.write("\tvar o = new Array();\r\n");
      out.write("\tif (obj.options==null) { return; }\r\n");
      out.write("\tfor (var i=0; i<obj.options.length; i++) {\r\n");
      out.write("\t\to[o.length] = new Option( obj.options[i].text, obj.options[i].value, obj.options[i].defaultSelected, obj.options[i].selected) ;\r\n");
      out.write("\t\t}\r\n");
      out.write("\tif (o.length==0) { return; }\r\n");
      out.write("\tif(document.theForm.viewckbox.checked == false){\r\n");
      out.write("\t\to = o.sort(\r\n");
      out.write("\t\t\tfunction(a,b) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif ((a.text+\"\") < (b.text+\"\")) { return -1; }\r\n");
      out.write("\t\t\t\t\tif ((a.text+\"\") > (b.text+\"\")) { return 1; }\r\n");
      out.write("\t\t\t\t\treturn 0;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("     }\r\n");
      out.write("    else{\r\n");
      out.write("\t\to = o.sort(\r\n");
      out.write("\t\t\tfunction(a,b) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (parseInt(a.value) < parseInt(b.value)) { return -1; }\r\n");
      out.write("\t\t\t\t\tif (parseInt(a.value) > parseInt(b.value)) { return 1; }\r\n");
      out.write("\t\t\t\t\treturn 0;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("    }\r\n");
      out.write("\tfor (var i=0; i<o.length; i++) {\r\n");
      out.write("\t\tobj.options[i] = new Option(o[i].text, o[i].value, o[i].defaultSelected, o[i].selected);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function changeAgentListView(){\r\n");
      out.write("\r\n");
      out.write("\tvar agents;\r\n");
      out.write("\tvar name=\"\";\r\n");
      out.write("\tvar o = new Array();\r\n");
      out.write("\tdocument.theForm.objects.length = 0;\r\n");
      out.write("   \tif (document.theForm.ckbox.checked == true)\r\n");
      out.write("    \tagents = String( appletObj.getAgentsByName(tenant_dbid) );\r\n");
      out.write("\telse\r\n");
      out.write("\t\tagents = String( appletObj.getAgentsByNameActif(tenant_dbid) );\r\n");
      out.write("\tvar jsAgents = agents + \"\";\r\n");
      out.write("    arrayAgents = jsAgents.split(\"|\");\r\n");
      out.write("    for (j = 0; j <arrayAgents.length; j++){\r\n");
      out.write("\t\t  var iStartPos = arrayAgents[j].indexOf('[');\r\n");
      out.write("\t\t  var iEndPos   = arrayAgents[j].indexOf(']');\r\n");
      out.write("\t\t  var login\t  = arrayAgents[j].substr(iStartPos+1,iEndPos-iStartPos-1);\r\n");
      out.write("\t\t  name = login+'['+arrayAgents[j].substr(0,iStartPos)+']'\r\n");
      out.write("\t\t  if (document.theForm.viewckbox.checked == false)  // show agents name as : firstname, lastname[login]\r\n");
      out.write("\t\t\tmyOption = new Option(arrayAgents [j],login);  // show agents name as : login[firstname, lastname]\r\n");
      out.write("\t\t  else\r\n");
      out.write("\t\t\tmyOption = new Option(name,login);\r\n");
      out.write("\t\t  o[o.length]=myOption\r\n");
      out.write("\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("\tsortSelect(o);\r\n");
      out.write("\r\n");
      out.write("\tfor (var i=0; i<o.length; i++) {\r\n");
      out.write("\t\tdocument.theForm.objects.options[i] = new Option(o[i].text, o[i].value, o[i].defaultSelected, o[i].selected);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var doingSearch = 0; // shows if a search is being performed\r\n");
      out.write("\r\n");
      out.write("function fillObjectCombo()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById(\"noresult\").style.visibility=\"hidden\";\r\n");
      out.write("\tvar o = new Array();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tif((vValue == 'Agents') || (vValue == 'AgentPerformance') ||(vValue =='AgentPerformanceDetails'))\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar searchId = new RegExp(document.getElementById(\"searchid\").value, \"gi\");\r\n");
      out.write("\t\tvar searchFirst = new RegExp(document.getElementById(\"searchfirst\").value, \"gi\");\r\n");
      out.write("\t\tvar searchLast = new RegExp(document.getElementById(\"searchlast\").value, \"gi\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar agents;\r\n");
      out.write("\t\tif (document.theForm.ckbox.checked == false) {\t//shows all agents\r\n");
      out.write("    \t\tagents = String( appletObj.getAgentsByName(tenant_dbid) );\r\n");
      out.write("\t\t}else{\t\t\t\t\t\t\t\t\t\t\t// shows only active agents\r\n");
      out.write("\t\t\tagents = String( appletObj.getAgentsByNameActif(tenant_dbid) );\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar jsAgents = agents + \"\";\r\n");
      out.write("    \tarrayAgents = jsAgents.split(\"|\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.theForm.objects.options.length=0; //remove 'loading' text\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (searchId!=\"//ig\" || searchFirst!=\"//ig\" || searchLast!=\"//ig\" && doingSearch==1) {\r\n");
      out.write("\t\t\tif(searchId==\"//ig\") {\r\n");
      out.write("\t\t\t\tsearchId=null;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(searchFirst==\"//ig\") {\r\n");
      out.write("\t\t\t\tsearchFirst=null;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(searchLast==\"//ig\") {\r\n");
      out.write("\t\t\t\tsearchLast=null;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdoingSearch=0;\r\n");
      out.write("    \t\tfor (j = 0; j <arrayAgents.length; j++){\r\n");
      out.write("    \t\t\tvar firstStartPos = arrayAgents[j].indexOf(',');\r\n");
      out.write("\t\t\t\tvar lastStartPos  = arrayAgents[j].indexOf('^');\r\n");
      out.write("\t\t\t\tvar iStartPos     = arrayAgents[j].indexOf('[');\r\n");
      out.write("    \t\t\tvar iEndPos       = arrayAgents[j].indexOf(']');\r\n");
      out.write("\t\t\t\tvar firstn\t      = arrayAgents[j].substr(firstStartPos+1,iStartPos-firstStartPos-1);\r\n");
      out.write("\t\t\t\tvar lastn\t      = arrayAgents[j].substr(lastStartPos+1,firstStartPos-lastStartPos-1);\r\n");
      out.write("    \t\t\tvar login\t      = arrayAgents[j].substr(iStartPos+1,iEndPos-iStartPos-1);\r\n");
      out.write("\t\t\t\tvar name = login+'['+arrayAgents[j].substr(0,iStartPos)+']';\r\n");
      out.write("\t\t\t\tif((firstn.search(searchFirst)==0 && searchLast==null && searchId==null) || (firstn.search(searchFirst)==0 && lastn.search(searchLast)==0 && searchId==null) || (firstn.search(searchFirst)==0 && searchLast==null && login.search(searchId)==0) || (firstn.search(searchFirst)==0 && lastn.search(searchLast)==0 && login.search(searchId)==0) || (searchFirst==null && lastn.search(searchLast)==0 && searchId==null) || (searchFirst==null && lastn.search(searchLast)==0 && login.search(searchId)==0) || (searchFirst==null && searchLast==null && login.search(searchId)==0)) {\r\n");
      out.write("\t\t\t\t\tif (document.theForm.viewckbox.checked == false) {  // show agents name as : firstname, lastname[login]\r\n");
      out.write("\t\t\t\t\t\tmyOption = new Option(arrayAgents [j],login);  // show agents name as : login[firstname, lastname]\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tmyOption = new Option(name,login);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\toptionPos = document.theForm.objects.options.length\r\n");
      out.write("\t\t\t\t\tdocument.theForm.objects.options[optionPos]=myOption\r\n");
      out.write("\t\t\t\t\to[o.length]=myOption\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tfor (j = 0; j <arrayAgents.length; j++){\r\n");
      out.write("\t\t\t\tvar iStartPos     = arrayAgents[j].indexOf('[');\r\n");
      out.write("    \t\t\tvar iEndPos       = arrayAgents[j].indexOf(']');\r\n");
      out.write("    \t\t\tvar login\t      = arrayAgents[j].substr(iStartPos+1,iEndPos-iStartPos-1);\r\n");
      out.write("\t\t\t\tvar name = login+'['+arrayAgents[j].substr(0,iStartPos)+']';\r\n");
      out.write("\t\t  \t\tif (document.theForm.viewckbox.checked == false) {  // show agents name as : firstname, lastname[login]\r\n");
      out.write("\t\t\t\t\tmyOption = new Option(arrayAgents [j],login);  // show agents name as : login[firstname, lastname]\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tmyOption = new Option(name,login);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("    \t\t\t\r\n");
      out.write("\t\t\t\toptionPos = document.theForm.objects.options.length\r\n");
      out.write("\t\t\t\tdocument.theForm.objects.options[optionPos]=myOption\r\n");
      out.write("\t\t\t\to[o.length]=myOption\r\n");
      out.write("    \t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tsortSelect(o);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor (var i=0; i<o.length; i++) {\r\n");
      out.write("\t\tdocument.theForm.objects.options[i] = new Option(o[i].text, o[i].value, o[i].defaultSelected, o[i].selected);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(document.theForm.objects.options.length==0) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"noresult\").style.visibility=\"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("    }else if((vValue=='AgentGroupsRTA')||(vValue =='AgentPerformanceByGrp')||(vValue =='AgentPerformanceDetailsByGrp')){\r\n");
      out.write("\t\tvar searchFull = new RegExp(document.getElementById(\"searchfullname\").value, \"gi\");\r\n");
      out.write("\t\tvar searchPart = new RegExp(document.getElementById(\"searchpartname\").value, \"gi\");\r\n");
      out.write("   \t\tvar agentGroups = String( appletObj.getAgentGroupByName(tenant_dbid) );\r\n");
      out.write("\t\tvar jsAgentGroups = agentGroups + \"\";\r\n");
      out.write("    \tarrayGroups = jsAgentGroups.split(\"|\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.theForm.objects.options.length=0; //remove 'loading' text\r\n");
      out.write("\t\tif(searchFull!=\"//ig\" && doingSearch==1) { // if full name search\r\n");
      out.write("\t\t\tdoingSearch=0;\r\n");
      out.write("    \t\tfor (j = 0; j <arrayGroups.length; j++){\r\n");
      out.write("\t\t\t\tif(arrayGroups[j].search(searchFull)==0) {\r\n");
      out.write("\t\t\t\t\tmyOption = new Option(arrayGroups[j],arrayGroups[j])\r\n");
      out.write("\t\t\t\t\toptionPos = document.theForm.objects.options.length\r\n");
      out.write("\t\t\t\t\tdocument.theForm.objects.options[optionPos]=myOption\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("    \t\t}\r\n");
      out.write("\t\t}else if(searchPart!=\"//ig\" && doingSearch==1) { // if partial name search\r\n");
      out.write("\t\t\tdoingSearch=0;\r\n");
      out.write("\t\t\tfor (j = 0; j <arrayGroups.length; j++){\r\n");
      out.write("\t\t\t\tif(arrayGroups[j].search(searchPart)!=-1) {\r\n");
      out.write("\t\t\t\t\tmyOption = new Option(arrayGroups[j],arrayGroups[j])\r\n");
      out.write("\t\t\t\t\toptionPos = document.theForm.objects.options.length\r\n");
      out.write("\t\t\t\t\tdocument.theForm.objects.options[optionPos]=myOption\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("    \t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tfor (j = 0; j <arrayGroups.length; j++){\r\n");
      out.write("    \t\t\tmyOption = new Option(arrayGroups[j],arrayGroups[j])\r\n");
      out.write("\t\t\t\toptionPos = document.theForm.objects.options.length\r\n");
      out.write("\t\t\t\tdocument.theForm.objects.options[optionPos]=myOption\r\n");
      out.write("    \t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.theForm.objects.options.length==0) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"noresult\").style.visibility=\"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("    }\r\n");
      out.write("\tformObjectsResize();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function formObjectsResize() {\r\n");
      out.write("\tif(document.theForm.objects.options.length >= 7)\r\n");
      out.write("\t   \tdocument.theForm.objects.size = 7;\r\n");
      out.write("\telse if(document.theForm.objects.options.length < 3)\r\n");
      out.write("\t\tdocument.theForm.objects.size = 3;\r\n");
      out.write("\telse\r\n");
      out.write("\t\tdocument.theForm.objects.size = document.theForm.objects.options.length+1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getSelectedObjects()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\tselectedObjects = new Array()\r\n");
      out.write("\tfor (i=0;i<document.theForm.objects.options.length;i++) {\r\n");
      out.write("  \t\tif (document.theForm.objects.options[i].selected) {\r\n");
      out.write("  \t\t\tselectedObjects[selectedObjects.length]=document.theForm.objects.options[i].value;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t}\r\n");
      out.write("    var url = '';\r\n");
      out.write("\tif (selectedObjects.length > 0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\turl= escape(selectedObjects.join('/'))\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\treturn url;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getSelectedTeams(){\r\n");
      out.write("var url = '';\r\n");
      out.write("\r\n");
      out.write("\t\tselectedTeams = new Array()\r\n");
      out.write("\t\tfor (i=teams.selectedIndex;i<teams.options.length;i++) {\r\n");
      out.write("  \t\t\tif (teams.options[i].selected) {\r\n");
      out.write("  \t\t\t\tselectedTeams[selectedTeams.length]=teams.options[i].value;\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t}\r\n");
      out.write("\t\tif (selectedObjects.length > 0){\r\n");
      out.write("\t\t\turl= escape(selectedObjects.join('/'))\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn url;\r\n");
      out.write("}\r\n");
      out.write("function hourChecker()\r\n");
      out.write("{\r\n");
      out.write("\tvar star_hour =parseInt(document.theForm.startTime.value.substring(0,2));\r\n");
      out.write("    var star_min =parseInt(document.theForm.startTime.value.substring(3,5));\r\n");
      out.write("\tvar end_hour =parseInt(document.theForm.endTime.value.substring(0,2));\r\n");
      out.write("\tvar end_min =parseInt(document.theForm.endTime.value.substring(3,5));\r\n");
      out.write("\tif((star_hour*60 + star_min) >= (end_hour*60 + end_min))\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("Your ending time cannnot be smaller than your starting time!"));
      out.write("\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function saveAdhViewData()\r\n");
      out.write("{\r\n");
      out.write("\tvar selectObjects;\r\n");
      out.write("\t\r\n");
      out.write("\tif(document.theForm.objects.selectedIndex == -1)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tselectObjects='None'; //no object selected for adherence\r\n");
      out.write("\t\talert(\"Please select one agent group, before vizualizing adherence.\");\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(hourChecker())\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t  selectObjects = document.theForm.objects.value;\r\n");
      out.write("\t\t  var adhRunning= appletObj.isAdherenceStarted();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t  if(adhRunning==\"true\")\r\n");
      out.write("\t\t  { \r\n");
      out.write("\t\t\t\tappletObj.sendRTAStopReq();\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t  appletObj.updateRTAViewInfo(document.theForm.startTime.value, document.theForm.endTime.value, document.theForm.spacing.value,selectObjects);\r\n");
      out.write("\t\t  appletObj.m_ScheduleAdherenceData=\"\";\r\n");
      out.write("\t\t   if(adhRunning==\"true\")\r\n");
      out.write("\t\t  { \r\n");
      out.write("\t\t\t\t  appletObj.sendRTAStartReq();\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tif(document.theForm.saveButton.disabled == false)\r\n");
      out.write("\t\t\t\tdocument.theForm.saveButton.disabled = true;\r\n");
      out.write("\t\t\twindow.top.main.rtop.stats.firstLoad = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sendRTAStartRequest()\r\n");
      out.write("{\r\n");
      out.write("\tif(hourChecker())\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//sends the start request to the CTI\r\n");
      out.write("\t\tsaveAdhViewData();\r\n");
      out.write("\t\tvar ret=appletObj.sendRTAStartReq();\r\n");
      out.write("\t\tupdateStartButton();\r\n");
      out.write("\t\treturn ret;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sendRTAStopRequest()\r\n");
      out.write("{\r\n");
      out.write(" \t//sends the stop request to the CTI\r\n");
      out.write("\tappletObj.sendRTAStopReq();\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updateStartButton()\r\n");
      out.write("{\r\n");
      out.write("if(hourChecker()){\r\n");
      out.write("\t if(document.theForm.startButton.disabled == true){\r\n");
      out.write("\t\tdocument.theForm.startButton.disabled = false;\r\n");
      out.write("\t\tdocument.theForm.stopButton.disabled = true;\r\n");
      out.write("\t  }\r\n");
      out.write("\t else{\r\n");
      out.write("\t\tdocument.theForm.startButton.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.stopButton.disabled = false;\r\n");
      out.write("\t }\r\n");
      out.write("\t }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updateStopButton()\r\n");
      out.write("{\r\n");
      out.write(" \tif(document.theForm.stopButton.disabled == true){\r\n");
      out.write("\t\tdocument.theForm.startButton.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.stopButton.disabled = false;\r\n");
      out.write("\t }\r\n");
      out.write(" else{\r\n");
      out.write("\t\tdocument.theForm.startButton.disabled = false;\r\n");
      out.write("\t\tdocument.theForm.stopButton.disabled = true;\r\n");
      out.write("\t }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function selectAll()\r\n");
      out.write("{\r\n");
      out.write("  for (j = 0; j <document.theForm.objects.options.length; j++)\r\n");
      out.write("\t  document.theForm.objects.options[j].selected = true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function unSelectAll()\r\n");
      out.write("{\r\n");
      out.write("  for (j = 0; j <document.theForm.objects.options.length; j++)\r\n");
      out.write("\t  document.theForm.objects.options[j].selected = false;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getRequestedReport()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\tvar destination = '';\r\n");
      out.write("\tif(document.theForm.period[0].checked){\r\n");
      out.write("\t\tif(document.theForm.startingDateDaily.value.length == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"");
      out.print( pageData.getWord("Please enter a starting date"));
      out.write("\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.theForm.endingDateDaily.value.length == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"");
      out.print( pageData.getWord("Please enter an ending date"));
      out.write("\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tif(document.theForm.objects.selectedIndex == -1)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print( pageData.getWord("Please select at least one object"));
      out.write("\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(dateChecker() == false)\r\n");
      out.write("\t{\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(vValue == 'Agents'){\r\n");
      out.write("\t\tdestination = \"../jsp/agentAdherenceReportView.jsp\"\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tdestination += \"?startingDate=\"\r\n");
      out.write("\tdestination += document.theForm.startingDateDaily.value;\r\n");
      out.write("\tdestination +=\"&endingDate=\";\r\n");
      out.write("\tdestination += document.theForm.endingDateDaily.value;\r\n");
      out.write("\tdestination +=\"&startTime=\";\r\n");
      out.write("\tdestination += document.theForm.startTime.value;\r\n");
      out.write("\tdestination +=\"&endTime=\";\r\n");
      out.write("\tdestination += document.theForm.endTime.value;\r\n");
      out.write("\tdestination +=\"&spacing=\";\r\n");
      out.write("\tdestination += document.theForm.spacing.value;\r\n");
      out.write("\r\n");
      out.write("\t/*destination +=\"&starting_year_yearly=\";\r\n");
      out.write("\tdestination += starting_year_yearly.value\r\n");
      out.write("\tdestination +=\"&ending_year_yearly=\";\r\n");
      out.write("\tdestination += ending_year_yearly.value*/\r\n");
      out.write("\tdestination +=\"&starting_month_monthly=\";\r\n");
      out.write("\tdestination += document.theForm.starting_month_monthly.value\r\n");
      out.write("\tdestination +=\"&starting_year_monthly=\";\r\n");
      out.write("\tdestination += document.theForm.starting_year_monthly.value\r\n");
      out.write("\tdestination +=\"&starting_month_monthly=\";\r\n");
      out.write("\tdestination += document.theForm.starting_month_monthly.value\r\n");
      out.write("\tdestination +=\"&ending_year_monthly=\";\r\n");
      out.write("\tdestination += document.theForm.starting_year_monthly.value\r\n");
      out.write("\r\n");
      out.write("\tdestination +=\"&reportType=\";\r\n");
      out.write("\t/*if(period[0].checked){\r\n");
      out.write("\t\tdestination += \"Yearly\";\r\n");
      out.write("\t} else*/\r\n");
      out.write("\t if(document.theForm.period[1].checked){\r\n");
      out.write("\t\tdestination += \"Monthly\";\r\n");
      out.write("\t} else if(document.theForm.period[0].checked){\r\n");
      out.write("\t\tdestination += \"Daily\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tif(vValue == 'AgentPerformanceReportsByLeader'){\r\n");
      out.write("\t\tdestination +=\"&teams=\";\r\n");
      out.write("\t\tdestination += getSelectedObjects();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t    destination +=\"&objects=\";\r\n");
      out.write("\t    destination += getSelectedObjects();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tdestination += \"&lang=\"+lang;\r\n");
      out.write("    //alert(destination)\r\n");
      out.write("\t//window.open(destination);\r\n");
      out.write("\tdocument.location = destination;\r\n");
      out.write("}\r\n");
      out.write("function dateChecker()\r\n");
      out.write("{\r\n");
      out.write("\tif(document.theForm.period[0].checked){// daily\r\n");
      out.write("\t\tvar startDate=new Date(document.theForm.startingDateDaily.value);\r\n");
      out.write("\t\tvar endDate = new Date(document.theForm.endingDateDaily.value);\r\n");
      out.write("\t\tif(endDate < startDate)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"");
      out.print( pageData.getWord("Your ending date cannnot be smaller than your starting date"));
      out.write("\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("  else if (document.theForm.period[1].checked){ // monthly\r\n");
      out.write("\tvar startDate='01-'+ document.theForm.starting_month_monthly.value + '-' + document.theForm.starting_year_monthly.value;\r\n");
      out.write("\tvar endDate ='01-'+  document.theForm.starting_month_monthly.value+ '-' + document.theForm.starting_year_monthly.value;\r\n");
      out.write("\tstartDate = new Date(startDate);\r\n");
      out.write("\tendDate = new Date(endDate);\r\n");
      out.write("\r\n");
      out.write("\tif(endDate < startDate || endDate > startDate)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Your ending month-year must be the same as your starting month-year!!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("}/*else if (period[0].checked){// yearly\r\n");
      out.write("    var startDate=starting_year_yearly.value ;\r\n");
      out.write("\tvar endDate = ending_year_yearly.value ;\r\n");
      out.write("\r\n");
      out.write("\tif(endDate < startDate)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Your ending date cannnot be smaller than your starting date!!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}*/\r\n");
      out.write("\r\n");
      out.write("return true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function setEndingMonth(){\r\n");
      out.write("\tif(document.theForm.period[1].checked){\r\n");
      out.write("\t  for (i=0; i<document.theForm.starting_month_monthly.options.length; i++)\r\n");
      out.write("\t\t  if(document.theForm.starting_month_monthly.options[i].value == document.theForm.starting_month_monthly.value)\r\n");
      out.write("\t\t\tdocument.theForm.starting_month_monthly.options[i].selected = true;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function changeDisabled(){\r\n");
      out.write("\tif(document.theForm.period[1].checked){\r\n");
      out.write("\t\tdocument.theForm.startingDateDaily.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.endingDateDaily.disabled = true;\r\n");
      out.write("\t\t/*starting_year_yearly.disabled = false;\r\n");
      out.write("\t\tending_year_yearly.disabled = false;*/\r\n");
      out.write("\t\tdocument.theForm.starting_month_monthly.disabled = false;\r\n");
      out.write("\t\tdocument.theForm.starting_year_monthly.disabled = false;\r\n");
      out.write("\t\tdocument.theForm.starting_month_monthly.disabled = false;\r\n");
      out.write("\t\tdocument.theForm.starting_year_monthly.disabled = false;\r\n");
      out.write("\t}/* else if(period[1].checked){\r\n");
      out.write("\t\tstartingDateDaily.disabled = true;\r\n");
      out.write("\t\tendingDateDaily.disabled = true;\r\n");
      out.write("\t\tstarting_year_yearly.disabled = true;\r\n");
      out.write("\t\tending_year_yearly.disabled = true;\r\n");
      out.write("\t\tstarting_month_monthly.disabled = false;\r\n");
      out.write("\t\tstarting_year_monthly.disabled = false;\r\n");
      out.write("\t\tstarting_month_monthly.disabled = false;\r\n");
      out.write("\t\tending_year_monthly.disabled = false;\r\n");
      out.write("\t} else*/\r\n");
      out.write("\tif(document.theForm.period[0].checked){\r\n");
      out.write("\t\tdocument.theForm.startingDateDaily.disabled = false;\r\n");
      out.write("\t\tdocument.theForm.endingDateDaily.disabled = false;\r\n");
      out.write("\t\t/*starting_year_yearly.disabled = true;\r\n");
      out.write("\t\tending_year_yearly.disabled = true;*/\r\n");
      out.write("\t\tdocument.theForm.starting_month_monthly.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.starting_year_monthly.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.starting_month_monthly.disabled = true;\r\n");
      out.write("\t\tdocument.theForm.starting_year_monthly.disabled = true;\r\n");
      out.write("\t}\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(" function enableUpdateButton()\r\n");
      out.write(" {\r\n");
      out.write("     var vValue = normalizeString(QueryString('type'));\r\n");
      out.write(" \t if (vValue == 'AgentGroupsRTA'){\r\n");
      out.write("\t    document.theForm.saveButton.value = \"");
      out.print( pageData.getWord("Update"));
      out.write("\";\r\n");
      out.write("\t\tdocument.theForm.saveButton.disabled = false;\r\n");
      out.write("\t }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write(" function setDefaultValue()\r\n");
      out.write(" {\r\n");
      out.write("     var vValue = normalizeString(QueryString('type'));\r\n");
      out.write("\r\n");
      out.write(" \t if (vValue == 'AgentGroupsRTA' || vValue == 'Agents'){\r\n");
      out.write("\t\t\t//window.top.comm.myApplet.m_adh_start_time = startTime.value;//normalizeString(QueryString('startTime'));\r\n");
      out.write("\t\t\t//window.top.comm.myApplet.m_adh_end_time   = endTime.value;//normalizeString(QueryString('endTime'));\r\n");
      out.write("\t\t\t//window.top.comm.myApplet.m_adh_spacing    = spacing.value;\r\n");
      out.write("\t\t\t//window.top.comm.myApplet.m_reloadAdherenceView = true;\r\n");
      out.write("\r\n");
      out.write("        \tfor (j = 0; j <document.theForm.startTime.length; j++){\r\n");
      out.write("\t\t   \t\tif(document.theForm.startTime.options[j].value == String( appletObj.m_adh_start_time ) )\r\n");
      out.write("\t\t\t\t\t{document.theForm.startTime.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\t break;}\r\n");
      out.write("        \t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor (j = 0; j <document.theForm.endTime.length; j++){\r\n");
      out.write("\t\t   \t\tif(document.theForm.endTime.options[j].value == String( appletObj.m_adh_end_time ) )\r\n");
      out.write("\t\t\t\t\t{document.theForm.endTime.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\t break;\r\n");
      out.write("\t\t\t\t\t }\r\n");
      out.write("        \t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor (j = 0; j <document.theForm.spacing.length; j++){\r\n");
      out.write("\t\t   \t\tif(document.theForm.spacing.options[j].value == String( appletObj.m_adh_spacing ))\r\n");
      out.write("\t\t\t\t\t{document.theForm.spacing.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\t break;\r\n");
      out.write("\t\t\t\t\t }\r\n");
      out.write("        \t}\r\n");
      out.write("\r\n");
      out.write("\t }\r\n");
      out.write("\r\n");
      out.write("\tif(  vValue == 'Agents'){\r\n");
      out.write("\t\tvar thetime =new Date();\r\n");
      out.write("\t\tvar thisYear = thetime.getYear();\r\n");
      out.write("\t\tvar thisMonth =thetime.getMonth()+1;\r\n");
      out.write("\r\n");
      out.write("\t\tfor (j = 0; j <document.theForm.starting_year_monthly.length; j++){\r\n");
      out.write("\t\t\tif(document.theForm.starting_year_monthly.options[j].value == thisYear)\r\n");
      out.write("\t\t\t\t{document.theForm.starting_year_monthly.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfor (j = 0; j <document.theForm.starting_month_monthly.length; j++){\r\n");
      out.write("\t\t\tif(document.theForm.starting_month_monthly.options[j].value == thisMonth)\r\n");
      out.write("\t\t\t\t{document.theForm.starting_month_monthly.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfor (j = 0; j <document.theForm.starting_year_monthly.length; j++){\r\n");
      out.write("\t\t\tif(document.theForm.starting_year_monthly.options[j].value == thisYear)\r\n");
      out.write("\t\t\t\t{document.theForm.starting_year_monthly.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfor (j = 0; j <document.theForm.starting_month_monthly.length; j++){\r\n");
      out.write("\t\t\tif(document.theForm.starting_month_monthly.options[j].value == thisMonth)\r\n");
      out.write("\t\t\t\t{document.theForm.starting_month_monthly.options[j].selected = true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write(".style1 {\r\n");
      out.write("    font-family:Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("    // Associate a default button with pressing the Enter key\r\n");
      out.write("\tfunction KeyDownHandler(btn)\r\n");
      out.write("    {\r\n");
      out.write("        // process only the Enter key\r\n");
      out.write("        if (event.keyCode == 13)\r\n");
      out.write("        {\r\n");
      out.write("            if (document.activeElement) { // for ie\r\n");
      out.write("\t\t\t\tif(document.activeElement.id==\"searchfirst\" || document.activeElement.id==\"searchlast\" || document.activeElement.id==\"searchid\" || document.activeElement.id==\"searchfullname\" || document.activeElement.id==\"searchpartname\") {\r\n");
      out.write("\t\t\t\t\tsearchFor();\r\n");
      out.write("/*\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t// cancel the default submit\r\n");
      out.write("           \t\t\tevent.returnValue=false;\r\n");
      out.write("          \t\t  \tevent.cancel = true;\r\n");
      out.write("          \t\t  \t// submit the form by programmatically clicking the specified button\r\n");
      out.write("            \t\tbtn.click();\r\n");
      out.write("*/\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}else{ // for firefox\r\n");
      out.write("\t\t\t\tif(document.focusNode.id==\"searchfirst\" || document.focusNode.id==\"searchlast\" || document.focusNode.id==\"searchid\" || document.focusNode.id==\"searchfullname\" || document.focusNode.id==\"searchpartname\") {\r\n");
      out.write("\t\t\t\t\tsearchFor();\r\n");
      out.write("/*\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t// cancel the default submit\r\n");
      out.write("           \t\t\tevent.returnValue=false;\r\n");
      out.write("          \t\t  \tevent.cancel = true;\r\n");
      out.write("          \t\t  \t// submit the form by programmatically clicking the specified button\r\n");
      out.write("            \t\tbtn.click();\r\n");
      out.write("*/\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("function searchFor() { // varify text search\r\n");
      out.write("\r\n");
      out.write("\tif (document.getElementById(\"searchfirst\")){\r\n");
      out.write("\t\tvar thisSearch1 = document.getElementById(\"searchfirst\").value;\r\n");
      out.write("\t\tvar thisSearch2 = document.getElementById(\"searchlast\").value;\r\n");
      out.write("\t\tvar thisSearch3 = document.getElementById(\"searchid\").value;\r\n");
      out.write("\t\tif (thisSearch1.match(/\\?/) || thisSearch1.match(/\\*/) || thisSearch1.match(/\\(/) || thisSearch1.match(/\\)/) || thisSearch1.match(/\\+/) || thisSearch1.match(/\\[/) || thisSearch1.match(/\\]/) || thisSearch1.match(/\\</) || thisSearch1.match(/\\>/) || thisSearch1.match(/\\|/) || thisSearch1.match(/\\./) || thisSearch2.match(/\\?/) || thisSearch2.match(/\\*/) || thisSearch2.match(/\\(/) || thisSearch2.match(/\\)/) || thisSearch2.match(/\\+/) || thisSearch2.match(/\\[/) || thisSearch2.match(/\\]/) || thisSearch2.match(/\\</) || thisSearch2.match(/\\>/) || thisSearch2.match(/\\|/) || thisSearch2.match(/\\./) || thisSearch3.match(/\\?/) || thisSearch3.match(/\\*/) || thisSearch3.match(/\\(/) || thisSearch3.match(/\\)/) || thisSearch3.match(/\\+/) || thisSearch3.match(/\\[/) || thisSearch3.match(/\\]/) || thisSearch3.match(/\\</) || thisSearch3.match(/\\>/) || thisSearch3.match(/\\|/) || thisSearch3.match(/\\./)) { // disallowed characters\r\n");
      out.write("\t\t\talert(\"");
      out.print(pageData.getWord("Search query cannot contain"));
      out.write(" '?', '*', '.', '+', '(', ')', '[', ']', '<', '>' ");
      out.print(pageData.getWord("or"));
      out.write(" '|'\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tdoingSearch=1;\r\n");
      out.write("\t\t\tfillObjectCombo();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tvar thisSearch1 = document.getElementById(\"searchfullname\").value;\r\n");
      out.write("\t\tvar thisSearch2 = document.getElementById(\"searchpartname\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (thisSearch1.match(/\\?/) || thisSearch1.match(/\\*/) || thisSearch1.match(/\\(/) || thisSearch1.match(/\\)/) || thisSearch1.match(/\\+/) || thisSearch1.match(/\\[/) || thisSearch1.match(/\\]/) || thisSearch1.match(/\\</) || thisSearch1.match(/\\>/) || thisSearch1.match(/\\|/) || thisSearch1.match(/\\./) || thisSearch2.match(/\\?/) || thisSearch2.match(/\\*/) || thisSearch2.match(/\\(/) || thisSearch2.match(/\\)/) || thisSearch2.match(/\\+/) || thisSearch2.match(/\\[/) || thisSearch2.match(/\\]/) || thisSearch2.match(/\\</) || thisSearch2.match(/\\>/) || thisSearch2.match(/\\|/) || thisSearch2.match(/\\./)) { // disallowed characters\r\n");
      out.write("\t\t\talert(\"");
      out.print(pageData.getWord("Search query cannot contain"));
      out.write(" '?', '*', '.', '+', '(', ')', '[', ']', '<', '>' ");
      out.print(pageData.getWord("or"));
      out.write(" '|'\");\r\n");
      out.write("\t\t}else if (document.getElementById(\"searchfullname\").value!=\"\" && document.getElementById(\"searchpartname\").value!=\"\"){\r\n");
      out.write("\t\t\talert(\"");
      out.print(pageData.getWord("Search for either"));
      out.write("\\n\\n'");
      out.print(pageData.getWord("Name"));
      out.write("'\\n(");
      out.print(pageData.getWord("can be the full name or the begining of the name"));
      out.write(')');
      out.write('\\');
      out.write('n');
      out.print(pageData.getWord("or"));
      out.write(' ');
      out.write('\'');
      out.print(pageData.getWord("Name includes"));
      out.write("'\\n(");
      out.print(pageData.getWord("search for text that is included anywhere in the name"));
      out.write(")\\n\\n");
      out.print(pageData.getWord("but not both"));
      out.write(".\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tdoingSearch=1;\r\n");
      out.write("\t\t\tfillObjectCombo();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function resetResults() {\r\n");
      out.write("\tif (document.getElementById(\"searchfirst\")){\r\n");
      out.write("\t\tdocument.getElementById(\"searchfirst\").value=\"\";\r\n");
      out.write("\t\tdocument.getElementById(\"searchlast\").value=\"\";\r\n");
      out.write("\t\tdocument.getElementById(\"searchid\").value=\"\";\r\n");
      out.write("\t\tfillObjectCombo();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tdocument.getElementById(\"searchfullname\").value=\"\";\r\n");
      out.write("\t\tdocument.getElementById(\"searchpartname\").value=\"\";\r\n");
      out.write("\t\tfillObjectCombo();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"adher_body\" onLoad=\"fillObjectCombo()\">\r\n");
      out.write("\t<div class=\"tab-pane\" id=\"tabPane1\">\r\n");
      out.write("\t\t<form name=\"theForm\" onKeyDown=\"KeyDownHandler(submit)\">\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\ttp1 = new WebFXTabPane( document.getElementById( \"tabPane1\" ) );\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<div class=\"tab-page\" id=\"tabGeneral\">\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend id=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t<script language=\"JavaScript\">\r\n");
      out.write("    \t\t\t\t\t\tvar vValue = normalizeString(QueryString('type'));\r\n");
      out.write("    \t\t\t\t\t\tif (vValue == 'Agents'){\r\n");
      out.write("       \t\t\t\t\t\t\tdocument.write(\"");
      out.print( pageData.getWord("Agent adherence view"));
      out.write("\");\r\n");
      out.write("    \t\t\t\t\t\t}else if (vValue == 'AgentGroupsRTA'){\r\n");
      out.write("       \t\t\t\t\t\t\tdocument.write(\"");
      out.print( pageData.getWord("Agent Group Real-Time Adherence View"));
      out.write("\");\r\n");
      out.write("    \t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t</legend>\r\n");
      out.write("\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;\"  width=\"574\">\r\n");
      out.write("  \t\t\t\t\t\t<tr height=\"45\">\r\n");
      out.write("\t\t\t\t\t\t\t<script language=\"JavaScript\">\r\n");
      out.write("\t\t\t\t\t\t\t\tvar vValue = normalizeString(QueryString('type'));\r\n");
      out.write("\t\t\t\t\t\t\t\tif (vValue != ''){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif (vValue == 'Agents'){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<td valign=\"top\" style=\"border-left-style:none; border-left-width:1; border-top-style:none; border-top-width:1;\" >')\r\n");
      out.write("\t\t\t    \t\t\t\t\t\tdocument.write('<br>')\r\n");
      out.write("\t\t\t    \t\t\t\t\t\tdocument.write('<select id=\"objects\" name=\"objects\" multiple>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<option value=\"\">&nbsp;</option>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<option value=\"\">&nbsp;&nbsp;");
      out.print(pageData.getWord("Loading"));
      out.write("...</option>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<option value=\"\">&nbsp;&nbsp;");
      out.print(pageData.getWord("Please wait"));
      out.write(".</option>')\r\n");
      out.write("\t\t\t    \t\t\t\t\t\tdocument.write('</select>')\r\n");
      out.write("\t\t\t    \t\t\t\t\t\tdocument.write('</td>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("     \t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<td valign=\"top\" style=\"border-left-style:none; border-left-width:1; border-top-style:none; border-top-width:1;\" >')\r\n");
      out.write("\t\t\t    \t\t\t\t\t\tdocument.write('<br>')\r\n");
      out.write("\t\t\t    \t\t\t\t\t\tdocument.write('<select id=\"objects\" name=\"objects\" multiple onClick=\"enableUpdateButton()\">')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<option value=\"\">&nbsp;</option>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<option value=\"\">&nbsp;&nbsp;");
      out.print(pageData.getWord("Loading"));
      out.write("...</option>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<option value=\"\">&nbsp;&nbsp;");
      out.print(pageData.getWord("Please wait"));
      out.write(".</option>')\r\n");
      out.write("\t\t\t    \t\t\t\t\t\tdocument.write('</select>')\r\n");
      out.write("\t\t\t    \t\t\t\t\t\tdocument.write('</td>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("    \t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("    \t\t\t\t\t\t\t\tif (vValue == 'Agents'){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<td valign=\"top\" style=\"padding-left:15px;\">')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<div style=\"width:450px;\">')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<div style=\"padding-top:8px; padding-bottom:4px;\">search for:</div>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<span style=\"width:130px\">");
      out.print(pageData.getWord("First name"));
      out.write("</span>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<span style=\"width:130px\">");
      out.print(pageData.getWord("Last name"));
      out.write("</span>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<span style=\"width:110px\">");
      out.print(pageData.getWord("Agent ID"));
      out.write("</span>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<br>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<span style=\"width:130px\"><input id=\"searchfirst\" type=\"text\" value=\"\" size=\"16\" name=\"searchfirst\" /></span>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<span style=\"width:130px\"><input id=\"searchlast\" type=\"text\" value=\"\" size=\"16\" name=\"searchlast\" /></span>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<span style=\"width:110px\"><input id=\"searchid\" type=\"text\" value=\"\" size=\"12\" name=\"searchid\" /></span>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<button id=\"searchbut\" onClick=\"searchFor()\" style=\"cursor:pointer\">");
      out.print(pageData.getWord("Search"));
      out.write("</button>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<br>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<span style=\"width:300px; padding top:5px;\">')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<input type=checkbox name=ckbox checked onClick=\"searchFor()\">')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('");
      out.print(pageData.getWord("Show only active agents"));
      out.write("'); // previously unchecked and text - Show all agents\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<br>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<input type=checkbox name=viewckbox onClick=\"searchFor()\" >')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write(\"");
      out.print(pageData.getWord("Show agent by ID"));
      out.write("\");\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('</span>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<span><button onClick=\"resetResults()\" style=\"cursor:pointer; margin-top:5px;\">");
      out.print(pageData.getWord("show full list"));
      out.write("</button></span>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('</div>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('</td>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("    \t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<td valign=\"top\" style=\"padding-left:15px;\">')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<div style=\"width:450px;\">')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<div style=\"padding-top:8px; padding-bottom:4px;\">");
      out.print(pageData.getWord("Search for either"));
      out.write(":</div>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<span style=\"width:130px\">");
      out.print(pageData.getWord("Name"));
      out.write("</span>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<span style=\"width:130px\">");
      out.print(pageData.getWord("Name includes"));
      out.write("</span>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<br>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<span style=\"width:130px\"><input id=\"searchfullname\" type=\"text\" value=\"\" size=\"16\" name=\"searchfullname\" /></span>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<span style=\"width:130px\"><input id=\"searchpartname\" type=\"text\" value=\"\" size=\"16\" name=\"searchpartname\" /></span>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<button id=\"searchbut\" onClick=\"searchFor()\" style=\"cursor:pointer\">");
      out.print(pageData.getWord("Search"));
      out.write("</button>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<br>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('<span><button onClick=\"resetResults()\" style=\"cursor:pointer; margin-top:5px;\">");
      out.print(pageData.getWord("show full list"));
      out.write("</button></span>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('</div>')\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tdocument.write('</td>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write('<td>&nbsp;</td>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write('<td>&nbsp;</td>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write('<td>&nbsp;</td>')\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"28%\"  valign=\"top\" style=\"border-right-style: none; border-right-width: 1; border-top-style: none; border-top-width: 1\" >\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse; margin-top:10px;\" width=\"700\">\r\n");
      out.write("\t\t\t\t\t\t<tr style=\"padding-bottom:4px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"100\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150\"><b>");
      out.print( pageData.getWord("Starting time"));
      out.write("</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150\"><b>");
      out.print( pageData.getWord("Ending time"));
      out.write("</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"250\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr style=\"padding-bottom:20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"100\">");
      out.print( pageData.getWord("Time period"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"170\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"startTime\" onChange=\"enableUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"00:00\">00:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"00:15\">00:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"00:30\">00:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"00:45\">00:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"01:00\">01:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"01:15\">01:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"01:30\">01:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"01:45\">01:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"02:00\">02:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"02:15\">02:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"02:30\">02:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"02:45\">02:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"03:00\">03:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"03:15\">03:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"03:30\">03:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"03:45\">03:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"04:00\">04:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"04:15\">04:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"04:30\">04:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"04:45\">04:45</option>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t<option value=\"05:00\">05:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"05:15\">05:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"05:30\">05:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"05:45\">05:45</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"06:00\">06:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"06:15\">06:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"06:30\">06:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"06:45\">06:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"07:00\">07:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"07:15\">07:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"07:30\">07:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"07:45\">07:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"08:00\">08:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"08:15\">08:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"08:30\">08:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"08:45\">08:45</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"09:00\">09:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"09:15\">09:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"09:30\">09:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"09:45\">09:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10:00\" selected>10:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10:15\">10:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10:30\">10:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10:45\">10:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"11:00\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"11:15\">11:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"11:30\">11:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"11:45\">11:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"12:00\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"12:15\">12:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"12:30\">12:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"12:45\">12:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"13:00\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"13:15\">13:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"13:30\">13:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"13:45\">13:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"14:00\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"14:15\">14:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"14:30\">14:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"14:45\">14:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"15:00\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"15:15\">15:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"15:30\">15:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"15:45\">15:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"16:00\">16:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"16:15\">16:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"16:30\">16:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"16:45\">16:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"17:00\">17:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"17:15\">17:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"17:30\">17:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"17:45\">17:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"18:00\">18:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"18:15\">18:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"18:30\">18:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"18:45\">18:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"19:00\">19:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"19:15\">19:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"19:30\">19:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"19:45\">19:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"20:00\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"20:15\">20:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"20:30\">20:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"20:45\">20:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"21:00\">21:00</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"21:15\">21:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"21:30\">21:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"21:45\">21:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"22:00\">22:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"22:15\">22:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"22:30\">22:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"22:45\">22:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"23:00\">23:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"23:15\">23:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"23:30\">23:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"23:45\">23:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"24:00\">24:00</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"endTime\"  onChange=\"enableUpdateButton()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"00:00\">00:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"00:15\">00:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"00:30\">00:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"00:45\">00:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"01:00\">01:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"01:15\">01:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"01:30\">01:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"01:45\">01:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"02:00\">02:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"02:15\">02:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"02:30\">02:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"02:45\">02:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"03:00\">03:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"03:15\">03:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"03:30\">03:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"03:45\">03:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"04:00\">04:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"04:15\">04:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"04:30\">04:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"04:45\">04:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"05:00\">05:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"05:15\">05:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"05:30\">05:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"05:45\">05:45</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"06:00\">06:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"06:15\">06:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"06:30\">06:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"06:45\">06:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"07:00\">07:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"07:15\">07:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"07:30\">07:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"07:45\">07:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"08:00\">08:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"08:15\">08:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"08:30\">08:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"08:45\">08:45</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"09:00\">09:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"09:15\">09:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"09:30\">09:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"09:45\">09:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10:00\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10:15\">10:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10:30\">10:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10:45\">10:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"11:00\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"11:15\">11:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"11:30\">11:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"11:45\">11:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"12:00\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"12:15\">12:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"12:30\">12:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"12:45\">12:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"13:00\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"13:15\">13:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"13:30\">13:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"13:45\">13:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"14:00\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"14:15\">14:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"14:30\">14:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"14:45\">14:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"15:00\">15:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"15:15\">15:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"15:30\">15:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"15:45\">15:45</option>\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t<option value=\"16:00\">16:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"16:15\">16:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"16:30\">16:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"16:45\">16:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"17:00\" selected>17:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"17:15\">17:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"17:30\">17:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"17:45\">17:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"18:00\">18:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"18:15\">18:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"18:30\">18:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"18:45\">18:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"19:00\">19:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"19:15\">19:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"19:30\">19:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"19:45\">19:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"20:00\">20:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"20:15\">20:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"20:30\">20:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"20:45\">20:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"21:00\">21:00</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"21:15\">21:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"21:30\">21:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"21:45\">21:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"22:00\">22:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"22:15\">22:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"22:30\">22:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"22:45\">22:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"23:00\">23:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"23:15\">23:15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"23:30\">23:30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"23:45\">23:45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"24:00\">24:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"230\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( pageData.getWord("Spacing(mn)"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"spacing\" onChange=\"enableUpdateButton()\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"15\" selected>15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"30\">30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"45\">45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"60\">60</option>\r\n");
      out.write("      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--<option value=\"120\">2h</option>-->\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\tif (vValue == 'Agents'){\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<tr style=\"padding-bottom:4px;\">');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<td width=\"100\">");
      out.print( pageData.getWord("Report"));
      out.write("</td>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<td width=\"170\"><b>");
      out.print( pageData.getWord("Starting date"));
      out.write("</b></td>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<td width=\"380\" colspan=\"2\"><b>");
      out.print( pageData.getWord("Ending date"));
      out.write("</b></td>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('</tr>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<tr>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<td width=\"100\"><input name=\"period\" type=\"radio\" value=\"daily\"  onClick=\"changeDisabled()\" checked style=\"margin-right:10px;\">");
      out.print( pageData.getWord("Daily"));
      out.write("</td>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<td width=\"170\"><input id=\"id_startingDateDaily\" type=\"text\" size=\"20\" onFocus=\"showCalendar(\\'\\',this,this,\\'\\',\\'id_startingDateDaily\\',0,30,1);this.blur()\" name=\"startingDateDaily\" /></td>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<td width=\"380\" colspan=\"2\"><input id=\"id_endingDateDaily\" type=\"text\" size=\"20\" onFocus=\"showCalendar(\\'\\',this,this,\\'\\',\\'id_endingDateDaily\\',0,30,1);this.blur()\" name=\"endingDateDaily\"/></td>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('</tr>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<tr style=\"padding-top:4px;\">');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<td width=\"100\"><input name=\"period\" type=\"radio\" value=\"monthly\"  onClick=\"changeDisabled()\" style=\"margin-right:10px;\">");
      out.print( pageData.getWord("Monthly"));
      out.write("</td>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<td width=\"170\">');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<select name=\"starting_month_monthly\" disabled=\"true\" onChange=\"setEndingMonth()\" style=\"margin-right:4px;\">');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"01\">01</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"02\">02</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"03\">03</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"04\">04</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"05\">05</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"06\">06</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"07\">07</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"08\">08</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"09\">09</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"10\">10</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"11\">11</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"12\">12</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('</select>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<select name=\"starting_year_monthly\" disabled=\"true\">');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"2004\">2004</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"2005\">2005</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"2006\">2006</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"2007\">2007</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"2008\">2008</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"2009\">2009</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"2010\">2010</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"2011\">2011</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"2012\">2012</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"2013\">2013</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"2014\">2014</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<option value=\"2015\">2015</option>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('</select>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('</td>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<td width=\"380\" colspan=\"2\"></td>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('</tr>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<tr style=\"padding-bottom:4px;\">');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<td width=\"100\">&nbsp;</td>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<td width=\"550\" colspan=\"3\"><button onClick=\"getRequestedReport()\">");
      out.print( pageData.getWord("Submit"));
      out.write("</button></td>');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('</tr>');\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t}else if(vValue == 'AgentGroupsRTA'){\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<tr style=\"padding-bottom:4px;\">');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('<td width=\"100\">&nbsp;</td>');\r\n");
      out.write("\t\t\t\t\t\t\t\tvar showAdherenceValue = String( appletObj.m_showAdherenceValue );\r\n");
      out.write("\t\t\t\t\t\t\t\tif (showAdherenceValue == 'true')\t\t{\r\n");
      out.write("//\t\t\t\t\t\t\t\t\tdocument.startButton.disabled = true;\r\n");
      out.write("//\t\t\t\t\t\t\t\t\tdocument.stopButton.disabled = false;\r\n");
      out.write("\t  \t\t\t\t\t\t\t\tif(String(appletObj.m_gotAdherence) == 'false'){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<td width=\"550\" colspan=\"3\">');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<button name=\"saveButton\" disabled onClick=\"saveAdhViewData()\">");
      out.print( pageData.getWord("Save"));
      out.write("</button>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<button name=\"startButton\" onClick=\"var sret=sendRTAStartRequest()\">");
      out.print( pageData.getWord("Start"));
      out.write("</button>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<button name=\"stopButton\" onClick=\"sendRTAStopRequest(); updateStopButton()\">");
      out.print( pageData.getWord("Stop"));
      out.write("</button>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('</td>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<td width=\"550\" colspan=\"3\">');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<button name=\"saveButton\" disabled onClick=\"saveAdhViewData()\">");
      out.print( pageData.getWord("Save"));
      out.write("</button>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<button name=\"startButton\" disabled onClick=\"var sret=sendRTAStartRequest()\">");
      out.print( pageData.getWord("Start"));
      out.write("</button>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('<button name=\"stopButton\" onClick=\"sendRTAStopRequest(); updateStopButton()\">");
      out.print( pageData.getWord("Stop"));
      out.write("</button>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write('</td>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write('<td width=\"550\" colspan=\"3\">');\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write('<button name=\"saveButton\" disabled onClick=\"saveAdhViewData()\">");
      out.print( pageData.getWord("Save"));
      out.write("</button>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write('<button name=\"startButton\" onClick=\"var sret=sendRTAStartRequest()\">");
      out.print( pageData.getWord("Start"));
      out.write("</button>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write('<button name=\"stopButton\" disabled onClick=\"sendRTAStopRequest(); updateStopButton()\">");
      out.print( pageData.getWord("Stop"));
      out.write("</button>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write('</td>');\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write('</tr>');\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\tsetDefaultValue();\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"noresult\" style=\"position:absolute; top:60px; left:60px; visibility:hidden\">No match.</div>\r\n");
      out.write("</body>\r\n");
 pageData.closeConnection(); 
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
