package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.*;
import aheevaManager.ressources.*;

public final class rtaview1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
    pageData.openConnection();

      out.write("\r\n");
      out.write("<LINK href=\"../Resources_pages/style.css\" type=text/css rel=stylesheet>\r\n");
      out.write("<style>\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("/* Context menu Script- © Dynamic Drive (www.dynamicdrive.com) Last updated: 01/08/22\r\n");
      out.write("For full source code and Terms Of Use, visit http://www.dynamicdrive.com */\r\n");
      out.write("\r\n");
      out.write(".skin0{\r\n");
      out.write("position:absolute;\r\n");
      out.write("width:145px;\r\n");
      out.write("border:2px solid black;\r\n");
      out.write("background-color:lavenderblush ;\r\n");
      out.write("font-family:Verdana;\r\n");
      out.write("line-height:15px;\r\n");
      out.write("cursor:default;\r\n");
      out.write("font-size:10px;\r\n");
      out.write("z-index:80;\r\n");
      out.write("visibility:hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menuitems{\r\n");
      out.write("padding-left:6px;\r\n");
      out.write("padding-right:6px;\r\n");
      out.write("height:17;\r\n");
      out.write("visibility:visible;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.sousmenu{\r\n");
      out.write("position:absolute;\r\n");
      out.write("left:0;\r\n");
      out.write("height:20;\r\n");
      out.write("width:145px;\r\n");
      out.write("visibility:hidden;\r\n");
      out.write("border:2px solid black;\r\n");
      out.write("border-style: solid;\r\n");
      out.write("border-color: #000000;\r\n");
      out.write("background-color:#C3C9D4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.menu{font-family:arial; color: black; font-size: 11px; font-weight:bold; text-decoration: none;}\r\n");
      out.write("a.smenu{font-family:arial; color:black; font-size: 11px; font-weight:bold; text-decoration: none;}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<head>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<SCRIPT language=\"JAVASCRIPT\" src=\"../Resources_pages/jsUtil.js\"></SCRIPT>\r\n");
      out.write("<SCRIPT language=\"JAVASCRIPT\" src=\"../Resources_pages/Table1.js\"></SCRIPT>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Browser.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("document.oncontextmenu=new Function(\"return false;\");\r\n");
      out.write("\r\n");
      out.write("\t/* Variables declarations and Initializations*/\r\n");
      out.write("\t\t var myTable ;\t\t\t\t\t\t\t// the table object that will be drawn for scheduling & adherence\r\n");
      out.write("\t\t var layer;\r\n");
      out.write("\t\t var rows = 1, cntRow = 0;\t\t\t\t// the number of rows in the table\r\n");
      out.write("\t\t var cols = 1, cntCol = 0;\t\t\t\t// the number of columns in the table\r\n");
      out.write("\t\t var myData ;\t\t\t\t\t\t\t// the data in each cell of the table\r\n");
      out.write("\t\t var cells;\r\n");
      out.write("\t\t var hoverHelpData;\r\n");
      out.write("\t\t var personalData;\t\t\t\t\t\t// table containing private data as: IP, first login, group name, etc..\r\n");
      out.write("\t\t var adherenceDetails;\t\t\t\t\t// table containing adherence details for each period\r\n");
      out.write("\r\n");
      out.write("\t\t var bhh;\t\t\t\t\t\t\t\t// tmp. variable indicating the begin hour value of the current cell\r\n");
      out.write("\t\t var bmm;\t\t\t\t\t\t\t\t// tmp. variable indicating the begin minute value\r\n");
      out.write("\t\t var ehh, emm;\t\t\t\t\t\t\t// tmp. variable indicating the end hour value, end minute value\r\n");
      out.write("\t\t var increment;\t\t\t\t\t\t\t// spacing between column in minutes\r\n");
      out.write("\t\t var agt_id;\r\n");
      out.write("\t\t var viewHTML;\t\t\t\t\t\t\t//the html code of the view\r\n");
      out.write("         var allAgentScheduleData=new Array();    //Tab containing all schedule and adherence data received from CTI\r\n");
      out.write("\t\t var thisDayScheduleInfo=new Array();    //Tab containing only schedule info received from CTI for all agents\r\n");
      out.write("         var nrow ;\r\n");
      out.write("\t\t var beginTime, endTime, starttime, endtime;\r\n");
      out.write("\t\t var period;\r\n");
      out.write("\t\t var thetime =new Date();\r\n");
      out.write("         var today=thetime.getYear()+\"/\"+(thetime.getMonth()+1)+\"/\"+thetime.getDate();\r\n");
      out.write("\t\t var firstLoad = true;\r\n");
      out.write("\t\t var lastZoomFactor = 0.5;\r\n");
      out.write("\t\t var adherenceValue, lglobaladherence ;\r\n");
      out.write("\t\t var rowSelected = 0;\r\n");
      out.write("\t\t var nreload = 0;\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t var autoReFreshRta = null;// used with function setInterval() to update RTA each minute\r\n");
      out.write("\t\t var autoRefreshOn = false;// this variable tells us if the function autoRefresh() is running or not\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction refreshConfigData()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//Read the new config data in CommApplet to track the user's change\r\n");
      out.write("\t\tperiod  = \"1\";\r\n");
      out.write("\t\tvar curHr,startHr, endHr, curMin, minute, startHrStr, endHrSTr, minuteStr;\r\n");
      out.write("\t\tvar curTime = new Date();\r\n");
      out.write("\t\tcurHr = curTime.getHours();\r\n");
      out.write("\t\tcurMin = curTime.getMinutes() ;\r\n");
      out.write("\t\tif(curMin >= 30)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tstartHr = curHr % 24;\r\n");
      out.write("\t\t\tendHr = (curHr +1) % 24;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tstartHr = (curHr -1)  % 24;\r\n");
      out.write("\t\t\tendHr = curHr  % 24;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tminute =(curMin + 30) % 60;\t\r\n");
      out.write("\t\t//Build start and end time in hhmm format\r\n");
      out.write("\t\tif(startHr <= 9)//one digit\r\n");
      out.write("\t\t\tstartHrStr = \"0\" + startHr;\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\tstartHrStr = \"\" + startHr;\r\n");
      out.write("\t\tif(endHr <= 9)\r\n");
      out.write("\t\t\tendHrSTr = \"0\" + endHr;\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\tendHrSTr = \"\" + endHr;\t\t\t\r\n");
      out.write("\t\tif( minute <= 9 )\r\n");
      out.write("\t\t\tminuteStr = \"0\" + minute;\r\n");
      out.write("\t\telse \r\n");
      out.write("\t\t\tminuteStr = \"\" + minute;\r\n");
      out.write("\t\r\n");
      out.write("\t\tbeginTime = \"\" + startHrStr + minuteStr;\r\n");
      out.write("\t\tendTime = \"\" + endHrSTr + minuteStr;\r\n");
      out.write("\t\t//alert(\"beginTime\"+beginTime+\"endTime\"+endTime);  \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// build starttime, endtime in 'hh:mm' format to send to request updating RTA \r\n");
      out.write("\t\tstarttime = \"\" + startHrStr + \":\" + minuteStr;\r\n");
      out.write("\t\tendtime = \"\" + endHrSTr + \":\" + minuteStr;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tfunction loadAllAgentGroups()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar arrayGroups;\r\n");
      out.write("\t\tvar allAgentGroups  = String(appletObj.getActiveAgentGroupByName());\r\n");
      out.write("\t\tvar jsGroups = allAgentGroups  + \"\";\r\n");
      out.write("\t\tarrayGroups = jsGroups.split(\"|\");\r\n");
      out.write("\t\tfor (j = 0; j <arrayGroups.length; j++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tmyOption = new Option(arrayGroups[j], arrayGroups[j]);\r\n");
      out.write("\t\t\toptionPos = adhGroup.options.length;\r\n");
      out.write("\t\t\tadhGroup.options[optionPos]=myOption;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar adhRunning= appletObj.isAdherenceStarted();\r\n");
      out.write("\t\tvar selected = appletObj.getAdhereceSelectedGroup();\r\n");
      out.write("\t\tif(selected != \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tfor(i=0;i<adhGroup.options.length;i++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif(adhGroup.options[i].value==selected)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tadhGroup.options[i].selected=true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tadhGroup.disabled=true;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction onGroupChange()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//change comApplet adherence group\r\n");
      out.write("\t\tappletObj.updateRTAGroup(adhGroup.options[adhGroup.selectedIndex].value);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction setRowNum(numrows)\r\n");
      out.write("\t{\r\n");
      out.write("\t  rows = 2*parseInt(numrows,10) + 1;\r\n");
      out.write("\t  myData = new Array(rows);\r\n");
      out.write("\t  cells = new Array(rows);\r\n");
      out.write("\t  hoverHelpData = new Array(rows);\r\n");
      out.write("\t  personalData = new Array(rows);\r\n");
      out.write("\t  adherenceDetails\t= new Array(rows);\r\n");
      out.write("\t  cntRow = 0;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction createTable()\r\n");
      out.write("\t{\r\n");
      out.write("\t  // alert(rows+'..'+cols)\r\n");
      out.write("\t  myTable = new Table(rows,cols);\r\n");
      out.write("\t  myTable.enableHoverHelp(true,hoverHelpData);\r\n");
      out.write("\t  myTable.setTableData(myData);\r\n");
      out.write("\t  myTable.setCellData(cells);\r\n");
      out.write("\t  myTable.setTablePos(4,125);\r\n");
      out.write("\t  myTable.enableColumnHeaders(true);\r\n");
      out.write("\t  myTable.enableRowHeaders(true);\r\n");
      out.write("\t  myTable.setRowHeight(18);    //18\r\n");
      out.write("\t  myTable.setFirstRowHeight(30);\r\n");
      out.write("\t  myTable.setTableModelSchedule(true);\r\n");
      out.write("\t  myTable.setTableModelRta(true);\r\n");
      out.write("\t  myTable.enableCellSelection(false);\r\n");
      out.write("\t  myTable.enableRowSelection(true,\"lightgrey\");\r\n");
      out.write("\t  myTable.setCellColor(\"royalblue\",\"yellow\", \"skyblue\",\"green\", \"red\");\r\n");
      out.write("\t  myTable.setHightLightCellColor(\"darkblue\",\"gold\",\"powderblue\",\"lightgreen\",\"darkred\",\"powderblue\");\r\n");
      out.write("\t  myTable.paint3(viewHTML);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction scrollingDetector(){\r\n");
      out.write("\t\tif (navigator.appName == \"Microsoft Internet Explorer\")\t{\r\n");
      out.write("\t\t\talert(\"");
      out.print( pageData.getWord("You are at"));
      out.write("\" + document.body.scrollLeft + \"");
      out.print( pageData.getWord(" pixels"));
      out.write("\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t    alert(\"");
      out.print( pageData.getWord("You are at"));
      out.write("\" + window.pageYOffset + \"");
      out.print( pageData.getWord(" pixels"));
      out.write("\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction startScrollingDetector(){\r\n");
      out.write("\t\tsetInterval(\"scrollingDetector()\", 60000);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction setPageTitle()\r\n");
      out.write("\t{\r\n");
      out.write("\t\twindow.top.document.title = \t\"Agent Schedule and Adherence data\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction setColumNum()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t  bhh = parseInt(beginTime.substring(0,2),10);\r\n");
      out.write("\t\t  bmm = parseInt(beginTime.substring(2,4),10);\r\n");
      out.write("\t\t  ehh = parseInt(endTime.substring(0,2),10);\r\n");
      out.write("\t\t  emm = parseInt(endTime.substring(2,4),10);\r\n");
      out.write("\t\t  increment =  parseInt(period,10);\r\n");
      out.write("\t\t  var ncols = 0;\r\n");
      out.write("\t\t  for(i=bhh,j=bmm;i<ehh || j<=emm;j+=increment){\r\n");
      out.write("\t\t\tif(j>=60){\r\n");
      out.write("\t\t\t   j=j-60;\r\n");
      out.write("\t\t\t   i=i+1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(String(j).length ==1)\r\n");
      out.write("\t\t\t   k=\"0\"+j;\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t   k=j;\r\n");
      out.write("\t\t\tncols = ncols+1;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\tcols = ncols;\r\n");
      out.write("\t\t//alert(cols)\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction setColumHeadersValue()\r\n");
      out.write("\t{\r\n");
      out.write("\t   var colNum=0\r\n");
      out.write("\t   //Set array for row header data\r\n");
      out.write("\t   myData[0] = new Array(cols);\r\n");
      out.write("\t   hoverHelpData[0] = new Array(cols);\r\n");
      out.write("\t   cells[0]= new Array(cols);\r\n");
      out.write("\t   myData[0][0]=\" ");
      out.print( pageData.getWord("Time hh:mm"));
      out.write("\";//\" Time hh:mm\";\r\n");
      out.write("\t   hoverHelpData[0][0]=\"\";\r\n");
      out.write("\t   cells[0][0]= \"\";\r\n");
      out.write("\t   personalData[0]=\"\";\r\n");
      out.write("\t   adherenceDetails[0]=\"\";\r\n");
      out.write("\t   for(i=bhh,j=bmm;i<ehh || j<=emm;j+=increment){\r\n");
      out.write("\t\t  colNum++;\r\n");
      out.write("\t\t  if(j>=60){\r\n");
      out.write("\t\t\t j=j-60;\r\n");
      out.write("\t\t\t i=i+1;\r\n");
      out.write("\t\t  }\r\n");
      out.write("\r\n");
      out.write("\t\tif(String(j).length ==1)\r\n");
      out.write("\t\t\t k=\"0\"+j;\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\t k=j;\r\n");
      out.write("\t\tvalue = i+\":\"+k;\r\n");
      out.write("\t\tmyData[0][colNum]= value;\r\n");
      out.write("\t\thoverHelpData[0][colNum]=value;\r\n");
      out.write("\t\tcells[0][colNum] = value;\r\n");
      out.write("\t  }\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("   function generateRtaView()\r\n");
      out.write("   {\r\n");
      out.write("        viewHTML = \"<TABLE cellspacing=1px bgcolor=lightyellow>\";\r\n");
      out.write("    \tsetColumNum();\r\n");
      out.write("\t\t//Set the number of rows in the table\r\n");
      out.write("\t\tnrow = allAgentScheduleData.length;\r\n");
      out.write("\t\tif(nrow == 0 || (allAgentScheduleData[0].length==0)){\r\n");
      out.write("\t\t\tif(appletObj.isAdherenceStarted()==\"false\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tallAgentScheduleData=new Array();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\twindow.top.main.rtop.refreshAgentAdherenceStats();\r\n");
      out.write("\t\t\tnrow = allAgentScheduleData.length;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\tif(allAgentScheduleData[0] != null )\r\n");
      out.write("\t\t  if( allAgentScheduleData[0].length == 0)\r\n");
      out.write("\t\t\tnrow = 0;\r\n");
      out.write("\t\tsetRowNum(nrow);\r\n");
      out.write("\t\tsetColumHeadersValue();\r\n");
      out.write("\t\tviewHTML += '<TR>';\r\n");
      out.write("\t\tfor(c=0;c < cols ; c++)\r\n");
      out.write("\t\t   viewHTML += \"<TD align='center' width=100 height=30 bgcolor=gray  title=\\\"\"+ hoverHelpData[0][c]+\"\\\">\"+myData[0][c]+\"</TD>\";\r\n");
      out.write("\t\tviewHTML += '</TR>';\r\n");
      out.write("\r\n");
      out.write("\t   var cnt=0,iter=0, n=0, nParam;       //counter for iteration\r\n");
      out.write("\t   var nb_elt = 0;\r\n");
      out.write("\t   var timeBlockData;                   //Data for this time block\r\n");
      out.write("\t   var agentDaySchedAdherence;          //all schedule and adherence data for an agent\r\n");
      out.write("\r\n");
      out.write("\t   var curAgtID, curAgtName='';         //the current agent ID and name\r\n");
      out.write("\t   var nbCells=0;\r\n");
      out.write("\t   var jsSchedData, arrayTimeBlock;\r\n");
      out.write("\t   var startTime,stopTime,activity_type,adherenceData;\r\n");
      out.write("\t   var nNoAdh = 0, nAdh = 0;\r\n");
      out.write("\t   lglobaladherence = 0;\r\n");
      out.write("\r\n");
      out.write("\t   if(nrow > 1 ){\r\n");
      out.write("\t\t  //Loop for every agent\r\n");
      out.write("\t\t  for(cnt = 0;cnt < allAgentScheduleData.length;cnt++){\r\n");
      out.write("\t\t\t //Get the adherence and schedule data for this agent\r\n");
      out.write("\t\t\t agentDaySchedAdherence = allAgentScheduleData[cnt];\r\n");
      out.write("\r\n");
      out.write("\t\t\t //Add a new row to myData for this agent schedule\r\n");
      out.write("\t\t\t cntRow++;\r\n");
      out.write("\t\t\t myData[cntRow] = new Array(cols);\r\n");
      out.write("\t\t\t hoverHelpData[cntRow] = new Array(cols);\r\n");
      out.write("\t\t\t cells[cntRow] = new Array(cols);\r\n");
      out.write("\t\t\t //Add a new row to myData for this agent adherence\r\n");
      out.write("\t\t\t myData[cntRow+1] = new Array(cols);\r\n");
      out.write("\t\t\t hoverHelpData[cntRow+1] = new Array(cols);\r\n");
      out.write("\t\t\t cells[cntRow+1] = new Array(cols);\r\n");
      out.write("\t\t\t for (nc=0;nc<cols;nc++) {\r\n");
      out.write("\t\t\t \tcells[cntRow][nc] = \"\";\r\n");
      out.write("\t\t\t\tcells[cntRow+1][nc] = \"\";\r\n");
      out.write("\t\t\t\tif ((cntRow+1) %2 == 0 && (cntRow+1)!= 0)\r\n");
      out.write("\t\t\t\t   {\r\n");
      out.write("\t\t\t\t\t  myData[cntRow][nc] = \"\";\r\n");
      out.write("\t\t\t\t   }\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\r\n");
      out.write("\t\t\t //Set current agent ID and Fill the new row with schedule data :\r\n");
      out.write("\t\t\t //1047^0-17:2,18-29:5,30-30:3,31-31:6,32-41:5^0-26:2,27-27:0|\r\n");
      out.write("\t\t\t var jsAgentData = agentDaySchedAdherence + \"\";\r\n");
      out.write("\t\t\t arrayAgentData\t= jsAgentData .split(\"^\");\r\n");
      out.write("\t\t\t var colIndex = 0;\r\n");
      out.write("\t\t\t for(nElt = 0; nElt < arrayAgentData.length; nElt++)\r\n");
      out.write("\t\t\t  {\r\n");
      out.write("\t\t\t  \t\t  nbCells=0;\r\n");
      out.write("\t\t\t\t\t  if(nElt == 0){\r\n");
      out.write("\t\t\t\t\t\t\tcurAgtID = arrayAgentData[0];\r\n");
      out.write("\t\t\t\t\t\t\tif(curAgtID == null)\r\n");
      out.write("\t\t\t\t\t\t\t   curAgtID = '';\r\n");
      out.write("\t\t\t\t\t\t\tif(curAgtID.length > 0 && window.top.comm.myApplet != null)\r\n");
      out.write("\t\t\t\t\t\t\t\tcurAgtName = appletObj.getAgentFullName(curAgtID);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tif(curAgtName == null)\r\n");
      out.write("\t\t\t\t\t\t\t\tcurAgtName = '';\r\n");
      out.write("\t\t\t\t\t\t\t//Set agent id value for the first cell of the row\r\n");
      out.write("\t\t\t\t\t\t\tmyData[cntRow][0]= curAgtID;\r\n");
      out.write("\t\t\t\t\t\t\thoverHelpData[cntRow][0]=curAgtID+'['+curAgtName+']' ;\r\n");
      out.write("\t\t\t\t\t\t\thoverHelpData[cntRow+1][0]=curAgtID+'['+curAgtName+']' ;\r\n");
      out.write("\t\t\t\t\t\t\tcells[cntRow][0]= curAgtID;\r\n");
      out.write("\t\t\t\t\t\t\tcells[cntRow+1][0]= curAgtID;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t  else if(nElt ==1){\r\n");
      out.write("\t\t\t\t\t  \t\tadherenceDetails[cntRow] = arrayAgentData[nElt] + \"\";\r\n");
      out.write("\t\t\t\t\t\t\tadherenceDetails[cntRow+1] = arrayAgentData[nElt] + \"\";\r\n");
      out.write("                            lglobaladherence += parseFloat(arrayAgentData[nElt]);\r\n");
      out.write("\t\t\t\t\t  }else if (nElt ==2){\r\n");
      out.write("\t\t\t\t\t  \t\tpersonalData[cntRow] = arrayAgentData[nElt] + \"\";\r\n");
      out.write("\t\t\t\t\t\t\tpersonalData[cntRow+1] = arrayAgentData[nElt] + \"\";\r\n");
      out.write("\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t  else {\r\n");
      out.write("\t\t\t\t\t\t\t   nbCells=1;\r\n");
      out.write("\t\t\t\t\t  \t\t   if(nElt ==3)\r\n");
      out.write("\t\t\t\t\t  \t\t   \t\tviewHTML += \"<TR id=\"+cntRow+\">\";\r\n");
      out.write("\t\t\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t\t   viewHTML += \"<TR id=\"+(parseInt(cntRow)+1)+\">\";\r\n");
      out.write("\t\t\t\t\t\t\t   //viewHTML += '<TD width='+this.columnWidth[0]+' rowspan=2 height='+this.rowHeight+' bgcolor='+this.headerBackgroundColor+'>'+curAgtID+'</TD>';\r\n");
      out.write("\t\t\t\t\t\t\t   if(nElt ==3)\r\n");
      out.write("   \t\t\t\t\t\t\t      viewHTML += \"<TD align='center' id='\"+cntRow+\"-0' width=100 rowspan=2 height=18 bgcolor=gray title=\\\"\"+ hoverHelpData[cntRow][0]+\"\\\" onMouseDown=\\\"highLightRow('\"+cntRow+\"')\\\">\"+curAgtID+\"</TD>\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   jsSchedData = arrayAgentData[nElt] + \"\";   //we got a schedule info : 0-17:2,18-29:5,30-30:3,31-31:6,32-41:5\r\n");
      out.write("\t\t\t\t\t\t\t   arrayTimeBlock = jsSchedData.split(\",\");\r\n");
      out.write("\t\t\t\t\t\t\t   //nParam = arrayTimeBlock.length;\r\n");
      out.write("\t\t\t\t\t\t\t   var viewUnit=\"\";\r\n");
      out.write("\t\t\t\t\t\t\t   var valPos = 0, stPos=0, ePos=0, cellval=2, ccolor=\"\";\r\n");
      out.write("\t\t\t\t\t\t\t   var stInd=0, endInd=0 ;\r\n");
      out.write("\t\t\t\t\t\t\t   for(k=0; k < arrayTimeBlock.length; k++)\r\n");
      out.write("\t\t\t\t\t\t\t   {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t viewUnit = arrayTimeBlock[k];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t valPos  = \tviewUnit.indexOf(':');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t sepPos  =  viewUnit.indexOf('-');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t stPos   = \tparseInt(viewUnit.substring(0,sepPos), 10);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t ePos    = \tparseInt(viewUnit.substring(sepPos+1,valPos), 10);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t cellval =  parseInt(viewUnit.substring(valPos+1), 10);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t //Fill cell between column stPos and ePos with cellval\r\n");
      out.write("\t\t\t\t\t\t\t\t\t for(cpos=stPos; cpos <= ePos; cpos++){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \tif(nElt == 3){     //we got schedule info\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   if(cellval == 6)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\tcellval = 10;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif(cellval == 2)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcellval=\"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   myData[cntRow][cpos+1] = cellval;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   hoverHelpData[cntRow][cpos+1]=curAgtID+'['+curAgtName+'] ' ;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   //alert('..cellval..'+ cellval + '..cntRow..'+cntRow+'..cpos+1..'+cpos+1)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\telse if(nElt == 4){ //we got adherence info\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thoverHelpData[cntRow+1][cpos+1]=curAgtID+'['+curAgtName+']';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar string0 =\"");
      out.print( pageData.getWord(" was LOGGED OUT.** Should be logged in during this period"));
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar string1 =\"");
      out.print( pageData.getWord(" was LOGGED IN.** Should be logged in during this period"));
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   if(cellval == 0 || cellval == 4)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tif(cellval == 0)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\thoverHelpData[cntRow+1][cpos+1] = curAgtID+'['+curAgtName+']'+ string0.replace(\"**\",\"\\n\"); \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\thoverHelpData[cntRow+1][cpos+1] = curAgtID+'['+curAgtName+']'+ string1.replace(\"**\",\"\\n\"); \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcellval = 101;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tnNoAdh ++;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   else if(cellval == 1)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcellval = 100;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tnAdh++;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   /*else\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcellval = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \tnAdh++;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}*/\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   if(cellval != 2)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \t\tmyData[cntRow+1][cpos+1] = cellval;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//alert('cntRow..' +cntRow+'..cpos..'+cpos+'..cellval'+cellval)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t }//end for(cpos..)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t //viewHTML\r\n");
      out.write("\t\t\t\t\t\t\t\t\t if(cellval == 100)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \tccolor = \"green\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t else if(cellval == 3)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \tccolor = \"yellow\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t else if(cellval == 4 || cellval==101)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \tccolor = \"red\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t else if (cellval == 5)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \tccolor = \"blue\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t else if (cellval == 6 || cellval == 10)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    ccolor = \"skyblue\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t else\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \tccolor = \"lightyellow\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t var cid= String((nElt==3?cntRow:cntRow+1))+'-'+String(k+1);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t var lcolspan = ePos - stPos +1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t var cwidth = lcolspan*75;\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t viewHTML +=  \"<TD id=\"+cid+\" colspan=\"+lcolspan+\" height=18 width=\"+cwidth+\" bgcolor=\"+ccolor+\" title=\\\"\"+ hoverHelpData[(nElt==3?cntRow:cntRow+1)][stPos+1]+ \"\\\" onMouseDown=\\\"highLightRow('\"+(nElt==3?cntRow:cntRow+1)+\"')\\\"></TD>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t cells[(nElt==3?cntRow:cntRow+1)][nbCells++] = cellval;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t \t  }//fin du for(k..)\r\n");
      out.write("\t\t\t\t\t\t\t/* if(nElt==4){\r\n");
      out.write("\t\t\t\t\t\t\t         lcolspan = cols - stPos +1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t cwidth = lcolspan*75;\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t viewHTML +=  \"<TD id=\"+String(cntRow+1)+'-'+String(k+1)+\" colspan=\"+lcolspan+\" height=18 width=\"+cwidth+\" bgcolor='lightyellow' onMouseDown=\\\"highLightRow('\"+(cntRow+1)+\"')\\\"></TD>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t cells[(cntRow+1)][nbCells] = 2;\r\n");
      out.write("\t\t\t\t\t\t\t }\t*/\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t viewHTML += \"</TR>\";\r\n");
      out.write("\t\t\t\t\t \t}//fin else\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}// fin du for(nElt...)\r\n");
      out.write("\r\n");
      out.write("\t\t\t   //Go to the next row, this row will show the adherence data\r\n");
      out.write("\t\t\t   //Leave the row for adherence data\r\n");
      out.write("\t\t\t   cntRow++;\r\n");
      out.write("\t\t  } //fin du for(cnt..)\r\n");
      out.write("\t   } // fin du if(nrow > 1 )\r\n");
      out.write("\t   else{\r\n");
      out.write("\t   \tviewHTML += '<TR>';\r\n");
      out.write("\t   \t if(appletObj.isAdhGot() == 'false')\r\n");
      out.write("\t\t viewHTML += \"<TD align='justify' height=50   colspan=\"+cols+\"><font face='Arial, Helvetica, sans-serif' size='3' color='#f000000'><b> <marquee WIDTH=100% direction=right behavior=alternate>    ");
      out.print( pageData.getWord("Click Start in"));
      out.write("     <a style=\\\"color:#000000\\\" href='rta1.jsp?type=AgentGroupsRTA&tenant_dbid=1' target='rbottom'><u>   ");
      out.print( pageData.getWord("Real Time Adherence"));
      out.write(" </u></a>   ");
      out.print( pageData.getWord("under Work Force Management--Adherence to view adherence data for this day"));
      out.write(" . </marquee></b></font></TD>\";\r\n");
      out.write("\t   \t else\r\n");
      out.write("\t\t    viewHTML += \"<TD align='justify' height=50   colspan=\"+cols+\"><font face='Arial, Helvetica, sans-serif' size='3' color='#ff0000'><b> <marquee WIDTH=100% direction=right behavior=alternate>  ");
      out.print( pageData.getWord("No schedule data found in database. Please load schedule data for this day"));
      out.write(". </marquee></b></font></TD>\";\r\n");
      out.write("\t\t\tviewHTML += '</TR>';\r\n");
      out.write("\r\n");
      out.write("\t   }\r\n");
      out.write("\t   viewHTML += \"</TABLE>\";\r\n");
      out.write("\t   /*alert(viewHTML);\r\n");
      out.write("\t   var adhVal;\r\n");
      out.write("\t   if( (nNoAdh + nAdh) > 0)\r\n");
      out.write("\t   \t\tadhVal = 100*nAdh/(nNoAdh + nAdh);\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\t adhVal = 100;\r\n");
      out.write("\t   adherenceValue=new String(adhVal);*/\r\n");
      out.write("\t  if(allAgentScheduleData.length > 1)\r\n");
      out.write("\t\t\tlglobaladherence = lglobaladherence/(allAgentScheduleData.length-1);\r\n");
      out.write("      else\r\n");
      out.write("\t\t\tlglobaladherence ='100';\r\n");
      out.write("\t  adherenceValue=new String(lglobaladherence);\r\n");
      out.write("\t  if(adherenceValue.indexOf('.') > 0)\r\n");
      out.write("\t   \t adherenceValue = adherenceValue.substring(0,adherenceValue.indexOf('.')+2);\r\n");
      out.write("\t   adherenceValue=adherenceValue+' %';\r\n");
      out.write("\t   adherence.value = adherenceValue\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\tfunction drawHeader()\r\n");
      out.write("\t{\r\n");
      out.write("\t\theaderHTML = \"<TABLE cellspacing=1px bgcolor=lightyellow>\";\r\n");
      out.write("\r\n");
      out.write("\t\theaderHTML += '<TR>';\r\n");
      out.write("\t\tfor(c=0;c < cols ; c++)\r\n");
      out.write("\t\t   headerHTML += \"<TD align=center  width=100 height=30 bgcolor=gray  title=\\\"\"+ hoverHelpData[0][c]+\"\\\">\"+myData[0][c]+\"</TD>\";\r\n");
      out.write("\t\theaderHTML += '</TR>';\r\n");
      out.write("\r\n");
      out.write("\t\theaderHTML += \"</TABLE>\";\r\n");
      out.write("\t   var oElem = document.getElementById('divRtaHead');\r\n");
      out.write("  \t   oElem.innerHTML = headerHTML;\r\n");
      out.write("\t   oElem.style.height = 30;\r\n");
      out.write("\t   if(firstLoad == true) {\r\n");
      out.write("\t   \t  oElem.style.top = 96;\r\n");
      out.write("\t\t  oElem.style.visibility = 'hidden';\r\n");
      out.write("\t   }\r\n");
      out.write("\t   \r\n");
      out.write("\t   else{\r\n");
      out.write("\t         //var sommet= parseInt(oElem.style.top.substring(0,oElem.style.top.length-2));\r\n");
      out.write("\t\t\t if(document.body.scrollTop > 96){\r\n");
      out.write("             \tvar sommet = document.body.scrollTop;\r\n");
      out.write("\t         \toElem.style.top = sommet;\r\n");
      out.write("\t\t\t \toElem.style.visibility = 'visible';\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction updateHeaderBarPosition()\r\n");
      out.write("\t\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar oElem = document.getElementById('divRtaHead');\r\n");
      out.write("\t\tif(document.body.scrollTop > 96) {\r\n");
      out.write("\t\t\tif(oElem != null){\r\n");
      out.write("\t\t\t oElem.style.top = document.body.scrollTop;\r\n");
      out.write("\t\t\t oElem.style.visibility = 'visible';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tif(oElem != null){\r\n");
      out.write("\t\t\t oElem.style.visibility = 'hidden';\r\n");
      out.write("\t\t\t oElem.style.top = 96;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction refreshRtaView()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar adhRunning= appletObj.isAdherenceStarted();//setTimeout\r\n");
      out.write("\t\tadhGroup.disabled=true;//user can't change agent group here\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(adhRunning==\"true\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t//adhGroup.disabled=false;\r\n");
      out.write("\t\t\tvar i=0;\r\n");
      out.write("\t\t\tvar selected=appletObj.getAdhereceSelectedGroup();\r\n");
      out.write("\t\t\tfor(i=0;i<adhGroup.options.length;i++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif(adhGroup.options[i].value==selected)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tadhGroup.options[i].selected=true;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tadhGroup.disabled=true;\r\n");
      out.write("\t\t} ****************/\r\n");
      out.write("\t\r\n");
      out.write("\t\tnreload++;\r\n");
      out.write("\t\trefreshConfigData() ;\r\n");
      out.write("\t\tgenerateRtaView();\r\n");
      out.write("\t\tdrawHeader();\r\n");
      out.write("\t\tif(firstLoad == true)\r\n");
      out.write("\t\t\tcreateTable();\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tcreateTable();\r\n");
      out.write("\t\t\t\tmyTable.setTableData(myData);\r\n");
      out.write("\t\t\t\t//myTable.paint2();\r\n");
      out.write("\t\t\t\tmyTable.paint3(viewHTML);\r\n");
      out.write("\t\t\t\t// var oElement = document.getElementById('divRtaTab');\r\n");
      out.write("  \t\t\t\t// oElement.innerHTML = viewHTML;\r\n");
      out.write("\t\t\t\tmyTable.enableHoverHelp(true,hoverHelpData);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tsetZoom(lastZoomFactor);\r\n");
      out.write("\t\tif(allAgentScheduleData != null &&  allAgentScheduleData[0] != null ) {\r\n");
      out.write("\t\t\tif(allAgentScheduleData[0].length > 0 || nreload >1)\r\n");
      out.write("\t\t\t\tfirstLoad = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif( (appletObj.isAdherenceStarted()== \"true\") && (!autoRefreshOn) )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t//alert(\"call autoRefresh()\");\r\n");
      out.write("\t\t\tautoRefreshOn = true;\r\n");
      out.write("\t\t\tautoReFreshRta = setInterval('autoRefresh()', 60000);\t\t\r\n");
      out.write("\t\t} \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//This function sends the updated info to the ComApplet object and requests the updated RTA info for each minute \r\n");
      out.write("\tfunction autoRefresh()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif( (appletObj.isAdherenceStarted()== \"true\") && (appletObj.getShowAdhValue() == \"true\") )\r\n");
      out.write("\t\t{ //alert(\"autorefresh\");\r\n");
      out.write("\t\t\trefreshRtaView();\r\n");
      out.write("\t\t\tappletObj.updateRTAViewInfo(starttime, endtime,\"1\",appletObj.getAdhereceSelectedGroup());\r\n");
      out.write("\t\t\tappletObj.sendRTAStartReq();// alert(\"autoRefresh()--- sendRTAStartReq\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(autoReFreshRta != null)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tclearInterval(autoReFreshRta);\r\n");
      out.write("\t\t\tautoRefreshOn = false; //alert(\"stop autorefresh\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t} \r\n");
      out.write("\r\n");
      out.write("\tfunction zoomIn()\r\n");
      out.write("\t{\r\n");
      out.write("\r\n");
      out.write("\t\tif(document.getElementById('divRtaTab').style.zoom == \"\")\r\n");
      out.write("\t\t\tdocument.getElementById('divRtaTab').style.zoom = 1.0;\r\n");
      out.write("\r\n");
      out.write("\t\tif(document.getElementById('divRtaTab').style.zoom <= 1.50)\r\n");
      out.write("\t\t\tdocument.getElementById('divRtaTab').style.zoom = parseFloat(document.getElementById('divRtaTab').style.zoom) + 0.25;\r\n");
      out.write("\t\t\t//document.body.style.zoom = 1.4;\r\n");
      out.write("\t\tlastZoomFactor = document.getElementById('divRtaTab').style.zoom;\r\n");
      out.write("\t    document.getElementById('divRtaHead').style.zoom=document.getElementById('divRtaTab').style.zoom;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction zoomOut()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(document.getElementById('divRtaTab').style.zoom == \"\")\r\n");
      out.write("\t\t\tdocument.getElementById('divRtaTab').style.zoom = 1.0;\r\n");
      out.write("\t\tif(document.getElementById('divRtaTab').style.zoom >= 0.30)\r\n");
      out.write("\t\t\tdocument.getElementById('divRtaTab').style.zoom = document.getElementById('divRtaTab').style.zoom - 0.20;\r\n");
      out.write("\r\n");
      out.write("\t\tlastZoomFactor = document.getElementById('divRtaTab').style.zoom;\r\n");
      out.write("\t\t\t//document.body.style.zoom = 0.5;\r\n");
      out.write("\t    document.getElementById('divRtaHead').style.zoom=document.getElementById('divRtaTab').style.zoom;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction zoomFit()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById('divRtaTab').style.zoom = 0.5;\r\n");
      out.write("\t\tlastZoomFactor = document.getElementById('divRtaTab').style.zoom;\r\n");
      out.write("\t\tdocument.getElementById('divRtaHead').style.zoom=document.getElementById('divRtaTab').style.zoom;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction setZoom(value)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById('divRtaTab').style.zoom = parseFloat(value);\r\n");
      out.write("\t    document.getElementById('divRtaHead').style.zoom=document.getElementById('divRtaTab').style.zoom;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onLoad=\"loadAllAgentGroups()\">\r\n");
      out.write("<table width=\"947\" border=\"0\" align=\"center\" >\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"176\"  class=\"reportsID\"><div align=\"center\"></div></td>\r\n");
      out.write("    <td width=\"284\" valign=\"middle\" >\r\n");
      out.write("       <b>\r\n");
      out.write("\t\t");
      out.print( pageData.getWord("Real-time adherence view for"));
      out.write(" : </b><script language=\"javascript\" type=\"text/javascript\">document.write(' '+today); </script></td>\r\n");
      out.write("    <td width=\"284\" valign=\"middle\"></td>\r\n");
      out.write("\t<td width=\"31\" valign=\"top\"  class=\"reportsID\">&nbsp;</td>\r\n");
      out.write("    <td width=\"438\" valign=\"top\"  class=\"reportsID\">\r\n");
      out.write("\t\t<table width=\"373\" border=\"0\">\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t<td height=\"4\" bgcolor=\"#3333FF\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td >");
      out.print( pageData.getWord("Work period"));
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td bgcolor=\"#339933\" >&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td >");
      out.print( pageData.getWord("Adherence value"));
      out.write(':');
      out.print( pageData.getWord("yes"));
      out.write(" </td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  <tr >\r\n");
      out.write("\t\t\t\t<td width=\"11\" height=\"4\" bgcolor=\"#FFFF00\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td width=\"183\" >");
      out.print( pageData.getWord("Break/Meal period"));
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td width=\"11\" bgcolor=\"#FF0000\" >&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td width=\"150\" >");
      out.print( pageData.getWord("Adherence value"));
      out.write(':');
      out.print( pageData.getWord("no"));
      out.write(" </td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  <tr >\r\n");
      out.write("\t\t\t\t<td height=\"4\" bgcolor=\"#3399CC\" >&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td >");
      out.print( pageData.getWord("Gap between work and break"));
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td >&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td >&nbsp;</td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t</table> </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr align=\"center\">\r\n");
      out.write("    <td height=\"4\" rowspan=\"2\" bgcolor=\"#FFFFFF\">&nbsp;</td>\r\n");
      out.write("  \t<td ><div align=\"justify\"><b> ");
      out.print( pageData.getWord("Global adherence"));
      out.write(" :\r\n");
      out.write("          <input  style=\"background-color:#EEEEEE\" id=\"adhval\" name=\"adherence\" value=\"100%\" size=\"8\"  maxlength=\"8\" type=\"text\" border=\"0\" readonly=\"true\">\r\n");
      out.write("        <script language=\"javascript\" type=\"text/javascript\"> document.write(\"\");</script>\r\n");
      out.write("    </b></div></td>\r\n");
      out.write("\t<td rowspan=\"2\">&nbsp;</td>\r\n");
      out.write("\t<td rowspan=\"2\" align=\"left\"><table><tr><td><img id=\"zin\" src=\"../img/stock_zoom_in.png\" alt=\"Zoom in\" width=\"24\" height=\"24\" onClick=\"zoomIn()\" onMouseOver=\"border=1; width=23; height=23; \" onMouseOut=\"border=0; width=24; height=24;\" >&nbsp;&nbsp;&nbsp;</td> <td> <img src=\"../img/stock_zoom_out.png\"  alt=\"Zoom out\" width=\"24\" height=\"24\" onClick=\"zoomOut()\" onMouseOver=\"border=1; width=23; height=23;\"   onMouseOut=\"border=0; width=24; height=24; \">&nbsp;&nbsp;&nbsp;</td><td><img src=\"../img/stock_zoom_fit.png\" width=\"24\" height=\"24\" alt=\"Remove zoom\" onClick=\"zoomFit()\" onMouseOver=\"border=1; width=23; height=23;\" onMouseOut=\"border=0; width=24; height=24; \"></td></tr></table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr align=\"center\">\r\n");
      out.write("    <td align=\"left\"><b>");
      out.print( pageData.getWord("Agent group"));
      out.write(":\r\n");
      out.write("\t</b><div align=\"left\"><select name=\"adhGroup\" id=\"adhGroup\" onChange=\"onGroupChange()\" size=\"1\"></select>\r\n");
      out.write("&nbsp;</div></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<!--<DIV ID=\"divRta\"></DIV>-->\r\n");
      out.write("\t\t<DIV id=\"divRtaHead\"  style=\"position:absolute; visibility:visible; top:auto\" > </DIV>\r\n");
      out.write("\r\n");
      out.write("\t\t<DIV ID=\"divRtaTab\" class=\"rtaTableClass\"></DIV>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\tif(firstLoad)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//alert(\"Loading real time adherence, Please wait...\");\t\r\n");
      out.write("\t\trefreshRtaView();\r\n");
      out.write("\t\tappletObj.updateRTAViewInfo(starttime, endtime,\"1\",appletObj.getAdhereceSelectedGroup());\t\r\n");
      out.write("\t\tautoReFreshRta = setInterval('autoRefresh()', 60000); //alert(\"Loading real time adherence, Please wait...\");\r\n");
      out.write("\t\tautoRefreshOn = true;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\telse if( (appletObj.isAdherenceStarted()== \"true\") && (appletObj.getShowAdhValue() == \"true\") )\r\n");
      out.write("\t{\r\n");
      out.write("\t\tautoReFreshRta = setInterval('autoRefresh()', 60000);\r\n");
      out.write("\t\tautoRefreshOn = true;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\tsetInterval('updateHeaderBarPosition()',100);\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"ie5menu\" class=\"skin0\" style=\"visibility:hidden \" onMouseover=\"highlightie5(event)\" onMouseout=\"lowlightie5(event)\"   display:none> <!-- onClick=\"jumptoie5(event)\"-->\r\n");
      out.write("   <div id=\"menu1\"  class=\"menuitems\"  onClick=\"showmenuitems(1)\"  style=\"visibility:hidden\">");
      out.print( pageData.getWord("View agent schedule"));
      out.write("\r\n");
      out.write("\t\t<div id=\"sousmenu1\" class=\"sousmenu\" style=\"visibility:hidden\">\r\n");
      out.write("\t\t   <div id=\"sousmenu11\" height=\"12\"><a href=\"#\" class=\"smenu\">");
      out.print( pageData.getWord("Work"));
      out.write("</a></div>\r\n");
      out.write("\t\t   <div id=\"sousmenu12\" height=\"12\"><a href=\"#\" class=\"smenu\">");
      out.print( pageData.getWord("Break/Meal"));
      out.write("</a></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("\t<div id=\"menu2\" class=\"menuitems\"  onClick=\"showmenuitems(2)\"  target=\"newwin\" style=\"visibility:hidden\">");
      out.print( pageData.getWord("View adherence details"));
      out.write("\r\n");
      out.write("\t\t<div id=\"sousmenu2\" class=\"sousmenu\" style=\"visibility:hidden\" >\r\n");
      out.write("\t\t <!-- <div id=\"sousmenu21\" height=\"12\"><a href=\"#\" class=\"smenu\">details1</a></div>\r\n");
      out.write("\t\t  <div id=\"sousmenu22\" height=\"12\"><a href=\"#\" class=\"smenu\">details2:</a></div>\r\n");
      out.write("\t\t  <div id=\"sousmenu23\" height=\"12\"><a href=\"#\" class=\"smenu\">adherence:</a></div>-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--<hr>-->\r\n");
      out.write("\t<div id=\"menu3\" class=\"menuitems\" onClick=\"showmenuitems(3)\" style=\"visibility:hidden\"> ");
      out.print( pageData.getWord("Agent personal info"));
      out.write("\r\n");
      out.write("\t\t<div id=\"sousmenu3\" class=\"sousmenu\" style=\"visibility:hidden\" >\r\n");
      out.write("\t\t  <div id=\"sousmenu31\" height=\"12\"><a class=\"smenu\">");
      out.print( pageData.getWord("Agent name"));
      out.write(":</a></div>\r\n");
      out.write("\t\t  <div id=\"sousmenu32\" height=\"12\"><a class=\"smenu\">");
      out.print( pageData.getWord("IP Address"));
      out.write(":</a></div>\r\n");
      out.write("\t\t  <div id=\"sousmenu33\" height=\"12\"><a class=\"smenu\">");
      out.print( pageData.getWord("Host name"));
      out.write(":</a></div>\r\n");
      out.write("\t\t  <div id=\"sousmenu34\" height=\"12\"><a class=\"smenu\">");
      out.print( pageData.getWord("Group name"));
      out.write(": </a></div>\r\n");
      out.write("\t\t  <div id=\"sousmenu35\" height=\"12\"><a class=\"smenu\">");
      out.print( pageData.getWord("Team Name"));
      out.write(":</a></div>\r\n");
      out.write("\t\t  <div id=\"sousmenu36\" height=\"12\"><a class=\"smenu\">");
      out.print( pageData.getWord("First login"));
      out.write(":</a></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript1.2\">\r\n");
      out.write("\r\n");
      out.write("//set this variable to 1 if you wish the URLs of the highlighted menu to be displayed in the status bar\r\n");
      out.write("var new_left_click;   //  indicates whether the user made a new left-click\r\n");
      out.write("var display_url=0;\r\n");
      out.write("var conf = -1; //\r\n");
      out.write("var begin = 0; //\r\n");
      out.write("var nb_elem = 3;\r\n");
      out.write("var nb_souscat = new Array(nb_elem);//Nb_souscat contient le nombre de sous categorie pour chaque categorie\r\n");
      out.write("\r\n");
      out.write("nb_souscat[0] = 2;//Nombre de sous categorie 1\r\n");
      out.write("nb_souscat[1] = 0;//Nombre de sous categorie 2\r\n");
      out.write("nb_souscat[2] = 6;//Nombre de sous categorie 3\r\n");
      out.write("//nb_souscat[3] = 3;//Nombre de sous categorie 4\r\n");
      out.write("\r\n");
      out.write("var ie5=document.all&&document.getElementById\r\n");
      out.write("var ns6=document.getElementById&&!document.all\r\n");
      out.write("\r\n");
      out.write("if (ie5||ns6)\r\n");
      out.write(" var menuobj=document.getElementById(\"ie5menu\")\r\n");
      out.write("\r\n");
      out.write("function showmenuie5(e){\r\n");
      out.write("     //cols*100\r\n");
      out.write("    // alert(document.body.scrollLeft + event.clientX)\r\n");
      out.write("    if((document.body.scrollTop+event.clientY > 110) && (document.body.scrollLeft + event.clientX) >10){\r\n");
      out.write("\t\t//Find out how close the mouse is to the corner of the window\r\n");
      out.write("\t\tvar rightedge=ie5? document.body.clientWidth-event.clientX : window.innerWidth-e.clientX\r\n");
      out.write("\t\tvar bottomedge=ie5? document.body.clientHeight-event.clientY : window.innerHeight-e.clientY\r\n");
      out.write("\r\n");
      out.write("\t\t//if the horizontal distance isn't enough to accomodate the width of the context menu\r\n");
      out.write("\t\tif (rightedge<menuobj.offsetWidth)\r\n");
      out.write("\t\t\t//move the horizontal position of the menu to the left by it's width\r\n");
      out.write("\t\t\tmenuobj.style.left=ie5? document.body.scrollLeft+event.clientX-menuobj.offsetWidth : window.pageXOffset+e.clientX-menuobj.offsetWidth\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\t//position the horizontal position of the menu where the mouse was clicked\r\n");
      out.write("\t\t\tmenuobj.style.left=ie5? document.body.scrollLeft+event.clientX : window.pageXOffset+e.clientX\r\n");
      out.write("\r\n");
      out.write("\t\t//same concept with the vertical position\r\n");
      out.write("\t\tif (bottomedge<menuobj.offsetHeight)\r\n");
      out.write("\t\t\tmenuobj.style.top=ie5? document.body.scrollTop+event.clientY-menuobj.offsetHeight : window.pageYOffset+e.clientY-menuobj.offsetHeight\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\tmenuobj.style.top=ie5? document.body.scrollTop+event.clientY : window.pageYOffset+e.clientY\r\n");
      out.write("\r\n");
      out.write("\t\tmenuobj.style.visibility=\"visible\"\r\n");
      out.write("\t\tInit();\r\n");
      out.write("\t\tnew_left_click = true;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn false\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function hidemenuie5(e){\r\n");
      out.write("\t//A left click event has occured\r\n");
      out.write("\tvar diffX = document.body.scrollLeft + event.clientX -  parseInt(menuobj.style.left.substring(0,menuobj.style.left.length-2));\r\n");
      out.write("\tvar diffY = document.body.scrollTop + event.clientY -  parseInt(menuobj.style.top.substring(0,menuobj.style.top.length-2));\r\n");
      out.write("\tif((diffX < 0) || (diffX > 145) ||(diffY < 0) || (diffY > 50)){\r\n");
      out.write("\t\tmenuobj.style.visibility=\"hidden\";\r\n");
      out.write("\t\tvar z=1;\r\n");
      out.write("\t\tfor(z=1;z<=nb_elem;z++){\r\n");
      out.write("\t\t\tdocument.getElementById(\"menu\"+z+\"\").style.visibility = 'hidden';\r\n");
      out.write("\t\t\tdocument.getElementById(\"sousmenu\"+z+\"\").style.visibility = 'hidden';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t \t//alert('...left..'+menuobj.style.left+'..begin..'+menuobj.style.top+'..event.x..'+event.clientX+'..event.y..'+event.clientY+'..scrollLeft..'+document.body.scrollLeft+'..scrollTop..'+document.body.scrollTop)\r\n");
      out.write("\t}\r\n");
      out.write("\t//menuobj.style.visibility=\"hidden\"\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function highlightie5(e){\r\n");
      out.write("\tvar firingobj=ie5? event.srcElement : e.target\r\n");
      out.write("\tif(firingobj != null){\r\n");
      out.write("\t\tif (firingobj.className==\"menuitems\" || ns6&&firingobj.parentNode.className==\"menuitems\"){\r\n");
      out.write("\t\t\tif (ns6&&firingobj.parentNode.className==\"menuitems\") firingobj=firingobj.parentNode //up one node\r\n");
      out.write("\t\t\tfiringobj.style.backgroundColor=\"goldenrod\"//\"highlight\"\r\n");
      out.write("\t\t\tfiringobj.style.color=\"white\"\r\n");
      out.write("\t\t\tif (display_url==1)\r\n");
      out.write("\t\t\t\twindow.status=event.srcElement.url\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function lowlightie5(e){\r\n");
      out.write("\tvar firingobj=ie5? event.srcElement : e.target\r\n");
      out.write("\tif (firingobj != null){\r\n");
      out.write("\t\tif (firingobj.className==\"menuitems\"||ns6&&firingobj.parentNode.className==\"menuitems\"){\r\n");
      out.write("\t\tif (ns6&&firingobj.parentNode.className==\"menuitems\") firingobj=firingobj.parentNode //up one node\r\n");
      out.write("\t\t\tfiringobj.style.backgroundColor=\"\"\r\n");
      out.write("\t\t\tfiringobj.style.color=\"black\"\r\n");
      out.write("\t\t\twindow.status=''\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function jumptoie5(e){\r\n");
      out.write("\tvar firingobj=ie5? event.srcElement : e.target\r\n");
      out.write("\tif (firingobj.className==\"menuitems\"||ns6&&firingobj.parentNode.className==\"menuitems\"){\r\n");
      out.write("\tif (ns6&&firingobj.parentNode.className==\"menuitems\") firingobj=firingobj.parentNode\r\n");
      out.write("\tif (firingobj.getAttribute(\"target\"))\r\n");
      out.write("\t\twindow.open(firingobj.getAttribute(\"url\"),firingobj.getAttribute(\"target\"))\r\n");
      out.write("\telse\r\n");
      out.write("\t\twindow.location=firingobj.getAttribute(\"url\")\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function Init()\r\n");
      out.write("{\r\n");
      out.write("\tmenuobj.style.height = 55;\r\n");
      out.write("\t////////////////////Mes ajouts/////////////////\r\n");
      out.write("    begin= parseInt(menuobj.style.top.substring(0,menuobj.style.top.length-2));\r\n");
      out.write("\tvar hauteur = begin;\r\n");
      out.write("\tif(conf < 4)\r\n");
      out.write("    \tdocument.getElementById(\"sousmenu\"+(conf==-1?1:conf)+\"\").style.visibility = 'hidden';\r\n");
      out.write("    for(i=1;i<=nb_elem;i++){\r\n");
      out.write("\t// alert('begin '+document.getElementById(\"menu\"+i+\"\").style.top )\r\n");
      out.write("        document.getElementById(\"menu\"+i+\"\").style.top = hauteur;\r\n");
      out.write("        hauteur = parseInt(hauteur) + 17;\r\n");
      out.write("\t\tdocument.getElementById(\"menu\"+i+\"\").style.height = 17;\r\n");
      out.write("\t\tdocument.getElementById(\"menu\"+i+\"\").style.visibility = 'visible';\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showmenuitems(z){\r\n");
      out.write("\tif((conf==z)  && (new_left_click==false) ){\r\n");
      out.write("        document.getElementById(\"sousmenu\"+z+\"\").style.visibility = 'hidden';\r\n");
      out.write("        Init();\r\n");
      out.write("        conf=conf+3;\r\n");
      out.write("    }else{\r\n");
      out.write("        conf=z;\r\n");
      out.write("        new_left_click = false;\r\n");
      out.write("        //Calcul de la hauteur dont doit se baisser le menu\r\n");
      out.write("        haut=0;\r\n");
      out.write("        var haut = 12*nb_souscat[z-1]+z*18+begin;\r\n");
      out.write("\r\n");
      out.write("        //On retracte tous les éléments\r\n");
      out.write("        for(i=1;i<=nb_elem;i++){\r\n");
      out.write("            document.getElementById(\"sousmenu\"+i+\"\").style.visibility = 'hidden';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        //on les remet tous à leur place\r\n");
      out.write("        Init();\r\n");
      out.write("\r\n");
      out.write("        //on cale le sous menu sous la categorie\r\n");
      out.write("        document.getElementById(\"sousmenu\"+z+\"\").style.top = z*18;//16;\r\n");
      out.write("        dec = haut;\r\n");
      out.write("\t\t//menuobj.style.height = parseInt(menuobj.style.height.substring(0,menuobj.style.height.length-2))+12*nb_souscat[z-1];\r\n");
      out.write("\r\n");
      out.write("\t\t/**********/\r\n");
      out.write("\t\tvar arrayScheduleDetails=\"\";\r\n");
      out.write(" \t\tvar jsScheduleData = \"\";\r\n");
      out.write("\t\tvar schedLen=0;\r\n");
      out.write("\t\tvar name = hoverHelpData[rowSelected][0];\r\n");
      out.write("\t\tvar ind = name.indexOf('[');\r\n");
      out.write("\t\tvar loginID = name.substring(0,ind);\r\n");
      out.write("\t\tvar findItem = false;\r\n");
      out.write("\t\tif(z ==1) {\r\n");
      out.write("\t\t\t\t//Look for tha agent schedule info..\r\n");
      out.write("\t\t\t\tif(thisDayScheduleInfo.length ==0)\r\n");
      out.write("\t\t\t\t\twindow.top.main.rtop.setAgentScheduleData();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t \t\tfor(nbElt = 0; nbElt < thisDayScheduleInfo.length; nbElt++)\r\n");
      out.write("\t\t\t\t  {\r\n");
      out.write("\t\t\t\t  //alert(loginID+'..'+thisDayScheduleInfo[nbElt])\r\n");
      out.write("\t\t\t\t\tjsScheduleData=thisDayScheduleInfo[nbElt] + \"\";\r\n");
      out.write("\t\t\t\t\tarrayScheduleDetails = jsScheduleData.split(\"^\");\r\n");
      out.write("\t\t\t\t\tif((arrayScheduleDetails.length > 1) && (arrayScheduleDetails[0]==loginID))\r\n");
      out.write("\t\t\t\t\t   {\r\n");
      out.write("\t\t\t\t\t\t  findItem = true;\r\n");
      out.write("\t\t\t\t\t\t  break;\r\n");
      out.write("\t\t\t\t\t   }\r\n");
      out.write("\t\t\t\t }\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif(findItem == true){\r\n");
      out.write("\t\t\t\t\tschedLen = arrayScheduleDetails.length;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t//Remove all child nodes for sousmenu1\r\n");
      out.write("\t\t\tvar d2=document.getElementById(\"sousmenu\"+z+\"\");\r\n");
      out.write("\t\t\t// -- d2Len holds the fixed starting value of the number of childNodes\r\n");
      out.write("\t\t\tvar d2Len=d2.childNodes.length;\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor (i=0;i<d2Len;i++){\r\n");
      out.write("\t\t\t\t   d2.removeChild(d2.childNodes[0]);\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\r\n");
      out.write("\t\t\t//Build layers HTML code\r\n");
      out.write("\t\t\tfor(var nl=1; nl<schedLen; nl++) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t var lyr=document.createElement(\"DIV\");\r\n");
      out.write("\t\t\t\t lyr.style.backgroundColor='#C3C9D4';\r\n");
      out.write("\t\t\t\t lyr.id=\"sousmenu\"+z+\"\"+nl;\r\n");
      out.write("\t\t\t\t var tHeader = '<TABLE WIDTH=\"100%\" HEIGHT=\"12\"  CELLPADDING=\"0\" CELLSPACING=\"0\"><TR><TD NOWRAP ALIGN=\"left\">'\r\n");
      out.write("\t\t\t\t var tFooter = '</TD></TR></TABLE>';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t var code=\"<a class='smenu'>\";\r\n");
      out.write("\t\t\t\t tmpVal = '<font color=#000000>'+ arrayScheduleDetails[nl]+'</font>';\r\n");
      out.write("\t\t\t\t code = code + tmpVal + '</a>';\r\n");
      out.write("\t\t\t\t code = tHeader+code+tFooter;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t if (ie5) {\r\n");
      out.write("\t\t\t\t\t  lyr.innerHTML=code;\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"sousmenu\"+z+\"\").appendChild(lyr);\r\n");
      out.write("\t\t\t\t//document.getElementById(\"sousmenu\"+z+\"\").replaceChild(lyr,document.getElementById(\"sousmenu\"+z+\"\"+nl));\r\n");
      out.write("\r\n");
      out.write("\t\t\t}//fin du for\r\n");
      out.write("    \t }//fin du if(z==1)\r\n");
      out.write("\r\n");
      out.write("\t    if(z==2){\r\n");
      out.write("\t\t\tvar jsadherenceData = adherenceDetails[rowSelected] + \"\";\r\n");
      out.write("\t\t\tarrayAdherenceDetails = jsadherenceData.split(\"*\");\r\n");
      out.write("\t\t\tschedLen = arrayAdherenceDetails.length;\r\n");
      out.write("\t\t\t//Remove all child nodes for sousmenu2\r\n");
      out.write("\t\t\tvar d2=document.getElementById(\"sousmenu\"+z+\"\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t// -- d2Len holds the fixed starting value of the number of childNodes\r\n");
      out.write("\t\t\tvar d2Len=d2.childNodes.length;\r\n");
      out.write("\t\t\tfor (i=0;i<d2Len;i++){\r\n");
      out.write("\t\t\t\t   d2.removeChild(d2.childNodes[0]);\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\r\n");
      out.write("\t\t\t//Build layers HTML code\r\n");
      out.write("\r\n");
      out.write("\t\t\tschedLen = 1; //just show the first element\r\n");
      out.write("\t\t\tfor(var nl=0; nl<schedLen; nl++) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t var lyr=document.createElement(\"DIV\");\r\n");
      out.write("\t\t\t\t lyr.style.backgroundColor='#C3C9D4';\r\n");
      out.write("\t\t\t\t lyr.id=\"sousmenu\"+z+\"\"+nl;\r\n");
      out.write("\t\t\t\t var tHeader = '<TABLE WIDTH=\"100%\" HEIGHT=\"12\"  CELLPADDING=\"0\" CELLSPACING=\"0\"><TR><TD NOWRAP ALIGN=\"left\">'\r\n");
      out.write("\t\t\t\t var tFooter = '</TD></TR></TABLE>';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t var code=\"<a class='smenu'>\";\r\n");
      out.write("\t\t\t\t if (nl == 0)\r\n");
      out.write("\t\t\t\t \ttmpVal = '<font color=#900000> Adherence  ['+ arrayAdherenceDetails[nl]+'%]</font>';\r\n");
      out.write("\t\t\t\t else\r\n");
      out.write("\t\t\t\t \ttmpVal = '<font color=#000000>'+ arrayAdherenceDetails[nl]+'</font>';\r\n");
      out.write("\t\t\t\t code = code + tmpVal + '</a>';\r\n");
      out.write("\t\t\t\t code = tHeader+code+tFooter;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t if (ie5) {\r\n");
      out.write("\t\t\t\t\t  lyr.innerHTML=code;\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"sousmenu\"+z+\"\").appendChild(lyr);\r\n");
      out.write("\t\t\t\t//document.getElementById(\"sousmenu\"+z+\"\").replaceChild(lyr,document.getElementById(\"sousmenu\"+z+\"\"+nl));\r\n");
      out.write("\t\t\t}//fin du for\r\n");
      out.write("\r\n");
      out.write("\t\t} //fin if(z==2)\r\n");
      out.write("\r\n");
      out.write("\t\tif(z == 3){\r\n");
      out.write("\t\t\tfor(var nl=1; nl<=nb_souscat[z-1]; nl++) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t var lyr=document.createElement(\"DIV\");\r\n");
      out.write("\t\t\t\t\t lyr.style.backgroundColor='#C3C9D4';\r\n");
      out.write("\t\t\t\t\t lyr.id=\"sousmenu\"+z+\"\"+nl;\r\n");
      out.write("\t\t\t\t\t var tHeader = '<TABLE WIDTH=\"100%\" HEIGHT=\"12\"  CELLPADDING=\"0\" CELLSPACING=\"0\"><TR><TD NOWRAP ALIGN=\"left\">'\r\n");
      out.write("\t\t\t\t\t var tFooter = '</TD></TR></TABLE>'\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t var code=\"<a class='smenu'>\";\r\n");
      out.write("\t\t\t\t //if(z==3){\r\n");
      out.write("\t\t\t\t\t var jsPersonalData = personalData[rowSelected] + \"\";\r\n");
      out.write("\t\t\t\t\t var ipAddr = 'unknown';\r\n");
      out.write("\t\t\t\t\t var host \t= 'unknown';\r\n");
      out.write("\t\t\t\t\t var m_grp  = 'unknown';\r\n");
      out.write("\t\t\t\t\t var m_team = 'unknown';\r\n");
      out.write("\t\t\t\t\t var first_login = 'unknown';\r\n");
      out.write("\t\t\t\t\t if(jsPersonalData.length > 1) {\r\n");
      out.write("\t\t\t\t\t\t arrayPersoDetails = jsPersonalData.split(\"*\");\r\n");
      out.write("\t\t\t\t\t\t for(m=0; m < arrayPersoDetails.length; m++)\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tif(m==0)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tipAddr = arrayPersoDetails[m];\r\n");
      out.write("\t\t\t\t\t\t\t\telse if(m==1)\r\n");
      out.write("\t\t\t\t\t\t\t\t\thost =  arrayPersoDetails[m];\r\n");
      out.write("\t\t\t\t\t\t\t\telse if(m==2)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tm_grp =  arrayPersoDetails[m];\r\n");
      out.write("\t\t\t\t\t\t\t\telse if(m==3)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tm_team =  arrayPersoDetails[m];\r\n");
      out.write("\t\t\t\t\t\t\t\telse if(m==4){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  first_login =  arrayPersoDetails[m];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  var loginTime = parseInt(first_login,10);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  hhLog  = String(parseInt(loginTime/3600));\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  minLog = String(parseInt((loginTime % 3600)/60));\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  minLog = (minLog.length == 1 ? '0'+ minLog : minLog);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  first_login = hhLog+':'+minLog;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t} //fin for\r\n");
      out.write("\t\t\t\t\t  }  //fin if\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif(nl==1)\r\n");
      out.write("\t\t\t\t\t\ttmpVal = '<font color=#800000>'+ hoverHelpData[rowSelected][0]+'</font>';\r\n");
      out.write("\t\t\t\t\telse if(nl==2)\r\n");
      out.write("\t\t\t\t\t\ttmpVal = 'IP :     '+'<font color=#330033>'+ipAddr+'</font>';\r\n");
      out.write("\t\t\t\t\telse if(nl==3)\r\n");
      out.write("\t\t\t\t\t\ttmpVal = 'Host :   '+'<font color=#330033>'+host+'</font>';\r\n");
      out.write("\t\t\t\t\telse if(nl==4)\r\n");
      out.write("\t\t\t\t\t\ttmpVal = 'Group : '+'<font color=#330033>'+m_grp+'</font>';\r\n");
      out.write("\t\t\t\t\telse if(nl==5)\r\n");
      out.write("\t\t\t\t\t\ttmpVal = 'Team :   '+'<font color=#330033>'+m_team+'</font>';\r\n");
      out.write("\t\t\t\t\telse if(nl==6)\r\n");
      out.write("\t\t\t\t\t\ttmpVal = 'Login : '+'<font color=#330033>'+first_login+'</font>';\r\n");
      out.write("\t\t\t\t// } //fin if(z == 3)\r\n");
      out.write("\t\t\t\t code = code + tmpVal + '</a>';\r\n");
      out.write("\t\t\t\t code = tHeader+code+tFooter;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t if (ie5) {\r\n");
      out.write("\t\t\t\t\t  lyr.innerHTML=code;\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t//document.getElementById(\"sousmenu\"+z+\"\").appendChild(lyr);\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"sousmenu\"+z+\"\").replaceChild(lyr,document.getElementById(\"sousmenu\"+z+\"\"+nl));\r\n");
      out.write("\r\n");
      out.write("\t\t\t}//fin du for\r\n");
      out.write("\t\t}//fin(if z==3)\r\n");
      out.write("\r\n");
      out.write("        //On peut alors baisser tous les autre menus\r\n");
      out.write("        for(i=z+1;i<=nb_elem;i++){\r\n");
      out.write("           document.getElementById(\"menu\"+i+\"\").style.top = dec;\r\n");
      out.write("           dec=dec+18;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        //Enfin, on rend le menu visible\r\n");
      out.write("\t\tif(z==1)\r\n");
      out.write("\t\t\tdocument.getElementById(\"sousmenu\"+z+\"\").style.height = 12*schedLen;\r\n");
      out.write("\t\telse if(z==3)\r\n");
      out.write("\t\t\tdocument.getElementById(\"sousmenu\"+z+\"\").style.height = 12*nb_souscat[z-1];\r\n");
      out.write("\r\n");
      out.write("        document.getElementById(\"sousmenu\"+z+\"\").style.visibility = 'visible';\r\n");
      out.write("        document.getElementById(\"sousmenu\"+z+\"\").style.left = -1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("if (ie5||ns6){\r\n");
      out.write("\tmenuobj.style.visibility = 'hidden';\r\n");
      out.write("\tmenuobj.style.display=''\r\n");
      out.write("\tdocument.oncontextmenu=showmenuie5\r\n");
      out.write("\tdocument.onclick=hidemenuie5\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
 pageData.closeConnection(); 
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
