package org.apache.jsp.aheevaManager.Resources_005fpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.lang.*;
import aheevaManager.ressources.*;
import aheevaManager.ressources.*;

public final class userLiveStatsPreferences_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/aheevaManager/Resources_pages/agentGroupFunctions_labels.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

response.setHeader("Pragma", "no-cache");
response.setHeader("Cache-Control", "no-cache");
response.setDateHeader("Expires", 0);

      out.write('\r');
      out.write('\n');

	beanManagerData pageData = new beanManagerData();
	if( session.getAttribute("USER_LANGUAGE") != null )
		pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));

	String currentUserDbid = (String)session.getAttribute("CURRENT_USER_DBID");
	
	String tenantDbid = request.getParameter("tenant_dbid");
	
	String userPreferencesQuery = "SELECT * FROM cfg_user_live_stats_preferences WHERE USER_DBID='"+currentUserDbid+"'";
	

	pageData.openConnection();
	pageData.executeFromString(userPreferencesQuery);
	Vector <HashMap<String,String>> userPreferences = pageData.CreateVectorFromBean();

	
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Start Tab pane -->\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"tab_luna.css\" />\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style_2.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\" href=\"slider/css/luna.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t200px;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control .tab-page .dynamic-tab-pane-control .tab-page {\r\n");
      out.write("\theight:\t\t100px;\r\n");
      out.write("}\r\n");
      out.write("html, body {\r\n");
      out.write("\t/*background:\tThreeDFace;*/\r\n");
      out.write("}\r\n");
      out.write("form {\r\n");
      out.write("\tmargin:\t\t0;\r\n");
      out.write("\tpadding:\t0;\r\n");
      out.write("}\r\n");
      out.write("/* over ride styles from webfxlayout */\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:\t\t10px;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("\theight:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 {\r\n");
      out.write("\ttext-align:\tcenter;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control h2 a {\r\n");
      out.write("\tdisplay:\tinline;\r\n");
      out.write("\twidth:\t\tauto;\r\n");
      out.write("}\r\n");
      out.write(".dynamic-tab-pane-control a:hover {\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write('\r');
      out.write('\n');

beanManagerData pageGrpFData = new beanManagerData();
pageGrpFData.openConnection();
if( session.getAttribute("USER_LANGUAGE") != null )
	pageGrpFData.setDefaultLanguage( (String)session.getAttribute("USER_LANGUAGE") );


      out.write("\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/javascript\">\r\n");
      out.write("var GrpF= new Array();\r\n");
      out.write("GrpF[0]=\"");
      out.print(pageGrpFData.getWord("Save") );
      out.write("\";\r\n");
      out.write("GrpF[1]=\"");
      out.print(pageGrpFData.getWord("AGERR Length") );
      out.write("\";\r\n");
      out.write("GrpF[2]=\"");
      out.print(pageGrpFData.getWord("AGERR Char") );
      out.write("\";\r\n");
      out.write("GrpF[3]=\"");
      out.print(pageGrpFData.getWord("You must enter a GROUP NAME") );
      out.write("\";\r\n");
      out.write("GrpF[4]=\"");
      out.print(pageGrpFData.getWord("Invalid use of character") );
      out.write("\";\r\n");
      out.write("GrpF[5]=\"");
      out.print(pageGrpFData.getWord("Group name") );
      out.write("\";\r\n");
      out.write("GrpF[6]=\"");
      out.print(pageGrpFData.getWord("You must enter a GROUP QUEUE") );
      out.write("\";\r\n");
      out.write("GrpF[7]=\"");
      out.print(pageGrpFData.getWord("Queue name") );
      out.write("\";\r\n");
      out.write("GrpF[8]=\"");
      out.print(pageGrpFData.getWord("Your description should be filled. Use valid characters.") );
      out.write("\";\r\n");
      out.write("GrpF[9]=\"");
      out.print(pageGrpFData.getWord("The maximum wrap up time must be in seconds") );
      out.write("\";\r\n");
      out.write("GrpF[10]=\"");
      out.print(pageGrpFData.getWord("The maximum wrap up time must be less than 99999 seconds") );
      out.write("\";\r\n");
      out.write("GrpF[11]=\"");
      out.print(pageGrpFData.getWord("The maximum wrap up time must be at least 1 second") );
      out.write("\";\r\n");
      out.write("GrpF[12]=\"");
      out.print(pageGrpFData.getWord("The maximum wrap up time that does not affect productivity must be in seconds") );
      out.write("\";\r\n");
      out.write("GrpF[13]=\"");
      out.print(pageGrpFData.getWord("This QUEUE is already assigned. You must enter a NEW QUEUE") );
      out.write("\";\r\n");
      out.write("GrpF[14]=\"");
      out.print(pageGrpFData.getWord("You must enter the encryption server IP or uncheck the encryption box") );
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("GrpF[15]=\"");
      out.print(pageGrpFData.getWord("You must enter the encryption method or uncheck the encryption box") );
      out.write("\";\r\n");
      out.write("GrpF[16]=\"");
      out.print(pageGrpFData.getWord("Agent group already exists") );
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("GrpF[17]=\"");
      out.print(pageGrpFData.getWord("Minimum recording time must be smaller than maximum recording time") );
      out.write("\";\r\n");
      out.write("GrpF[18]=\"");
      out.print(pageGrpFData.getWord("Are you sure you wish to delete this group?") );
      out.write("\";\r\n");
      out.write("GrpF[19]=\"");
      out.print(pageGrpFData.getWord("A running campaign uses this group! You can't delete it") );
      out.write("\";\r\n");
      out.write("GrpF[20]=\"");
      out.print(pageGrpFData.getWord("Delete") );
      out.write("\";\r\n");
      out.write("GrpF[21]=\"");
      out.print(pageGrpFData.getWord("There is no active non-global not-ready-reason in the system.") );
      out.write("\";\r\n");
      out.write("GrpF[22]=\"");
      out.print(pageGrpFData.getWord("You cannot select a reason several times") );
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 pageGrpFData.closeConnection(); 
      out.write("\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../lang_browser.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jsUtil.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Browser.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"tabpane.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"agentGroupFunctions.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function setDefault()\r\n");
      out.write("{\r\n");
      out.write("\tvar myform = document.userPreferencesForm;\r\n");
      out.write("\t\r\n");
      out.write("\talert(\"");
      out.print(pageData.getWord("Live statistics preferences will be set to default values."));
      out.write("\");\r\n");
      out.write("\tmyform.refresh_rate.value=\"7\";\r\n");
      out.write("\tmyform.have_agent_stats.checked=true;\r\n");
      out.write("\tmyform.have_agent_group_stats.checked=true;\r\n");
      out.write("\tmyform.have_queue_stats.checked=true;\r\n");
      out.write("\tmyform.have_campaign_stats.checked=true;\r\n");
      out.write("\tmyform.have_calling_list_stats.checked=true;\r\n");
      out.write("\tmyform.have_performance_stats.checked=true;\r\n");
      out.write("\tmyform.have_team_stats.checked=true;\r\n");
      out.write("\tmyform.have_line_management_stats.checked=true;\r\n");
      out.write("\tmyform.have_adherence_stats.checked=true;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("var rate;\r\n");
      out.write("function validateBeforeSubmit()\r\n");
      out.write("{\r\n");
      out.write("\tvar myform = document.userPreferencesForm;\r\n");
      out.write("\t\r\n");
      out.write("\trate = parseInt(myform.refresh_rate.value)*1000;\r\n");
      out.write("\t\r\n");
      out.write("\tif(IsNumeric(myform.refresh_rate.value)==false)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print(pageData.getWord("Please, select a refresh rate between 7 and 3600 seconds."));
      out.write("\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\telse \r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(rate < 7000 || rate > 3600000 )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"");
      out.print(pageData.getWord("Please, select a refresh rate between 7 and 3600 seconds."));
      out.write("\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(myform.have_agent_stats.checked==false &&\r\n");
      out.write("\tmyform.have_agent_group_stats.checked==false &&\r\n");
      out.write("\tmyform.have_queue_stats.checked==false &&\r\n");
      out.write("\tmyform.have_campaign_stats.checked==false &&\r\n");
      out.write("\tmyform.have_calling_list_stats.checked==false &&\r\n");
      out.write("\tmyform.have_performance_stats.checked==false &&\r\n");
      out.write("\tmyform.have_team_stats.checked==false &&\r\n");
      out.write("\tmyform.have_line_management_stats.checked==false &&\r\n");
      out.write("\tmyform.have_adherence_stats.checked==false)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print(pageData.getWord("Select at least one type of live statistic to visualize"));
      out.write("\");\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tsendUpdate();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sendUpdate()\r\n");
      out.write("{\r\n");
      out.write("\tvar myform = document.userPreferencesForm;\r\n");
      out.write("\tvar tosend;\r\n");
      out.write("\ttosend=");
      out.print(currentUserDbid);
      out.write("+\"^\"+rate;\r\n");
      out.write("\t\r\n");
      out.write("\tif(myform.have_agent_stats.checked)\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^1\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^0\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(myform.have_agent_group_stats.checked)\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^1\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^0\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(myform.have_queue_stats.checked)\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^1\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^0\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(myform.have_calling_list_stats.checked)\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^1\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^0\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(myform.have_campaign_stats.checked)\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^1\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^0\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tif(myform.have_performance_stats.checked)\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^1\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^0\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(myform.have_team_stats.checked)\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^1\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^0\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tif(myform.have_line_management_stats.checked)\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^1\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^0\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(myform.have_adherence_stats.checked)\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^1\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttosend=tosend+\"^0\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tappletObj.modifyUserLiveStatsPreferences(tosend);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"tab_luna.css\">\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style_2.css\">\r\n");
      out.write("<link id=\"luna-tab-style-sheet\" type=\"text/css\" rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("<link href=\"livestats.css\" \trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<meta http-equiv=\"Content-Language\" content=\"en-us\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"use_pref_body\">\r\n");
      out.write("\t<div class=\"tab-pane\" id=\"tabPane1\">\r\n");
      out.write("\t\t<form name=\"userPreferencesForm\" id=\"userPreferencesForm\">\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\ttp1 = new WebFXTabPane( document.getElementById( \"tabPane1\" ) );\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<div class=\"tab-page\" id=\"tabGeneral\">\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t<legend>");
      out.print(pageData.getWord("USER LIVE STATISTICS MANAGEMENT"));
      out.write("</legend>\r\n");
      out.write("\t\t\t\t  <table width=\"100%\">\r\n");
      out.write("\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t      <td colspan=\"2\"><p align=\"center\" class=\"style1\"><b>");
      out.print(pageData.getWord("Enter your live statistics view settings"));
      out.write(" </b></p><br/>\r\n");
      out.write("\t\t\t\t  \t</td>\r\n");
      out.write("\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t    <tr> \r\n");
      out.write("\t\t\t\t      <td width=\"50%\">\r\n");
      out.write("\t\t\t\t\t\t\t<div align=\"right\" class=\"style1\">");
      out.print(pageData.getWord("Refresh rate"));
      out.write(" </div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t      \t<td width=\"50%\"> \r\n");
      out.write("\t\t\t\t        \t<div align=\"left\"><span class=\"style1\"> \r\n");
      out.write("\t\t\t\t          \t\t<input name=\"refresh_rate\" type=\"text\" id=\"refresh_rate\" value=\"");
      out.print(Integer.parseInt(userPreferences.elementAt(0).get("REFRESH_RATE"))/1000);
      out.write("\" size=\"5\" maxlength=\"4\">\r\n");
      out.write("\t\t\t\t          ");
      out.print(pageData.getWord("seconds"));
      out.write("</span></div></td>\r\n");
      out.write("\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t    <tr> \r\n");
      out.write("\t\t\t\t      <td width=\"50%\">\r\n");
      out.write("\t\t\t\t<div align=\"right\" class=\"style1\">");
      out.print(pageData.getWord("Agents"));
      out.write(" </div></td>\r\n");
      out.write("\t\t\t\t      <td width=\"50%\"> \r\n");
      out.write("\t\t\t\t        <div align=\"left\"><span class=\"style1\"> \r\n");
      out.write("\t\t\t\t          <input name=\"have_agent_stats\" type=\"checkbox\" id=\"have_agent_stats\" ");
      out.print(userPreferences.elementAt(0).get("AGENT_STATS").compareTo("1")==0?"checked":"");
      out.write(" \r\n");
      out.write("\t\t\t\t\t  onClick=\"\">\r\n");
      out.write("\t\t\t\t          </span></div></td>\r\n");
      out.write("\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t    <tr> \r\n");
      out.write("\t\t\t\t      <td width=\"50%\">\r\n");
      out.write("\t\t\t\t<div align=\"right\" class=\"style1\">");
      out.print(pageData.getWord("Agent groups"));
      out.write(" </div></td>\r\n");
      out.write("\t\t\t\t      <td width=\"50%\"> \r\n");
      out.write("\t\t\t\t        <div align=\"left\"><span class=\"style1\"> \r\n");
      out.write("\t\t\t\t          <input name=\"have_agent_group_stats\" type=\"checkbox\" id=\"have_agent_group_stats\" ");
      out.print(userPreferences.elementAt(0).get("AGENT_GROUP_STATS").compareTo("1")==0?"checked":"");
      out.write(">\r\n");
      out.write("\t\t\t\t          </span></div></td>\r\n");
      out.write("\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t    <tr> \r\n");
      out.write("\t\t\t\t      <td width=\"50%\" class=\"style1\">\r\n");
      out.write("\t\t\t\t<div align=\"right\" class=\"style1\">");
      out.print(pageData.getWord("Queues"));
      out.write(" </div></td>\r\n");
      out.write("\t\t\t\t      <td width=\"50%\"> \r\n");
      out.write("\t\t\t\t        <div align=\"left\"><span class=\"style1\"> \r\n");
      out.write("\t\t\t\t          <input name=\"have_queue_stats\" type=\"checkbox\" id=\"have_queue_stats\" ");
      out.print(userPreferences.elementAt(0).get("QUEUE_STATS").compareTo("1")==0?"checked":"");
      out.write(">\r\n");
      out.write("\t\t\t\t          </span></div></td>\r\n");
      out.write("\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t    <tr> \r\n");
      out.write("\t\t\t\t      <td width=\"50%\" align=\"right\"> \r\n");
      out.write("\t\t\t\t        <div align=\"right\" class=\"style1\">");
      out.print(pageData.getWord("Campaigns"));
      out.write(" </div></td>\r\n");
      out.write("\t\t\t\t      <td width=\"50%\" align=\"left\"> \r\n");
      out.write("\t\t\t\t        <div align=\"left\"><span class=\"style1\"> \r\n");
      out.write("\t\t\t\t          <input name=\"have_campaign_stats\" type=\"checkbox\" id=\"have_campaign_stats\" ");
      out.print(userPreferences.elementAt(0).get("CAMPAIGN_STATS").compareTo("1")==0?"checked":"");
      out.write(">\r\n");
      out.write("\t\t\t\t          </span></div></td>\r\n");
      out.write("\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t    <tr> \r\n");
      out.write("\t\t\t\t      <td width=\"50%\" align=\"right\"> \r\n");
      out.write("\t\t\t\t        <div align=\"right\" class=\"style1\">");
      out.print(pageData.getWord("Calling lists"));
      out.write(" </div></td>\r\n");
      out.write("\t\t\t\t      <td width=\"50%\" align=\"left\"> \r\n");
      out.write("\t\t\t\t        <div align=\"left\"><span class=\"style1\"> \r\n");
      out.write("\t\t\t\t          <input name=\"have_calling_list_stats\" type=\"checkbox\" id=\"have_calling_list_stats\" ");
      out.print(userPreferences.elementAt(0).get("CALLING_LIST_STATS").compareTo("1")==0?"checked":"");
      out.write(">\r\n");
      out.write("\t\t\t\t          </span></div></td>\r\n");
      out.write("\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t    <tr> \r\n");
      out.write("\t\t\t\t      <td width=\"50%\" align=\"right\"> \r\n");
      out.write("\t\t\t\t        <div align=\"right\" class=\"style1\">");
      out.print(pageData.getWord("Performance"));
      out.write(" </div></td>\r\n");
      out.write("\t\t\t\t      <td width=\"50%\" align=\"left\"> \r\n");
      out.write("\t\t\t\t        <div align=\"left\"><span class=\"style1\"> \r\n");
      out.write("\t\t\t\t          <input name=\"have_performance_stats\" type=\"checkbox\" id=\"have_performance_stats\"");
      out.print(userPreferences.elementAt(0).get("PERFORMANCE_STATS").compareTo("1")==0?"checked":"");
      out.write(">\r\n");
      out.write("\t\t\t\t          </span></div></td>\r\n");
      out.write("\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t    <tr> \r\n");
      out.write("\t\t\t\t      <td width=\"50%\" align=\"right\"> \r\n");
      out.write("\t\t\t\t        <div align=\"right\" class=\"style1\">");
      out.print(pageData.getWord("Teams"));
      out.write(" </div></td>\r\n");
      out.write("\t\t\t\t      <td width=\"50%\" align=\"left\"> \r\n");
      out.write("\t\t\t\t        <div align=\"left\"><span class=\"style1\"> \r\n");
      out.write("\t\t\t\t          <input name=\"have_team_stats\" type=\"checkbox\" id=\"have_team_stats\" ");
      out.print(userPreferences.elementAt(0).get("TEAMS_STATS").compareTo("1")==0?"checked":"");
      out.write(">\r\n");
      out.write("\t\t\t\t          </span></div></td>\r\n");
      out.write("\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t    <tr> \r\n");
      out.write("\t\t\t\t      <td width=\"50%\" align=\"right\"> \r\n");
      out.write("\t\t\t\t        <div align=\"right\" class=\"style1\">");
      out.print(pageData.getWord("Adherence"));
      out.write(" </div></td>\r\n");
      out.write("\t\t\t\t      <td width=\"50%\" align=\"left\"> \r\n");
      out.write("\t\t\t\t        <div align=\"left\"><span class=\"style1\"> \r\n");
      out.write("\t\t\t\t          <input name=\"have_adherence_stats\" type=\"checkbox\" id=\"have_adherence_stats\" ");
      out.print(userPreferences.elementAt(0).get("ADHERENCE_STATS").compareTo("1")==0?"checked":"");
      out.write(">\r\n");
      out.write("\t\t\t\t          </span></div></td>\r\n");
      out.write("\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t    <tr> \r\n");
      out.write("\t\t\t\t      <td width=\"50%\" align=\"right\"> \r\n");
      out.write("\t\t\t\t        <div align=\"right\" class=\"style1\">");
      out.print(pageData.getWord("Line management"));
      out.write("</div></td>\r\n");
      out.write("\t\t\t\t      <td width=\"50%\" align=\"left\"> \r\n");
      out.write("\t\t\t\t        <div align=\"left\"><span class=\"style1\"> \r\n");
      out.write("\t\t\t\t          <input name=\"have_line_management_stats\" type=\"checkbox\" id=\"have_line_management_stats\" ");
      out.print(userPreferences.elementAt(0).get("LINE_MANAGEMENT_STATS").compareTo("1")==0?"checked":"");
      out.write(">\r\n");
      out.write("\t\t\t\t          </span></div></td>\r\n");
      out.write("\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t  </table>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t  <div align=\"center\"><br>\r\n");
      out.write("\t\t\t\t    <br>\r\n");
      out.write("\t\t\t\t    <input name=\"submit\" id=\"submit\" value=\"");
      out.print(pageData.getWord("Update"));
      out.write("\" type=\"button\" onClick=\"validateBeforeSubmit()\"> \r\n");
      out.write("\t\t\t\t    <input name=\"setToDefault\" id=\"setToDefault\" value=\"");
      out.print(pageData.getWord("Default"));
      out.write("\" type=\"button\" onClick=\"setDefault()\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t </fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
 pageData.closeConnection(); 
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
