// JavaScript Document

// --- The menu rights tables
var RIGHTS = new Array();

RIGHTS["TENANT_REPORT_CAMPAIGN"]  		= true;
RIGHTS["TENANT_REPORT_CALLING_LIST"] 	= true;

function setRights(userRole)
{
	switch(userRole)
		{
		case '0':
			RIGHTS["CONFIGURATION"] = false;
				RIGHTS["TENANT_MANAGEMENT"] = false;
				RIGHTS["USER_MANAGEMENT"] = false;
				RIGHTS["LIVE_MONITORING"] = false;
				RIGHTS["SWITCHES"] = false;
			RIGHTS["TENANT"] = false;	
				RIGHTS["TENANT_RESSOURCES"] = false;
					RIGHTS["TENANT_RESSOURCES_AGENT_GROUPS"] = false;
					RIGHTS["TENANT_RESSOURCES_AGENTS"] = false;
					RIGHTS["TENANT_RESSOURCES_CAMPAIGNS"] = false;
					RIGHTS["TENANT_RESSOURCES_CALLING_LISTS"] = false;
					RIGHTS["TENANT_RESSOURCES_FILTERS"] = false;
					RIGHTS["TENANT_RESSOURCES_TREATMENTS"] = false;
					RIGHTS["TENANT_RESSOURCES_NOT_READY_REASON"] = false;
					RIGHTS["TENANT_RESSOURCES_QUEUE"] = false;
					RIGHTS["TENANT_RESSOURCES_SKILLS"] = false;
				RIGHTS["TENANT_HISTORICAL_REPORTS"] = false;
				RIGHTS["TENANT_QUALITY_MONITORING"] = false;
				RIGHTS["TENANT_WORK_FORCE"] = false;
				RIGHTS["TENANT_MOP_MANAGEMENT"] = false;
				RIGHTS["TENANT_ROUTING_SCRIPTS"] = false;
				RIGHTS["TENANT_MESSAGE_CENTER"] = false;
				
		break;
		
		
		case '10':
			RIGHTS["CONFIGURATION"] = true;
				RIGHTS["TENANT_MANAGEMENT"] = true;
				RIGHTS["USER_MANAGEMENT"] = true;
				RIGHTS["LIVE_MONITORING"] = true;
				RIGHTS["SWITCHES"] = true;
			RIGHTS["TENANT"] = true;	
				RIGHTS["TENANT_RESSOURCES"] = true;
					RIGHTS["TENANT_RESSOURCES_AGENT_GROUPS"] = true;
					RIGHTS["TENANT_RESSOURCES_AGENTS"] = true;
					RIGHTS["TENANT_RESSOURCES_CAMPAIGNS"] = true;
					RIGHTS["TENANT_RESSOURCES_CALLING_LISTS"] = true;
					RIGHTS["TENANT_RESSOURCES_FILTERS"] = true;
					RIGHTS["TENANT_RESSOURCES_TREATMENTS"] = true;
					RIGHTS["TENANT_RESSOURCES_NOT_READY_REASON"] = true;
					RIGHTS["TENANT_RESSOURCES_QUEUE"] = true;
					RIGHTS["TENANT_RESSOURCES_SKILLS"] = true;
				RIGHTS["TENANT_HISTORICAL_REPORTS"] = true;
				RIGHTS["TENANT_QUALITY_MONITORING"] = true;
				RIGHTS["TENANT_WORK_FORCE"] = true;
				RIGHTS["TENANT_MOP_MANAGEMENT"] = true;
				RIGHTS["TENANT_ROUTING_SCRIPTS"] = true;
				RIGHTS["TENANT_MESSAGE_CENTER"] = true;
		break;
		
		case '20':
			RIGHTS["CONFIGURATION"] = false;
				RIGHTS["TENANT_MANAGEMENT"] = false;
				RIGHTS["USER_MANAGEMENT"] = false;
				RIGHTS["LIVE_MONITORING"] = false;
				RIGHTS["SWITCHES"] = false;
			RIGHTS["TENANT"] = true;	
				RIGHTS["TENANT_RESSOURCES"] = true;
					RIGHTS["TENANT_RESSOURCES_AGENT_GROUPS"] = true;
					RIGHTS["TENANT_RESSOURCES_AGENTS"] = true;
					RIGHTS["TENANT_RESSOURCES_CAMPAIGNS"] = true;
					RIGHTS["TENANT_RESSOURCES_CALLING_LISTS"] = true;
					RIGHTS["TENANT_RESSOURCES_FILTERS"] = true;
					RIGHTS["TENANT_RESSOURCES_TREATMENTS"] = true;
					RIGHTS["TENANT_RESSOURCES_NOT_READY_REASON"] = true;
					RIGHTS["TENANT_RESSOURCES_QUEUE"] = true;
					RIGHTS["TENANT_RESSOURCES_SKILLS"] = true;
				RIGHTS["TENANT_HISTORICAL_REPORTS"] = true;
				RIGHTS["TENANT_QUALITY_MONITORING"] = true;
				RIGHTS["TENANT_WORK_FORCE"] = true;
				RIGHTS["TENANT_MOP_MANAGEMENT"] = false;
				RIGHTS["TENANT_ROUTING_SCRIPTS"] = true;;
				RIGHTS["TENANT_MESSAGE_CENTER"] = true;
		break;
		
		case '30':
			RIGHTS["CONFIGURATION"] = false;
				RIGHTS["TENANT_MANAGEMENT"] = false;
				RIGHTS["USER_MANAGEMENT"] = false;
				RIGHTS["LIVE_MONITORING"] = false;
				RIGHTS["SWITCHES"] = false;
			RIGHTS["TENANT"] = true;	
				RIGHTS["TENANT_RESSOURCES"] = false;
					RIGHTS["TENANT_RESSOURCES_AGENT_GROUPS"] = false;
					RIGHTS["TENANT_RESSOURCES_AGENTS"] = false;
					RIGHTS["TENANT_RESSOURCES_CAMPAIGNS"] = false;
					RIGHTS["TENANT_RESSOURCES_CALLING_LISTS"] = false;
					RIGHTS["TENANT_RESSOURCES_FILTERS"] = false;
					RIGHTS["TENANT_RESSOURCES_TREATMENTS"] = false;
					RIGHTS["TENANT_RESSOURCES_NOT_READY_REASON"] = false;
					RIGHTS["TENANT_RESSOURCES_QUEUE"] = false;
					RIGHTS["TENANT_RESSOURCES_SKILLS"] = false;
				RIGHTS["TENANT_HISTORICAL_REPORTS"] = true;
				RIGHTS["TENANT_QUALITY_MONITORING"] = false;
				RIGHTS["TENANT_WORK_FORCE"] = false;
				RIGHTS["TENANT_MOP_MANAGEMENT"] = false;
				RIGHTS["TENANT_ROUTING_SCRIPTS"] = false;
				RIGHTS["TENANT_MESSAGE_CENTER"] = false;
		break;
		
		case '40':
			RIGHTS["CONFIGURATION"] = false;
				RIGHTS["TENANT_MANAGEMENT"] = false;
				RIGHTS["USER_MANAGEMENT"] = false;
				RIGHTS["LIVE_MONITORING"] = false;
				RIGHTS["SWITCHES"] = false;
			RIGHTS["TENANT"] = true;	
				RIGHTS["TENANT_RESSOURCES"] = false;
					RIGHTS["TENANT_RESSOURCES_AGENT_GROUPS"] = false;
					RIGHTS["TENANT_RESSOURCES_AGENTS"] = false;
					RIGHTS["TENANT_RESSOURCES_CAMPAIGNS"] = false;
					RIGHTS["TENANT_RESSOURCES_CALLING_LISTS"] = false;
					RIGHTS["TENANT_RESSOURCES_FILTERS"] = false;
					RIGHTS["TENANT_RESSOURCES_TREATMENTS"] = false;
					RIGHTS["TENANT_RESSOURCES_NOT_READY_REASON"] = false;
					RIGHTS["TENANT_RESSOURCES_QUEUE"] = false;
					RIGHTS["TENANT_RESSOURCES_SKILLS"] = false;
				RIGHTS["TENANT_HISTORICAL_REPORTS"] = false;
				RIGHTS["TENANT_QUALITY_MONITORING"] = true;
				RIGHTS["TENANT_WORK_FORCE"] = false;
				RIGHTS["TENANT_MOP_MANAGEMENT"] = false;
				RIGHTS["TENANT_ROUTING_SCRIPTS"] = false;
				RIGHTS["TENANT_MESSAGE_CENTER"] = false;
		break;
		
		default:
			RIGHTS["CONFIGURATION"] = false;
				RIGHTS["TENANT_MANAGEMENT"] = false;
				RIGHTS["USER_MANAGEMENT"] = false;
				RIGHTS["LIVE_MONITORING"] = false;
				RIGHTS["SWITCHES"] = false;
			RIGHTS["TENANT"] = false;	
				RIGHTS["TENANT_RESSOURCES"] = false;
					RIGHTS["TENANT_RESSOURCES_AGENT_GROUPS"] = false;
					RIGHTS["TENANT_RESSOURCES_AGENTS"] = false;
					RIGHTS["TENANT_RESSOURCES_CAMPAIGNS"] = false;
					RIGHTS["TENANT_RESSOURCES_CALLING_LISTS"] = false;
					RIGHTS["TENANT_RESSOURCES_FILTERS"] = false;
					RIGHTS["TENANT_RESSOURCES_TREATMENTS"] = false;
					RIGHTS["TENANT_RESSOURCES_NOT_READY_REASON"] = false;
					RIGHTS["TENANT_RESSOURCES_QUEUE"] = false;
					RIGHTS["TENANT_RESSOURCES_SKILLS"] = false;
				RIGHTS["TENANT_HISTORICAL_REPORTS"] = false;
				RIGHTS["TENANT_QUALITY_MONITORING"] = false;
				RIGHTS["TENANT_WORK_FORCE"] = false;
				RIGHTS["TENANT_MOP_MANAGEMENT"] = false;
				RIGHTS["TENANT_ROUTING_SCRIPTS"] = false;
				RIGHTS["TENANT_MESSAGE_CENTER"] = false;
		break;
		}
		//Retrieve denied services
		var deniedServices = String( appletObj.getDeniedServices() );
		var deniedServicesArray = deniedServices.split("^");
		var i; 
		for(i = 0; i < deniedServicesArray.length; i++)
		{
			if(deniedServicesArray[i] == "TENANT_WORK_FORCE")
				RIGHTS["TENANT_WORK_FORCE"] = false;
			if(deniedServicesArray[i] == "TENANT_SKILL_BASE_ROUTING")
			{
				RIGHTS["TENANT_ROUTING_SCRIPTS"] =  false
				RIGHTS["TENANT_RESSOURCES_SKILLS"] =  false
			}
			if(deniedServicesArray[i] == "TENANT_RESSOURCES_CAMPAIGNS")
			{
				RIGHTS["TENANT_RESSOURCES_CAMPAIGNS"] =  false 
				RIGHTS["TENANT_RESSOURCES_CALLING_LISTS"] =  false 
				RIGHTS["TENANT_RESSOURCES_FILTERS"] =  false 
				RIGHTS["TENANT_RESSOURCES_TREATMENTS"] =  false 
				RIGHTS["TENANT_REPORT_CAMPAIGN"] =  false 
				RIGHTS["TENANT_REPORT_CALLING_LIST"] =  false 
			}
			if(deniedServicesArray[i] == "TENANT_QUALITY_MONITORING")
				RIGHTS["TENANT_QUALITY_MONITORING"] =  false
				
			
		}
		
}