/* Message variables */

var MSG_ID_SEPARATOR 			= ","
var MSG_FIELD_SEPARATOR 		= "^"
var MSG_RESOURCE_SEPARATOR		= "|"

var MSG_TYPE_IDENTITY=0
var MSG_TYPE_UNDEFINED=1
var MSG_TYPE_INVALID_MESSAGE=2
var MSG_TYPE_ADD_AGENT=3
var MSG_TYPE_DELETE_AGENT=4
var MSG_TYPE_MODIFY_AGENT=5
var MSG_TYPE_GET_ALL_AGENTS=6

var MSG_TYPE_ADD_CAMPAIGN=7
var MSG_TYPE_DELETE_CAMPAIGN=8
var MSG_TYPE_MODIFY_CAMPAIGN=9
var MSG_TYPE_GET_ALL_CAMPAIGNS=10

var MSG_TYPE_ADD_AGENT_GROUP=11
var MSG_TYPE_DELETE_AGENT_GROUP=12
var MSG_TYPE_MODIFY_AGENT_GROUP=13
var MSG_TYPE_GET_ALL_AGENT_GROUPS=14

var MSG_TYPE_ADD_TREATMENT=15
var MSG_TYPE_DELETE_TREATMENT=16
var MSG_TYPE_MODIFY_TREATMENT=17
var MSG_TYPE_GET_ALL_TREATMENTS=18

var MSG_TYPE_ADD_FILTER=19
var MSG_TYPE_DELETE_FILTER=20
var MSG_TYPE_MODIFY_FILTER=21
var MSG_TYPE_GET_ALL_FILTERS=22

var MSG_TYPE_ADD_CALLING_LIST=23
var MSG_TYPE_DELETE_CALLING_LIST=24
var MSG_TYPE_MODIFY_CALLING_LIST=25
var MSG_TYPE_GET_ALL_CALLING_LISTS=26

var MSG_TYPE_LOAD_CAMPAIGN=27
var MSG_TYPE_UNLOAD_CAMPAIGN=28
var MSG_TYPE_START_CAMPAIGN=29
var MSG_TYPE_STOP_CAMPAIGN=30
var MSG_TYPE_SET_DIALING_MODE=31

var MSG_TYPE_DIAL_NUMBER=32
var MSG_TYPE_UPDATE_CALL_RESULT=33

var MSG_TYPE_AGENT_LOGIN=34
var MSG_TYPE_AGENT_LOGOUT=35
var MSG_TYPE_AGENT_READY=36
var MSG_TYPE_AGENT_NOT_READY=37

var MSG_TYPE_QUEUE_CALL=38
var MSG_TYPE_QUEUE_DISTRIBUTE=39
var MSG_TYPE_QUEUE_ABANDONED=40
var MSG_TYPE_TERMINATE_CALL=41

var MSG_TYPE_CALL_ABANDONED=42
var MSG_TYPE_CALL_ANSWERED=43
var MSG_TYPE_CALL_BUSY=44
var MSG_TYPE_CALL_FAXMODEM=45
var MSG_TYPE_CALL_ANSWER_MACHINE=46
var MSG_TYPE_CALL_NO_ANSWER=47
var MSG_TYPE_CALL_SIT=48

var MSG_TYPE_URL=49
var MSG_TYPE_SAVE_VOICE_FILE=50

var MSG_TYPE_GET_CAMPAIGNS_STATUS=51
var MSG_TYPE_AGENT_STATS=52
var MSG_TYPE_QUEUE_STATS=53
var MSG_TYPE_CMP_STATS=54
var MSG_TYPE_LIST_STATS=55
var MSG_TYPE_AGENT_GROUP_STATS=56
var MSG_TYPE_AGENT_PERF_STATS=57

var MSG_TYPE_HEARTBEAT=58
var MSG_TYPE_GET_ALL_TENANTS=59

var MSG_TYPE_ADD_LIST_TREATMENT=60
var MSG_TYPE_DELETE_LIST_TREATMENT=61
var MSG_TYPE_GET_ALL_LIST_TREATMENTS=62
var MSG_TYPE_NO_MORE_TRUNK=63

var MSG_TYPE_AGENT_DIALING=64
var MSG_TYPE_AGENT_IN_CALL=65
var MSG_TYPE_CANCEL_DIALING=66

var MSG_TYPE_ADD_TENANT=67
var MSG_TYPE_MODIFY_TENANT=68
var MSG_TYPE_DELETE_TENANT=69

var MSG_TYPE_ADD_USER=70
var MSG_TYPE_MODIFY_USER=71
var MSG_TYPE_DELETE_USER=72
var MSG_TYPE_GET_ALL_USERS=73
var MSG_TYPE_LOGIN_INFO=74

var MSG_TYPE_GET_SWITCH=75
var MSG_TYPE_GET_SWITCH_MOST_IDLE_AGENT=76
var MSG_TYPE_DO_SINGLE_STEP_TRANSFER=77
var MSG_TYPE_DO_TWO_STEP_TRANSFER=78
var MSG_TYPE_GET_QUEUE_CONFIG=79

var MSG_TYPE_ADD_LIVE_MONITORING_USER=80
var MSG_TYPE_MODIFY_LIVE_MONITORING_USER=81
var MSG_TYPE_DELETE_LIVE_MONITORING_USER=82

var MSG_TYPE_VALIDATE_SUPID=83
var MSG_TYPE_VALIDATE_SUPPWD=84
var MSG_TYPE_AGENTBARGE_AUTH_REQ=85

var MSG_TYPE_GET_ALL_USERS_MONITORING_INFO=86

var MSG_TYPE_GET_ALL_SWITCHES=87
var MSG_TYPE_UNDEFINED1=88
var MSG_TYPE_MODIFY_SWITCH=89
var MSG_TYPE_DELETE_SWITCH=90

var MSG_TYPE_GET_ALL_TEAMS=91
var MSG_TYPE_ADD_TEAM=92
var MSG_TYPE_MODIFY_TEAM=93
var MSG_TYPE_DELETE_TEAM=94

var MSG_TYPE_GET_ALL_TEAM_AGENTS=95
var MSG_TYPE_ADD_TEAM_AGENT=96
var MSG_TYPE_MODIFY_TEAM_AGENT=97
var MSG_TYPE_DELETE_TEAM_AGENT=98

var MSG_TYPE_PERSONNAL_DIAL=99
var MSG_TYPE_HOLD=100
var MSG_TYPE_UNHOLD=101
var MSG_TYPE_DIAL_PREVIEW=102

var MSG_TYPE_GET_ALL_USERS_AUTHORIZE_GROUP=103

var MSG_TYPE_GET_ALL_MOP=104
var MSG_TYPE_ADD_MOP=105
var MSG_TYPE_DELETE_MOP=106
var MSG_TYPE_MODIFY_MOP=107

var MSG_TYPE_GET_ALL_TREAT_MOPS=108
var MSG_TYPE_ADD_TREAT_MOP=109
var MSG_TYPE_DELETE_TREAT_MOP=110
var MSG_TYPE_MODIFY_TREAT_MOP=111

var MSG_TYPE_GET_ALL_SKILLS=112
var MSG_TYPE_ADD_SKILL=113
var MSG_TYPE_MODIFY_SKILL=114
var MSG_TYPE_DELETE_SKILL=115

var MSG_TYPE_GET_ADHERENCE_DATA=116
var MSG_TYPE_STOP_ADHERENCE_DATA=117
var MSG_TYPE_AGENT_ADHERENCE_STATS=118

var MSG_TYPE_GET_ALL_AGENT_SKILLS=119
var MSG_TYPE_ADD_AGENT_SKILL=120
var MSG_TYPE_MODIFY_AGENT_SKILL=121
var MSG_TYPE_DELETE_AGENT_SKILL=122

var MSG_TYPE_GET_ROUTING_SCRIPT=123
var MSG_TYPE_SAVE_ROUTING_SCRIPT=124

var MSG_TYPE_GET_ALL_TREATS=125
var MSG_TYPE_ADD_TREAT=126
    MSG_TYPE_DELETE_TREAT=127

var MSG_TYPE_GET_ALL_SCHEDULE=128
var MSG_TYPE_ADD_ROUTING_SCRIPT=129

var MSG_TYPE_AHPHONE_INIT=130
var MSG_TYPE_AGENT_REALLY_START_DIALING=131

var MSG_TYPE_SBR_ROUTING_REQUEST=132
var MSG_TYPE_SBR_PBX_EXEC=133

var MSG_TYPE_GET_PBX_LINE_STATUS=134
var MSG_TYPE_GET_AHEEVA_TRACKNUM=135
var MSG_TYPE_AGENT_CANCEL_CONFERENCE=136
var MSG_TYPE_UNDEFINED7=137

var MSG_TYPE_DELETE_ROUTING_SCRIPT=138

var MSG_TYPE_UNDEFINED8=139
var MSG_TYPE_UNDEFINED9=140
var MSG_TYPE_UNDEFINED10=141

var MSG_TYPE_UNDEFINED11=142
var MSG_TYPE_UNDEFINED12=143

var MSG_TYPE_CALL_AM_MSG_LEFT=144
var MSG_TYPE_SBR_NO_ONE_AVAILABLE=145
var MSG_TYPE_SBR_DISTRIBUTE=146
var MSG_TYPE_SBR_ABANDONED=147
var MSG_TYPE_VQUEUE_ABANDONED_ON_PICKUP=148
var MSG_TYPE_VQUEUE_DISTRIBUTE_ON_PICKUP=149
var MSG_TYPE_SBR_GET_DTMF=150
var MSG_TYPE_FORCE_AGENT_STATUS=151
var MSG_TYPE_SBR_NO_SCRIPT_DEFINED=152
var MSG_TYPE_SBR_END_OF_CALL=153

var MSG_AGENT_LOGIN=154
var MSG_AGENT_CONNECT=155
var MSG_AGENT_ANSWER=156
var MSG_GET_CHANNEL=157
var MSG_SEND_CHANNEL=158
var MSG_HANGUP_CHANNEL=159
var MSG_DIAL_NUMBER=160

var MSG_TYPE_GET_ALL_DENIED_MENUS=161
var MSG_TYPE_RSCRIPT_COUNTERS_STATS=162
var MSG_TYPE_MANAGER_AUTH=163

var MSG_TYPE_ASTERISK_NOT_ALLOWED=164

var MSG_LINE_HANGUP=165
var MSG_TRANSFERT_CHANNEL=166
var MSG_HOLD_CHANNEL=167
var MSG_UNHOLD_CHANNEL=168
var MSG_INITIATE_CONFERENCE=169
var MSG_SWITCH_LINE=170
var MSG_COMPLETE_CONFERENCE=171

var MSG_TYPE_GET_ALL_QUEUES=172

var MSG_TYPE_MODIFY_PREFER_SITES=173
var MSG_TYPE_GET_ALL_PREFER_SITES=174

var MSG_STARPHONE_UPDATE_RECORDING=175
var MSG_TYPE_SWITCH_STATS=176

var MSG_TYPE_MODIFY_STARPHONE_AUTO_UPDATE=177
var MSG_TYPE_GET_STARPHONE_AUTO_UPDATE=178

var MSG_TYPE_GET_ALL_SITES=179
var MSG_TYPE_MODIFY_SITES=180

var MSG_TYPE_ADD_GROUP_SCHEDULE=181
var MSG_TYPE_DELETE_GROUP_SCHEDULE=182
var MSG_TYPE_MODIFY_GROUP_SCHEDULE=183
var MSG_TYPE_GET_ALL_GROUP_SCHEDULE=184

var MSG_TYPE_VIDEO_SCHEDULE_REQUEST=185

var MSG_TYPE_GET_ALL_NOT_READY_REASON=186
var MSG_TYPE_ADD_NOT_READY_REASON=187
var MSG_TYPE_DELETE_NOT_READY_REASON=188
var MSG_TYPE_MODIFY_NOT_READY_REASON=189

var MSG_TYPE_GET_ALL_LIST_NOT_READY_REASON=190
var MSG_TYPE_ADD_LIST_NOT_READY_REASON=191
var MSG_TYPE_DELETE_LIST_NOT_READY_REASON=192

var MSG_TYPE_HAD_EXECUTE_APPLICATION=193

var MSG_TYPE_REMOVE_VIDEO_SCHEDULE=194

var MSG_TYPE_ADD_ALERT_STARPHONE=195
var MSG_TYPE_DELETE_ALERT_STARPHONE=196
var MSG_TYPE_MODIFY_ALERT_STARPHONE=197
var MSG_TYPE_GET_ALL_ALERT_STARPHONE=198

var MSG_TYPE_ADD_ALERT_MANAGER=199
var MSG_TYPE_DELETE_ALERT_MANAGER=200
var MSG_TYPE_MODIFY_ALERT_MANAGER=201
var MSG_TYPE_GET_ALL_ALERT_MANAGER=202

var MSG_TYPE_ADD_STATISTIC_STARPHONE=203
var MSG_TYPE_DELETE_STATISTIC_STARPHONE=204
var MSG_TYPE_MODIFY_STATISTIC_STARPHONE=205
var MSG_TYPE_GET_ALL_STATISTIC_STARPHONE=206

var MSG_TYPE_ADD_GROUP_SCHEDULE_MANAGER=207
var MSG_TYPE_DELETE_GROUP_SCHEDULE_MANAGER=208
var MSG_TYPE_MODIFY_GROUP_SCHEDULE_MANAGER=209
var MSG_TYPE_GET_ALL_GROUP_SCHEDULE_MANAGER=210

var MSG_TYPE_GET_ALL_LIST_SCHEDULE_ALERT_STARPHONE=211
var MSG_TYPE_ADD_LIST_SCHEDULE_ALERT_STARPHONE=212
var MSG_TYPE_DELETE_LIST_SCHEDULE_ALERT_STARPHONE=213

var MSG_TYPE_GET_ALL_LIST_SCHEDULE_ALERT_MANAGER=214
var MSG_TYPE_ADD_LIST_SCHEDULE_ALERT_MANAGER=215
var MSG_TYPE_DELETE_LIST_SCHEDULE_ALERT_MANAGER=216

var MSG_TYPE_CANCEL_PREVIEW_DIALING=217
var MSG_TYPE_GET_ALL_DYNAMIC_MODULES=218
var MSG_TYPE_LIVE_CAST=219
var MSG_TYPE_SAVE_NETWORK_CFG_LAYOUT=220
var MSG_TYPE_GET_NETWORK_CFG_LAYOUT=221

var MSG_TYPE_GET_ALL_ENCSERVERS=250
var MSG_TYPE_ADD_ENCSERVER=251
var MSG_TYPE_MODIFY_ENCSERVER=252
var MSG_TYPE_DELETE_ENCSERVER=253

var MSG_TYPE_MODIFY_TREAT=254

var MSG_TYPE_ADD_TREAT_COM=255
var MSG_TYPE_DELETE_TREAT_COM=256
var MSG_TYPE_GET_ALL_TREAT_COM=257
var MSG_TYPE_MODIFY_TREAT_COM=258

var MSG_TYPE_RECORDING_DATA=259
var MSG_TYPE_RECORDSERVER_NOT_ALLOWED=260
var MSG_TYPE_GET_RECORDSERVER_CONFIG=261
var MSG_TYPE_GET_RECORDSERVER=262
var MSG_TYPE_RECORDSERVER_STATS=263
var MSG_TYPE_RECORDSERVER_SYNC_ORDER=264

var MSG_TYPE_GET_ALL_RECORDSERVERS=265
var MSG_TYPE_ADD_RECORDSERVER=266
    MSG_TYPE_MODIFY_RECORDSERVER=267
    MSG_TYPE_DELETE_RECORDSERVER=268

var MSG_TYPE_GET_RECORD_PARAMS_FOR_AGENT=269
var MSG_TYPE_SAVE_CONVERSATION_IN_DB=270
var MSG_TYPE_RECORDSERVER_SYNC_RESP=271
var MSG_TYPE_RECORDSERVER_SYNC_CANCEL=272
var MSG_TYPE_RECORDSERVER_SYNC_END=273
var MSG_TYPE_CTI_SERVER_STATS=274
var MSG_TYPE_CTI_DATETIME=275
var MSG_TYPE_RECORDSERVER_REMOVE_ORDER=276
var MSG_TYPE_UPDATE_CONVERSATION_IN_DB=277
var MSG_TYPE_START_SCREEN_CAPTURE=278
var MSG_TYPE_STOP_SCREEN_CAPTURE=279

var MSG_TYPE_ADD_BLACKLIST = 280
var MSG_TYPE_DELETE_BLACKLIST=281
var MSG_TYPE_GET_ALL_BLACKLIST=282

var MSG_TYPE_ADD_BLACKLIST_CAMPAIGN=283
var MSG_TYPE_DELETE_BLACKLIST_CAMPAIGN=284
var MSG_TYPE_GET_ALL_BLACKLIST_CAMPAIGN=285

var MSG_TYPE_ADD_BLACKLIST_GROUP=286
var MSG_TYPE_DELETE_BLACKLIST_GROUP=287
var MSG_TYPE_GET_ALL_BLACKLIST_GROUP=288

var MSG_TYPE_DELETE_ONE_BLACKLIST_CAMPAIGN=289

var MSG_TYPE_CLI_CMD_EXEC=290

var MSG_TYPE_AGENT_NO_LONGER_AVAILABLE=291

var MSG_TYPE_DELETE_NUMBER_FROM_BLACKLIST_GROUP=292

var MSG_TYPE_CLI_LIST_ALL_COMMANDS=293

var MSG_TYPE_MODIFY_LIST_NOT_READY_REASON = 298

var MSG_TYPE_GET_ALL_WORK_PERIOD = 300
var MSG_TYPE_ADD_WORK_PERIOD=301
var MSG_TYPE_MODIFY_WORK_PERIOD=302
var MSG_TYPE_DELETE_WORK_PERIOD=303

var MSG_TYPE_GET_ALL_GLOBAL_NRR_DURATION=304
var MSG_TYPE_ADD_GLOBAL_NRR_DURATION=305
var MSG_TYPE_MODIFY_GLOBAL_NRR_DURATION=306
var MSG_TYPE_DELETE_GLOBAL_NRR_DURATION=307
var MSG_TYPE_DELETE_GLOBAL_NRR_DURATION_BY_WP_ID=308

var MSG_TYPE_GET_ALL_PAYABLE_NRR=309
var MSG_TYPE_ADD_PAYABLE_NRR=310
var MSG_TYPE_MODIFY_PAYABLE_NRR=311
var MSG_TYPE_DELETE_PAYABLE_NRR=312

var MSG_TYPE_GET_ALL_ACTIVITY=313
var MSG_TYPE_ADD_ACTIVITY=314
var MSG_TYPE_MODIFY_ACTIVITY=315
var MSG_TYPE_DELETE_ACTIVITY=316

var MSG_TYPE_AHPHONE_AUTHENTICATE=317

var MSG_TYPE_ADD_LISTEN_HISTORY = 400
var MSG_TYPE_DELETE_LISTEN_HISTORY = 401

var MSG_TYPE_ADD_QUEUE2 = 402
var MSG_TYPE_MODIFY_QUEUE2 =403
var MSG_TYPE_GET_ALL_QUEUE2 =404

var MSG_TYPE_AGENT_HANG_UP =405
var MSG_TYPE_AGENT_CLICK_NOT_READY =406
var MSG_TYPE_GET_GRP_STARPHONE=407
var MSG_TYPE_AGENT_NOT_READY_REASON_SET=408
var MSG_TYPE_AGENT_NOT_READY_AFTER_WRAP_UP =409
var MSG_TYPE_GET_CURRENT_STATS=410
var MSG_TYPE_MANAGER_ALERT_MESSAGE = 440 //receive the manager alert messages from the message center

var MSG_TYPE_SEND_ALL_DATA = 10000			//10000


function send_message_to_cti( message_type, message_body )
{
	var full_message = "";
	full_message += message_type + MSG_ID_SEPARATOR + message_body;
	appletObj.sendInfo( full_message );
}
