#!/bin/sh
#

PID_FILE="pid.txt"

CHECK_CMD="kill -0 `head -1 $PID_FILE`"
KILL_CMD="kill `head -1 $PID_FILE`"
RUN_CMD="nohup ./dbCruncher"

if [ ! -d logs ] ; then
   mkdir logs
fi

if test -f $PID_FILE ; then
    $CHECK_CMD >> /dev/null 2>&1
    if test $? -eq 0 ; then
        echo ""
        echo "dbCruncher process already running..."
        echo ""
        exit 0
    fi
fi

$RUN_CMD >> /dev/null 2>&1 &

$CHECK_CMD >> /dev/null 2>&1

if test $? -ne 0 ; then
    echo ""
    echo "dbCruncher process running."
    echo ""
    exit 0
else
    echo ""
    echo "Failed to start dbCruncher process."
    echo ""
    exit 1
fi


