package org.apache.jsp.aheevaManager.Resources_005fpages.popup;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import aheevaManager.ressources.popbuilder.*;
import aheevaManager.ressources.*;
import java.util.*;

public final class popup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/aheevaManager/Resources_pages/popup/include_labels.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");



beanManagerData pageData = new beanManagerData();
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage( (String)session.getAttribute("USER_LANGUAGE") );
else 
	pageData.setDefaultLanguage("ENGLISH");	

String currentUserDbid = (String)session.getAttribute("CURRENT_USER_DBID");

String xmlstr = request.getParameter("xmlstr");
Popup popup =new Popup(pageData);
String popup_dbid = (request.getParameter("popdbid")==null)?"":request.getParameter("popdbid");

String currentpagename =  (request.getParameter("currentpagename")==null)?"":request.getParameter("currentpagename");

if (xmlstr != null) {
	
	String del = request.getParameter("del");
	if ("1".equals(del) ) {
		if ( !"".equals(popup_dbid)) {
			popup.deletePopup(popup_dbid);
			popup_dbid = "";
		}
	} else {
		popup_dbid = popup.savePop(xmlstr,currentUserDbid);
	}
}
	

if ("".equals(popup_dbid)) {
	popup = new Popup(pageData);
	Date d = new Date();
	
	String uniqueid = String.valueOf(d.getTime());
	session.setAttribute("uniqueid",uniqueid);
}
else {
	popup = new Popup(popup_dbid,pageData);
	session.setAttribute("uniqueid","");
}

pageData.openConnection();	

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script>\r\n");
      out.write("var lab_state = \"");
      out.print(popup.getState());
      out.write("\";\r\n");
      out.write(" ");
      out.write("var lab_arr = new Array();\r\n");
      out.write("lab_arr[0] = \"");
      out.print(pageData.getWord("Add page"));
      out.write("\";\r\n");
      out.write("lab_arr[1] = \"");
      out.print(pageData.getWord("Page"));
      out.write("\";\r\n");
      out.write("lab_arr[2] = \"");
      out.print(pageData.getWord("Page name"));
      out.write("\";\r\n");
      out.write("lab_arr[3] = \"");
      out.print(pageData.getWord("Add"));
      out.write("\";\r\n");
      out.write("lab_arr[4] = \"");
      out.print(pageData.getWord("Cancel"));
      out.write("\";\r\n");
      out.write("lab_arr[5] = \"");
      out.print(pageData.getWord("Please enter a page name"));
      out.write("\";\r\n");
      out.write("lab_arr[6] = \"");
      out.print(pageData.getWord("Are you sure you want to delete this object?"));
      out.write("\";\r\n");
      out.write("lab_arr[7] = \"");
      out.print(pageData.getWord("Add row"));
      out.write("\";\r\n");
      out.write("lab_arr[8] = \"");
      out.print(pageData.getWord("Delete"));
      out.write("\";\r\n");
      out.write("lab_arr[9] = \"");
      out.print(pageData.getWord("Save"));
      out.write("\";\r\n");
      out.write("lab_arr[10] = \"");
      out.print(pageData.getWord("List of values"));
      out.write("\";\r\n");
      out.write("lab_arr[11] = \"");
      out.print(pageData.getWord("Description"));
      out.write("\";\r\n");
      out.write("lab_arr[12] = \"");
      out.print(pageData.getWord("Default"));
      out.write("\";\r\n");
      out.write("lab_arr[13] = \"");
      out.print(pageData.getWord("Datasource"));
      out.write("\";\r\n");
      out.write("lab_arr[14] = \"");
      out.print(pageData.getWord("Table"));
      out.write("\";\r\n");
      out.write("lab_arr[15] = \"");
      out.print(pageData.getWord("Form name should not be empty"));
      out.write("\";\r\n");
      out.write("lab_arr[16] = \"");
      out.print(pageData.getWord("Colors pannel"));
      out.write("\";\r\n");
      out.write("lab_arr[17] = \"");
      out.print(pageData.getWord("Ok"));
      out.write("\";\r\n");
      out.write("lab_arr[18] = \"");
      out.print(pageData.getWord("Code"));
      out.write("\";\r\n");
      out.write("lab_arr[19] = \"");
      out.print(pageData.getWord("Are you sure you want to delete this page?"));
      out.write("\";\r\n");
      out.write("lab_arr[20] = \"");
      out.print(pageData.getWord("Please enter form name"));
      out.write("\";\r\n");
      out.write("lab_arr[21] = \"");
      out.print(pageData.getWord("Field"));
      out.write("\";\r\n");
      out.write("lab_arr[22] = \"");
      out.print(pageData.getWord("Database configuration"));
      out.write("\";\r\n");
      out.write("lab_arr[23] = \"");
      out.print(pageData.getWord("Add database"));
      out.write("\";\r\n");
      out.write("lab_arr[24] = \"");
      out.print(pageData.getWord("Close"));
      out.write("\";\r\n");
      out.write("lab_arr[25] = \"");
      out.print(pageData.getWord("Add Parameter"));
      out.write("\";\r\n");
      out.write("lab_arr[26] = \"");
      out.print(pageData.getWord("Parameters configuration"));
      out.write("\";\r\n");
      out.write("lab_arr[27] = \"");
      out.print(pageData.getWord("Where Clause Config."));
      out.write("\";\r\n");
      out.write("lab_arr[28] = \"");
      out.print(pageData.getWord("Database"));
      out.write("\";\r\n");
      out.write("lab_arr[29] = \"");
      out.print(pageData.getWord("Add Where Clause"));
      out.write("\";\r\n");
      out.write("lab_arr[30] = \"");
      out.print(pageData.getWord("From table"));
      out.write("\";\r\n");
      out.write("lab_arr[31] = \"");
      out.print(pageData.getWord("Where Field"));
      out.write("\";\r\n");
      out.write("lab_arr[32] = \"");
      out.print(pageData.getWord("Dest. type"));
      out.write("\";\r\n");
      out.write("lab_arr[33] = \"");
      out.print(pageData.getWord("Dest. table"));
      out.write("\";\r\n");
      out.write("lab_arr[34] = \"");
      out.print(pageData.getWord("Dest. Field"));
      out.write("\";\r\n");
      out.write("lab_arr[35] = \"");
      out.print(pageData.getWord("Dest. Param"));
      out.write("\";\r\n");
      out.write("lab_arr[36] = \"");
      out.print(pageData.getWord("Fields list"));
      out.write("\";\r\n");
      out.write("lab_arr[37] = \"");
      out.print(pageData.getWord("Are you sure you want to delete this parameter?"));
      out.write("\";\r\n");
      out.write("lab_arr[38] = \"");
      out.print(pageData.getWord("Are you sure you want to remove the link to this database?"));
      out.write("\";\r\n");
      out.write("lab_arr[39] = \"");
      out.print(pageData.getWord("Tables configuration"));
      out.write("\";\r\n");
      out.write("lab_arr[40] = \"");
      out.print(pageData.getWord("Tables list"));
      out.write("\";\r\n");
      out.write("lab_arr[41] = \"");
      out.print(pageData.getWord("Test Connection"));
      out.write("\";\r\n");
      out.write("lab_arr[42] = \"");
      out.print(pageData.getWord("Properties list"));
      out.write("\";\r\n");
      out.write("lab_arr[43] = \"");
      out.print(pageData.getWord("RGB"));
      out.write("\";\r\n");
      out.write("lab_arr[44] = \"");
      out.print(pageData.getWord("Connection succeded"));
      out.write("\";\r\n");
      out.write("lab_arr[45] = \"");
      out.print(pageData.getWord("Connection failed"));
      out.write("\";\r\n");
      out.write("lab_arr[46] = \"");
      out.print(pageData.getWord("Parameter"));
      out.write("\";\r\n");
      out.write("lab_arr[47] = \"");
      out.print(pageData.getWord("List forms"));
      out.write("\";\r\n");
      out.write("lab_arr[48] = \"");
      out.print(pageData.getWord("Pop:"));
      out.write("\";\r\n");
      out.write("lab_arr[49] = \"");
      out.print(pageData.getWord("Databases list"));
      out.write("\";\r\n");
      out.write("lab_arr[50] = \"");
      out.print(pageData.getWord("Please do not forget that you must have at least one page in your form") );
      out.write("\";\r\n");
      out.write("lab_arr[51] = \"");
      out.print(pageData.getWord("Delete item") );
      out.write("\";\r\n");
      out.write("lab_arr[52] = \"");
      out.print(pageData.getWord("This form name already exists, please enter another one") );
      out.write("\";\r\n");
      out.write("lab_arr[53] = \"");
      out.print(pageData.getWord("Page properties") );
      out.write("\";\r\n");
      out.write("lab_arr[54] = \"");
      out.print(pageData.getWord("Delete page"));
      out.write("\";\r\n");
      out.write("lab_arr[55] = \"");
      out.print(pageData.getWord("from table should not be empty, please choose one") );
      out.write("\";\r\n");
      out.write("lab_arr[56] = \"");
      out.print(pageData.getWord("from field should not be empty, please choose one") );
      out.write("\";\r\n");
      out.write("lab_arr[57] = \"");
      out.print(pageData.getWord("To parameter should not be empty, please choose one") );
      out.write("\";\r\n");
      out.write("lab_arr[58] = \"");
      out.print(pageData.getWord("To table should not be empty, please choose one") );
      out.write("\";\r\n");
      out.write("lab_arr[59] = \"");
      out.print(pageData.getWord("To field should not be empty, please choose one") );
      out.write("\";\r\n");
      out.write("lab_arr[60] = \"");
      out.print(pageData.getWord("The path sould not be empty, please enter one") );
      out.write("\";\r\n");
      out.write("lab_arr[61] = \"");
      out.print(pageData.getWord("Database Label already exists, please enter another one") );
      out.write("\";\r\n");
      out.write("lab_arr[62] = \"");
      out.print(pageData.getWord("Save as form") );
      out.write("\";\r\n");
      out.write("lab_arr[63] = \"");
      out.print(pageData.getWord("Form name") );
      out.write("\";\r\n");
      out.write("lab_arr[64] = \"");
      out.print(pageData.getWord("You cannot add filter to a table already used as filter for another table, please change it") );
      out.write("\";\r\n");
      out.write("lab_arr[65] = \"");
      out.print(pageData.getWord("You cannot use table as filter before defining the filters for it, please change it") );
      out.write("\";\r\n");
      out.write("lab_arr[66] = \"");
      out.print(pageData.getWord("Files path") );
      out.write("\";\r\n");
      out.write("lab_arr[67] = \"");
      out.print(pageData.getWord("Path for the php genration files") );
      out.write("\";\r\n");
      out.write("lab_arr[68] = \"");
      out.print(pageData.getWord("should not be empty") );
      out.write("\";\r\n");
      out.write("lab_arr[69] = \"");
      out.print(pageData.getWord("value should be greater than") );
      out.write("\";\r\n");
      out.write("lab_arr[70] = \"");
      out.print(pageData.getWord("value should be less than") );
      out.write("\";\r\n");
      out.write("lab_arr[71] = \"");
      out.print(pageData.getWord("Name") );
      out.write("\";\r\n");
      out.write("lab_arr[72] = \"");
      out.print(pageData.getWord("Properties") );
      out.write("\";\r\n");
      out.write("lab_arr[73] = \"");
      out.print(pageData.getWord("Master") );
      out.write("\";\r\n");
      out.write("lab_arr[74] = \"");
      out.print(pageData.getWord("You must choose a master") );
      out.write("\";\r\n");
      out.write("lab_arr[75] = \"");
      out.print(pageData.getWord("Outbound form should be related to one calling list") );
      out.write("\";\r\n");
      out.write("lab_arr[76] = \"");
      out.print(pageData.getWord("You should add elements related to") );
      out.write("\";\r\n");
      out.write("lab_arr[77] = \"");
      out.print(pageData.getWord("Please enter a valid hexadecimal color value"));
      out.write("\";\r\n");
      out.write("lab_arr[78] = \"");
      out.print(pageData.getWord("This page name already exists, please enter another one") );
      out.write("\";\r\n");
      out.write("lab_arr[79] = \"");
      out.print(pageData.getWord("Color should not be empty, please choose one") );
      out.write("\";\r\n");
      out.write("lab_arr[80] = \"");
      out.print(pageData.getWord("Please enter a unique code") );
      out.write("\";\r\n");
      out.write("lab_arr[81] = \"");
      out.print(pageData.getWord("Please enter a unique description") );
      out.write("\";\r\n");
      out.write("lab_arr[82] = \"");
      out.print(pageData.getWord("Please remove the specified characters") );
      out.write("\";\r\n");
      out.write("lab_arr[83] = \"");
      out.print(pageData.getWord("Are you sure you want to delete this form?") );
      out.write("\";\r\n");
      out.write("lab_arr[84] = \"");
      out.print(pageData.getWord("Delete form") );
      out.write("\";\r\n");
      out.write("lab_arr[85] = \"");
      out.print(pageData.getWord("This parameter already exists, please enter another one") );
      out.write("\";\r\n");
      out.write("lab_arr[86] = \"");
      out.print(pageData.getWord("List tables [Displayed in insert order]") );
      out.write("\";\r\n");
      out.write("lab_arr[87] = \"");
      out.print(pageData.getWord("Warning:") );
      out.write("\";\r\n");
      out.write("lab_arr[88] = \"");
      out.print(pageData.getWord("Are you sure you want to remove this condition?") );
      out.write("\";\r\n");
      out.write("lab_arr[89] = \"");
      out.print(pageData.getWord("Please verify the order of insert for the tables") );
      out.write("\";\r\n");
      out.write("lab_arr[90] = \"");
      out.print(pageData.getWord("Type:"));
      out.write("\";\r\n");
      out.write("lab_arr[91] = \"");
      out.print(pageData.getWord("Name:") );
      out.write("\";\r\n");
      out.write("lab_arr[92] = \"");
      out.print(pageData.getWord("Created:") );
      out.write("\";\r\n");
      out.write("lab_arr[93] = \"");
      out.print(pageData.getWord("Created by:") );
      out.write("\";\r\n");
      out.write("lab_arr[94] = \"");
      out.print(pageData.getWord("Last modified:") );
      out.write("\";\r\n");
      out.write("lab_arr[95] = \"");
      out.print(pageData.getWord("Modified by:") );
      out.write("\";\r\n");
      out.write("lab_arr[96] = \"");
      out.print(pageData.getWord("Database information") );
      out.write("\";\r\n");
      out.write("lab_arr[97] = \"");
      out.print(pageData.getWord("Outbound") );
      out.write("\";\r\n");
      out.write("lab_arr[98] = \"");
      out.print(pageData.getWord("Inbound") );
      out.write("\";\r\n");
      out.write("lab_arr[99] = \"");
      out.print(pageData.getWord("Form Properties") );
      out.write("\";\r\n");
      out.write("lab_arr[100] = \"");
      out.print(pageData.getWord("Elements triggers") );
      out.write("\";\r\n");
      out.write("lab_arr[101] = \"");
      out.print(pageData.getWord("Add element trigger") );
      out.write("\";\r\n");
      out.write("lab_arr[102] = \"");
      out.print(pageData.getWord("Trigger page") );
      out.write("\";\r\n");
      out.write("lab_arr[103] = \"");
      out.print(pageData.getWord("Element") );
      out.write("\";\r\n");
      out.write("lab_arr[104] = \"");
      out.print(pageData.getWord("Operator") );
      out.write("\";\r\n");
      out.write("lab_arr[105] = \"");
      out.print(pageData.getWord("Value") );
      out.write("\";\r\n");
      out.write("lab_arr[106] = \"");
      out.print(pageData.getWord("Action") );
      out.write("\";\r\n");
      out.write("lab_arr[107] = \"");
      out.print(pageData.getWord("Action page") );
      out.write("\";\r\n");
      out.write("lab_arr[108] = \"");
      out.print(pageData.getWord("Values") );
      out.write("\";\r\n");
      out.write("lab_arr[109] = \"");
      out.print(pageData.getWord("Trigger and action elements should be different") );
      out.write("\";\r\n");
      out.write("lab_arr[110] = \"");
      out.print(pageData.getWord("Check") );
      out.write("\";\r\n");
      out.write("lab_arr[111] = \"");
      out.print(pageData.getWord("Uncheck") );
      out.write("\";\r\n");
      out.write("lab_arr[112] = \"");
      out.print(pageData.getWord("Are you sure you want to delete this trigger?"));
      out.write("\";\r\n");
      out.write("lab_arr[113] = \"");
      out.print(pageData.getWord("Are you sure you want to delete this row?"));
      out.write("\";\r\n");
      out.write("lab_arr[114] = \"");
      out.print(pageData.getWord("Trigger name") );
      out.write("\";\r\n");
      out.write("lab_arr[116] = \"");
      out.print(pageData.getWord("Type"));
      out.write("\";\r\n");
      out.write("lab_arr[117] = \"");
      out.print(pageData.getWord("You have changed the name of this form."));
      out.write("\";\r\n");
      out.write("lab_arr[118] = \"");
      out.print(pageData.getWord("Clicking 'OK' will overwrite form:"));
      out.write("\";\r\n");
      out.write("lab_arr[119] = \"");
      out.print(pageData.getWord("If you want to keep the original form"));
      out.write("\";\r\n");
      out.write("lab_arr[120] = \"");
      out.print(pageData.getWord("click 'Cancel' and select 'Save as' from the file menu"));
      out.write("\";\r\n");
      out.write("lab_arr[121] = \"");
      out.print(pageData.getWord("Changing form state..."));
      out.write("\";\r\n");
      out.write("lab_arr[122] = \"");
      out.print(pageData.getWord("Please wait"));
      out.write("\";\r\n");
      out.write("lab_arr[123] = \"");
      out.print(pageData.getWord("Saving form..."));
      out.write("\";\r\n");
      out.write("lab_arr[124] = \"");
      out.print(pageData.getWord("before setting the state to inactive."));
      out.write("\";\r\n");
      out.write("lab_arr[125] = \"");
      out.print(pageData.getWord("Changes have been made to the form."));
      out.write("\";\r\n");
      out.write("lab_arr[126] = \"");
      out.print(pageData.getWord("Clicking 'OK' will save these changes and set the form state to inactive."));
      out.write("\";\r\n");
      out.write("lab_arr[127] = \"");
      out.print(pageData.getWord("Click 'Cancel' to make further alterations."));
      out.write("\";\r\n");
      out.write("lab_arr[128] = \"");
      out.print(pageData.getWord("Event name should not be empty"));
      out.write("\";\r\n");
      out.write("lab_arr[129] = \"");
      out.print(pageData.getWord("Event page should not be empty"));
      out.write("\";\r\n");
      out.write("lab_arr[130] = \"");
      out.print(pageData.getWord("Event element should not be empty"));
      out.write("\";\r\n");
      out.write("lab_arr[131] = \"");
      out.print(pageData.getWord("Action page should not be empty"));
      out.write("\";\r\n");
      out.write("lab_arr[132] = \"");
      out.print(pageData.getWord("Action element should not be empty"));
      out.write("\";\r\n");
      out.write("lab_arr[133] = \"");
      out.print(pageData.getWord("You should not have same data for 2 triggers"));
      out.write("\";\r\n");
      out.write("lab_arr[134] = \"");
      out.print(pageData.getWord("Name shoud be unique"));
      out.write("\";\r\n");
      out.write("lab_arr[135] = \"");
      out.print(pageData.getWord("Changes have been made to your current form."));
      out.write("\";\r\n");
      out.write("lab_arr[136] = \"");
      out.print(pageData.getWord("If you continue any unsaved data will be lost."));
      out.write("\";\r\n");
      out.write("lab_arr[137] = \"");
      out.print(pageData.getWord("Loading form..."));
      out.write("\";\r\n");
      out.write("lab_arr[138] = \"");
      out.print(pageData.getWord("You will lose any unsaved data."));
      out.write('"');
      out.write(';');
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"popup.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"validation.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"../jsUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"wz_jsgraphics.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("html, body {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\toverflow:auto;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tmargin-left: 0px;\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<LINK href=\"popup.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var tenantDbid = ");
      out.print(request.getParameter("tenant_dbid"));
      out.write('\r');
      out.write('\n');
      out.print(popup.getListObject());
      out.write("\r\n");
      out.write("var uniqueid = \"");
      out.print((String)session.getAttribute("uniqueid"));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script for=\"window\" event=\"onload\">\r\n");
      out.write("\r\n");
      out.write("//alert(\"starting onload function - call inner html for 'hideloading'\");\r\n");
      out.write("setPopWidth(popWidth);\r\n");
      out.write("setPopHeight(popHeight);\r\n");
      out.write("setPopBgColor(popBgColor);\r\n");
      out.write("setReqBgColor(reqBgColor);\r\n");
      out.write("setGridColor(myGridColor);\r\n");
      out.write("gridColor(gridCol.substr(gridCol.length-1,1));\r\n");
      out.write("document.getElementById(\"popw\").value= getPopWidth();\r\n");
      out.write("document.getElementById(\"poph\").value= getPopHeight();\r\n");
      out.write(" \r\n");
      out.print(popup.drawPages());
      out.write("\r\n");
      out.write("// document.getElementById(\"popname\").value = getPopDescription();\r\n");
      out.write("setPopDescription(getPopDescription());\r\n");
      out.write("initialPopName = popDescription;\r\n");

if (popup.getDbid().equals("")) {
	
      out.write("document.getElementById(\"introdiv\").style.display=\"block\";\r\n");
      out.write("\tdocument.getElementById(\"introback\").style.filter=\"alpha(opacity=90)\";\r\n");
      out.write("\t//document.getElementById(\"introdiv\").style.-moz-opacity=\".55\";\r\n");
      out.write("\r\n");
      out.write("\t");

};


      out.write("\r\n");
      out.write("if (popState==\"1\") {\r\n");
      out.write("\tdocument.getElementById(\"activeId\").checked = true;\r\n");
      out.write("}\r\n");
      out.write("skinFit();\r\n");
      out.write("makeDraggablePop(document.getElementById(\"popupwin\"));\r\n");
      out.write("makeDraggablePop(document.getElementById(\"popupalldetwin\"));\r\n");
      out.write("fillProperties(-2);\r\n");
      out.write("\r\n");
      out.write("var currentpagename = \"");
      out.print(currentpagename);
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("var f_selected = 0;\r\n");
      out.write("for (var i=0; i < listPages.length;i++) {\r\n");
      out.write("\tif (listPages[i].page_name==currentpagename) {\r\n");
      out.write("\t\tdocument.getElementById(i).click();\r\n");
      out.write("\t\tf_selected=1;\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("if (f_selected==0 && listPages.length>0) {\r\n");
      out.write("\tdocument.getElementById(0).click();\r\n");
      out.write("}\r\n");
      out.write("startPopType = popType;\r\n");
      out.write("//alert(\"full page loaded - hide 'hideloading\");\r\n");
      out.write("document.getElementById(\"hideloading\").style.display=\"none\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("window.onbeforeunload = exitPopup;\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<title>Aheeva Form Builder</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body onResize=\"skinFit()\" window.onunload=\"unloadPopup()\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"hideloading\" style=\"position:absolute; top:0px; left:0px;width:100%; height:100%; z-index:300;\" class=\"propdivbg\">\r\n");
      out.write("\r\n");
      out.write("\t<table border=0 cellspacing=0 cellpadding=0 align=\"center\" style=\"margin-top:70px\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"introContainer\">\r\n");
      out.write("\t\t\t\t<div class=\"introInnerBorder\" style=\"width:367px; height:150px;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"version\" style=\"float:right; padding-right:4px; padding-top:2px; font-weight:normal;\">");
      out.print(pageData.getWord("Form Builder Version Number") );
      out.write("</div><br /><br />\r\n");
      out.write("\t\t\t\t\t<div id=\"prodname\" style=\"float:right; padding-right:125px; padding-top:100px;\">");
      out.print(pageData.getWord("FORM BUILDER"));
      out.write("</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"actionMessage\" style=\"width:300px; margin-left:40px; padding-top:4px; padding-left:5px; border-bottom-style:solid; border-bottom-width:1px; border-bottom-color:#52636D;\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"progressBar\" style=\"width:300px; margin-left:40px; padding-top:9px; padding-bottom:14px; padding-left:5px; padding-right:0px; border-top-style:solid; border-top-width:1px; border-top-color:#B0CFE2; border-bottom-style:solid; border-bottom-width:1px; border-bottom-color:#52636D; text-align:center;\">\r\n");
      out.write("\t\t\t\t");
      out.print(pageData.getWord("Loading"));
      out.write("...<br /><br />");
      out.print(pageData.getWord("Please wait"));
      out.write(".\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"width:300px; margin-left:40px; padding-bottom:4px; padding-left:5px; border-top-style:solid; border-top-width:1px; border-top-color:#B0CFE2; text-align:center;\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"maindiv\" style=\"width:100%; height:100%;\" class=\"maindivbg\">\r\n");
      out.write("\t<div id=\"menuDiv\" style=\"position:absolute; top:0px; left:0px; height:62px;\" class=\"toolbardivbg\">\r\n");
      out.write("\t\t<div id=\"toolbar\">");
      out.print(popup.drawToolbar());
      out.write("</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
if(popup.getState().equals("0")){ 
      out.write("\r\n");
      out.write("\t\t<div id=\"hidetools\" style=\"position:absolute;top:0px;left:100px;width:0px;height:62px;\" class=\"toolbardivbg\">\r\n");
      out.write("\t\t<div style=\"position:absolute;top:15px;left:165px;\"><img id=\"poplock\" src=\"../../img/popup/poplock1.gif\" border=\"0\" /></div><div style=\"position:absolute;top:8px;left:200px;line-height:18px;\"><font color=\"#B2573B\"><b>");
      out.print(pageData.getWord("THIS FORM IS SET TO INACTIVE AND CANNOT BE EDITED"));
      out.write("</b></font><br />");
      out.print(pageData.getWord("To make changes set the form state to active"));
      out.write(".</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"activelock\" style=\"position:absolute; top:25px; left:0px;\">");
      out.print(pageData.getWord("Active"));
      out.write("<input type='checkbox' value='1' id='activeId' onclick='setPopState(this)' ");
if(popup.getTenantDbid()!= null && popup.getTenantDbid().equals("0")){out.print("DISABLED");} 
      out.write(" /></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"pages\" style=\"position:absolute; top:62px; left:0px; width:150px;\" class=\"pagesbg\"></div>\r\n");
      out.write("\t<div id=\"pageshead\" style=\"position:absolute; top:62px; left:0px; width:150px;\" class=\"pagesbg\">\r\n");
      out.write("\t<div class=\"popdisplay\" id=\"popdisplay\" style=\"width:125px;\" onmouseover='linkOverPopName(this)' onmouseout='linkOutPopName(this)' onClick=\"linkClickPopName(this);fillProperties(-2)\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"pagesDivOuter\" style=\"position:absolute; top:62px; left:150px; overflow:scroll; background-image: url(../../img/popup/workgrid02.gif);\">\r\n");
      out.write("\t\t<div id=\"pagesDiv\" class=\"cnvdivbg\"><b>");
      out.print(pageData.getWord("To start creating your form:"));
      out.write("</b><br /><br />");
      out.print(pageData.getWord("Add a new page with the button to the left,"));
      out.write("<br />");
      out.print(pageData.getWord("then click the page name to activate the work space"));
      out.write("</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"propDiv\" style=\"position:absolute; top:62px; width:200px; text-transform:capitalize;\" class=\"propdivbg\"></div>\r\n");
      out.write("\t<div id=\"deleteBin\" class=\"bin_off\" style=\"position:absolute; width:39px; height:39px; visibility:hidden;\" onmouseup=\"deleteBin()\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t");
if(popup.getState().equals("0")){ 
      out.write("\t\r\n");
      out.write("\t<div id=\"disablePropDiv\" style=\"position:absolute;top:62px;width:200px;background-color:#E9E9E9;filter:alpha(opacity=40);\"></div>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"menuBotDiv\" style=\"position:absolute; top:10px; left:0px; width:10px; height:57px; text-transform:capitalize;\" class=\"menubotdivbg\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"botDivTable\" id=\"botDivContent\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"left\" valign=\"top\" width=\"138px\" class=\"botDivTableCol1\">&nbsp;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td align=\"left\" valign=\"top\" class=\"botDivTableCol2\">\r\n");
      out.write("\t\t\t<div class=\"botDivTableCol2Div1\">\r\n");
      out.write("\t\t\t\t");
      out.print(pageData.getWord("Form Settings"));
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<span style=\"padding-left:15px; color:#A8A494; cursor:default;\">\r\n");
      out.write("\t\t\t\t\t");
      out.print(pageData.getWord("Width"));
      out.write("\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t<input type=\"text\"  value=\"\" onBlur=\"savePopWidth(this), skinFit()\" onkeyPress=\"doEnter(this,event)\" id=\"popw\" size=\"6\" class=\"textbox1\">\r\n");
      out.write("\t\t\t\t<span style=\"padding-left:15px; color:#A8A494; cursor:default;\">\r\n");
      out.write("\t\t\t\t\t");
      out.print(pageData.getWord("Height"));
      out.write("\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t<input type=\"text\"  value=\"\" onBlur=\"savePopHeight(this), skinFit()\"  onkeyPress=\"doEnter(this,event)\" id=\"poph\" size=\"6\" class=\"textbox1\">\r\n");
      out.write("\t\t\t\t<span style=\"padding-left:20px; color:#A8A494; cursor:default;\">\r\n");
      out.write("\t\t\t\t\t");
      out.print(pageData.getWord("Backgd color"));
      out.write("\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t<span id='tdpopbg' style='padding-left:20px; background:");
      out.print(popup.getPopBgColor());
      out.write("' onclick='showColorPannel(\"popBgColor\");' onmouseover='doMouseOverLinkColor(this)' class=\"borderspan\">&nbsp;</span>\r\n");
      out.write("\t\t\t\t<span style=\"padding-left:15px; color:#A8A494; cursor:default;\">\r\n");
      out.write("\t\t\t\t\t");
      out.print(pageData.getWord("Required"));
      out.write("\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t<span id='tdreqbg' style='padding-left:20px; margin-right:15px; background:");
      out.print(popup.getReqBgColor());
      out.write(";' onclick='showColorPannel(\"reqBgColor\");' onmouseover='doMouseOverLinkColor(this)' class=\"borderspan\">&nbsp;</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td align=\"left\" valign=\"top\" class=\"botDivTableCol3\">&nbsp;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"gridoptions\" class=\"gridoptionsOuter\" style=\"position:absolute; top:10px; visibility:hidden;\">\r\n");
      out.write("\t<div id=\"gridoptionsInner\" class=\"botDivTableCol2\">\r\n");
      out.write("\t\t<div id=\"gridtitle\" class=\"botDivTableCol2Div1\" style=\"width:10px\">");
      out.print(pageData.getWord("Grid Shade"));
      out.write("</div>\r\n");
      out.write("\t\t<div style=\"padding-top:3px; padding-bottom:2px; width:190px;\">\r\n");
      out.write("\t\t\t<span id=\"gridlist\" class=\"toolbarElementsBox\"><span class=\"gridoptions_off\" onmouseover=\"gridoptMouseOver(this)\" onmouseout=\"gridoptMouseOut(this)\" onclick=\"gridColor(0), saveChangeState()\"><img src=\"../../img/popup/gridopt0.gif\" alt=\"none\" name=\"none\" width=\"35\" height=\"18\" hspace=\"0\" vspace=\"0\" border=\"0\" id=\"none\" /></span><span class=\"gridoptions_off\" onmouseover=\"gridoptMouseOver(this)\" onmouseout=\"gridoptMouseOut(this)\" onclick=\"gridColor(1), saveChangeState()\"><img src=\"../../img/popup/gridopt1.gif\" alt=\"light\" name=\"light\" width=\"35\" height=\"18\" hspace=\"0\" vspace=\"0\" border=\"0\" id=\"none\" /></span><span class=\"gridoptions_on\" onmouseover=\"gridoptMouseOver(this)\" onmouseout=\"gridoptMouseOut(this)\" onclick=\"gridColor(2), saveChangeState()\"><img src=\"../../img/popup/gridopt2.gif\" alt=\"normal\" name=\"normal\" width=\"35\" height=\"18\" hspace=\"0\" vspace=\"0\" border=\"0\" id=\"none\" /></span><span class=\"gridoptions_off\" onmouseover=\"gridoptMouseOver(this)\" onmouseout=\"gridoptMouseOut(this)\" onclick=\"gridColor(3), saveChangeState()\"><img src=\"../../img/popup/gridopt3.gif\" alt=\"dark\" name=\"dark\" width=\"35\" height=\"18\" hspace=\"0\" vspace=\"0\" border=\"0\" id=\"none\" /></span></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
if(popup.getState().equals("0")){ 
      out.write("\r\n");
      out.write("<div id=\"disableMenuBotDiv\" style=\"position:absolute;top:10px;left:0px;width:10px;height:57px;\" class=\"menubotdivbg\"></div>\r\n");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"popupwin\"  style=\"position:absolute; display:none\" class=\"popupwindiv\"></div>\r\n");
      out.write("<div id=\"popupallwin\"   position=\"absolute\" style=\"position:absolute;top:0px;left:0px;padding:0px;display:none;\" class=\"popallwindivbg\" ></div>\r\n");
      out.write("<div id=\"popupsuballwin\"   position=\"absolute\" style=\"position:absolute;top:62px;left:100px;padding:0px;display:none;\" class=\"popsuballwindivbg\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form method=\"post\" action=\"popup.jsp\" name=\"frm\">\r\n");
      out.write("<input type=\"hidden\" name =\"xmlstr\" value=\"\">\r\n");
      out.write("<input type=\"hidden\" name =\"del\" value=\"0\">\r\n");
      out.write("<input type=\"hidden\" name =\"popdbid\" value=\"");
      out.print(popup_dbid);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name =\"tenant_dbid\" value=\"");
      out.print(request.getParameter("tenant_dbid"));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name =\"currentpagename\" value=\"\">\r\n");
      out.write("\r\n");
if(popup.getState().equals("0")){ 
      out.write("\r\n");
      out.write("<div style=\"position:absolute; top:5px; left:10px;\">\r\n");
      out.write("\t<span id=\"dynmenu1\" onMouseOver=\"doMouseOver(this,0)\" onMouseOut=\"doMouseOut(this,0)\"  onclick=\"containerClick(this,0)\" class=\"lev0\">");
      out.print(pageData.getWord("File"));
      out.write("\r\n");
      out.write("\t\t<div id=\"cdynmenu1\"  onMouseOut=\"doMouseOut(this,1)\" class=\"lev1\"  style=\"display:none;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"dynmenu11\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(2,this,2)\"><nobr>");
      out.print(pageData.getWord("New"));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu12\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(11,this,2)\"><nobr>");
      out.print(pageData.getWord("Open..."));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu13\" class=\"lev2inact\"><nobr>");
      out.print(pageData.getWord("Save"));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu14\"  onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" onClick=\"doMouseClick(4,this,2)\" class=\"lev2\"><nobr>");
      out.print(pageData.getWord("Save As..."));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu15\" class=\"lev2inact\"><nobr>");
      out.print(pageData.getWord("Delete"));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div class=\"hr\"><img src=\"../../img/popup/spacer.gif\" width=\"100%\" height=\"1\"></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu16\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(8,this,2)\"><nobr>");
      out.print(pageData.getWord("Preview"));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write(" \t   </div>\r\n");
      out.write("\t</span>\r\n");
      out.write("\t<span id=\"dynmenu2\" class=\"lev0\" style=\"visibility:hidden\" >");
      out.print(pageData.getWord("Tools") );
      out.write("\r\n");
      out.write("\t\t<div id=\"cdynmenu2\"  onMouseOut=\"doMouseOut(this,1)\" class=\"lev1\"  style=\"display:none;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"dynmenu21\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(7,this,2)\"><nobr>");
      out.print(pageData.getWord("Database Configuration"));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu22\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(6,this,2)\"><nobr>");
      out.print(pageData.getWord("Table Configuration"));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu23\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(9,this,2)\"><nobr>");
      out.print(pageData.getWord("Parameters Configuration"));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu24\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(10,this,2)\"><nobr>");
      out.print(pageData.getWord("Where Clause Config."));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu25\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(14,this,2)\"><nobr>");
      out.print(pageData.getWord("Elements triggers") );
      out.write("</nobr></div>\t\r\n");
      out.write("\t\t\t<div id=\"dynmenu26\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(12,this,2)\"><nobr>");
      out.print(pageData.getWord("Global Parameters") );
      out.write("</nobr></div>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t     </div>\t\r\n");
      out.write("\t</span>\r\n");
      out.write("</div>\r\n");
}else{ 
      out.write("\r\n");
      out.write("<div style=\"position:absolute; top:5px; left:10px;\">\r\n");
      out.write("\t<span id=\"dynmenu1\" onMouseOver=\"doMouseOver(this,0)\" onMouseOut=\"doMouseOut(this,0)\"  onclick=\"containerClick(this,0)\" class=\"lev0\">");
      out.print(pageData.getWord("File"));
      out.write("\r\n");
      out.write("\t\t<div id=\"cdynmenu1\"  onmouseout=\"doMouseOut(this,1)\" class=\"lev1\"  style=\"display:none;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"dynmenu11\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(2,this,2)\"><nobr>");
      out.print(pageData.getWord("New"));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu12\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(11,this,2)\"><nobr>");
      out.print(pageData.getWord("Open..."));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu13\"  onmouseover=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" onClick=\"doMouseClick(3,this,2)\" class=\"lev2\"><nobr>");
      out.print(pageData.getWord("Save"));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu14\"  onmouseover=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" onClick=\"doMouseClick(4,this,2)\" class=\"lev2\"><nobr>");
      out.print(pageData.getWord("Save As..."));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu15\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(13,this,2)\"><nobr>");
      out.print(pageData.getWord("Delete"));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div class=\"hr\"><img src=\"../../img/popup/spacer.gif\" width=\"100%\" height=\"1\"></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu16\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(8,this,2)\"><nobr>");
      out.print(pageData.getWord("Preview"));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write(" \t   </div>\r\n");
      out.write("\t</span>\r\n");
      out.write("\t<span id=\"dynmenu2\"  onMouseOut=\"doMouseOut(this,0)\" onMouseOver=\"doMouseOver(this,0)\" onClick=\"containerClick(this,0)\" class=\"lev0\" >");
      out.print(pageData.getWord("Tools") );
      out.write("\r\n");
      out.write("\t\t<div id=\"cdynmenu2\"  onmouseout=\"doMouseOut(this,1)\" class=\"lev1\"  style=\"display:none;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"dynmenu21\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(7,this,2)\"><nobr>");
      out.print(pageData.getWord("Database Configuration"));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu22\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(6,this,2)\"><nobr>");
      out.print(pageData.getWord("Table Configuration"));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu23\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(9,this,2)\"><nobr>");
      out.print(pageData.getWord("Parameters Configuration"));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu24\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(10,this,2)\"><nobr>");
      out.print(pageData.getWord("Where Clause Config."));
      out.write("</nobr></div>\r\n");
      out.write("\t\t\t<div id=\"dynmenu25\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(14,this,2)\"><nobr>");
      out.print(pageData.getWord("Elements triggers") );
      out.write("</nobr></div>\t\r\n");
      out.write("\t\t\t<div id=\"dynmenu26\" onMouseOver=\"doMouseOver(this,2)\" onMouseOut=\"doMouseOut(this,2)\" class=\"lev2\" onClick=\"doMouseClick(12,this,2)\"><nobr>");
      out.print(pageData.getWord("Global Parameters") );
      out.write("</nobr></div>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t     </div>\t\r\n");
      out.write("\t</span>\r\n");
      out.write("</div>\r\n");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"introdiv\" position=\"absolute\" style=\"position:absolute; top:0px; left:0px; display:none;\">\r\n");
      out.write("\t<div id=\"introback\" position=\"absolute\" style=\"position:absolute; top:0px; left:0px; z-index:5\" class=\"popallwindivbg\"></div>\r\n");
      out.write("\t<div id=\"introfront\" position=\"absolute\" style=\"position:absolute; top:0px; left:0px; z-index:10;\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<table border=0 cellspacing=0 cellpadding=0 align=\"center\" style=\"margin-top:70px\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"introContainer\">\r\n");
      out.write("\t\t\t\t\t<div class=\"introInnerBorder\" style=\"width:367px; height:150px;\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"this1\" style=\"float:right; padding-right:4px; padding-top:2px; font-weight:normal;\">");
      out.print(pageData.getWord("Form Builder Version Number"));
      out.write("</div><br /><br />\r\n");
      out.write("\t\t\t\t\t\t<div id=\"this2\" style=\"float:right; padding-right:125px; padding-top:100px;\">");
      out.print(pageData.getWord("FORM BUILDER"));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width:370px; margin-left:5px; padding-top:4px; padding-bottom:9px; padding-left:5px; border-bottom-style:solid; border-bottom-width:1px; border-bottom-color:#52636D;\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(pageData.getWord("Open an existing form"));
      out.write("<input class=\"formfields\" id=\"introdiv_popname2\" type=\"button\" value=\" ... \" onClick=\"openPopupList('popupwin')\" style=\"margin-left:10px; vertical-align:middle;\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width:368px; margin-left:5px; padding-top:9px; padding-bottom:4px; padding-left:5px; padding-right:2px; border-top-style:solid; border-top-width:1px; border-top-color:#B0CFE2;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"float:right;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"formfields\" id=\"introdiv_type\" type=\"radio\" name=\"poptype\" value=\"OUT\" checked />");
      out.print(pageData.getWord("Outbound"));
      out.write("<input class=\"formfields\" id=\"introdiv_type\" type=\"radio\" name=\"poptype\" value=\"IN\" style=\"margin-left:20px\" />");
      out.print(pageData.getWord("Inbound"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(pageData.getWord("Create a new form"));
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width:375px; margin-left:5px; padding-top:4px; padding-bottom:4px; text-align:right;\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(pageData.getWord("Name"));
      out.write("<input class=\"formfields\" id=\"introdiv_popname\" type=\"text\" value=\"\" onKeyPress=\"checkEnterPopUp(event)\" style=\"margin-left:10px\" /><input class=\"formfields\" type=\"text\" style=\"display:none\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width:375px; margin-left:5px; padding-top:4px; padding-bottom:4px; text-align:right;\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"formfields\" type=button value=\"");
      out.print(pageData.getWord("Click here to continue"));
      out.write("\" onClick=\"goMainDiv(); skinFit(); saveChangeState();\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"helpbar\" style=\"cursor:pointer; position:absolute; top:5px; left:0px;\" onclick='doHelp()' onmouseover='imgOver(helpbutton, \"9\")' onmouseout='imgOver(helpbutton, \"8\")'><nobr>");
      out.print(pageData.getWord("Help"));
      out.write("<img id=\"helpbutton\" src=\"../../img/popup/helpbut01.gif\" border=\"0\" align=\"absmiddle\" style=\"margin-left:5px;\" /></nobr>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"popupalldetwin\"   position=\"absolute\" style=\"position:absolute;top:0px;left:0px;padding:0px;display:none;\" class=\"popallwindetdivbg\"></div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
 pageData.closeConnection(); 
      out.write('\r');
      out.write('\n');

if (xmlstr != null) {
	
      out.write("<script>\r\n");
      out.write("\ttry {\r\n");
      out.write("\t\twindow.opener.location.reload();\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tcatch(exp) {\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>");

}


      out.write("\r\n");
      out.write("\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
