package org.apache.jsp.aheevaManager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.*;
import javax.sql.*;
import java.sql.*;
import java.io.*;
import aheevaManager.csvinterface.*;
import aheevaManager.ressources.*;
import java.util.*;
import jxl.*;

public final class login_005fbr_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

////open connection to database///////
beanManagerData pageData = new beanManagerData();
System.out.println(session.getAttribute("USER_LANGUAGE"));
if( session.getAttribute("USER_LANGUAGE") != null )
	pageData.setDefaultLanguage((String)session.getAttribute("USER_LANGUAGE"));
    pageData.openConnection();

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Aheeva Version 3.1.0</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<!-- Fixes the IE6 & IE7 \"Press SP\r\n");
      out.write("ACEBAR or ENTER to activate and use this control\" - must be at the beginning of the file-->\r\n");
      out.write("<script language=\"JScript\" type=\"text/jscript\" src=\"activateActiveX_onload.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT LANGUAGE=\"JavaScript\">\r\n");
      out.write("function refreshFrame() {\r\n");
      out.write("frames['comm'].window.location.href = \"CommPage.jsp\"; // frame 1's page\r\n");
      out.write("}\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<script language=\"javascript\" src=\"Resources_pages/globFuncsIndexHTM.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("<script language=\"JavaScript\" src=\"Resources_pages/jsUtil.js\"> </script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Resources_pages/Browser.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\" src=\"lang_browser.js\"></script>\r\n");
      out.write("<link href=\"Resources_pages/style.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("var i\r\n");
      out.write("\r\n");
      out.write("var variable = normalizeString(QueryString('lan'));\r\n");
      out.write("var ip = '<!--#echo var=\"REMOTE_ADDR\"-->';\r\n");
      out.write("\r\n");
      out.write("var lang_id\r\n");
      out.write("function language_changed(lang_id)\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("var appletObj;\r\n");
      out.write("   \r\n");
      out.write("    window.top.comm.lang = lang_id; \r\n");
      out.write("    appletObj=window.top.comm.myApplet;\r\n");
      out.write("\tappletObj.setLanguage(lang_id);\r\n");
      out.write("\t\t\r\n");
      out.write("\tif(lang_id == '0') \r\n");
      out.write("\t\tdocument.location.href = 'login.jsp?login=' + document.login.username.value;\r\n");
      out.write("\telse if\t(lang_id == '1')\t\r\n");
      out.write("\t\tdocument.location.href = 'login_fr.jsp?login=' + document.login.username.value;\r\n");
      out.write("\telse if\t(lang_id == '2')\t\r\n");
      out.write("\t\tdocument.location.href = 'login_sp.jsp?login=' + document.login.username.value;\r\n");
      out.write("\telse if (lang_id == '3')\r\n");
      out.write("\t\tdocument.location.href = 'login_br.jsp?login=' + document.login.username.value;\r\n");
      out.write("\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function d_funtion()\r\n");
      out.write("{\r\n");
      out.write("//alert (\"in\");\r\n");
      out.write("//alert(variable);\r\n");
      out.write("\tif (variable == \"en\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\ti =0;\r\n");
      out.write("\t\t//alert (i);\r\n");
      out.write("\t}\r\n");
      out.write("\telse if (variable == \"fr\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\ti = 1;\r\n");
      out.write("\t\t//alert (i);\r\n");
      out.write("\t}\r\n");
      out.write("\telse if (variable == \"es\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\ti = 2;\r\n");
      out.write("\t\t//alert (i);\r\n");
      out.write("\t}\r\n");
      out.write("\telse if (variable = \"br\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\ti = 3;\r\n");
      out.write("\t}\r\n");
      out.write(" \t//Get the applet object\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function submitInfo()\r\n");
      out.write("{\r\n");
      out.write("    if(document.login.username.value ==\"\")\r\n");
      out.write("    {\r\n");
      out.write("        alert(\"Por favor, digite o nome do usuario!\");\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("    if(document.login.password.value == \"\")\r\n");
      out.write("    {\r\n");
      out.write("    \talert(\"Por favor, digite a senha\");\r\n");
      out.write("    \treturn false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write(" \tif(validation(document.login.username.value) == 0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Caracter inválido no nome\");\r\n");
      out.write("\t\tdocument.login.username.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(validation(document.login.password.value) == 0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Caracter inválido na senha\");\r\n");
      out.write("\t\tdocument.login.password.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write(" \t//Get the applet object\r\n");
      out.write("\tvar appletObj;\r\n");
      out.write("\tif(at.b == 'ie')\r\n");
      out.write("\t{\r\n");
      out.write("\t\tappletObj = window.top.comm.myApplet;\r\n");
      out.write("\t\twindow.top.comm.language = document.login.login_language.value;\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\tappletObj = parent.frames.comm.document.getElementById(\"myApplet\");\t\r\n");
      out.write("\t\ttop.frames.comm.language = document.login.login_language.value;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tdisplayTmpMessage(\"Validando Acceso.<br>Por favor aguarde...\", \"#3366CC\");\r\n");
      out.write("    appletObj.verifyPassword(document.login.username.value, document.login.password.value);\r\n");
      out.write("\r\n");
      out.write("     return true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checkTheKey(e)\r\n");
      out.write("{\t\r\n");
      out.write("\tvar pressedKey = \"\";\r\n");
      out.write("\r\n");
      out.write("\t//emod = (e) ? (e.eventPhase) ? \"W3C\" : \"NN4\" : (window.event) ? \"IE4+\" : \"unknown\";\r\n");
      out.write("\tswitch(at.b)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tcase \"ie\":\r\n");
      out.write("\t\t\tpressedKey = window.event.keyCode;\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\t\tcase \"ns\":\t\t\t\r\n");
      out.write("\t\t\tpressedKey = e.which;\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("  \tif(pressedKey == 13)\t//13 = <Enter>\r\n");
      out.write("    \tsubmitInfo();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function setLoginValidationForUser(result, dbid, state)\r\n");
      out.write("{\t\r\n");
      out.write("\tretrieveTmpMessage();\r\n");
      out.write("\tif( String(result) == \"SUCCEED\" )\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.location =\"./mainWindow.jsp?&lang=\"+lang+\"&user_dbid=\"+dbid;\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\t\t\t\r\n");
      out.write("\t\tdisplayTmpMessage(\"Dados Inválidos.<br>Tente novamente...\", \"#FF0000\");\r\n");
      out.write("\t\tsetTimeout(\"retrieveTmpMessage()\", 2000);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function displayTmpMessage(theMess, color)\r\n");
      out.write("{\t\r\n");
      out.write("\tvar TempMsgObj = document.getElementById('TempMsg');\r\n");
      out.write("\tvar TempMessagesObj = document.getElementById('TempMessages');\r\n");
      out.write("\tTempMsgObj.innerHTML = theMess;\r\n");
      out.write("\tif(color != \"\")\r\n");
      out.write("\t\tTempMsgObj.style.color = color;\r\n");
      out.write("\tTempMessagesObj.style.top = document.body.clientHeight/2-TempMessagesObj.clientHeight/2;\r\n");
      out.write("\tTempMessagesObj.style.left = document.body.clientWidth/2-TempMessagesObj.clientWidth/2;\r\n");
      out.write("\tvar selectobj = document.getElementById('login_language');\r\n");
      out.write("\tif( selectobj )\r\n");
      out.write("\t\tselectobj.style.visibility = 'hidden';\r\n");
      out.write("\tTempMessagesObj.style.visibility = \"visible\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function retrieveTmpMessage()\r\n");
      out.write("{\t\r\n");
      out.write("\tvar TempMsgObj = document.getElementById('TempMsg');\r\n");
      out.write("\tvar TempMessagesObj = document.getElementById('TempMessages');\r\n");
      out.write("\tTempMsgObj.innerHTML = \"\";\r\n");
      out.write("\tTempMessagesObj.style.visibility = \"hidden\";\r\n");
      out.write("\t\r\n");
      out.write("\tvar selectobj = document.getElementById('login_language');\r\n");
      out.write("\tif( selectobj )\r\n");
      out.write("\t\tselectobj.style.visibility = 'visible';\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("//alert(window.top.comm)\r\n");
      out.write("\tif(at.b == \"ie\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(window.top.comm == null || window.top.comm == undefined)\r\n");
      out.write("\t\t\tdocument.location.href = \"./index.htm\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(top.frames.comm == null || top.frames.comm == undefined)\r\n");
      out.write("\t\t\tdocument.location.href = \"./index.htm\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("function MM_preloadImages() { //v3.0\r\n");
      out.write("  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();\r\n");
      out.write("    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)\r\n");
      out.write("    if (a[i].indexOf(\"#\")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function MM_swapImgRestore() { //v3.0\r\n");
      out.write("  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function MM_findObj(n, d) { //v4.01\r\n");
      out.write("  var p,i,x;  if(!d) d=document; if((p=n.indexOf(\"?\"))>0&&parent.frames.length) {\r\n");
      out.write("    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}\r\n");
      out.write("  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];\r\n");
      out.write("  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);\r\n");
      out.write("  if(!x && d.getElementById) x=d.getElementById(n); return x;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function MM_swapImage() { //v3.0\r\n");
      out.write("  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)\r\n");
      out.write("   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<SCRIPT LANGUAGE=\"JavaScript\">\r\n");
      out.write("<!-- Original: Ronnie T. Moore -->\r\n");
      out.write("<!-- Web Site: The JavaScript Source -->\r\n");
      out.write("<!-- Begin -->\r\n");
      out.write("var expDays = 30;\r\n");
      out.write("var exp = new Date();\r\n");
      out.write("exp.setTime(exp.getTime() + (expDays*24*60*60*1000));\r\n");
      out.write("function getCookieVal (offset) {\r\n");
      out.write("var endstr = document.cookie.indexOf (\";\", offset);\r\n");
      out.write("if (endstr == -1)\r\n");
      out.write("endstr = document.cookie.length;\r\n");
      out.write("return unescape(document.cookie.substring(offset, endstr));\r\n");
      out.write("}\r\n");
      out.write("function GetCookie (name) {\r\n");
      out.write("var arg = name + \"=\";\r\n");
      out.write("var alen = arg.length;\r\n");
      out.write("var clen = document.cookie.length;\r\n");
      out.write("var i = 0;\r\n");
      out.write("while (i < clen) {\r\n");
      out.write("var j = i + alen;\r\n");
      out.write("if (document.cookie.substring(i, j) == arg)\r\n");
      out.write("return getCookieVal (j);\r\n");
      out.write("i = document.cookie.indexOf(\" \", i) + 1;\r\n");
      out.write("if (i == 0) break;\r\n");
      out.write("}\r\n");
      out.write("return null;\r\n");
      out.write("}\r\n");
      out.write("function SetCookie (name, value) {\r\n");
      out.write("var argv = SetCookie.arguments;\r\n");
      out.write("var argc = SetCookie.arguments.length;\r\n");
      out.write("var expires = (argc > 2) ? argv[2] : null;\r\n");
      out.write("var path = (argc > 3) ? argv[3] : null;\r\n");
      out.write("var domain = (argc > 4) ? argv[4] : null;\r\n");
      out.write("var secure = (argc > 5) ? argv[5] : false;\r\n");
      out.write("document.cookie = name + \"=\" + escape (value) +\r\n");
      out.write("((expires == null) ? \"\" : (\"; expires=\" + expires.toGMTString())) +\r\n");
      out.write("((path == null) ? \"\" : (\"; path=\" + path)) +\r\n");
      out.write("((domain == null) ? \"\" : (\"; domain=\" + domain)) +\r\n");
      out.write("((secure == true) ? \"; secure\" : \"\");\r\n");
      out.write("}\r\n");
      out.write("function DeleteCookie (name) {\r\n");
      out.write("var exp = new Date();\r\n");
      out.write("exp.setTime (exp.getTime() - 1);\r\n");
      out.write("var cval = GetCookie (name);\r\n");
      out.write("document.cookie = name + \"=\" + cval + \"; expires=\" + exp.toGMTString();\r\n");
      out.write("}\r\n");
      out.write("var favorite = GetCookie('animal');\r\n");
      out.write("if (favorite != null && favorite != '3') {\r\n");
      out.write("var url\r\n");
      out.write("switch (favorite) {\r\n");
      out.write("case '0' : language_changed('0');\r\n");
      out.write("break;\r\n");
      out.write("case '1' : language_changed('1');\r\n");
      out.write("break;\r\n");
      out.write("case '2' : language_changed('2');\r\n");
      out.write("break;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("//window.location.href = url;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function loginAlign() {\r\n");
      out.write("\tvar availableWidth = document.getElementById(\"poweredBy\").offsetWidth;\r\n");
      out.write("\tvar loginFormTableWidth = document.getElementById(\"loginFormTable\").offsetWidth;\r\n");
      out.write("\tvar loginFormTableHeight = document.getElementById(\"loginFormTable\").offsetHeight;\r\n");
      out.write("\tvar halfLoginBoxWidth = (loginFormTableWidth +10)/2;\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById(\"loginBack\").style.width = availableWidth - 4 + \"px\";\r\n");
      out.write("\tdocument.getElementById(\"loginFront\").style.width = availableWidth - 4 + \"px\";\r\n");
      out.write("\tdocument.getElementById(\"copyLine\").style.width = availableWidth + \"px\";\r\n");
      out.write("\tdocument.getElementById(\"powerLine\").style.width = availableWidth - 155 + \"px\";\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById(\"loginBox\").style.width = loginFormTableWidth +10 + \"px\";\r\n");
      out.write("\tdocument.getElementById(\"loginBox\").style.height = loginFormTableHeight +10 + \"px\";\r\n");
      out.write("\tdocument.getElementById(\"loginBox\").style.left = ((availableWidth /2)-halfLoginBoxWidth) + \"px\";\r\n");
      out.write("\t\r\n");
      out.write("\tif (document.getElementById(\"loginBack\").style.visibility == \"hidden\") {\r\n");
      out.write("\t\tdocument.getElementById(\"loginBack\").style.visibility = \"visible\";\r\n");
      out.write("\t\tdocument.getElementById(\"loginFront\").style.visibility = \"visible\";\r\n");
      out.write("\t\tdocument.getElementById(\"loginBox\").style.visibility = \"visible\";\r\n");
      out.write("\t\tdocument.getElementById(\"copyLine\").style.visibility = \"visible\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".style1 {\r\n");
      out.write("\tfont-family: Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tcolor: #FF6600;\r\n");
      out.write("   \tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".style2 {\r\n");
      out.write("\tfont-family: Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tcolor: #000099;\r\n");
      out.write("   \tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".style6 {\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("\tfont-family: Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\tcolor: #49392A;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".style11 {\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("\tfont-family: Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor: #000000;\r\n");
      out.write("}\r\n");
      out.write(".style11 {\r\n");
      out.write("\tfont-size: 10px;\r\n");
      out.write("\tfont-family: Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor: #63513F;\r\n");
      out.write("}\r\n");
      out.write(".style12 {\r\n");
      out.write("\tfont-size: 10px;\r\n");
      out.write("\tfont-family: Verdana, Arial, Helvetica, sans-serif;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor: #000000;\r\n");
      out.write("}\r\n");
      out.write(".style13 {\r\n");
      out.write("  font-family: Verdana, Arial, Helvetica, sans-serif; \r\n");
      out.write("  font-size: 9px; \r\n");
      out.write("  color: #666666; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".introbg1 {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\theight: 310px;\r\n");
      out.write("\twidth: 5px;\r\n");
      out.write("\tleft: 2px;\r\n");
      out.write("\ttop: 50px;\r\n");
      out.write("\tbackground-image: url(img/intro_bg01.png);\r\n");
      out.write("\tbackground-position: left top;\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".introbg2 {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\theight: 70px;\r\n");
      out.write("\twidth: 5px;\r\n");
      out.write("\tleft: 2px;\r\n");
      out.write("\ttop: 290px;\r\n");
      out.write("\tbackground-image: url(img/intro_bg04.gif);\r\n");
      out.write("\tbackground-position: right bottom;\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tfont-family: Verdana, Arial, Helvetica, sans-serif; \r\n");
      out.write("\tfont-size: 9px; \r\n");
      out.write("\tcolor: #938970; \r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding-top:52px;\r\n");
      out.write("/*\tborder-bottom: 2px solid #680D12;*/\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("\tmargin-left: 0px;\r\n");
      out.write("\tmargin-top: 4px;\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onLoad=\"loginAlign();document.login.username.focus();MM_preloadImages('img/login2.jpg')\" onResize=\"loginAlign()\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"width:74px; height:2px; text-align:center; position:absolute; top:30px; left:0px; border-top: 1px solid #E0DBCD;\"></div>\r\n");
      out.write("<div id=\"powerLine\" style=\"width:10px; height:2px; text-align:center; position:absolute; top:30px; left:155px; border-top: 1px solid #E0DBCD;\"></div>\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"poweredBy\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"42px\" align=\"left\" style=\"padding-left:10px; padding-bottom:1px; border-bottom: 1px solid #A39D86;\"><img src=\"img/powered_by.jpg\" width=\"145\" height=\"42\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<div id=\"loginBack\" class=\"introbg1\" style=\"visibility:hidden\"></div>\r\n");
      out.write("<div id=\"loginFront\" class=\"introbg2\" style=\"visibility:hidden\">\r\n");
      out.write("<b>\r\n");
      out.write("&copy;\r\n");
      out.write("\t\t");

			java.util.Calendar cal = java.util.Calendar.getInstance();
			cal.setTime(new java.util.Date());
			int year = cal.get(Calendar.YEAR);
		
      out.write("\r\n");
      out.write("        2002-");
      out.print( year );
      out.write(" Aheeva Technology. Todos os direitos reservados.\r\n");
      out.write("</b>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"loginBox\" style=\"width:368px; height:183px; position:absolute; top:106px; left:0px; visibility:hidden; padding-top:4px; background-color:#d1cdbc; border-left: 1px solid #888888; border-top: 1px solid #888888; border-right: 1px solid #ffffff; border-bottom: 1px solid #ffffff;\">\r\n");
      out.write("\t<table id=\"loginFormTable\" width=\"358\" height=\"165\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\" border-left: 1px solid #ffffff; border-top: 1px solid #ffffff; border-right: 1px solid #888888; border-bottom: 1px solid #888888;\">\r\n");
      out.write("\t\t<form action=\"\" method=\"\" name=\"login\" id=\"login\">\r\n");
      out.write("        \r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr valign=\"top\" style=\"background-image:url(img/loginbx1.jpg); background-position:right bottom; background-repeat:no-repeat\"> \r\n");
      out.write("\t\t\t\t\t<td width=\"318\" height=\"42\" align=\"right\" class=\"style2\" style=\"border-bottom: 1px solid #ffffff; padding: 4px; background-color: #ffffff;\"> \r\n");
      out.write("\t\t\t\t\t\t<div align=\"left\"><span class=\"vers_name\">Aheeva </span><span class=\"vers_numb\">");
      out.print( pageData.getWord("AHVersion"));
      out.write("</span><br>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/spacer.gif\" width=\"310\" height=\"2\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"38\" align=\"right\" class=\"style13\" style=\"border-bottom: 1px solid #ffffff; padding: 4px; background-color: #ffffff;\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/spacer.gif\" width=\"30\" height=\"2\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\"  align=\"center\" background=\"img/chain_b2.jpg\" style=\"padding: 5px; background-color: rgb(221, 221, 221)\"> \r\n");
      out.write("\t\t\t\t\t\t<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"2\" width=\"99%\">\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td height=\"23\" colspan=\"2\" class=\"style6\" style=\"padding-bottom: 5px;\">Favor digitar o nome de usu&aacute;rio e a senha.</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"style11\" width=\"143\">Usuario:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"194\">\r\n");
 String user = "";
   if(request.getParameter("login") != null)
     user = request.getParameter("login");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input size=\"20\" name=\"username\" onKeyPress=\"checkTheKey(event)\" value=\"");
      out.print(user);
      out.write("\" type=\"text\" class=\"style11\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"143\" class=\"style11\">Senha:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input size=\"20\" name=\"password\" value=\"\" type=\"password\" onFocus=\"this.select()\" onKeyPress=\"checkTheKey(event)\" class=\"style11\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"143\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:;\" onMouseOver=\"MM_swapImage('img_button','','img/login2.jpg',1)\" onMouseOut=\"MM_swapImgRestore()\"><img src=\"img/login.jpg\" name=\"img_button\" width=\"70\" height=\"20\" border=\"0\" id=\"img_button\" onClick=\"return submitInfo();\"></a> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"more\">\r\n");
      out.write("\t\t\t\t\t\t\t<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"2\" width=\"99%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"143\" height=\"20\" class=\"style11\">Idioma:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"194\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select onChange=\"SetCookie('animal', this.value, exp);language_changed(this.options[this.selectedIndex].value)\" id=\"login_language\" name=\"login_language\" class=\"style11\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"3\">Português(BR)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\">US English</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">Français</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2\">Espanol</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write(" \t\t\t</tbody>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"copyLine\" class=\"style13\" style=\"width:10px; height:12px; text-align:center; position:absolute; top:360px; left:0px; margin-top:2px; padding-top:4px; border-top: 1px solid #A39D86; border-bottom: 1px solid #E0DBCD; visibility:hidden;\"></div>\r\n");
      out.write("<div style=\"position:absolute; top:210px; left:20px; height:15px; width:120px;\"><a href=\"http://www.aheeva.com\" target=\"_blank\"><img src=\"img/spacer.gif\" width=\"120\" height=\"15\" hspace=\"0\" vspace=\"0\" border=\"0\"></a></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"TempMessages\" id=\"TempMessages\"> \r\n");
      out.write("  <table border=\"0\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" height=\"100%\">\r\n");
      out.write("    <tr> \r\n");
      out.write("      <td width=\"100%\" id=\"TempMsg\" align=\"center\" class=\"TempMsg\"> </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Fixes the IE6 & IE7 \"Press SPACEBAR or ENTER to activate and use this control\" - must be at the end of the file-->\r\n");
      out.write("<script language=\"JScript\" type=\"text/jscript\" src=\"activateActiveX.js\"></script>\r\n");
      out.write("</body>\r\n");
 pageData.closeConnection(); 
      out.write("\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
