package org.apache.jsp.aheevaManager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.*;
import javax.sql.*;
import java.sql.*;
import java.util.*;
import java.lang.*;
import aheevaManager.ressources.*;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	
	beanManagerData pageData = new beanManagerData();
	if( session.getAttribute("USER_LANGUAGE") != null )
		pageData.setDefaultLanguage( (String)session.getAttribute("USER_LANGUAGE") );
	else	
		pageData.setDefaultLanguage("ENGLISH");	
	
	System.out.println("top.jsp "+session.getAttribute("USER_LANGUAGE"));
		
	
		
	String CURRENT_USER_DBID = ((String)session.getAttribute("CURRENT_USER_DBID"));
	
	String userPrivilegesQuery 			= "select * from cfg_user where dbid='"+CURRENT_USER_DBID+"'";
	String userPreferencesQuery = "SELECT * FROM cfg_user_live_stats_preferences WHERE USER_DBID='"+CURRENT_USER_DBID+"'";
	

	
	
	
	pageData.openConnection();
	pageData.executeFromString(userPrivilegesQuery);
	Vector <HashMap> userPrivilegesDataResult = pageData.CreateVectorFromBean();	
	pageData.executeFromString(userPreferencesQuery);
	Vector <HashMap<String,String>> userPreferences = pageData.CreateVectorFromBean();
	
	
	
		
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--<HTML>-->\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<META HTTP-EQUIV=\"CACHE-CONTROL\" CONTENT=\"NO-CACHE\">\r\n");
      out.write("<META HTTP-EQUIV=\"PRAGMA\" CONTENT=\"NO-CACHE\">\r\n");
      out.write("<LINK href=\"Resources_pages/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!--[if lt IE 7]>\r\n");
      out.write("<link href=\"Resources_pages/styleie6.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<!--<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\">-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\" src=\"Resources_pages/jsUtil.js\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"Resources_pages/globFuncsTopHTM.js\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"Resources_pages/Browser.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"Resources_pages/statsRightsTable.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"lang_browser.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"Resources_pages/mootools-release2222.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<SCRIPT LANGUAGE=\"JavaScript\">\r\n");
      out.write("var agentStats\t\t= \"\";\r\n");
      out.write("var agentGroupStats\t= \"\";\r\n");
      out.write("var campaignStats\t= \"\";\r\n");
      out.write("var callingListStats= \"\";\r\n");
      out.write("var queueStats\t\t= \"\";\r\n");
      out.write("var aPerfStats\t\t= \"\";\r\n");
      out.write("var teamStats\t\t= \"\";\r\n");
      out.write("var adherenceStats  = \"\";\r\n");
      out.write("var logoTab         = \"\"; \r\n");
      out.write("var rClickMenu;\r\n");
      out.write("// Align Tab: LEFT, CENTER, RIGHT\r\n");
      out.write("var tabAlign = \"LEFT\";\r\n");
      out.write("var currentTab;\r\n");
      out.write("var currentTabID; //store the id of the current live stat tab\r\n");
      out.write("var iRecordPwd = window.top.comm.myApplet.getIRecordPwd();\r\n");
      out.write("\r\n");
      out.write("function updateAgentStats(svalue)\r\n");
      out.write("{\t\r\n");
      out.write("    if(currentTab[0] == 'Agents')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(at.b == \"ie\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif( stats.document.readyState == 'complete')\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tstats.replaceStatDivision(svalue);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//stats.document.body.innerHTML = svalue;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t/*var statsObj = document.getElementById('stats');\t\t\t\t\r\n");
      out.write("\t\t\t\tstatsObj.contentDocument.body.innerHTML = svalue;*/\r\n");
      out.write("\t\t\t\tvar statsObj = document.getElementById('stats');\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\tstatsObj.contentDocument.replaceStatDivision(svalue);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tshowLayer(\"divTabFrame\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updateAgentGroupStats(svalue)\r\n");
      out.write("{\r\n");
      out.write("\tagentGroupStats = svalue;\r\n");
      out.write("\t\r\n");
      out.write("    if(currentTab[0] == 'AgentGroups')\r\n");
      out.write("    \t{\r\n");
      out.write("\t\t\tif(at.b == \"ie\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif( stats.document.readyState == 'complete')\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tstats.replaceStatDivision(svalue);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//stats.document.body.innerHTML = svalue;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t/*var statsObj = document.getElementById('stats');\t\t\t\t\r\n");
      out.write("\t\t\t\tstatsObj.contentDocument.body.innerHTML = svalue;*/\r\n");
      out.write("\t\t\t\tvar statsObj = document.getElementById('stats');\t\t\t\t\r\n");
      out.write("\t\t\t\tstatsObj.contentDocument.replaceStatDivision(svalue);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tshowLayer(\"divTabFrame\");\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updateQueueStats(svalue)\r\n");
      out.write("{\r\n");
      out.write("\tqueueStats = svalue;\r\n");
      out.write("\t\r\n");
      out.write("\tif(currentTab[0] == 'Queues')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(at.b == \"ie\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif( stats.document.readyState == 'complete')\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tstats.replaceStatDivision(svalue);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//stats.document.body.innerHTML = svalue;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t/*var statsObj = document.getElementById('stats');\t\t\t\t\r\n");
      out.write("\t\t\t\tstatsObj.contentDocument.body.innerHTML = svalue;*/\r\n");
      out.write("\t\t\t\tvar statsObj = document.getElementById('stats');\t\t\t\t\r\n");
      out.write("\t\t\t\tstatsObj.contentDocument.replaceStatDivision(svalue);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tshowLayer(\"divTabFrame\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updateCampaignStats(svalue)\r\n");
      out.write("{\r\n");
      out.write("\tcampaignStats = svalue;\r\n");
      out.write("\t\r\n");
      out.write("\tif(currentTab[0] == 'Campaigns')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(at.b == \"ie\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif( stats.document.readyState == 'complete')\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tstats.replaceStatDivision(svalue);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//stats.document.body.innerHTML = svalue;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t/*var statsObj = document.getElementById('stats');\t\t\t\t\r\n");
      out.write("\t\t\t\tstatsObj.contentDocument.body.innerHTML = svalue;*/\r\n");
      out.write("\t\t\t\tvar statsObj = document.getElementById('stats');\t\t\t\t\r\n");
      out.write("\t\t\t\tstatsObj.contentDocument.replaceStatDivision(svalue);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\tshowLayer(\"divTabFrame\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updateCallingListStats(svalue)\r\n");
      out.write("{\r\n");
      out.write("\tcallingListStats = svalue;\r\n");
      out.write("\t\r\n");
      out.write("\tif(currentTab[0] == 'CallingLists')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(at.b == \"ie\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif( stats.document.readyState == 'complete')\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tstats.replaceStatDivision(svalue);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//stats.document.body.innerHTML = svalue;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t/*var statsObj = document.getElementById('stats');\t\t\t\t\r\n");
      out.write("\t\t\t\tstatsObj.contentDocument.body.innerHTML = svalue;*/\r\n");
      out.write("\t\t\t\tvar statsObj = document.getElementById('stats');\t\t\t\t\r\n");
      out.write("\t\t\t\tstatsObj.contentDocument.replaceStatDivision(svalue);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tshowLayer(\"divTabFrame\");\r\n");
      out.write("\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updateAgentPerfStats(svalue)\r\n");
      out.write("{\r\n");
      out.write("    aPerfStats= svalue;\r\n");
      out.write("\t\r\n");
      out.write("    if(currentTab[0] == 'Performance')\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(at.b == \"ie\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif( stats.document.readyState == 'complete')\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tstats.replaceStatDivision(svalue);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//stats.document.body.innerHTML = svalue;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t/*var statsObj = document.getElementById('stats');\t\t\t\t\r\n");
      out.write("\t\t\t\tstatsObj.contentDocument.body.innerHTML = svalue;*/\r\n");
      out.write("\t\t\t\tvar statsObj = document.getElementById('stats');\t\t\t\t\r\n");
      out.write("\t\t\t\tstatsObj.contentDocument.replaceStatDivision(svalue);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tshowLayer(\"divTabFrame\");\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updateAgentTeamStats(svalue)\r\n");
      out.write("{\r\n");
      out.write("\tteamStats = svalue;\r\n");
      out.write("\t\r\n");
      out.write("\tif(currentTab[0] == 'Teams')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(at.b == \"ie\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif( stats.document.readyState == 'complete')\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tstats.replaceStatDivision(svalue);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//stats.document.body.innerHTML = svalue;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t/*var statsObj = document.getElementById('stats');\t\t\t\t\r\n");
      out.write("\t\t\t\tstatsObj.contentDocument.body.innerHTML = svalue;*/\r\n");
      out.write("\t\t\t\tvar statsObj = document.getElementById('stats');\t\t\t\t\r\n");
      out.write("\t\t\t\tstatsObj.contentDocument.replaceStatDivision(svalue);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tshowLayer(\"divTabFrame\");\r\n");
      out.write("\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function updateAgentAdherenceStats()\r\n");
      out.write("{ \r\n");
      out.write("\t//alert(\"updateAgentAdherenceStats------\");\r\n");
      out.write("\trefreshAgentAdherenceStats(); \r\n");
      out.write("\t/*alert('Inside updateAgentAdherenceStats');\r\n");
      out.write("\t\r\n");
      out.write("\tif(currentTab[0] == 'Adherence')\r\n");
      out.write("\t{\r\n");
      out.write("\t\tappletObj.updateRTAViewInfo(appletObj.m_adh_start_time, appletObj.m_adh_end_time, appletObj.m_adh_spacing,\"All\");\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t}*/\r\n");
      out.write("\tif(appletObj.getShowAdhValue() != \"true\")\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t//showLayer(\"divTabFrame\");\r\n");
      out.write("\tif(at.b == \"ie\")\t\r\n");
      out.write("\t{\t\r\n");
      out.write("\t\tstats.refreshRtaView();// alert(\"stats.refreshRtaView.....\");\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar statsObj = document.getElementById('stats');\t\t\t\t\r\n");
      out.write("\t\tstatsObj.contentDocument.refreshRtaView();//\talert(\"statsObj.contentDocument.refreshRtaView...\");\t\t\t\t\t\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function refreshAgentAdherenceStats()\r\n");
      out.write("{\r\n");
      out.write("       var svalue=\"\" ;    //is given as  '^0-17:2,18-29:5,30-30:3,31-31:6,32-41:5^0-26:2,27-27:0|0-35:2,36-41:5^0-27:2|';\r\n");
      out.write("       var statsObj;\r\n");
      out.write("\t   svalue = appletObj.m_ScheduleAdherenceData;\r\n");
      out.write("\t  \r\n");
      out.write("       //var allAgentScheduleData;                       //Tab containing all schedule and adherence data received from CTI\r\n");
      out.write("       var nrow = 0;\r\n");
      out.write("       data = svalue + \"\";\r\n");
      out.write("       jsArray = data.split(\"|\");\r\n");
      out.write("       nrow = jsArray.length;\r\n");
      out.write("      if(nrow >= 0) \r\n");
      out.write("\t  {       \t\r\n");
      out.write("       \tif(at.b == \"ie\")\r\n");
      out.write("          \tstats.allAgentScheduleData=new Array(nrow);\r\n");
      out.write("        else{\r\n");
      out.write(" \t\t\tstatsObj = document.getElementById('stats');\t\t\t\t\r\n");
      out.write("\t\t\tstatsObj.contentDocument.allAgentScheduleData=new Array(nrow);\t\t\t\t\t\t\t\r\n");
      out.write("       \t\r\n");
      out.write("        \t}\r\n");
      out.write("         for (i=0; i < nrow; i++)\r\n");
      out.write("          {\r\n");
      out.write("\t        if(at.b == \"ie\")\r\n");
      out.write("\t          \tstats.allAgentScheduleData[i] = jsArray[i];\r\n");
      out.write("\t        else{\r\n");
      out.write("\t \t\t\tstatsObj = document.getElementById('stats');\t\t\t\t\r\n");
      out.write("\t\t\t\tstatsObj.contentDocument.allAgentScheduleData[i] = jsArray[i];\t\t\t\t\t\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \t}\r\n");
      out.write("          }\r\n");
      out.write("       }\r\n");
      out.write("\t\t//appletObj.m_ScheduleAdherenceData=\"\";\r\n");
      out.write("\t   // fin if\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function setAgentScheduleData()\r\n");
      out.write("{\r\n");
      out.write("\t   var schedule_data ='';\r\n");
      out.write("\t   schedule_data  = appletObj.m_all_ScheduleData;\r\n");
      out.write("       var nrow = 0;\r\n");
      out.write("       data = schedule_data + \"\";\r\n");
      out.write("       var jsSchArray = data.split(\"|\");\r\n");
      out.write("       nrow = jsSchArray.length;\r\n");
      out.write("       if(nrow > 0) {\r\n");
      out.write("         stats.thisDayScheduleInfo=new Array(nrow);\r\n");
      out.write("         for (i=0; i < nrow; i++)\r\n");
      out.write("          {\r\n");
      out.write("              stats.thisDayScheduleInfo[i] = jsSchArray[i];\r\n");
      out.write("          }\r\n");
      out.write("       }\t\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("//#93BEE2 ancien couleur pour TAB ON\r\n");
      out.write("//#c4e0f0 ancien couleur pour TAB OFF\r\n");
      out.write("// Tab Name | URL | * (Default Selected Tab)\r\n");
      out.write("\r\n");
      out.write("function updateLineManagementStats(svalue)\r\n");
      out.write("{\r\n");
      out.write("\tlineStats = svalue;\r\n");
      out.write("\tif(currentTab[0] == 'Line Management')\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(at.b == \"ie\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif( stats.document.readyState == 'complete')\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tstats.replaceStatDivision(svalue);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar statsObj = document.getElementById('stats');\r\n");
      out.write("\t\t\tstatsObj.contentDocument.replaceStatDivision(svalue);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tshowLayer(\"divTabFrame\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var tabs = new Array\r\n");
      out.write("(\r\n");
      out.write("\t\"Agents|agentStats\",\r\n");
      out.write("\t\"AgentGroups|agentGroupStats\",\r\n");
      out.write("\t\"Queues|queueStats\",\r\n");
      out.write("\t\"Campaigns|campaignStats\",\r\n");
      out.write("\t\"CallingLists|callingListStats\",\r\n");
      out.write("\t\"Performance|aPerfStats\",\r\n");
      out.write("\t\"Teams|teamStats\",\r\n");
      out.write("\t\"Adherence|adherenceStats\",\r\n");
      out.write("\t\"Line Management|lineStats\",\r\n");
      out.write("\t\"Logo|logoTab|*\"\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("/*********************************************/\r\n");
      out.write("\r\n");
      out.write("function tabOnClick(ID){\r\n");
      out.write("\tvar oElement = null;\r\n");
      out.write("\t\r\n");
      out.write("\tfor (var i = 0; i < tabs.length; i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\toElement = document.getElementById(i);\r\n");
      out.write("\t\tif(oElement != null)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t//oElement.className = \"kwick\";\r\n");
      out.write("\t\t\tswitch(i)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\tcase 0:\r\n");
      out.write("\t\t\t\t\toElement.className = \"kwick\";\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 1:\r\n");
      out.write("\t\t\t\t\toElement.className = \"kwick\";\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 2:\r\n");
      out.write("\t\t\t\t\toElement.className = \"kwick\";\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 3:\r\n");
      out.write("\t\t\t\t\toElement.className = \"kwick\";\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 4:\r\n");
      out.write("\t\t\t\t\toElement.className = \"kwick\";\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 5:\r\n");
      out.write("\t\t\t\t\toElement.className = \"kwick\";\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\tcase 6:\r\n");
      out.write("\t\t\t\t\toElement.className = \"kwick\";\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 7:\r\n");
      out.write("\t\t\t\t\toElement.className = \"kwick\";\r\n");
      out.write("\t\t\t\t\t/*var start =  window.top.comm.myApplet.m_adh_start_time;\r\n");
      out.write("\t\t\t\t\tvar end  =   window.top.comm.myApplet.m_adh_end_time;\r\n");
      out.write("\t\t\t\t\tvar spacing  =   window.top.comm.myApplet.m_adh_spacing;\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('stats').src=\"Resources_pages/essai.jsp?startTime=\"+start+\"&endTime=\"+end+\"&spacing=\"+spacing+\"\";\r\n");
      out.write("\t\t\t\t\t*/\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tcase 8: \r\n");
      out.write("\t\t\t\t\toElement.className = \"kwick\";\r\n");
      out.write("\t\t\t\tbreak;\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tcase 9: \r\n");
      out.write("\t\t\t\t\toElement.className = \"\";\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("\toElement = document.getElementById(ID);\r\n");
      out.write("\t//oElement.className = \"tabOn\";\r\n");
      out.write("\tif(oElement)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tswitch(oElement.id)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\tcase \"0\":\r\n");
      out.write("\t\t\t\t//oElement.className = \"\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tcase \"url(img/background_AgentsGroups.gif)\":\r\n");
      out.write("\t\t\t\t//oElement.style.backgroundImage = \"url(img/background_AgentsGroupsOn.gif)\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tcase \"url(img/background_Queue.gif)\":\r\n");
      out.write("\t\t\t\toElement.style.backgroundImage = \"url(img/background_QueueOn.gif)\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tcase \"url(img/background_Campaigns.gif)\":\r\n");
      out.write("\t\t\t\t//oElement.style.backgroundImage = \"url(img/background_CampaignsOn.gif)\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tcase \"url(img/background_CallingList.gif)\":\r\n");
      out.write("\t\t\t\t//oElement.style.backgroundImage = \"url(img/background_CallingListOn.gif)\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tcase \"url(img/background_performance.gif)\":\r\n");
      out.write("\t\t\t\t//oElement.style.backgroundImage = \"url(img/background_performanceOn.gif)\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tcase \"url(img/background_TeamList.gif)\":\r\n");
      out.write("\t\t\t\t//oElement.style.backgroundImage = \"url(img/background_TeamListOn.gif)\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tcase \"url(img/background_Adherence.gif)\":\r\n");
      out.write("\t\t\t\t//oElement.style.backgroundImage = \"url(img/background_AdherenceOn.gif)\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tcase \"url(img/background_LineManagement.gif)\":\r\n");
      out.write("\t\t\t\t//oElement.style.backgroundImage = \"url(img/background_LineManagementOn.gif)\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tcase \"url(img/aheeva_tab_icon.gif)\":\r\n");
      out.write("\t\t\t\t//oElement.style.backgroundImage = \"url(img/aheeva_tab_icon_on.gif)\";\r\n");
      out.write("\t\t\tbreak;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("*/\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\toElement = document.getElementById(ID);\r\n");
      out.write("\t//oElement.className = \"tabOn\";\r\n");
      out.write("\r\n");
      out.write("\tswitch(oElement.id)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tcase \"0\":\r\n");
      out.write("\t\t\toElement.className = \"koff\";\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\r\n");
      out.write("\t\tcase \"1\":\r\n");
      out.write("\t\t\toElement.className = \"koff\";\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\r\n");
      out.write("\t\tcase \"2\":\r\n");
      out.write("\t\t\toElement.className = \"koff\";\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\r\n");
      out.write("\t\tcase \"3\":\r\n");
      out.write("\t\t\toElement.className = \"koff\";\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\r\n");
      out.write("\t\tcase \"4\":\r\n");
      out.write("\t\t\toElement.className = \"koff\";\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\r\n");
      out.write("\t\tcase \"5\":\r\n");
      out.write("\t\t\toElement.className = \"koff\";\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\r\n");
      out.write("\t\tcase \"6\":\r\n");
      out.write("\t\t\toElement.className = \"koff\";\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\r\n");
      out.write("\t\tcase \"7\":\r\n");
      out.write("\t\t\toElement.className = \"koff\";\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcase \"8\":\r\n");
      out.write("\t\t\toElement.className = \"koff\";\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcase \"9\":\r\n");
      out.write("\t\t\toElement.className = \"\";\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//alert(oElement.style.backgroundImage)\r\n");
      out.write("\r\n");
      out.write("\tcurrentTab = tabs[ID].split(\"|\");\r\n");
      out.write("\tcurrentTabID=ID; //store the id of the current tab\r\n");
      out.write("\thideLayer(\"divTabFrame\");\r\n");
      out.write("\r\n");
      out.write("\t//clearing all the livestats data\r\n");
      out.write("\tagentStats\t\t= \"\";\r\n");
      out.write("\tagentGroupStats\t= \"\";\r\n");
      out.write("\tampaignStats\t= \"\";\r\n");
      out.write("\tcallingListStats= \"\";\r\n");
      out.write("\tqueueStats\t\t= \"\";\r\n");
      out.write("\taPerfStats\t\t= \"\";\r\n");
      out.write("\tteamStats\t\t= \"\";\r\n");
      out.write("\tadherenceStats  = \"\";\r\n");
      out.write("\tlineStats       = \"\";\r\n");
      out.write("\tlogoTab         = \"\";  \r\n");
      out.write("\tvar divTabFrameObj = document.getElementById('divTabFrame');\r\n");
      out.write("\t/*divTabFrameObj.innerHTML = \"<IFRAME ID='stats' CLASS='tabFrame'></IFRAME>\";*/\r\n");
      out.write("\t\r\n");
      out.write("\tif(currentTab[0] == 'Adherence')\r\n");
      out.write("\t{\r\n");
      out.write("\t\t// var start =  window.top.comm.myApplet.m_adh_start_time;\r\n");
      out.write("\t\t//var end  =   window.top.comm.myApplet.m_adh_end_time;\r\n");
      out.write("\t\t// var spacing  =  5;// window.top.comm.myApplet.m_adh_spacing;\r\n");
      out.write("\t\tdocument.getElementById('stats').src=\"Resources_pages/rtaview1.jsp\";//?startTime=\"+start+\"&endTime=\"+end+\"&spacing=\"+spacing+\"\";\r\n");
      out.write("\t\tdocument.getElementById('stats').className=\"tabFrameAdher\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t\r\n");
      out.write("\tif(currentTab[0] == 'Logo')\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById('stats').src=\"Resources_pages/logo1.jsp\";\r\n");
      out.write("\t\tdocument.getElementById('stats').className=\"tabFrame\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\tif(at.b==\"ie\")\t\t\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(stats.document.body)\r\n");
      out.write("\t\t\t\tstats.document.body.innerHTML = eval(currentTab[1]);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar statsObj = document.getElementById('stats');\t\t\t\r\n");
      out.write("\t\t\tsetTimeout(\"\", 100);\t\t\t\r\n");
      out.write("\t\t\tstatsObj.contentDocument.body.innerHTML = eval(currentTab[1]);\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t*/\r\n");
      out.write("\t\tif( document.getElementById('stats').src.indexOf(\"Resources_pages/topstats.jsp\") == -1 )\r\n");
      out.write("\t\t\tdocument.getElementById('stats').src=\"Resources_pages/topstats.jsp\";\r\n");
      out.write("\t\t\tdocument.getElementById('stats').className=\"tabFrame\";\r\n");
      out.write("\t\tif(at.b == \"ie\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t//alert('stats.document='+stats.document);\t\t\t\r\n");
      out.write("\t\t\tif( stats.document.readyState == 'complete')\r\n");
      out.write("\t\t\t{\t\t\t\t\r\n");
      out.write("\t\t\t\tstats.hideAllContextMenus(ID);\r\n");
      out.write("\t\t\t\tstats.replaceStatDivision( eval(currentTab[1]) );\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar statObj = document.getElementById('stats').contentDocument;\r\n");
      out.write("\t\t\talert(eval(currentTab[1]));\r\n");
      out.write("\t\t\t//document.getElementById('stats').contentDocument.replaceStatDivision( eval(currentTab[1]) );\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t//document.body.contentWindow.focus();\r\n");
      out.write("\t//document.body.focus();\r\n");
      out.write("\r\n");
      out.write("\tif(currentTabID==7){\r\n");
      out.write("\t\tappletObj.enableShowAdherence(); \r\n");
      out.write("\t\tshowLayer(\"divTabFrame\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tif(currentTabID!=9){\r\n");
      out.write("\t\t\tif( stats.document.readyState == 'complete'){\t\t\t\t\r\n");
      out.write("\t\t\t\tappletObj.updateLiveStatView(currentTabID); //update the comApplet live stat view property\r\n");
      out.write("\t\t\t\tappletObj.disableShowAdherence();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tappletObj.updateLiveStatView(currentTabID);\r\n");
      out.write("\t\t\tshowLayer(\"divTabFrame\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("/*********************************************/\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("window.addEvent('domready', function () {\r\n");
      out.write("\r\n");
      out.write("var szNormal = 14, szSmall  = 14, szFull   = 25, szUp   = 5, szDown   = 16;\r\n");
      out.write(" \r\n");
      out.write("var kwicks = $$(\".kwick\");\r\n");
      out.write("var fx = new Fx.Elements(kwicks, {wait: false, duration: 300, transition: Fx.Transitions.Back.easeOut});\r\n");
      out.write("kwicks.each(function(kwick, i) {\r\n");
      out.write("\t\r\n");
      out.write("\tkwick.addEvent(\"mouseenter\", function(event) {\r\n");
      out.write("\t\tvar o = {};\r\n");
      out.write("\t\to[i] = {height: [kwick.getStyle(\"height\").toInt(), szFull], top: [kwick.getStyle(\"top\").toInt(), szUp]}\r\n");
      out.write("\t\tkwicks.each(function(other, j) {\r\n");
      out.write("\t\t\tif(i != j) {\r\n");
      out.write("\t\t\t// -- to keep active tab always elevated --\r\n");
      out.write("\t\t\t/*if(other.className.match(/koff/)) {\r\n");
      out.write("\t\t\to[j] = {height: [other.getStyle(\"height\").toInt(), szFull], top: [other.getStyle(\"top\").toInt(), szUp]}\r\n");
      out.write("\t\t\t}else{\t*/\t\t\r\n");
      out.write("\t\t\t\tvar w = other.getStyle(\"height\").toInt();\r\n");
      out.write("\t\t\t\tvar w2 = other.getStyle(\"top\").toInt();\r\n");
      out.write("\t\t\t\tif(w != szSmall) o[j] = {height: [w, szSmall], top: [w2, szDown]};\r\n");
      out.write("\t\t\t/*}*/\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfx.start(o);\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write(" \r\n");
      out.write("$(\"kwicks\").addEvent(\"mouseleave\", function(event) {\r\n");
      out.write("\tvar o = {};\r\n");
      out.write("\tkwicks.each(function(kwick, i) {\r\n");
      out.write("\tif(kwick.className.match(/koff/)) {\r\n");
      out.write("\to[i] = {height: [kwick.getStyle(\"height\").toInt(), szFull], top: [kwick.getStyle(\"top\").toInt(), szUp]}\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\to[i] = {height: [kwick.getStyle(\"height\").toInt(), szNormal], top: [kwick.getStyle(\"top\").toInt(), szDown]}\r\n");
      out.write("\t}\r\n");
      out.write("\t});\r\n");
      out.write("\tfx.start(o);\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function tabOver(id) {\r\n");
      out.write("var overTab = document.getElementById(id);\r\n");
      out.write("overTab.className = (overTab.className.replace(/kwick/,\"kwickover\"));\r\n");
      out.write("\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("function tabOut(id) {\r\n");
      out.write("var overTab = document.getElementById(id);\r\n");
      out.write("overTab.className = (overTab.className.replace(/kwickover/,\"kwick\"));\r\n");
      out.write("//this.style.backgroundImage = (this.style.backgroundImage.replace(/_a/,\"_r\"));\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("function logoOver(idlogo) {\r\n");
      out.write("var logoTab = document.getElementById(idlogo);\r\n");
      out.write("logoTab.className = \"logoover\";\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("function logoOut(idlogo) {\r\n");
      out.write("var logoTab = document.getElementById(idlogo);\r\n");
      out.write("logoTab.className = \"\";\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("function hei1 (){\r\n");
      out.write("\t\r\n");
      out.write("\tif(document.body.clientHeight>30){\r\n");
      out.write("\t\tdocument.getElementById('stats').style.height = (document.body.clientHeight)-30 + \"px\";\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tdocument.getElementById('stats').style.height = 0 + \"px\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("};\r\n");
      out.write("window.onload=hei1;\r\n");
      out.write("window.onresize=hei1;\r\n");
      out.write("//-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<base target=\"rbottom\">\r\n");
      out.write("<BODY class=\"toppagebody\"  scroll=\"no\"> \r\n");
      out.write("\t<div id=\"kwicks_container\">\r\n");
      out.write("\t\t<div id=\"kwicks\">\r\n");
      out.write("\t\t\t<div id=\"0\" class=\"kwick\" onMouseOver=\"tabOver(0)\" onMouseOut=\"tabOut(0)\" onClick=\"tabOnClick(0)\" style=\"display:");
      out.print(pageData.userHasRight(userPrivilegesDataResult, "ALLOW_VIEW_AGENT_STATS") && userPreferences.elementAt(0).get("AGENT_STATS").compareTo("1")==0?"":"none");
      out.write("\">\r\n");
      out.write("\t\t\t");
      out.print(pageData.getWord("Agents"));
      out.write("</div>\r\n");
      out.write("\t\t\t<div id=\"1\" class=\"kwick\" onMouseOver=\"tabOver(1)\" onMouseOut=\"tabOut(1)\" onClick=\"tabOnClick(1)\" style=\"display:");
      out.print(pageData.userHasRight(userPrivilegesDataResult, "ALLOW_VIEW_AGENT_STATS") && userPreferences.elementAt(0).get("AGENT_GROUP_STATS").compareTo("1")==0?"":"none");
      out.write("\">\r\n");
      out.write("\t\t\t");
      out.print(pageData.getWord("Agent Groups"));
      out.write("</div>\r\n");
      out.write("\t\t\t<div id=\"2\" class=\"kwick\" onMouseOver=\"tabOver(2)\" onMouseOut=\"tabOut(2)\" onClick=\"tabOnClick(2)\" style=\"display:");
      out.print(pageData.userHasRight(userPrivilegesDataResult, "ALLOW_VIEW_QUEUES_STATS") && userPreferences.elementAt(0).get("QUEUE_STATS").compareTo("1")==0?"":"none");
      out.write("\">\r\n");
      out.write("\t\t\t");
      out.print(pageData.getWord("Queues"));
      out.write("</div>\r\n");
      out.write("\t\t\t<div id=\"3\" class=\"kwick\" onMouseOver=\"tabOver(3)\" onMouseOut=\"tabOut(3)\" onClick=\"tabOnClick(3)\" style=\"display:");
      out.print(pageData.userHasRight(userPrivilegesDataResult, "ALLOW_VIEW_CAMPAIGN_STATS") && userPreferences.elementAt(0).get("CAMPAIGN_STATS").compareTo("1")==0?"":"none");
      out.write("\">\r\n");
      out.write("\t\t\t");
      out.print(pageData.getWord("Campaigns"));
      out.write("</div>\r\n");
      out.write("\t\t\t<div id=\"4\" class=\"kwick\" onMouseOver=\"tabOver(4)\" onMouseOut=\"tabOut(4)\" onClick=\"tabOnClick(4)\" style=\"display:");
      out.print(pageData.userHasRight(userPrivilegesDataResult, "ALLOW_VIEW_CALLING_LIST_STATS") && userPreferences.elementAt(0).get("CALLING_LIST_STATS").compareTo("1")==0?"":"none");
      out.write("\">\r\n");
      out.write("\t\t\t");
      out.print(pageData.getWord("Calling lists"));
      out.write("</div>\r\n");
      out.write("\t\t\t<div id=\"5\" class=\"kwick\" onMouseOver=\"tabOver(5)\" onMouseOut=\"tabOut(5)\" onClick=\"tabOnClick(5)\" style=\"display:");
      out.print(pageData.userHasRight(userPrivilegesDataResult, "ALLOW_VIEW_PERFOMANCE_STATS") && userPreferences.elementAt(0).get("PERFORMANCE_STATS").compareTo("1")==0?"":"none");
      out.write("\">\r\n");
      out.write("\t\t\t");
      out.print(pageData.getWord("Performance"));
      out.write("</div>\r\n");
      out.write("\t\t\t<div id=\"6\" class=\"kwick\" onMouseOver=\"tabOver(6)\" onMouseOut=\"tabOut(6)\" onClick=\"tabOnClick(6)\" style=\"display:");
      out.print(pageData.userHasRight(userPrivilegesDataResult, "ALLOW_VIEW_TEAM_STATS") && userPreferences.elementAt(0).get("TEAMS_STATS").compareTo("1")==0?"":"none");
      out.write("\">\r\n");
      out.write("\t\t\t");
      out.print(pageData.getWord("Teams"));
      out.write("</div>\r\n");
      out.write("\t\t\t<div id=\"7\" class=\"kwick\" onMouseOver=\"tabOver(7)\" onMouseOut=\"tabOut(7)\" onClick=\"tabOnClick(7)\" style=\"display:");
      out.print(pageData.userHasRight(userPrivilegesDataResult, "ALLOW_VIEW_ADHERENCE_STATS") && userPreferences.elementAt(0).get("ADHERENCE_STATS").compareTo("1")==0?"":"none");
      out.write("\">\r\n");
      out.write("\t\t\t");
      out.print(pageData.getWord("adherence"));
      out.write("</div>\r\n");
      out.write("\t\t\t<div id=\"8\" class=\"kwick\" onMouseOver=\"tabOver(8)\" onMouseOut=\"tabOut(8)\" onClick=\"tabOnClick(8)\" style=\"display:");
      out.print(pageData.userHasRight(userPrivilegesDataResult, "ALLOW_VIEW_LINE_MANAGEMENT_STATS") && userPreferences.elementAt(0).get("LINE_MANAGEMENT_STATS").compareTo("1")==0?"":"none");
      out.write("\">\r\n");
      out.write("\t\t\t");
      out.print(pageData.getWord("Line management"));
      out.write("</div>\r\n");
      out.write("\t\t\t<div id=\"9\" onMouseOver=\"logoOver(9)\" onMouseOut=\"logoOut(9)\" onClick=\"tabOnClick(9)\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<DIV ID=\"divTabFrame\"><IFRAME ID=\"stats\" name=\"stats\" border=\"0\" frameborder=\"0\" CLASS=\"tabFrame\" src=\"Resources_pages/topstats.jsp\" style=\"height:1px;\"></IFRAME></DIV>\r\n");
      out.write("\r\n");
      out.write("<DIV id=\"divLoadingState\">\r\n");
      out.write("\t<table class=\"topstatsbody\" width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t<tr><td align=\"center\" valign=\"middle\">\t\r\n");
      out.write("\t\t<img src=\"img/aheeva_loading_stat.gif\">\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</DIV>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t/* select default view */\r\n");
      out.write("\t//var divTabButtonsObj = document.getElementById('divTabButtons');\r\n");
      out.write("\t//divTabButtonsObj.innerHTML = HTML;\t\r\n");
      out.write("\tfor(var i = 0; i < tabs.length; i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar tab = tabs[i].split(\"|\");\r\n");
      out.write("\t\tif (tab[2] == \"*\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ttabOnClick(i);\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<!-- Fixes the IE6 & IE7 \"Press SPACEBAR or ENTER to activate and use this control\" - must be at the end of the file-->\r\n");
      out.write("<script language=\"JScript\" type=\"text/jscript\" src=\"activateActiveX.js\"></script>\t\r\n");
      out.write("\t\r\n");
      out.write("</BODY>\r\n");
 pageData.closeConnection(); 
      out.write("\r\n");
      out.write("</HTML>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
